// Datei: ./werkzeuge/werkzeuge-zur-paketverwaltung-ueberblick/ncurses-basiert/nala.adoc

// Baustelle: Notizen

[[nala]]

==== Nala ====

// Stichworte für den Index
(((Debianpaket, nala)))
(((nala)))
(((nala, install)))
(((nala, purge)))
(((nala, remove)))
(((nala, remove --purge)))

Das Werkzeug Nala ist bislang noch recht unbekannt und versteht sich als
Frontend für APT. Ziel ist, eine übersichtlichere Darstellung vom
aktuellen Paketbestand sowie bei dessen Änderung zu erhalten, indem
graphische Elemente in die Ausgabe einfließen.

Das gesamte Verhalten und die Bedienung von Nala lehnt sich an `DNF` an
- 'DNF für APT' wäre eine gute Zusammenfassung. An Schaltern versteht es
die Unterkommandos von APT, bspw. `install` zur Installation von
Softwarepaketen, `remove` zum Löschen sowie `purge` und `remove --purge`
zum vollständigen Löschen eines Softwarepakets.

Nala benutzt dabei nicht die APT-Bibliotheken, sondern stattdessen die
Python-apt-API zur Verwaltung der Pakete. Derzeit -- das heißt im Herbst
2022 -- befindet es sich noch im Test und ist daher noch nicht in der
stabilen Veröffentlichung enthalten.

// Stichworte für den Index
(((nala, history)))
(((nala, install)))
(((nala, list)))
(((nala, list -i)))
(((nala, list --installed)))
(((nala, list -N)))
(((nala, list --nala-installed)))
(((nala, purge)))
(((nala, remove)))
(((nala, remove --purge)))
(((nala, show)))
(((nala, update)))
(((nala, upgrade)))
* Kommandos:
** `nala update`
** `nala upgrade`
** `nala list`
** `nala list -i` (`nala list --installed`)
** `nala list -N` (`nala list --nala-installed`)
** `nala show` 'Paketname'
** `nala install` 'Paketname'
** `nala remove` 'Paketname'
** `nala purge` 'Paketname'
** `nala purge --remove` 'Paketname'
** `nala history`

// Datei (Ende): ./werkzeuge/werkzeuge-zur-paketverwaltung-ueberblick/ncurses-basiert/tasksel.adoc
