// Datei: ./werkzeuge/paketoperationen/pakete-ueber-den-namen-finden/grep-available.adoc

// Baustelle: Rohtext

===== `grep-available` und `grep-status` =====

// Stichworte für den Index
(((Debianpaket, dctrl-tools)))
(((grep-available, -F)))
(((grep-available, --field)))
(((grep-available, -i)))
(((grep-available, --ignore-case)))
(((grep-status)))
(((Paketsuche, mittels grep-available)))
(((Paketsuche, mittels grep-status)))
(((Paketsuche, über die Paketbeschreibung)))
(((Paketsuche, über ein Suchmuster)))

Die beiden Werkzeuge `grep-available` und `grep-status` sind Bestandteil
des Pakets 'dctrl-tools' <<Debian-Paket-dctrl-tools>>. Dieses gehört
nicht zur Standardinstallation und ist somit von Ihnen zusätzlich zu
installieren.

Ohne die Angabe weiterer Parameter durchsucht `grep-available` die
gesamte Paketbeschreibung (siehe
<<pakete-ueber-die-paketbeschreibung-finden-grep-available>>). Mit Hilfe
der Option `-F` (Langform `--field`) schränken Sie den Vorgang auf einen
darüber ausgewählten Feldnamen ein. Nachfolgender Aufruf zeigt Ihnen von
allen verfügbaren Paketen die Paketnamen an, bei denen in der
Beschreibung und im Paketnamen die Zeichenfolge `xpdf` enthalten ist.
Durch den Schalter `-i` (Langform `--ignore-case`) erfolgt die Suche
dabei unabhängig von der Groß- und Kleinschreibung. Das abschließende
`sort`-Kommando sorgt darüber hinaus für eine Ausgabe in alphabetisch
aufsteigender Abfolge.

.Verfügbare Pakete mittels `grep-available` anzeigen, bei denen in der Beschreibung und im Paketnamen die Zeichenfolge `xpdf` enthalten ist
----
$ grep-available -F Description -F Package -i xpdf | grep Package | sort
Package: flpsed
Package: libpoppler19
Package: libpoppler3
Package: libpoppler5
Package: libpoppler-cpp0
Package: libpoppler-glib3
Package: libpoppler-glib4
Package: libpoppler-glib8
Package: libpoppler-qt2
Package: libpoppler-qt4-3
Package: poppler-utils
Package: python-poppler
Package: xpdf
$
----

// Stichworte für den Index
(((grep-available, -P)))
(((grep-available, -S)))
Um den Aufruf für den Paketnamen zu vereinfachen, stellt Ihnen
`grep-available` zudem die beiden Abkürzungen `-P` für `-FPackage` und
`-S` für `-FSource:Package` bereit.

// Stichworte für den Index
(((grep-status, -s)))
(((grep-status, --show-field)))
Obige Liste enthält alle Pakete – unabhängig davon, ob diese auf ihrem
System installiert sind, oder nicht. Um das einzugrenzen, kommt das
Werkzeug `grep-status` ins Spiel. Mit dem nachfolgenden Aufruf
reduzieren Sie die Liste entsprechend. Dabei kommt der Schalter `-s`
(Langform `--show-field`) zum tragen, der den Paketstatus passend
auswertet.

.Lediglich die installierten Pakete anzeigen, bei denen in der Beschreibung und im Paketnamen die Zeichenfolge `xpdf` enthalten ist
----
$ grep-status -F Description -P -i -s Package xpdf | grep Package | sort
Package: flpsed
Package: libpoppler19
Package: libpoppler-cpp0
Package: libpoppler-glib8
Package: libpoppler-qt4-3
Package: poppler-utils
Package: python-poppler
Package: xpdf
$
----

// Stichworte für den Index
(((grep-status, -v)))
(((grep-status, --invert-match)))
Analog zu `grep` verfügt `grep-status` ebenfalls über den hilfreichen
Schalter `-v` (Langversion `--invert-match`). Bei Bedarf verkehren Sie
somit das Suchergebnis in das Gegenteil.

// Datei (Ende): ./werkzeuge/paketoperationen/pakete-ueber-den-namen-finden/synaptic.adoc
