// Datei: ./praxis/paketverwaltung-ohne-internet/apt-offline.adoc

// Baustelle: Notizen

[[paketverwaltung-offline-apt-offline]]
==== Das Projekt 'apt-offline' ====

===== Projektidee =====

// Stichworte für den Index
(((Debianpaket, apt-offline)))
(((Debianpaket, apt-offline-gui)))

Nicht immer hängt ein Computer am Netzwerk und hat Zugang zu dem
hinterlegten Paketmirror. Das Projekt 'apt-offline' (Projektseite
<<apt-offline-Projektseite>>) baut Ihnen eine Brücke, um mit Hilfe eines
anderen Rechners Änderungen am Paketbestand möglich zu machen. Es steht
in Form der beiden Pakete 'apt-offline' <<Debian-Paket-apt-offline>> für
die Kommandozeile und 'apt-offline-gui' <<Debian-Paket-apt-offline-gui>>
mit graphischer Bedienoberfläche zur Verfügung. Beide Pakete setzen auf 
der Programmiersprache Python auf. Seit der Version 11 _Bullseye_ sind
die beiden Pakete fester Bestandteil der stabilen Veröffentlichung.

Die Idee hinter 'apt-offline' ist das Erzeugen einer Beschreibungsdatei
mit allen Informationen für die Abfrage der Paketdatenbank. Damit weiß 
der Paketmirror, welche Pakete er bereitstellen muß. Diese bezogenen
Pakete übertragen Sie auf das eigentliche System -- bspw. mit einem
USB-Stick oder einer externen Festplatte -- und spielen diese wie
gewohnt über die Paketverwaltung ein. Wie das genau funktioniert,
erklären wir Ihnen gleich.

* Beschreibungen und Idee: 
** Offline Package Management for APT (<<Ritesh-apt-offline>>, <<xubuntu-apt-offline>>, <<Damienoh-apt-offline>>)

===== Benutzung im Detail =====

// Stichworte für den Index
(((apt-offline, get)))
(((apt-offline, install)))
(((apt-offline, set)))
(((apt-offline, --update)))
(((apt-offline, --upgrade)))

* Ablauf:
** Signatur für die Maschine erzeugen, die aktualisierte
Paketinformationen und Pakete bekommen soll (auf der Maschine, die
offline ist)

----
# apt-offline set /tmp/apt-offline.sig
----

*** Option `--update`: nur Updates (Einspielen aktualisierter,
fehlerbereinigter Pakete mit der gleichen Versionsnummer)
*** Option `--upgrade`: nur Upgrades (Einspielen aktualisierter,
fehlerbereinigter Pakete mit einer neueren Version)
*** ohne Optionen: alles auf den allerneuesten Stand bringen (entspricht
einem `dist-upgrade`)

** Paketinfo für die offline-Maschine holen, inkl. Bug-Reports und
Ausführung als parallele 5 Threads (auf einer Maschine, die über eine
Netzanbindung verfügt)

----
# apt-offline get apt-offline.sig --bug-reports --threads 5
----

** bezogene Paketinformationen auf der offline-Maschine einspielen, hier
beispielhaft als Datei von einem Speichermedium, welches über USB
eingehängt ist (USB-Stick oder USB-Festplatte)

----
# apt-offline install /media/USB/apt-offline.zip
----

*** aktualisiert den APT-Cache, sodaß alles daher kommt und nichts von
extern bezogen werden muß

// Datei (Ende): ./praxis/paketverwaltung-ohne-internet/apt-offline.adoc
