// Datei: ./praxis/paketverwaltung-ohne-internet/dpkg-split.adoc

// Baustelle: Notizen

[[paketverwaltung-offline-dpkg-split]]
==== Pakete mit `dpkg-split` aufteilen ====

// Stichworte für den Index
(((Debianpaket, dpkg)))
(((dpkg-split)))
(((dpkg-split, -?)))
(((dpkg-split, --help)))
(((dpkg-split, -a)))
(((dpkg-split, --auto)))
(((dpkg-split, -d)))
(((dpkg-split, --discard)))
(((dpkg-split, -I)))
(((dpkg-split, --info)))
(((dpkg-split, -j)))
(((dpkg-split, --join)))
(((dpkg-split, -l)))
(((dpkg-split, --listq)))
(((dpkg-split, -o)))
(((dpkg-split, --output)))
(((dpkg-split, -Q)))
(((dpkg-split, --npquiet)))
(((dpkg-split, -S)))
(((dpkg-split, --partsize)))
(((dpkg-split, -s)))
(((dpkg-split, --split)))
(((dpkg-split, --depotdir)))
(((dpkg-split, --msdos)))
(((dpkg-split, --version)))

* Werkzeug `dpkg-split` aus dem Paket 'dpkg' <<Debian-Paket-dpkg>>
* zerlegt eine `deb`-Datei in kleinere Stücke und kann diese Stücke
  wieder zusammensetzen
* nützlich, um Binärpakete auf mehrere Medien mit geringer Kapazität zu
  verteilen (wenn man grade nichts anderes zur Hand hat ...)
* Schalter:
** `-?` (Langform: `--help`)
** `-a` (Langform: `--auto`)
** `-d` (Langform: `--discard`)
** `-I` (Langform: `--info`)
** `-j` (Langform: `--join`)
** `-l` (Langform: `--listq`)
** `-o` (Langform: `--output`)
** `-Q` (Langform: `--npquiet`)
** `-S` (Langform: `--partsize`)
** `-s` (Langform: `--split`)
** `--depotdir`
** `--msdos`
** `--version`

* Beispiele
** das Paket 'xsnow' in Stücke mit einer Größe von 10 KB zerlegen
*** `-s`: zerlegen
*** `-S 10`: Blockgröße von maximal 10 KB
*** ergibt vier Blöcke
*** Benennung (default-Werte): 'Paketname.nofm.deb' mit 'n' als
Stücknummer (im Beispiel die Werte 1 bis 4) und 'm' als Anzahl der
Stücke (im Beispiel 4)

----
$ dpkg-split -s -S 10 xsnow_1%3a1.42-9_amd64.deb 
Paket xsnow wird in 4 Teile aufgeteilt: 1 2 3 4 fertig
$ ls -lh
insgesamt 136K
-rw-r--r--  1 frank frank 9,2K Jan  7 11:09 xsnow_1%3a1.42-9_amd64.1of4.deb
-rw-r--r--  1 frank frank 9,2K Jan  7 11:09 xsnow_1%3a1.42-9_amd64.2of4.deb
-rw-r--r--  1 frank frank 9,2K Jan  7 11:09 xsnow_1%3a1.42-9_amd64.3of4.deb
-rw-r--r--  1 frank frank 8,2K Jan  7 11:09 xsnow_1%3a1.42-9_amd64.4of4.deb
$
----

** Informationen zu einem Stück eines mittels `dpkg-split` zerlegten
deb-Pakets ausgeben
*** Schalter `-I`
*** Parameter: Dateiname, hier: 'xsnow_1%3a1.42-9_amd64.3of4.deb'
*** Ausgabe: Formatversion, Paketinformationen, Nummer des Stücks (hier
3 von 4), Größe ("Teil-Länge"), Offset im Originalpaket ("Teil-Offset")

----
$ dpkg-split -I xsnow_1%3a1.42-9_amd64.3of4.deb 
xsnow_1%3a1.42-9_amd64.3of4.deb:
    Teil-Formatversion:            2.1
    Teil des Paketes:               xsnow
        ... Version:                1:1.42-9
        ... Architektur:            amd64
        ... MD5-Prüfsumme:          3ddeabaec77416662e45de36d9960a2a
        ... Länge:                  35836 Byte
        ... geteilt alle:           9216 Byte
    Teil-Nummer:                    3/4
    Teil-Länge:                     9216 Byte
    Teil-Offset:                    18432 Byte
    Teil-Dateigröße (ben. Anteil):  9418 Byte

$
----

// Datei (Ende): ./praxis/paketverwaltung-ohne-internet/dpkg-split.adoc
