// Datei: ./praxis/paketverwaltung-ohne-internet/keryx.adoc

// Baustelle: Rohtext

[[paketverwaltung-offline-keryx]]

==== Keryx ==== 

// Stichworte für den Index
(((Debianpaket, python-wxversion)))
(((Keryx)))

Das Projekt 'Keryx' <<Keryx>> beschreibt sich als eine freie,
plattformunabhängige Softwareanwendung, um Linuxsysteme ohne
Internetanbindung zu aktualisieren. Es hat den Fokus auf Benutzer mit
Einwahlverbindungen und Systeme, die nur über eine dünne Leitung an das
Internet verfügen.

Ursprünglich nur für Ubuntu entwickelt, erlaubt es mittlerweile das
Auswählen und Herunterladen von Paketen auf Debian-basierten Systemen
und auch anderen Betriebssystemen wie bspw. Microsoft Windows. Die
bezogenen Pakete werden auf einem mobilen Speichermedium abgelegt und
können von da aus auf dem eigentlichen System eingespielt werden. Es ist
für die Anwendung an einzelnen Systemen gedacht, geschieht das in einem 
größeren Rahmen, ist für das Vorgehen der Begriff ``Turnschuhnetzwerk'' 
<<Turnschuhnetzwerk>> gebräuchlich.

Keryx basiert auf dem Gimp Tool Kit. Die letzte Veröffentlichung als
Ubuntu-PPA erfolgte 2011 (Version 1), 2017 wurde die Version 0.92.5
freigegeben. Aktuellere Veröffentlichungen sind nicht bekannt.

Es existiert zudem eine Erweiterung um eine graphische Bedienoberfläche,
die auf wxPython (Paket 'python-wxversion') aufsetzt.

// Datei (Ende): ./praxis/paketverwaltung-ohne-internet/keryx.adoc
