// Datei: ./praxis/paketverwaltung-ohne-internet/strategien.adoc

// Baustelle: Rohtext

[[paketverwaltung-offline-strategien]]

=== Strategien ===

// Stichworte für den Index
(((Debianpaket, apt-offline)))
(((Keryx)))

Aus unserer Sicht bestehen mehrere, grundlegende Verfahren, die sich
hier anbieten:

* die benötigten Pakete vorher explizit herunterladen
* die Einbindung fester Installationsmedien
* die Einbindung eines lokalen Paketmirrors

Diese drei Wege basieren auf den Werkzeugen und Verfahren, die wir
bislang im Buch bereits angesprochen haben. Nachfolgend beleuchten wir
die Verfahren noch etwas genauer.

Sagen Ihnen unsere Empfehlungen nicht zu, werfen Sie bitte einen
genaueren Blick auf die beiden Projekte `apt-offline` und Keryx. Diese
stellen wir Ihnen im Anschluss in <<paketverwaltung-offline-werkzeuge>>
genauer vor.

==== Benötigte Pakete vorher explizit herunterladen ====

// Stichworte für den Index
(((apt-get, download)))
(((apt-get, --no-download install)))
(((Paket, nur herunterladen)))

Dieser Weg setzt voraus, dass Sie wissen, was Sie brauchen werden. Das
gelingt nicht immer und lässt sich auch nicht in allen Fällen exakt
vorhersagen. Bitte testen Sie das daher im Vorfeld aus.

Wenn jedoch feststeht, welche Pakete erforderlich sind, laden Sie diese
zunächst explizit mittels APT oder `aptitude` herunter. Damit landen die
neuen Pakete inklusive der zusätzlich benötigten Abhängigkeiten im
lokalen Paketcache Ihres Systems. Zu einem späteren Zeitpunkt können Sie
die dort hinterlegten Pakete hervorholen und auf Ihrem System
installieren. Für das Paket 'debtags' mittels APT sind bspw. diese
beiden Aufrufe notwendig:

.APT-Aufrufe zum Zwischenspeichern und späteren Installieren eines Pakets
----
# apt-get download debtags
# apt-get --no-download install debtags
#
----

Ausführlicher besprechen wir jeden der beiden Einzelschritte in
<<paketdatei-nur-herunterladen>> und
<<installation-zwischengespeicherter-pakete-aus-dem-paketcache>>. Das
betrifft nicht nur APT, sondern auch `aptitude`.

==== Einbindung fester Installationsmedien ====

// Stichworte für den Index
(((Paketquelle, Installationsmedium einbinden)))
(((Paketquelle, lokales Paketarchiv)))
(((Paketquelle, Versionskonflikte)))

Vorbereitete Installationsmedien bekommen Sie von der Webseite des
Debian-Projekts als ISO-Image und Live-CD bzw. -DVD <<Debian-besorgen>>.
Alternativ können Sie auch selbst Diskimages erstellen und benutzen
<<Debian-Wiki-DiskImage>>. Ein solches Installationsmedium binden Sie
als lokales Paketarchiv wie folgt ein, hier unter dem Verzeichnis
`/mnt/iso`:

.Einbindung eines lokalen CD/DVD-Images namens `image.iso` als `loop device` unter `/mnt/iso`
----
# mkdir /mnt/iso
# mount -o loop -t iso9660 image.iso /mnt/iso
#
----

Bitte beachten Sie dabei, dass der Paketbestand zwischen dem
eingebundenen Diskimage und Ihrer lokalen Installation bezüglich Ihrer
benötigten Architektur und der genutzten Veröffentlichung harmonieren
muss. Passen beide nicht zusammen, provozieren Sie Versionskonflikte
zwischen den beiden Paketbeständen und mit hoher Wahrscheinlichkeit
werden Sie die benötigten Pakete von dem Diskimage nicht auf Ihr lokales
System einspielen können.

// Stichworte für den Index
(((apt-cdrom)))
(((Debianpaket, apt-cdrom)))

Eine Alternative stellt das Werkzeug `apt-cdrom` dar. Dieses stellen wir
Ihnen unter ``Physische Installationsmedien mit `apt-cdrom` einbinden'' in
<<physische-installationsmedien-mit-apt-cdrom-einbinden>> genauer vor.

==== Einbindung eines lokalen Paketmirrors ====

// Stichworte für den Index
(((/etc/apt/sources.list, Paketquelle nachtragen)))
(((Paketmirror)))

Variante Drei ist das Benutzen eines eigenen Paketmirrors. Dieser kann
lokal vorliegen (siehe <<eigenen-apt-mirror-aufsetzen>>), aber auch als
mobile Kopie auf einer externen (USB-)Festplatte überall zum Einsatz
kommen. Diesen Datenträger mounten Sie zunächst und tragen den
Paketmirror danach als zusätzliche Paketquelle ('Repository') in der
Datei `/etc/apt/sources.list` auf Ihrem lokalen System ein. Ist der
Datenträger bspw. als `/mnt/mirror` gemounted, sieht der Eintrag in der
Liste ihrer Paketquellen wie folgt aus:

.Einbinden einer externen Festplatte als Paketmirror
----
deb file:/mnt/mirror/debian stable main contrib non-free
----

Haben Sie den lokalen Paketmirror als zusätzliche Paketquelle in der
Datei `/etc/apt/sources.list` eingetragen, speichern Sie die Datei und
informieren danach ihr Debian-System über die Ergänzung. Aktualisieren
Sie den Paketbestand mittels `apt-get update`, `apt update` oder
`aptitude update`. Installieren Sie nun Pakete auf Ihrem lokalen System,
sucht die Paketverwaltung die Pakete ebenfalls in der angegebenen, neuen
Paketquelle.

Dieser Schritt setzt voraus, dass Sie über eine genügend großen,
zusätzlichen, mobilen Datenträger verfügen, um einen solchen Paketmirror
vorzubereiten (meist unproblematisch). Weiterhin probieren Sie zuvor
aus, ob die Paketinstallation von diesem Paketmirror klappt, um im
Ernstfall handlungsfähig zu sein (auch unproblematisch). Als drittes
sind Sie angeraten, diesen Datenträger dann auch mitzunehmen und nicht
im Büro zu vergessen (schon eher problematisch) -- ansonsten ist nämlich
alle Mühe umsonst.

// Datei (Ende): ./praxis/paketverwaltung-ohne-internet/strategien.adoc
