// Datei: ./praxis/automatisierte-aktualisierung/automatisierte-aktualisierung.adoc

// Baustelle: Notizen

[[automatisierte-aktualisierung]]

== Automatisierte Aktualisierung ==

=== Ziel ===

Hier besprechen wir, wie Sie eine ganze Menge von identisch aufgesetzten 
Rechnern aktualisieren, bspw. für einen Schulungsraum oder Cluster. Vereinfacht
wird es, wenn alle Rechner über eine identische Hardware verfügen. 

Der Unterschied zur regulären Installation ist, dass die Grundinstallation 
bereits erfolgt ist und nur bestehende Software auf den aktuellen Stand zu 
bringen ("zu aktualisieren") ist. Wichtig kann sein, daß ein Login auf allen 
Rechnern und zur Ausführung eines Kommandos notwendig ist. Als Werkzeuge
rücken 'apt-dater', 'multi-ssh' (https://multissh.dev/), Parallel-SSH 
(https://parallel-ssh.org/) und Zabbix (https://www.zabbix.com/) in das 
Blickfeld.

=== `apt-dater` ===

// Stichworte für den Index
(((apt-dater)))
(((Debianpaket, apt-dater)))

* Werkzeug/Paket: 'apt-dater' <<Debian-Paket-apt-dater>>
* terminal-based remote package update manager 
* Projektseite <<apt-dater-Projektseite>>
* Kurzbeschreibung: "apt-dater provides an ncurses frontend for
managing package updates on a large number of remote hosts using SSH. It
supports Debian-based managed hosts as well as rug (e.g. openSUSE) and
yum (e.g. CentOS) based systems."

* benötigt SSH und Screen

=== Mit Zabbix ===

// Stichworte für den Index
(((Debianpaket, zabbix-agent)))

* Monitoring eines Systems mit Zabbix
* zusätzlicher Service, der prüft, ob Aktualisierungen vorliegen

// Datei (Ende): ./praxis/automatisierte-aktualisierung/automatisierte-aktualisierung.adoc
