// Datei: ./praxis/apt-und-aptitude-auf-die-eigenen-beduerfnisse-anpassen/apt-und-aptitude-auf-die-eigenen-beduerfnisse-anpassen.adoc

// Baustelle: Rohtext

[[apt-und-aptitude-auf-die-eigenen-beduerfnisse-anpassen]]
== APT und `aptitude` auf die eigenen Bedürfnisse anpassen ==

// Einführung
Die Werkzeuge für `deb`-Pakete -- `apt-get`, `apt` und auch `aptitude` -- sind 
sehr flexibel in ihrer Ausführung. Die von Debian mitgelieferte Konfiguration
ist alltagstauglich und sorgt für ein stabiles Arbeiten.

Recherchieren Sie nach der Konfiguration von APT, erhalten Sie viele Beiträge, 
die sich lediglich auf die Liste der Paketquellen konzentrieren. Diesem Thema 
gehen wir bereits ausführlich in <<etc-apt-sources.list-verstehen>> nach. Das 
nun folgende Kapitel konzentriert sich hingegen auf die weiteren Einstellungen 
von `apt-get`, `apt` und `aptitude`. Es soll Ihnen dabei helfen, das Verhalten 
dieser Werkzeuge auf ihre eigenen Bedürfnisse anzupassen, insbesondere wenn es 
um Spezialfälle geht. 

Alle drei Werkzeuge greifen auf die gleichen Dateien zur Konfiguration zurück. 
APT liefert Erweiterungen -- genannt Hooks (siehe <<apt-hooks>>), und 
`aptitude` erlaubt sowohl permanente, globale Einstellungen als auch lokale 
Einstellungen (siehe <<konfigurationsdateien-von-aptitude>>) sowie das Ändern 
der Verhaltens beim Aufruf von `aptitude` (siehe dazu 
<<interaktives-aendern-von-optionen>>).

// Konfiguration von APT
include::konfiguration-von-apt.adoc[]

// Konfiguration von APT anzeigen
include::konfiguration-von-apt-anzeigen.adoc[]

// Konfigurationsdateien von APT im Detail
include::konfigurationsdateien-von-apt.adoc[]

// Konfigurationsoptionen von APT
include::konfigurationsoptionen-von-apt.adoc[]

// APT-Hooks
include::apt-hooks.adoc[]

// Konfiguration von aptitude
include::konfiguration-von-aptitude.adoc[]

// aptitude: Interaktives Ändern von Optionen
include::interaktives-aendern-von-optionen.adoc[]

// aptitude Formatstrings
include::aptitude-formatstrings.adoc[]

// aptitude Ausgabebreite festlegen
include::aptitude-ausgabebreite.adoc[]

// aptitude Ausgabe sortieren
include::aptitude-ausgabe-sortieren.adoc[]

// aptitude Gruppierung
include::aptitude-gruppierung.adoc[]

// aptitude-Farbschema anpassen
include::aptitude-farbschema-anpassen.adoc[]


// Datei (Ende): ./praxis/apt-und-aptitude-auf-die-eigenen-beduerfnisse-anpassen/apt-und-aptitude-auf-die-eigenen-beduerfnisse-anpassen.adoc
