// Datei: ./praxis/apt-und-aptitude-auf-die-eigenen-beduerfnisse-anpassen/aptitude-gruppierung.adoc

// Baustelle: Rohtext

[[aptitude-gruppierung]]

=== `aptitude`-Gruppierung ===

[[aptitude-gruppierung-kommandozeile]]
==== Kommandozeile ====

// Stichworte für den Index
(((aptitude, --group-by)))
(((Aptitude, Auflistung der Pakete umsortieren)))
Zur Gruppierung kennt `aptitude` den Schalter `--group-by`. Eine kurze Version des
Schalters existiert u.E. bislang nicht. Als Wert sind die folgenden
Möglichkeiten zulässig:

`archive`:: 
nach dem Enthaltensein eines Pakets in einer Veröffentlichung, bspw.
`stable` oder `unstable`.

`auto`::
Gruppierung nach dem Paketnamen

`none`::
Darstellung aller Versionen in einer einzigen Liste ohne jegliche
Sortierung

`package`::
Gruppierung nach dem Paketnamen

`source-package`::
Gruppierung nach dem Namen des Sourcepakets

`source-version`::
Gruppierung nach dem Namen und der Version des Sourcepakets

Diese Werte korrespondieren mit der Einstellung
`Aptitude::CmdLine::Versions-Group-By` in der Konfigurationsdatei zu
`aptitude`.

[[aptitude-gruppierung-tui]]
==== Textoberfläche ====

// Stichworte für den Index
(((Aptitude, Aussehen der Textoberfläche ändern)))
(((Aptitude, Aptitude::UI::Default-Package-View)))
Auch die textbasierte Bedienoberfläche ist nicht in Stein gemeisselt und
lässt sich anpassen. Dazu gehören die Anordnung und Breite der Spalten
zu den Paketen und deren Informationen sowie die Aufteilung auf dem
Bildschirm -- horizontal oder vertikal geteilt.

===== Anordnung und Breite der Spalten =====

Die Darstellung entnimmt Aptitude der Konfigurationsgruppe
`Aptitude::UI::Default-Package-View`. Diese beinhaltet eine Liste der
Komponenten, die in der TUI auftauchen. Jede Komponente bennenen Sie und
konfigurieren Sie über mindestens die nachfolgenden vier Angaben genauer:

.Beschreibung für eine Komponente der Aptitude-TUI
----
Komponentenname Typ {
  Row Zeile;
  Column Spalte;
  Width Breite;
  Height Höhe;
};
----

Der 'Komponentenname' ist frei wählbar, darf aber nur aus einem einzigen
Wort ohne Trennzeichen bestehen. Der 'Typ' bestimmt, was in der
Komponente dargestellt wird. Zur Auswahl stehen:

`Description` :: Informationsfeld, bspw. für die Beschreibung des
aktuell ausgewählten Debianpaketes

`MainWidget` :: Feld mit der Liste der Pakete; dieses muss genau einmal
vorkommen

`Static` :: Feld mit statischem Text

Die Angaben für `Zeile`, `Spalte`, `Breite` und `Höhe` entsprechen denen
einer Tabelle, wobei die obere, linke Ecke die Position 0,0 hat. Mit den
nachfolgenden Zusatzoptionen gestalten Sie die Drastellung einer Spalte
und deren jeweiligen Inhalt noch genauer (Auswahl):

* `ColAlign` Ausrichtung
* `ColExpand`
* `Color`
* `ColShrink`

===== Aufteilung auf dem Bildschirm ===== 

Dieses Thema besprechen wir im <<aptitude-farbschema-anpassen>> genauer.

// Datei (Ende): ./praxis/apt-und-aptitude-auf-die-eigenen-beduerfnisse-anpassen/aptitude-gruppierung.adoc
