// Datei: ./praxis/apt-und-aptitude-auf-die-eigenen-beduerfnisse-anpassen/aptitude-formatstrings.adoc

// Baustelle: Rohtext

[[aptitude-format-strings]]
=== `aptitude` Format Strings ===

// Stichworte für den Index
(((aptitude, Format Strings)))
(((aptitude, die Ausgabe anpassen)))
'Format Strings' sind eine spezifische Schreibweise einer Ausgabe anhand
von Platzhaltern. Sie ähneln der Art und Weise, wie sie in der
`printf()`-Funktion in der Programmiersprache C respektive der
`print()`-Funktion in Python üblich sind. Eine ausführliche Beschreibung
der Platzhalter finden Sie im `aptitude`-Handbuch unter 'Customizing the
package list' <<aptitude-dokumentation-package-list>>.

<<tab.aptitude-format-strings>> gibt Ihnen eine Übersicht zu den
verfügbaren Format Strings. Diese Platzhalter helfen Ihnen in
Kombination mit der Suche nach Paketen und bei der Gestaltung der
Ausgabe. Sie bestimmen damit, welche Informationen `aptitude`
spaltenweise zu einem Paket darstellt.

.Format Strings in `aptitude`
[frame="topbot",options="header",cols="1,9",id="tab.aptitude-format-strings"]
|====
| Platzhalter | Bedeutung
| `%c` | aktueller Paketstatus ('Current State Flag')
| `%a` | Aktion des Pakets ('Action Flag')
| `%M` | gesetzt, falls das Paket automatisch installiert wurde ('Automatic Flag')
| `%p` | Paketname ('package name')
| `%d` | Paketbeschreibung ('description')
| `%m` | Paketmaintainer ('maintainer')
| `%I` | Installationsgröße ('installed size')
|====

Die Voreinstellung von `aptitude` beinhaltet die Platzhalter `%c`, `%a`,
`%M`, `%p%` und `d`. Es umfasst somit die einzelnen Spalten mit dem
Paketstatus, der Aktion, das 'Automatic Flag', den Paketnamen und die
Paketbeschreibung. Mit zusätzlichen Trennzeichen und dezimalen Angaben
vor einem Platzhalter legen Sie die Gestaltung der Ausgabe und die
jeweilige Spaltenbreite fest.

Mit der Angabe `%c%a | %15p` erzeugen Sie drei Spalten -- den
Paketstatus, die Aktion des Pakets und den Paketname -- wobei zwischen
der zweiten und dritten Spalte ein senkrechter Trennstrich eingefügt
wird, der davor und danach noch ein Leerzeichen zur besseren Lesbarkeit
umfaßt. Die dritte Spalte hat eine feste Breite von 15 Zeichen, während
die anderen Spalten variabel bleiben. 

// Stichworte für den Index
(((aptitude, Ausgabespalten festlegen)))
(((aptitude, search --display-format)))
(((aptitude, search -F)))
Im Aufruf von `aptitude search` geben Sie die Platzhalterfolge als Wert
zur zusätzlichen Option `-F` (Langform `--display-format`) wie folgt an:

.Individuelle Gestaltung des Ausgabeformats von `aptitude` bei der Suche
nach dem Paket 'tzdata'
----
aptitude search -F "%c%a | %15p" tzdata
i  | tzdata
v  | tzdata:i386
i  | tzdata-java
v  | tzdata-java:i386
v  | tzdata-jessie
v  | tzdata-jessie:i386
----

// Stichworte für den Index
(((aptitude, search -O)))
(((aptitude, search --sort)))
(((aptitude, Sortierung der Ausgabe festlegen)))
Möchten Sie die Ausgabe darüberhinaus noch sortieren, hilft Ihnen der
Schalter `-O` (Langform `--sort`) weiter. Die Sortierung der Ausgabe
erlaubt bspw. die Werte `installsize` (Installationsgröße), `name`
(Paketname) und `version` (Versionsnummer). Die Basiseinstellung ist
`name,version`, wobei `aptitude` zuerst eine Sortierung anhand des
Paketnamens und danach noch anhand der Paketversion durchführt. Somit
erscheinen ältere Pakete in der Auflistung zuoberst.

Nachfolgend sehen Sie wiederum eine dreispaltige Ausgabe, die hier aus
der Größe nach der Installation (Platzbedarf auf dem Speichermedium),
dem Paketnamen sowie dem Namen und der EMailadresse des Paketmaintainers
besteht. Zusätzlich ist die Ausgabe aufsteigend nach der Paketgröße
sortiert. Recherchiert wird dabei nach allen Paketen, die im Namen die
Zeichenkette `debtags` beinhalten.

.Suche nach `debtags`-Paketen mit spezifischer Formatierung der Ausgabe und Sortierung
----
$ aptitude search -F "%I %5p,%m" --sort installsize debtags
79,9 kB  python-debtagshw      ,Enrico Zini <enrico@debian.org>
79,9 kB  python3-debtagshw     ,Enrico Zini <enrico@debian.org>
826 kB   debtags:i386          ,Enrico Zini <enrico@debian.org>
910 kB   debtags               ,Enrico Zini <enrico@debian.org>
$
----

// Stichworte für den Index
(((aptitude, Breite der Ausgabe festlegen)))
(((aptitude, search -w)))
(((aptitude, search --width)))
Ohne weitere Angaben benutzt `aptitude` zur Ausgabe die gesamte Breite
des Terminals. Möchten Sie das auf einen bestimmten Wert festlegen,
nutzen Sie dafür den Schalter `-w` (Langform `--width`) gefolgt von der
Anzahl Zeichen. Das nachfolgende Beispiel zeigt Ihnen den Aufruf für
eine Breite von 40 Zeichen. Überflüssige Zeichen schneidet `aptitude` in
der Ausgabe ab.

.Begrenzung der Ausgabe auf eine feste Breite
----
$ aptitude search -w 40 debtags
i   debtags      - Akiviert die Unterstü
p   debtags:i386 - Akiviert die Unterstü
p   python-debta - Vergleicht »hardware:
p   python3-debt - Vergleicht »hardware:
$
----

// Datei (Ende): ./praxis/apt-und-aptitude-auf-die-eigenen-beduerfnisse-anpassen/aptitude-formatstrings.adoc
