// Datei: ./praxis/apt-und-aptitude-auf-die-eigenen-beduerfnisse-anpassen/aptitude-gruppierung.adoc

// Baustelle: Notizen

[[aptitude-gruppierung]]

=== `aptitude`-Gruppierung ===

==== Kommandozeile ====

`aptitude` kennt dazu den Schalter `--group-by`. Eine kurze Version des
Schalters existiert u.E. bislang nicht. Als Wert sind die folgenden
Möglichkeiten zulässig:

`archive`:: 
nach dem Enthaltensein eines Pakets in einer Veröffentlichung, bspw.
`stable` oder `unstable`.

`auto`::
Gruppierung nach dem Paketnamen

`none`::
Darstellung aller Versionen in einer einzigen Liste ohne jegliche
Sortierung

`package`::
Gruppierung nach dem Paketnamen

`source-package`::
Gruppierung nach dem Namen des Sourcepakets

`source-version`::
Gruppierung nach der Version des Sourcepakets

Diese Werte korrespondieren mit der Einstellung
`Aptitude::CmdLine::Versions-Group-By` in der Konfigurationsdatei zu
`aptitude`.

==== Textoberfläche ====

ToDo:

* Anordnung der Spalten in der Text-Modus-Oberfläche
* Breite der Spalten
* welche Spalten sind überhaupt darstellbar
* wie stelle ich das ein

// Datei (Ende): ./praxis/apt-und-aptitude-auf-die-eigenen-beduerfnisse-anpassen/aptitude-gruppierung.adoc
