// Datei: ./praxis/apt-und-aptitude-auf-die-eigenen-beduerfnisse-anpassen/aptitude-gruppierung.adoc

// Baustelle: Rohtext

[[aptitude-gruppierung]]

=== `aptitude`-Gruppierung ===

==== Kommandozeile ====

// Stichworte für den Index
(((aptitude, --group-by)))
(((Aptitude, Auflistung der Pakete umsortieren)))
Zur Gruppierung kennt `aptitude` den Schalter `--group-by`. Eine kurze Version des
Schalters existiert u.E. bislang nicht. Als Wert sind die folgenden
Möglichkeiten zulässig:

`archive`:: 
nach dem Enthaltensein eines Pakets in einer Veröffentlichung, bspw.
`stable` oder `unstable`.

`auto`::
Gruppierung nach dem Paketnamen

`none`::
Darstellung aller Versionen in einer einzigen Liste ohne jegliche
Sortierung

`package`::
Gruppierung nach dem Paketnamen

`source-package`::
Gruppierung nach dem Namen des Sourcepakets

`source-version`::
Gruppierung nach dem Namen und der Version des Sourcepakets

Diese Werte korrespondieren mit der Einstellung
`Aptitude::CmdLine::Versions-Group-By` in der Konfigurationsdatei zu
`aptitude`.

==== Textoberfläche ====

ToDo:

* konfigurierbar ist
** die Anordnung der Spalten zu den Paketen
** die Aufteilung auf dem Bildschirm -- horizontal oder vertikal geteilt

* Anordnung der Spalten in der Text-Modus-Oberfläche
* Breite der Spalten
* welche Spalten sind überhaupt darstellbar
* wie stelle ich das ein

Die Darstellung entnimmt Aptitude der Konfigurationsgruppe
`Aptitude::UI::Default-Package-View`. Diese beinhaltet eine Liste der
darzustellenden Spalten. Jeder Listeneintrag enthält mindestens die
nachfolgenden vier Angaben:

----
Komponentenname Typ {
  Row Zeile;
  Column Spalte;
  Width Breite;
  Height Höhe;
};
----

Typ kann sein:

* Description
* MainWidget
* Static

Zeile, Spalte, Breite und Höhe arrangieren Sie in einer Tabelle, wobei
die obere, linke Ecke die Position 0,0 hat.

Zusatzoptionen für eine Spalte (Auswahl):

* `ColAlign` Ausrichtung
* `ColExpand`
* `Color`
* `ColShrink`

Aufteilung auf dem Bildschirm: siehe <<aptitude-farbschema-anpassen>>

// Datei (Ende): ./praxis/apt-und-aptitude-auf-die-eigenen-beduerfnisse-anpassen/aptitude-gruppierung.adoc
