// Datei: ./praxis/apt-und-aptitude-auf-die-eigenen-beduerfnisse-anpassen/aptitude-formatstrings.adoc

// Baustelle: Rohtext

[[aptitude-format-strings]]
=== `aptitude` Format Strings ===

// Stichworte für den Index
(((aptitude, Format Strings)))
(((aptitude, die Ausgabe anpassen)))
'Format Strings' sind eine spezifische Schreibweise einer Ausgabe anhand
von Platzhaltern. Sie ähneln der Art und Weise, wie sie in der
`printf()`-Funktion in der Programmiersprache C respektive der
`print()`-Funktion in Python üblich sind. Eine ausführliche Beschreibung
der Platzhalter finden Sie im `aptitude`-Handbuch unter 'Customizing the
package list' <<aptitude-dokumentation-package-list>>.

<<tab.aptitude-format-strings>> gibt Ihnen eine Übersicht zu den
verfügbaren Format Strings. Diese Platzhalter helfen Ihnen in
Kombination mit der Suche nach Paketen und bei der Gestaltung der
Ausgabe. Sie bestimmen damit, welche Informationen `aptitude`
spaltenweise zu einem Paket darstellt.

.Format Strings in `aptitude`
[frame="topbot",options="header",cols="1,9",id="tab.aptitude-format-strings"]
|====
| Platzhalter | Bedeutung
| `%a` | Flag für die Aktion des Pakets ('Action Flag')
| `%c` | aktueller Paketstatus ('Current State Flag')
| `%d` | die kurze Paketbeschreibung ('description')
| `%E` | Name des Source-Pakets
| `%I` | die (geschätzte) Installationsgröße ('installed size')
| `%m` | der Name des Paketmaintainers ('maintainer')
| `%M` | gesetzt, falls das Paket automatisch installiert wurde ('Automatic Flag')
| `%p` | Paketname ('package name')
| `%P` | Paketpriorität ('priority')
| `%s` | Bereich, in den das Paket eingeordnet ist ('section')
|====

Die Voreinstellung von `aptitude` beinhaltet die Platzhalter `%c`, `%a`,
`%M`, `%p%` und `d`. Es umfasst somit die einzelnen Spalten mit dem
Paketstatus, der Aktion, das 'Automatic Flag', den Paketnamen und die
Paketbeschreibung. Mit zusätzlichen Trennzeichen und dezimalen Angaben
vor einem Platzhalter legen Sie die Gestaltung der Ausgabe und die
jeweilige Spaltenbreite fest.

Mit der Angabe `%c%a | %15p` erzeugen Sie drei Spalten -- den
Paketstatus, die Aktion des Pakets und den Paketname -- wobei zwischen
der zweiten und dritten Spalte ein senkrechter Trennstrich eingefügt
wird, der davor und danach noch ein Leerzeichen zur besseren Lesbarkeit
umfaßt. Die dritte Spalte hat eine feste Breite von 15 Zeichen, während
die anderen Spalten variabel bleiben. 

// Stichworte für den Index
(((aptitude, Ausgabespalten festlegen)))
(((aptitude, search --display-format)))
(((aptitude, search -F)))
Im Aufruf von `aptitude search` geben Sie die Platzhalterfolge als Wert
zur zusätzlichen Option `-F` (Langform `--display-format`) wie folgt an:

.Individuelle Gestaltung des Ausgabeformats von `aptitude` bei der Suche
nach dem Paket 'tzdata'
----
aptitude search -F "%c%a | %15p" tzdata
i  | tzdata
v  | tzdata:i386
i  | tzdata-java
v  | tzdata-java:i386
v  | tzdata-jessie
v  | tzdata-jessie:i386
----

// Datei (Ende): ./praxis/apt-und-aptitude-auf-die-eigenen-beduerfnisse-anpassen/aptitude-formatstrings.adoc
