// Datei: ./praxis/apt-und-aptitude-auf-die-eigenen-beduerfnisse-anpassen/aptitude-formatstrings.adoc

// Baustelle: Rohtext

[[aptitude-format-strings]]
=== `aptitude` Format Strings ===

'Format Strings' sind eine spezifische Schreibweise einer Ausgabe anhand
von Platzhaltern. Sie ähneln der Art und Weise, wie sie in der
`printf()`-Funktion in der Programmiersprache C respektiver der
`print()`-Funktion in Python üblich sind. Eine ausführliche Beschreibung
der Platzhalter finden Sie im `aptitude`-Handbuch unter 'Customizing the
package list' <<aptitude-dokumentation-package-list>>.

<<tab.aptitude-format-strings>> gibt Ihnen eine Übersicht zu den
verfügbaren Format Strings. Diese Format Strings helfen Ihnen in
Kombination mit der Suche nach Paketen und bei der Gestaltung der
Ausgabe. Sie bestimmen damit, welche Informationen spaltenweise zu einem
Paket sichtbar sind.

.Format Strings in `aptitude`
[frame="topbot",options="header",cols="1,9",id="tab.aptitude-format-strings"]
|====
| Platzhalter | Bedeutung
| `%c` | aktueller Paketstatus ('Current State Flag')
| `%a` | Aktion des Pakets ('Action Flag')
| `%M` | gesetzt, falls das Paket automatisch installiert wurde ('Automatic Flag')
| `%p` | Paketname ('package name')
| `%d` | Paketbeschreibung ('description')
| `%m` | Paketmaintainer ('maintainer')
| `%I` | Installationsgröße ('installed size')
|====

Die Voreinstellung von `aptitude` umfasst den Paketstatus, die Aktion,
das 'Automatic Flag', den Paketnamen und die Paketbeschreibung. Bei der
eigenen Auflistung bestehend aus der Installationsgröße und dem
Paketnamen helfen Ihnen die beiden Schalter `-F` und `--sort` weiter.
Während ersteres den Format String einleitet, kümmert sich der zweite
Schalter um die Sortierung der Ausgabe. 

Nachfolgend sehen Sie eine dreispaltige Ausgabe, die aus der
Installationsgröße nach der Installation, dem Paketnamen und dem
Paketmaintainer besteht. Die Recherche umfasst alle Pakete, die im Namen
die Zeichenkette `debtags` beinhalten.

.Suche nach `debtags`-Paketen mit spezifischer Formatierung der Ausgabe
----
$ aptitude search -F "%I,%15p,%m" debtags
938 kB  ,debtags           ,Enrico Zini <enrico@debian.org>
109 kB  ,python-debtagshw  ,Enrico Zini <enrico@debian.org>
$
----
// Datei (Ende): ./praxis/apt-und-aptitude-auf-die-eigenen-beduerfnisse-anpassen/aptitude-formatstrings.adoc
