// Datei: ./praxis/apt-und-aptitude-auf-die-eigenen-beduerfnisse-anpassen/aptitude-farbschema-anpassen.adoc

// Baustelle: Notizen

[[aptitude-farbschema-anpassen]]
=== `aptitude`-Farbschema anpassen ===

==== Zwischen `aptitude`-Themes wechseln ====
// Stichworte für den Index
(((aptitude, aptitude::Theme)))
(((aptitude, Aussehen der Bedienoberfläche anpassen

Das Aussehen von der `aptitude`-Bedienoberfläche hängt von drei
Einstellungen ab -- den gewählten Farben für Vorder- und Hintergrund, 
der Anordnung der einzelnen Ausgabeelemente für die Bedienoberfläche
(TUI) und dem Wert der Konfigurationsoption `aptitude::Theme`.

Die Farben für die einzelnen Ausgabeelemente sind vollständig im 
`aptitude`-Handbuch <<aptitude-dokumentation-themes>> dokumentiert; wir
widmen dem Thema den <<aptitude-farbschema-anpassen-strukturelemente>>. 
Über welche Elemente die TUI verfügt und wie Sie diese im Ausgabefenster 
anordnen, besprechen wir im <<aptitude-gruppierung>> genauer. 

Bleibt noch obige Konfigurationsoption `aptitude::Theme`, deren
Bedeutung es zu klären gilt. Für diese wählen Sie den Namen des von
Ihnen gewünschten Themes aus. `aptitude` liefert die folgenden zwei
Themes mit:

`Dselect`:: das `aptitude`-Standardtheme, welches an die
Bedienoberfläche des Werkzeugs `dselect` angelehnt ist. Oben befindet
sich der Paketbaum aus Kategorien und den sich darin befindlichen
Softwarepaketen, darunter die Paketbeschreibung zum jeweils ausgewählten
Paket

`Vertical-Split`:: Anordnung, in der die Ausgabe vertikal geteilt ist.
In der linken Spalte befindet der Paketbaum aus Kategorien und den sich
darin befindlichen Softwarepaketen, in der rechten Spalte die
Paketbeschreibung zum jeweils ausgewählten Paket

==== Standardvorgaben ====

`aptitude` kommt mit einer Auswahl an Standardfarben. Diese sind in
<<tab.aptitude-farben>> in <<aptitude>> benannt.

[[aptitude-farbschema-anpassen-strukturelemente]]
==== Eigene Farben vergeben ====

Gefällt Ihnen die mitgelieferte Farbauswahl nicht, bauen Sie sich am
besten ihr eigenes Theme. Dazu legen Sie für die einzelnen
Strukturelemente eigene Farben fest (siehe
<<aptitude-dokumentation-text-colors-and-styles>>). Anpassbare Elemente
sind:

** Bullet
** ChangelogNewerVersion
** Default
** DepBroken
** DisabledMenuEntry
** DownloadHit
** DownloadProgress
** EditLine
** Error
** Header
** HighlightedMenuBar
** HighlightedMenuEntry
** MediaChange
** MenuBar
** MenuBorder
** MenuEntry
** MineBomb
** MineBorder
** MineFlag
** MineNumberN
** MultiplexTab
** MultiplexTabHighlighted
** PkgBroken
** PkgBrokenHighlighted
** PkgNotInstalled
** PkgNotInstalledHighlighted
** PkgIsInstalled
** PkgIsInstalledHighlighted
** PkgToDowngrade
** PkgToDowngradeHighlighted
** PkgToHold
** PkgToHoldHighlighted
** PkgToInstall
** PkgToInstallHighlighted
** PkgToRemove
** PkgToRemoveHighlighted
** PkgToUpgrade
** PkgToUpgradeHighlighted
** Progress
** SolutionActionApproved
** SolutionActionRejected
** Status
** TreeBackground
** TrustWarning

Als Farben steht Ihnen eine Grundauswahl aus 8 Farben zur Verfügung.
<<tab.aptitude-farben-auswahl>> stellt diese zusammen.

.Farbauswahl bei `aptitude`
[options="header", id="tab.aptitude-farben-auswahl"]
|=============================
| Farbname  | Beschreibung
| `black`   | schwarz
| `blue`    | blau
| `cyan`    | hellblau
| `green`   | grün
| `magenta` | dunkelrosa
| `red`     | rot
| `white`   | weiss
| `yellow`  | gelb
|=============================

Ergänzend zur Farbauswahl erlaubt `aptitude` zusätzliche Hervorhebungen.
<<tab.aptitude-farben-hervorhebungen>> fasst die Einstellungen
dafür zusammen

.Hervorhebungen und deren Bedeutung bei `aptitude`
[options="header", id="tab.aptitude-farben-hervorhebungen"]
|=============================
| Hervorhebung | Beschreibung
| `blink`      | Enables blinking text.
| `bold`       | Makes the foreground color of the text (or the background if reverse video is enabled) brighter.
| `dim`        | May cause text to be extra-dim on some terminals. No effect has been observed on common Linux terminals.
| `reverse`    | Swaps the foreground and background colors. Many visual elements flip this attribute to perform common highlighting tasks.
| `standout`   | This enables “the best highlighting mode of the terminal”. In xterms it is similar, but not idential to, reverse video; behavior on other terminals may vary.
| `underline`  | Enables underlined text.
|=============================

* gibt es vorgefertigte Themes zum Download?

* Frage:
** ist das empfehlenswert, oder stiftet das nicht eher Verwirrung?
** Vorlieben und Gewohnheiten
** Sehfähigkeiten (Farben, Kontrast)
** Ausgabegerät, insbesondere Helligkeit


// Datei (Ende): ./praxis/apt-und-aptitude-auf-die-eigenen-beduerfnisse-anpassen/aptitude-farbschema-anpassen.adoc
