// Datei: ./praxis/apt-und-aptitude-auf-die-eigenen-beduerfnisse-anpassen/konfiguration-von-apt.adoc

// Baustelle: Rohtext

[[konfiguration-von-apt]]
=== Konfiguration von APT ===

// Stichworte für den Index
(((/etc/apt/apt.conf)))
(((/etc/apt/apt.conf.d)))
(((/etc/apt/listchanges.conf)))
(((/etc/apt/preferences)))
(((/etc/apt/preferences.d)))
(((/etc/apt/sources.list)))
(((/etc/apt/sources.list.d)))
(((/etc/apt/trusted.gpg)))
(((/etc/apt/trusted.gpg.d)))
(((apt-listchanges)))
(((Debianpaket, apt)))
(((Debianpaket, apt-listchanges)))
(((run-parts)))

APT und auch alle Programme, die die Bibliotheken von APT benutzen, greifen 
auf diverse Konfigurationsdateien zu. Über die Einstellungen darin werden
unterschiedliche Funktionen abgebildet. Alle globalen Konfigurationsdateien 
befinden sich im Verzeichnis `/etc/apt` und beinhalten:

`apt.conf` bzw. `apt.conf.d` :: Grundlegende Einstellungen von APT und den
Bedienschnittstellen (Frontends). Siehe dazu 
<<konfigurationsdateien-von-apt-apt.conf>>.

`listchanges.conf` :: Hinterlegte Einstellungen zu den Änderungen, die bei
der Aktualisierung von Paketen durchgeführt werden. Diese Datei wird vom 
Werkzeug `apt-listchanges` gepflegt (siehe dazu <<qualitaetskontrolle>>).

`preferences` bzw. `preferences.d` :: Diese Einträge steuern, welche Versionen 
von Paketen zur Installation ausgewählt werden (siehe dazu 
<<konfigurationsdateien-von-apt-preferences>>).

`sources.list` bzw. `sources.list.d` :: Beinhaltet die Liste der Paketquellen,
von denen APT Pakete bezieht. Ausführlich gehen wir darauf bereits in 
<<etc-apt-sources.list-verstehen>> ein.

`trusted.gpg` bzw. `trusted.gpg.d` :: Beinhaltet die kryptographischen 
Signaturen in Form von GnuPG-Schlüsseln der verwendeten Paketquellen. Darüber 
wird sichergestellt, welchen Paketquellen APT vertraut (siehe dazu 
<<paketquelle-auf-echtheit-ueberpruefen>>).

Alle Varianten der Konfigurationsdateien gibt es in zwei Geschmäckern:

als einzelne Datei :: Diese ist typischerweise Ihnen als lokaler 
Systemadministrator vorbehalten.

als Verzeichnis mit dem Suffix `.d` :: Alle Dateien in einem solchen 
Verzeichnis werden so interpretiert, als wären sie an der gleichnamigen Datei 
ohne `.d` angehängt (siehe dazu die Manpage zu `run-parts(8)`). Die einzelnen
Dateien müssen bestimmten Regeln hinsichtlich dem Dateinamen entsprechen. 
Insbesondere dürfen keine Punkte im Dateinamen vorkommen. Diese Verzeichnisse 
werden typischerweise von Paketen verwendet, um paketspezifische 
Konfigurationsschnipsel darin abzulegen. Auch Sie als Systemadministrator 
legen darin Dateien ab, bspw. über das Konfigurationsmanagement.

// Datei (Ende): ./praxis/apt-und-aptitude-auf-die-eigenen-beduerfnisse-anpassen/konfiguration-von-apt.adoc

