// Datei: ./praxis/apt-und-aptitude-auf-die-eigenen-beduerfnisse-anpassen/konfigurationsdateien-von-apt.adoc

// Baustelle: Rohtext
// Axel: Rohtext

[[konfigurationsdateien-von-apt]]
=== Konfigurationsdateien von APT im Detail ===

[[konfigurationsdateien-von-apt-apt.conf]]
==== `/etc/apt/apt.conf(.d)` verstehen ====

// Stichworte für den Index
(((/etc/apt/apt.conf)))
(((/etc/apt/apt.conf.d/)))
(((APT-Hooks)))
(((Debianpaket, adequate)))
(((Debianpaket, whatmaps)))

In der Datei `/etc/apt/apt.conf` bzw. in den Dateien im Verzeichnis
`/etc/apt/apt.conf.d/` können viele Aspekte von APT und anderen
APT-Frontends konfiguriert werden. Alle diese Einstellungen
überschreiben Sie bei Bedarf explizit auch auf der Kommandozeile. Dazu
verwenden Sie als Schalter `-o`, gefolgt von der Form `<Schlüssel>=<Wert>`.
Darunter fallen u.a.:

* wie oft APT selbstständig Paketlisten und Pakete herunterladen soll
  (alle Einstellungen, die mit `APT::Periodic::` beginnen),

* ob empfohlene ('Recommends') oder vorgeschlagene Pakete ('Suggests')
per Default installiert werden sollen,

* welche Pakete nie automatisch entfernt werden sollen,

* ob Paketlisten lokal entpackt oder komprimiert gespeichert werden
  sollen,

* welche Kompressionsalgorithmen beim Herunterladen von Paketlisten
  bevorzugt werden sollen,

* wohin APT Paketlisten und Pakete herunterladen soll. (Sollte man
  nicht systemweit ändern, kann aber beim Bearbeiten einer
  Chroot-Umgebung von außen durchaus als Einstellung auf der
  Kommandozeile nützlich sein.)

* An- und Abschalten von Fortschrittsbalken (verfügbar ab APT 1.0),

* wo Changelogs heruntergeladen werden können,

* welche Übersetzungen der Paketlisten heruntergeladen werden sollen,

* welche Parameter APT an `dpkg-deb` übergibt,

* Hooks, z.B. vor und nach dem Auspacken von Paketen,

* Konfigurationen für beliebige Tools im APT-Ökosystem, die ebenfalls
  diese Konfigurationsdateien verwenden, z.B. `aptitude`, `adequate`
  <<Debian-Paket-adequate>>, `whatmaps` <<Debian-Paket-whatmaps>>, etc.

Um das Vorgehen besser zu verstehen, werfen Sie am besten einen Blick in
das Verzeichnis `/etc/apt/apt.conf.d/`. Das nachfolgende Listing zeigt
den typischen Inhalt auf einem Debian 8 'Jessie'.

.Beispielhafter Inhalt von `/etc/apt/apt.conf.d/`
----
$ ls /etc/apt/apt.conf.d/
00trustcdrom    10periodic           20packagekit           99synaptic
01autoremove    20apt-show-versions  50unattended-upgrades
10apt-listbugs  20dbus               70debconf
$
----

[[konfigurationsdateien-von-apt-preferences]]
==== `preferences` bzw. `preferences.d` ====

* ToDo

==== cron.daily/apt ====

* Begriff und Nutzen


// Datei (Ende): ./praxis/apt-und-aptitude-auf-die-eigenen-beduerfnisse-anpassen/konfigurationsdateien-von-apt.adoc
