// Datei: ./praxis/apt-und-aptitude-auf-die-eigenen-beduerfnisse-anpassen/konfiguration-von-apt-anzeigen.adoc

// Baustelle: Fertig

[[konfiguration-von-apt-anzeigen]]
=== Konfiguration von APT anzeigen ===

// Stichworte für den Index
(((apt-config, dump)))
(((apt, Konfiguration anzeigen)))
(((Debianpaket, apt)))
Zu diesem Zweck steht Ihnen das Werkzeug `apt-config` zur Verfügung. Es ist
Bestandteil des Debianpakets 'apt' <<Debian-Paket-apt>>. Das Ziel des von 
den Entwicklern gewählten Schnittstellendesigns besteht in der leichten 
Benutzbarkeit des Programms -- auch von Shellskripten aus (siehe dazu 
<<Debian-Wiki-AptConf>>).

Die Konfiguration von APT erhalten Sie mit dem Schalter `dump`. Nachfolgend 
sehen Sie einen Auszug der Ausgabe. Um diese Informationen zusammenzustellen, 
kombiniert `apt-config` die Inhalte der einzelnen Module zur Konfiguration 
(siehe dazu <<konfigurationsdateien-von-apt>>).

.Ausgabe der aktuellen Einstellungen von APT mittels `apt-config`
----
$ apt-config dump
APT "";
APT::Architecture "i386";
APT::Build-Essential "";
APT::Build-Essential:: "build-essential";
APT::Install-Recommends "true";
APT::Install-Suggests "0";
APT::Authentication "";
APT::Authentication::TrustCDROM "true";
APT::NeverAutoRemove "";
APT::NeverAutoRemove:: "^firmware-linux.*";
APT::NeverAutoRemove:: "^linux-firmware$";
APT::NeverAutoRemove:: "^linux-image.*";
APT::NeverAutoRemove:: "^kfreebsd-image.*";
...
$
----

Weitere nützliche Schalter und Optionen von `apt-config` sind:

`--empty` :: Damit schließen Sie Optionen ein, die einen leeren Wert haben. Das
ist die Standardeinstellung. Das Gegenstück dazu ist `--no-empty`.

`--format` :: Darstellung der Ausgabe steuern. Zulässig sind diese Werte:
+
* `%f` -- vollständiger, hierarchischer Name der Option
* `%n` -- Zeilenumbruch
* `%N` -- Tabulator
* `%t` -- individueller Name der Option (Kurzform von `%f`)
* `%v` -- Wert der Option
+
Die Standardeinstellung ist `%f "%v";%n`. Die nachfolgende Ausgabe zeigt die 
Kurzform der Option inklusive deren Wert. Jede Zeile wird mit einem Semikolon 
abgeschlossen.
+
----
$ apt-config dump --format '%t "%v"; %n'
APT ""; 
Architecture "amd64"; 
Build-Essential ""; 
 "build-essential"; 
Install-Recommends "1"; 
Install-Suggests "0"; 
Sandbox ""; 
...
$ 
----

`--no-empty` :: Damit schließen Sie Optionen aus, die einen leeren Wert haben. 
Das Gegenstück dazu ist `--empty`.

`-c` (Langform `--config-file`) :: Angabe einer Konfigurationsdatei. Diese Datei
wird zusätzlich zur üblichen Konfigurationsdatei gelesen.

`-o` (Langform `--option`) :: Angabe einer Option direkt beim Aufruf. Diesen
Schalter können Sie mehrfach angeben.

// Datei (Ende): ./praxis/apt-und-aptitude-auf-die-eigenen-beduerfnisse-anpassen/konfiguration-von-apt-anzeigen.adoc
