// Datei: ./praxis/apt-und-aptitude-auf-die-eigenen-beduerfnisse-anpassen/konfigurationsoptionen-von-apt.adoc

// Baustelle: Notizen

[[konfigurationsoptionen-von-apt]]
=== Konfigurationsoptionen von APT ===

// Stichworte für den Index
(((APT, Konfigurationsoptionen)))
(((apt, -o)))
(((aptitude, -o)))
(((Aptitude, Konfigurationsoptionen)))
Neben den festen Einstellungen über die Konfigurationsdateien für APT und 
Aptitude (siehe <<konfigurationsdateien-von-apt>>) haben Sie jederzeit die
Möglichkeit, Fähigkeiten der Werkzeuge über Optionen ein- und auszuschalten.
Dazu ergänzen Sie im Aufruf den Schalter `-o`, gefolgt von einem oder 
mehreren Paaren aus Schlüssel und Wert. Nachfolgend besprechen wir die 
einzelnen Schalter genauer.

[[konfigurationsoptionen-von-apt-schalter]]
==== Schalter von Apt ====

* `APT::AutoRemove::RecommendsImportant`

* `APT::AutoRemove::SuggestsImportant`

`APT::Get::List-Cleanup` :: Hierüber steuern Sie, ob Aptitude alte 
 Paketlisten nach dem Bezug einer neuen Paketliste löscht, bspw. nach 
 dem Aufruf von `apt update` (siehe 
 <<liste-der-verfuegbaren-pakete-aktualisieren>>). Die Voreinstellung ist 
 `True`, sprich: ältere Paketlisten werden entfernt. Dieser Schalter ist 
 ein Synonym für `APT::List-Cleanup` und bei der Entscheidung, ob ältere 
 Paketlisten entfernt werden sollen oder nicht, werden beide Schalter 
 ausgewertet. Ist einer von beiden Schaltern auf `False` gesetzt, werden 
 ältere Paketlisten aufgehoben.

`APT::List-Cleanup` :: Hierüber steuern Sie, ob Aptitude alte Paketlisten 
 nach dem Bezug einer neuen Paketliste löscht, bspw. nach dem Aufruf von
 `apt update` (siehe <<liste-der-verfuegbaren-pakete-aktualisieren>>). Die 
 Voreinstellung ist `True`, sprich: ältere Paketlisten werden entfernt. 
 Dieser Schalter ist ein Synonym für `APT::Get::List-Cleanup` und bei der 
 Entscheidung, ob ältere Paketlisten entfernt werden sollen oder nicht, 
 werden beide Schalter ausgewertet. Ist einer von beiden Schaltern auf 
 `False` gesetzt, werden ältere Paketlisten aufgehoben.

* `APT::Install-Recommends`

[[konfigurationsoptionen-von-aptitude-schalter]]
==== Schalter von Aptitude ====

// Stichworte für den Index
(((aptitude, --safe-resolver)))
(((aptitude, -s)))
(((aptitude, --simulate)))

* `Aptitude::Allow-Null-Upgrade`

`Aptitude::Always-Use-Safe-Resolver` :: Hierüber verwendet Aptitude immer 
das sichere Verfahren zur Auflösung von Paketabhängigkeiten. Das ist analog
zur Kommandozeilenoption `--safe-resolver`. Die Voreinstellung ist `False`, 
d.h. Aptitude wendet das Standardverfahren an.

`Aptitude::Autoclean-After-Update` :: Wenn diese Option auf `True` gesetzt 
ist, bereinigt Aptitude alle Dateien im Paketcache nach erfolgreicher 
Aktualisierung von Paketen (oder ähnlichen Operationen). Diese Option ist 
ähnlich zu `Aptitude::Clean-After-Install`. Die Voreinstellung ist `False`, 
d.h. es findet kein Aufräumen statt.

`Aptitude::Auto-Fix-Broken` :: Mit dieser Option fragt Aptitude nach einer
Bestätigung, bevor es versucht, beschädigte Pakete zu reparieren. Die 
Voreinstellung ist `True`, d.h. es erfolgt keine Rückfrage vor der Reparatur.

`Aptitude::Auto-Install` :: Darüber versucht Aptitude, stets die 
Abhängigkeiten eines Pakets zu erfüllen, sobald Sie ein Paket zur 
Installation oder Aktualisierung markiert haben. Die Voreinstellung ist 
`True`, d.h. die Recherche zu den Paketabhängigkeiten ist aktiviert.

`Aptitude::Auto-Install-Remove-Ok` :: Hiermit entfernt Aptitude 
automatisch in Konflikt stehende Pakete, wenn Sie ein Paket zur 
Installation oder Aktualisierung markieren. Normalerweise sind diese
Konflikte von Ihnen manuell zubeheben. Daher ist die Voreinstellung auf 
`False` gesetzt, d.h. Aptitude nimmt keine automatische Entfernung vor.

`Aptitude::Auto-Upgrade` :: Damit markiert Aptitude automatisch alle 
erneuerbaren Pakete für eine Aktualisierung (Upgrade), wenn das Programm 
startet. Die Voreinstellung ist `False`.

`Aptitude::Clean-After-Install` :: Wenn diese Option auf `True` gesetzt
ist, bereinigt Aptitude alle Dateien im Paketcache nach erfolgreicher 
Installation von Paketen (oder ähnlichen Operationen). Diese Option ist 
ähnlich zu `Aptitude::Autoclean-After-Update`. Die Voreinstellung ist 
`False`.

* `Aptitude::CmdLine::Always-Prompt`

* `Aptitude::CmdLine::Assume-Yes`

* `Aptitude::CmdLine::Disable-Columns`

* `Aptitude::CmdLine::Download-Only`

* `Aptitude::CmdLine::Fix-Broken`

* `Aptitude::CmdLine::Versions-Group-By`

* `Aptitude::CmdLine::Ignore-Trust-Violations`

* `Aptitude::CmdLine::Package-Display-Format`

* `Aptitude::CmdLine::Package-Display-Width`

* `Aptitude::CmdLine::Progress::Percent-On-Right`

* `Aptitude::CmdLine::Progress::Retain-Completed`

* `Aptitude::CmdLine::Request-Strictness`

* `Aptitude::CmdLine::Resolver-Debug`

* `Aptitude::CmdLine::Resolver-Dump`

* `Aptitude::CmdLine::Resolver-Show-Steps`

* `Aptitude::CmdLine::Show-Deps`

* `Aptitude::CmdLine::Show-Size-Changes`

* `Aptitude::CmdLine::Show-Summary`

* `Aptitude::CmdLine::Show-Versions`

* `Aptitude::CmdLine::Show-Why`

* `Aptitude::CmdLine::Version-Display-Format`

* `Aptitude::CmdLine::Versions-Show-Package-Names`

* `Aptitude::Safe-Resolver::Show-Resolver-Actions`

* `Aptitude::Screenshot::IncrementalLoadLimit`

* `Aptitude::Screenshot::Cache-Max` 

* `Aptitude::CmdLine::Simulate`

* `Aptitude::CmdLine::Verbose`

* `Aptitude::CmdLine::Visual-Preview`

* `Aptitude::Delete-Unused`

* `Aptitude::Delete-Unused-Pattern`

* `Aptitude::Display-Planned-Action`

* `Aptitude::Forget-New-On-Install`

* `Aptitude::Forget-New-On-Update`

* `Aptitude::Get-Root-Command`

* `Aptitude::Ignore-Old-Tmp`

* `Aptitude::Ignore-Recommends-Important`

* `Aptitude::Keep-Recommends`

* `Aptitude::Keep-Suggests`

* `Aptitude::Keep-Unused-Pattern`

* `Aptitude::LockFile`

* `Aptitude::Localize-Log`

* `Aptitude::Log`

* `Aptitude::Logging::File`

* `Aptitude::Logging::Levels`

* `Aptitude::Parse-Description-Bullets`

* `Aptitude::Pkg-Display-Limit`

* `Aptitude::ProblemResolver::Allow-Break-Holds`

* `Aptitude::ProblemResolver::BreakHoldScore`

* `Aptitude::ProblemResolver::Break-Hold-Level`

* `Aptitude::ProblemResolver::BrokenScore`

* `Aptitude::ProblemResolver::CancelRemovalScore`

* `Aptitude::ProblemResolver::DefaultResolutionScore`

* `Aptitude::ProblemResolver::Discard-Null-Solution`

* `Aptitude::ProblemResolver::EssentialRemoveScore`

* `Aptitude::ProblemResolver::Remove-Essential-Level`

* `Aptitude::ProblemResolver::ExtraScore`

* `Aptitude::ProblemResolver::FullReplacementScore`

* `Aptitude::ProblemResolver::FutureHorizon`

* `Aptitude::ProblemResolver::Hints`

* `Aptitude::ProblemResolver::ImportantScore`

* `Aptitude::ProblemResolver::Infinity`

* `Aptitude::ProblemResolver::InstallScore`

* `Aptitude::ProblemResolver::Keep-All-Level`

* `Aptitude::ProblemResolver::KeepScore`

* `Aptitude::ProblemResolver::NonDefaultScore`

* `Aptitude::ProblemResolver::Non-Default-Level`

* `Aptitude::ProblemResolver::OptionalScore`

* `Aptitude::ProblemResolver::PreserveAutoScore`

* `Aptitude::ProblemResolver::PreserveManualScore`

* `Aptitude::ProblemResolver::RemoveObsoleteScore`

* `Aptitude::ProblemResolver::RemoveScore`

* `Aptitude::ProblemResolver::Remove-Level`

* `Aptitude::ProblemResolver::RequiredScore`

* `Aptitude::ProblemResolver::ResolutionScore`

* `Aptitude::ProblemResolver::Safe-Level`

* `Aptitude::ProblemResolver::SolutionCost`

* `Aptitude::ProblemResolver::StandardScore`

* `Aptitude::ProblemResolver::StepLimit`

* `Aptitude::ProblemResolver::StepScore`

* `Aptitude::ProblemResolver::Trace-Directory`

* `Aptitude::ProblemResolver::Trace-File`

* `Aptitude::ProblemResolver::UndoFullReplacementScore`

* `Aptitude::ProblemResolver::UnfixedSoftScore`

* `Aptitude::ProblemResolver::UpgradeScore`

* `Aptitude::Purge-Unused`

* `Aptitude::Recommends-Important`

* `Aptitude::Safe-Resolver::No-New-Installs`

* `Aptitude::Safe-Resolver::No-New-Upgrades`

* `Aptitude::Sections::Descriptions`

* `Aptitude::Sections::Top-Sections`

`Aptitude::Simulate` :: Hierüber simuliert Aptitude die Änderungen im 
Paketbestand, die stattfinden würden, ohne diese tatsächlich anzuwenden. 
Diese Konfigurationsoption entspricht der Aufrufoption `-s` (Langform 
`--simulate`). Die Voreinstellung ist `False` für 'keine Simulation'.

* `Aptitude::Spin-Interval`

* `Aptitude::Suggests-Important`

* `Aptitude::Suppress-Read-Only-Warning`

`Aptitude::Theme` :: Legt das Farbschema fest, welches Aptitude zur 
Darstellung der einzelnen Elemente in seiner Bedienoberfläche (TUI) 
benutzen soll (siehe dazu <<aptitude-farbschema-anpassen>>).

* Aptitude::Track-Dselect-State

* Aptitude::UI::Advance-On-Action

* Aptitude::UI::Auto-Show-Reasons

* Aptitude::UI::Default-Grouping

* Aptitude::UI::Default-Package-View

* Aptitude::UI::Default-Preview-Grouping

* Aptitude::UI::Default-Sorting

* Aptitude::UI::Description-Visible-By-Default

* Aptitude::UI::Exit-On-Last-Close

* Aptitude::UI::Fill-Text

* Aptitude::UI::Flat-View-As-First-View

* Aptitude::UI::HelpBar

* Aptitude::UI::Incremental-Search

* Aptitude::UI::InfoAreaTabs

* Aptitude::UI::Keybindings

* Aptitude::UI::Menubar-Autohide

* Aptitude::UI::Minibuf-Download-Bar

* Aptitude::UI::Minibuf-Prompts

* Aptitude::UI::New-Package-Commands

* Aptitude::UI::Package-Display-Format

* Aptitude::UI::Package-Header-Format

* Aptitude::UI::Package-Status-Format

* Aptitude::UI::Pause-After-Download

* Aptitude::UI::Preview-Limit

* Aptitude::UI::Prompt-On-Exit

`Aptitude::UI::Styles` :: Mit diesen Angaben legen Sie fest, welchen Stil 
die Textoberfläche von Aptitude benutzt, um die einzelnen Informationsblöcke 
darzustellen (siehe <<aptitude-farbschema-anpassen-strukturelemente>>).

* Aptitude::UI::ViewTabs

* Aptitude::Warn-Not-Root

* DebTags::Vocabulary

* Dir::Aptitude::state

`Quiet` :: Diese Variable legt fest, wie 'gesprächig' Aptitude beim Aufruf 
über die Kommandozeile ist. Der Wert der Voreinstellung ist 0. Je höher 
der Wert ist, umso mehr Informationen zum Fortschritt der Bearbeitung zeigt
Aptitude an.

==== Beispielaufrufe für die Kommandozeile ====

* Todo

// Datei (Ende): ./praxis/apt-und-aptitude-auf-die-eigenen-beduerfnisse-anpassen/konfigurationsoptionen-von-apt.adoc
