= Summary

. link:kann-denn-paketmanagement-spass-machen/kapitel-kann-denn-paketmanagement-spass-machen.adoc[Über dieses Buch]
.. link:kann-denn-paketmanagement-spass-machen/ja.adoc[Kann Paketmanagement Spaß machen?]
.. link:kann-denn-paketmanagement-spass-machen/zum-buch/zum-buch.adoc[Zum Buch]
... link:kann-denn-paketmanagement-spass-machen/zum-buch/autoren.adoc[Über die Autoren]
... link:kann-denn-paketmanagement-spass-machen/zum-buch/wie-entstand-dieses-buch.adoc[Wie und warum dieses Buch entstand]
... link:kann-denn-paketmanagement-spass-machen/zum-buch/grundlagenwissen-fuer-administratoren.adoc[Grundlagenwissen für Administratoren]
.... link:kann-denn-paketmanagement-spass-machen/zum-buch/dokumentation-zu-aptitude.adoc[Dokumentation zu `aptitude`]
... link:kann-denn-paketmanagement-spass-machen/zum-buch/dokumentation-deb-vs-rpm.adoc[Dokumentation `deb` vs. `rpm`]
... link:kann-denn-paketmanagement-spass-machen/zum-buch/was-ist-das-buch.adoc[Was ist das Buch – und was nicht ...]
... link:kann-denn-paketmanagement-spass-machen/zum-buch/zielgruppe.adoc[Zielgruppe und Lernziele]
... link:kann-denn-paketmanagement-spass-machen/zum-buch/vorausgesetztes-wissen-des-lesers.adoc[Vorkenntnisse]
... link:kann-denn-paketmanagement-spass-machen/zum-buch/was-koennen-sie-als-leser-am-ende.adoc[Und das können Sie nach der Lektüre ...]
... link:kann-denn-paketmanagement-spass-machen/zum-buch/buchinfo.adoc[Buchinfo]
.. link:kann-denn-paketmanagement-spass-machen/zum-buch/danksagung.adoc[Danksagung]
 link:konzepte/teil-konzepte.adoc[Konzepte]
. link:konzepte/linux-dschungel/linux-dschungel.adoc[Willkommen im Linux-Dschungel!]
.. link:konzepte/linux-dschungel/was-ist-debian.adoc[Was ist Debian?]
.. link:konzepte/linux-dschungel/debian-architekturen.adoc[Debian-Architekturen]
.. link:konzepte/linux-dschungel/vom-tar.gz-zur-linux-distribution.adoc[Vom `tar.gz` zur Linux-Distribution]
.. link:konzepte/linux-dschungel/debians-paketsystem.adoc[Debians Paketsystem]
.. link:konzepte/linux-dschungel/welche-unix-artigen-betriebssysteme-verwenden-das.adoc[Welche UNIX-artigen Betriebssysteme verwenden das Paketformat und das APT-Paketmanagement]
. link:konzepte/software-in-paketen-organisieren/software-in-paketen-organisieren.adoc[Software in Paketen organisieren]
.. link:konzepte/software-in-paketen-organisieren/paketmanagement-als-begriff.adoc[Was ist Paketmanagement]
.. link:konzepte/software-in-paketen-organisieren/varianten-und-formate-fuer-software-pakete.adoc[Varianten und Formate für Softwarepakete]
.. link:konzepte/software-in-paketen-organisieren/softwarestapel-und-ebenen.adoc[Softwarestapel und Ebenen]
.. link:konzepte/software-in-paketen-organisieren/alternativen-zu-apt.adoc[Alternativen zu APT]
.. link:konzepte/software-in-paketen-organisieren/zusammenspiel-von-dpkg-und-apt.adoc[Zusammenspiel von dpkg und APT]
.. link:konzepte/software-in-paketen-organisieren/vom-monolithischen-programm-zu-programmkomponenten.adoc[Vom monolithischen Programm zu Programmkomponenten]
.. link:konzepte/software-in-paketen-organisieren/debian-paket-varianten.adoc[Debian-Pakete (Varianten)]
.. link:konzepte/software-in-paketen-organisieren/sortierung-der-pakete-nach-verwendungszweck.adoc[Sortierung der Pakete nach Verwendungszweck]
.. link:konzepte/software-in-paketen-organisieren/distributionsbereiche.adoc[Distributionsbereiche]
.. link:konzepte/software-in-paketen-organisieren/veroeffentlichungen.adoc[Veröffentlichungen]
.. link:konzepte/software-in-paketen-organisieren/benennung-eines-debian-pakets.adoc[Benennung einer Paketdatei]
.. link:konzepte/software-in-paketen-organisieren/multiarch-einsetzen.adoc[Multiarch einsetzen]
.. link:konzepte/software-in-paketen-organisieren/paket-prioritaet-und-essentielle-pakete.adoc[Paket-Priorität und essentielle Pakete]
.. link:konzepte/software-in-paketen-organisieren/verbreitungsgrad-von-paketen.adoc[Verbreitungsgrad von Paketen]
.. link:konzepte/software-in-paketen-organisieren/lokale-paketmarkierungen.adoc[Paketflags]
.. link:konzepte/software-in-paketen-organisieren/wie-finde-ich-passende-pakete.adoc[Wie finde ich passende Pakete]
 link:werkzeuge/teil-werkzeuge.adoc[Werkzeuge]
. link:werkzeuge/paketquellen-und-werkzeuge/paketquellen-und-werkzeuge.adoc[Paketquellen und Werkzeuge]
.. link:werkzeuge/paketquellen-und-werkzeuge/paketquellen.adoc[Paketquellen]
.. link:werkzeuge/paketquellen-und-werkzeuge/empfehlung-zum-ablauf-fuer-das-hinzufuegen-und-aendern-von-paketquellen.adoc[Empfehlung zum Ablauf für das Hinzufügen und Ändern von Paketquellen]
.. link:werkzeuge/paketquellen-und-werkzeuge/etc-apt-sources.list-verstehen/etc-apt-sources.list-verstehen.adoc[`/etc/apt/sources.list` verstehen]
... link:werkzeuge/paketquellen-und-werkzeuge/etc-apt-sources.list-verstehen/format-der-paketliste.adoc[Format der Paketliste]
... link:werkzeuge/paketquellen-und-werkzeuge/etc-apt-sources.list-verstehen/format-eines-eintrags.adoc[Format eines Eintrags]
... link:werkzeuge/paketquellen-und-werkzeuge/etc-apt-sources.list-verstehen/beispieleintraege-fuer-offizielle-pakete.adoc[Beispieleinträge für offizielle Pakete]
... link:werkzeuge/paketquellen-und-werkzeuge/etc-apt-sources.list-verstehen/verzeichnis-als-paketquelle.adoc[Verzeichnis als Paketquelle]
... link:werkzeuge/paketquellen-und-werkzeuge/etc-apt-sources.list-verstehen/eintraege-fuer-sicherheitsaktualisierungen.adoc[Einträge für Sicherheitsaktualisierungen]
... link:werkzeuge/paketquellen-und-werkzeuge/etc-apt-sources.list-verstehen/eintraege-fuer-nicht-offizielle-pakete.adoc[Einträge für zusätzliche, nicht-offizielle Pakete]
... link:werkzeuge/paketquellen-und-werkzeuge/etc-apt-sources.list-verstehen/eintraege-fuer-quellpakete.adoc[Einträge für Quellpakete]
... link:werkzeuge/paketquellen-und-werkzeuge/etc-apt-sources.list-verstehen/eintraege-fuer-deutschland.adoc[Einträge für Deutschland]
.. link:werkzeuge/paketquellen-und-werkzeuge/geeigneten-paket-mirror-auswaehlen.adoc[Geeigneten Paketmirror auswählen]
.. link:werkzeuge/paketquellen-und-werkzeuge/am-besten-erreichbaren-paketmirror-finden/am-besten-erreichbaren-paketmirror-finden.adoc[Am besten erreichbaren Paketmirror finden]
... link:werkzeuge/paketquellen-und-werkzeuge/am-besten-erreichbaren-paketmirror-finden/netselect.adoc[Paketquellen mit `netselect` nach Pingzeiten und Entfernung auswählen]
.. link:werkzeuge/paketquellen-und-werkzeuge/automatisiertes-auswaehlen-von-paketquellen.adoc[Automatisiertes Auswählen von Paketquellen]
.. link:werkzeuge/paketquellen-und-werkzeuge/apt-setup.adoc[`apt-setup` -- Erstellung der Paketliste während der Installation]
.. link:werkzeuge/paketquellen-und-werkzeuge/physische-installationsmedien-mit-apt-cdrom-einbinden.adoc[Physische Installationsmedien mit `apt-cdrom` einbinden]
.. link:werkzeuge/paketquellen-und-werkzeuge/eintraege-mit-add-apt-repository-im-griff-behalten.adoc[Einträge mit `add-apt-repository` im Griff behalten]
.. link:werkzeuge/paketquellen-und-werkzeuge/einstellungen-synaptic.adoc[Einstellungen mit Synaptic und im Ubuntu Software Center]
.. link:werkzeuge/paketquellen-und-werkzeuge/debian-und-ubuntu-sources-list-generator.adoc[Debian und Ubuntu Sources List Generator]
.. link:werkzeuge/paketquellen-und-werkzeuge/paketquelle-auf-echtheit-ueberpruefen.adoc[Paketquelle auf Echtheit überprüfen]
.. link:werkzeuge/paketquellen-und-werkzeuge/liste-der-verfuegbaren-pakete-aktualisieren.adoc[Liste der verfügbaren Pakete aktualisieren]
.. link:werkzeuge/paketquellen-und-werkzeuge/lokale-paketliste-und-paketcache.adoc[Lokale Paketliste und Paketcache]
.. link:werkzeuge/paketquellen-und-werkzeuge/lokale-paketliste-reparieren.adoc[Lokale Paketliste reparieren]
. link:werkzeuge/debian-paketformat-im-detail/debian-paketformat-im-detail.adoc[Debian-Paketformat im Detail]
.. link:werkzeuge/debian-paketformat-im-detail/konzepte-und-ideen-dahinter.adoc[Konzepte und Ideen dahinter]
.. link:werkzeuge/debian-paketformat-im-detail/aufbau-und-format.adoc[Aufbau und Format]
. link:werkzeuge/apt-und-bibliotheken/apt-und-bibliotheken.adoc[APT und Bibliotheken]
. link:werkzeuge/werkzeuge-zur-paketverwaltung-ueberblick/werkzeuge-zur-paketverwaltung-ueberblick.adoc[Werkzeuge zur Paketverwaltung (Überblick)]
.. link:werkzeuge/werkzeuge-zur-paketverwaltung-ueberblick/frontends-fuer-das-paketmanagement.adoc[Frontends für das Paketmanagement]
.. link:werkzeuge/werkzeuge-zur-paketverwaltung-ueberblick/fuer-die-kommandozeile/fuer-die-kommandozeile.adoc[Für die Kommandozeile]
... link:werkzeuge/werkzeuge-zur-paketverwaltung-ueberblick/fuer-die-kommandozeile/dpkg.adoc[`dpkg`]
... link:werkzeuge/werkzeuge-zur-paketverwaltung-ueberblick/fuer-die-kommandozeile/apt.adoc[APT]
... link:werkzeuge/werkzeuge-zur-paketverwaltung-ueberblick/fuer-die-kommandozeile/aptsh.adoc[Die `aptsh`]
... link:werkzeuge/werkzeuge-zur-paketverwaltung-ueberblick/fuer-die-kommandozeile/wajig.adoc[`wajig`]
... link:werkzeuge/werkzeuge-zur-paketverwaltung-ueberblick/fuer-die-kommandozeile/cupt.adoc[Cupt]
.. link:werkzeuge/werkzeuge-zur-paketverwaltung-ueberblick/ncurses-basiert/ncurses-basiert.adoc[ncurses-basierte Programme]
... link:werkzeuge/werkzeuge-zur-paketverwaltung-ueberblick/ncurses-basiert/tasksel.adoc[tasksel]
... link:werkzeuge/werkzeuge-zur-paketverwaltung-ueberblick/ncurses-basiert/aptitude.adoc[`aptitude`]
.. link:werkzeuge/werkzeuge-zur-paketverwaltung-ueberblick/gui-zur-paketverwaltung/gui-zur-paketverwaltung.adoc[GUI zur Paketverwaltung]
... link:werkzeuge/werkzeuge-zur-paketverwaltung-ueberblick/gui-zur-paketverwaltung/synaptic.adoc[Synaptic]
... link:werkzeuge/werkzeuge-zur-paketverwaltung-ueberblick/gui-zur-paketverwaltung/muon.adoc[Muon]
... link:werkzeuge/werkzeuge-zur-paketverwaltung-ueberblick/gui-zur-paketverwaltung/smartpm.adoc[Smart Package Management (SmartPM)]
... link:werkzeuge/werkzeuge-zur-paketverwaltung-ueberblick/gui-zur-paketverwaltung/ubuntu-software-center.adoc[Ubuntu Software Center]
... link:werkzeuge/werkzeuge-zur-paketverwaltung-ueberblick/gui-zur-paketverwaltung/packagekit.adoc[PackageKit]
... link:werkzeuge/werkzeuge-zur-paketverwaltung-ueberblick/gui-zur-paketverwaltung/gdebi.adoc[GDebi]
.. link:werkzeuge/werkzeuge-zur-paketverwaltung-ueberblick/webbasierte-programme/webbasierte-programme.adoc[Webbasierte Programme]
... link:werkzeuge/werkzeuge-zur-paketverwaltung-ueberblick/webbasierte-programme/dpkg-www.adoc[In Paketen blättern mittels `dpkg-www`]
... link:werkzeuge/werkzeuge-zur-paketverwaltung-ueberblick/webbasierte-programme/ubuntu-landscape.adoc[Ubuntu Landscape]
... link:werkzeuge/werkzeuge-zur-paketverwaltung-ueberblick/webbasierte-programme/appnr.adoc[Appnr]
... link:werkzeuge/werkzeuge-zur-paketverwaltung-ueberblick/webbasierte-programme/communtu.adoc[Communtu]
... link:werkzeuge/werkzeuge-zur-paketverwaltung-ueberblick/webbasierte-programme/univention.adoc[Univention Corporate Server (UCS)]
. link:werkzeuge/paketcache/paketcache.adoc[Paketcache]
.. link:werkzeuge/paketcache/hintergrundwissen.adoc[Hintergrundwissen]
.. link:werkzeuge/paketcache/paketcache-status.adoc[Paketcache-Status]
.. link:werkzeuge/paketcache/paketcache-aufraeumen.adoc[Paketcache aufräumen]
. link:werkzeuge/paketoperationen/paketoperationen.adoc[Paketoperationen]
.. link:werkzeuge/paketoperationen/paketoperationen-und-deren-abfolge.adoc[Paketoperationen und deren Abfolge]
.. link:werkzeuge/paketoperationen/paketlisten-und-muster.adoc[Paketlisten und Muster]
.. link:werkzeuge/paketoperationen/bekannte-paketnamen-auflisten.adoc[Bekannte Paketnamen auflisten]
.. link:werkzeuge/paketoperationen/paketstatus-erfragen.adoc[Paketstatus erfragen]
.. link:werkzeuge/paketoperationen/liste-der-installierten-pakete-anzeigen-und-deuten.adoc[Liste der installierten Pakete anzeigen und deuten]
.. link:werkzeuge/paketoperationen/liste-der-installierten-kernelpakete-anzeigen.adoc[Liste der installierten Kernelpakete anzeigen]
.. link:werkzeuge/paketoperationen/neue-pakete-anzeigen.adoc[Neue Pakete anzeigen]
.. link:werkzeuge/paketoperationen/pakete-nach-prioritaeten-finden.adoc[Pakete nach Prioritäten finden]
.. link:werkzeuge/paketoperationen/automatisch-installierte-pakete-anzeigen.adoc[Automatisch installierte Pakete anzeigen]
.. link:werkzeuge/paketoperationen/obsolete-pakete-anzeigen.adoc[Obsolete Pakete anzeigen]
.. link:werkzeuge/paketoperationen/aktualisierbare-pakete-anzeigen.adoc[Aktualisierbare Pakete anzeigen]
.. link:werkzeuge/paketoperationen/installationsgroesse-eines-pakets.adoc[Installationsgröße eines Pakets]
.. link:werkzeuge/paketoperationen/groesstes-installiertes-paket-finden.adoc[Größtes installiertes Paket finden]
.. link:werkzeuge/paketoperationen/warum-ist-ein-paket-installiert.adoc[Warum ist ein Paket installiert]
.. link:werkzeuge/paketoperationen/liste-der-zuletzt-installierten-pakete-anzeigen.adoc[Liste der zuletzt installierten Pakete anzeigen]
.. link:werkzeuge/paketoperationen/paketabhaengigkeiten-anzeigen.adoc[Paketabhängigkeiten anzeigen]
.. link:werkzeuge/paketoperationen/aus-welchem-repo-kommen-die-pakete.adoc[Aus welchem Repo kommen die Pakete]
.. link:werkzeuge/paketoperationen/pakete-ueber-den-namen-finden.adoc[Pakete über den Namen finden]
.. link:werkzeuge/paketoperationen/pakete-ueber-die-paketbeschreibung-finden.adoc[Pakete über die Paketbeschreibung finden]
.. link:werkzeuge/paketoperationen/paket-nach-maintainer-finden.adoc[Paket nach Maintainer finden]
.. link:werkzeuge/paketoperationen/paket-zu-datei-finden.adoc[Paket zu Datei finden]
.. link:werkzeuge/paketoperationen/paketinhalte-anzeigen-apt-file.adoc[Paketinhalte anzeigen (`apt-file`)]
.. link:werkzeuge/paketoperationen/nach-muster-in-einem-paket-suchen.adoc[Nach Muster in einem Paket suchen]
.. link:werkzeuge/paketoperationen/ausfuehrbare-dateien-anzeigen.adoc[Ausführbare Dateien anzeigen]
.. link:werkzeuge/paketoperationen/manpages-anzeigen.adoc[Manpages anzeigen]
.. link:werkzeuge/paketoperationen/konfigurationsdateien-eines-pakets-anzeigen.adoc[Konfigurationsdateien eines Pakets anzeigen]
.. link:werkzeuge/paketoperationen/paketaenderungen-nachlesen.adoc[Paketänderungen nachlesen]
.. link:werkzeuge/paketoperationen/paket-auf-veraenderungen-pruefen.adoc[Paket auf Veränderungen prüfen]
.. link:werkzeuge/paketoperationen/liste-der-zuletzt-geaenderten-abhaengigkeiten.adoc[Liste der zuletzt geänderten Abhängigkeiten]
.. link:werkzeuge/paketoperationen/paketdatei-nur-herunterladen.adoc[Paketdatei nur herunterladen]
.. link:werkzeuge/paketoperationen/installation-zwischengespeicherter-pakete-aus-dem-paketcache.adoc[Installation zwischengespeicherter Pakete aus dem Paketcache]
.. link:werkzeuge/paketoperationen/sourcepakete-beziehen.adoc[Sourcepakete beziehen]
.. link:werkzeuge/paketoperationen/sourcepakete-anzeigen.adoc[Sourcepakete anzeigen]
.. link:werkzeuge/paketoperationen/bezogenes-paket-verifizieren.adoc[Bezogenes Paket verifizieren (GPG-Key)]
.. link:werkzeuge/paketoperationen/pakete-installieren.adoc[Pakete installieren]
.. link:werkzeuge/paketoperationen/pakete-erneut-installieren.adoc[Pakete erneut installieren]
.. link:werkzeuge/paketoperationen/pakete-konfigurieren.adoc[Pakete konfigurieren]
.. link:werkzeuge/paketoperationen/pakete-aktualisieren.adoc[Pakete aktualisieren]
.. link:werkzeuge/paketoperationen/pakete-downgraden.adoc[Pakete downgraden]
.. link:werkzeuge/paketoperationen/pakete-deinstallieren.adoc[Pakete deinstallieren]
.. link:werkzeuge/paketoperationen/umgang-mit-waisen.adoc[Umgang mit Waisen]
.. link:werkzeuge/paketoperationen/paketoperationen-erzwingen.adoc[Paketoperationen erzwingen]
.. link:werkzeuge/paketoperationen/paketstatusdatenbank-reparieren.adoc[Paketstatusdatenbank reparieren]
.. link:werkzeuge/paketoperationen/distribution-aktualisieren.adoc[Distribution aktualisieren (update und upgrade)]
. link:werkzeuge/dokumentation/dokumentation.adoc[Dokumentation]
.. link:werkzeuge/dokumentation/apt-dpkg-referenzliste.adoc[Die apt-dpkg-Referenzliste]
.. link:werkzeuge/dokumentation/apt-doc.adoc[`apt-doc` -- das Benutzerhandbuch zu APT]
.. link:werkzeuge/dokumentation/nixcraft-apt-cheatsheet.adoc[APT-Spickzettel von Nixcraft]
.. link:werkzeuge/dokumentation/pacman-rosetta.adoc[Pacman Rosetta]
.. link:werkzeuge/dokumentation/aptitude-handbuch.adoc[Handbuch zu `aptitude`]
.. link:werkzeuge/dokumentation/the-debian-administrators-handbook.adoc[The Debian Administrator's Handbook]
.. link:werkzeuge/dokumentation/weitere-buecher.adoc[Weitere Bücher]
 link:praxis/teil-praxis.adoc[Praxis]
. link:praxis/apt-und-aptitude-auf-die-eigenen-beduerfnisse-anpassen/apt-und-aptitude-auf-die-eigenen-beduerfnisse-anpassen.adoc[APT und `aptitude` auf die eigenen Bedürfnisse anpassen]
.. link:praxis/apt-und-aptitude-auf-die-eigenen-beduerfnisse-anpassen/konfigurationsdateien-von-apt.adoc[Konfigurationsdateien von APT]
.. link:praxis/apt-und-aptitude-auf-die-eigenen-beduerfnisse-anpassen/konfiguration-von-apt-anzeigen.adoc[Konfiguration von APT anzeigen]
.. link:praxis/apt-und-aptitude-auf-die-eigenen-beduerfnisse-anpassen/interaktives-aendern-von-optionen.adoc[Interaktives Ändern von Optionen]
.. link:praxis/apt-und-aptitude-auf-die-eigenen-beduerfnisse-anpassen/aptitude-formatstrings.adoc[`aptitude` Format Strings]
.. link:praxis/apt-und-aptitude-auf-die-eigenen-beduerfnisse-anpassen/aptitude-gruppierung.adoc[`aptitude`-Gruppierung]
.. link:praxis/apt-und-aptitude-auf-die-eigenen-beduerfnisse-anpassen/aptitude-farbschema-anpassen.adoc[`aptitude`-Farbschema anpassen]
. link:praxis/mit-aptitude-vormerkungen-machen/mit-aptitude-vormerkungen-machen.adoc[Mit `aptitude` Vormerkungen machen]
.. link:praxis/mit-aptitude-vormerkungen-machen/vormerkungen-ueber-die-kommandozeile-durchfuehren.adoc[Vormerkungen über die Kommandozeile durchführen]
.. link:praxis/mit-aptitude-vormerkungen-machen/vormerkungen-ueber-die-textoberflaeche-durchfuehren.adoc[Vormerkungen über die Textoberfläche durchführen]
.. link:praxis/mit-aptitude-vormerkungen-machen/bestehende-vormerkungen-anzeigen.adoc[Bestehende Vormerkungen anzeigen]
.. link:praxis/mit-aptitude-vormerkungen-machen/vormerkungen-simulieren.adoc[Vormerkungen simulieren]
.. link:praxis/mit-aptitude-vormerkungen-machen/vormerkungen-wieder-aufheben.adoc[Vormerkungen wieder aufheben]
.. link:praxis/mit-aptitude-vormerkungen-machen/vormerkungen-ausfuehren.adoc[Vormerkungen ausführen]
.. link:praxis/mit-aptitude-vormerkungen-machen/risiken-und-seiteneffekte.adoc[Risiken und Seiteneffekte]
. link:praxis/apt-und-aptitude-mischen/apt-und-aptitude-mischen.adoc[APT und `aptitude` mischen]
.. link:praxis/apt-und-aptitude-mischen/sollten-sie-das-ueberhaupt-machen.adoc[Sollten Sie das überhaupt machen?]
.. link:praxis/apt-und-aptitude-mischen/was-ist-zu-beachten-wenn-sie-das-machen.adoc[Was ist zu beachten, wenn Sie das machen]
.. link:praxis/apt-und-aptitude-mischen/empfehlungen-fuer-dokumentation-und-beispiele.adoc[Empfehlungen für Dokumentation und Beispiele]
. link:praxis/debtags/debtags.adoc[Erweiterte Paketklassifikation mit Debtags]
.. link:praxis/debtags/debtags-einfuehrung.adoc[Einführung]
.. link:praxis/debtags/debtags-projekt.adoc[Kurzinfo zum Debtags-Projekt]
.. link:praxis/debtags/debtags-webseite.adoc[Webseite zum Projekt]
.. link:praxis/debtags/debtags-werkzeuge.adoc[Debtags-Werkzeuge]
.. link:praxis/debtags/vergebene-schlagworte-anzeigen.adoc[Vergebene Schlagworte anzeigen]
.. link:praxis/debtags/suche-anhand-der-schlagworte.adoc[Suche anhand der Schlagworte]
.. link:praxis/debtags/pakete-um-schlagworte-ergaenzen.adoc[Pakete um Schlagworte ergänzen]
.. link:praxis/debtags/verwendetes-vokabular-bearbeiten-und-erweitern.adoc[Verwendetes Vokabular bearbeiten und erweitern]
. link:praxis/mehrere-pakete-in-einem-schritt-aendern/mehrere-pakete-in-einem-schritt-aendern.adoc[Mehrere Pakete in einem Schritt ändern]
.. link:praxis/mehrere-pakete-in-einem-schritt-aendern/mit-apt-get.adoc[Mit `apt-get`]
.. link:praxis/mehrere-pakete-in-einem-schritt-aendern/mit-aptitude.adoc[`aptitude`]
. link:praxis/ausgewaehlte-pakete-aktualisieren.adoc[Ausgewählte Pakete aktualisieren]
. link:praxis/ausgewaehlte-pakete-nicht-aktualisieren.adoc[Ausgewählte Pakete nicht aktualisieren]
. link:praxis/fehlende-pakete-bei-bedarf-hinzufuegen/fehlende-pakete-bei-bedarf-hinzufuegen.adoc[Fehlende Pakete bei Bedarf hinzufügen]
.. link:praxis/fehlende-pakete-bei-bedarf-hinzufuegen/neue-hardware.adoc[Neue Hardware]
.. link:praxis/fehlende-pakete-bei-bedarf-hinzufuegen/neue-software.adoc[Neue Software]
. link:praxis/alternatives/alternatives.adoc[Alternative Standard-Programme mit Debians Alternativen-System]
. link:praxis/debian-backports.adoc[Backports]
. link:praxis/veroeffentlichungen-mischen/veroeffentlichungen-mischen.adoc[Veröffentlichungen mischen]
.. link:praxis/veroeffentlichungen-mischen/pinning-default.adoc[Die bevorzugte Veröffentlichung für alle Pakete festlegen]
.. link:praxis/veroeffentlichungen-mischen/pinning-apt-get.adoc[`apt-get` mit expliziter Angabe der Veröffentlichung]
.. link:praxis/veroeffentlichungen-mischen/von-apt-zu-apt-pinning.adoc[Von APT zu APT-Pinning]
.. link:praxis/veroeffentlichungen-mischen/pinning-paketweise-festlegen.adoc[Paketweise festlegen]
.. link:praxis/veroeffentlichungen-mischen/pinning-praktische-beispiele.adoc[Praktische Beispiele]
. link:praxis/checkinstall.adoc[Pakete bauen mit `checkinstall`]
. link:praxis/paketformate-mischen/paketformate-mischen.adoc[Paketformate mischen]
.. link:praxis/paketformate-mischen/einfuehrung.adoc[Einführung]
.. link:praxis/paketformate-mischen/alien.adoc[Fremdformate mit `alien` hinzufügen]
... link:praxis/paketformate-mischen/apt4rpm.adoc[`deb`-Pakete in `rpm`-Strukturen]
. link:praxis/webbasierte-installation-von-paketen/webbasierte-installation-von-paketen.adoc[Webbasierte Installation von Paketen mit `apturl`]
.. link:praxis/webbasierte-installation-von-paketen/sinn-und-zweck.adoc[Sinn und Zweck]
.. link:praxis/webbasierte-installation-von-paketen/risiken-und-bedenken.adoc[Risiken und Bedenken]
.. link:praxis/webbasierte-installation-von-paketen/apturl-in-der-praxis.adoc[apturl in der Praxis]
. link:praxis/paketverwaltung-beschleunigen/paketverwaltung-beschleunigen.adoc[Paketverwaltung beschleunigen]
.. link:praxis/paketverwaltung-beschleunigen/hintergrund.adoc[Hintergrund]
.. link:praxis/paketverwaltung-beschleunigen/moeglichkeiten-zur-beschleunigung.adoc[Möglichkeiten zur Beschleunigung]
.. link:praxis/paketverwaltung-beschleunigen/empfehlungen-zum-umgang-im-alltag.adoc[Empfehlungen zum Umgang im Alltag]
. link:praxis/apt-cache/apt-cache.adoc[Einen APT-Cache einrichten]
.. link:praxis/apt-cache/begriff.adoc[Begriff]
.. link:praxis/apt-cache/approx.adoc[approx]
.. link:praxis/apt-cache/apt-cacher.adoc[apt-cacher]
.. link:praxis/apt-cache/apt-cacher-ng.adoc[apt-cacher-ng]
.. link:praxis/apt-cache/debtorrent.adoc[debtorrent]
. link:praxis/cache-verzeichnis-auf-separater-partition/cache-verzeichnis-auf-separater-partition.adoc[Cache-Verzeichnis auf separater Partition]
. link:praxis/apt-mirror/eigenen-apt-mirror-anlegen.adoc[Einen eigenen APT-Mirror aufsetzen]
.. link:praxis/apt-mirror/apt-mirror.adoc[apt-mirror]
.. link:praxis/apt-mirror/debmirror.adoc[debmirror]
.. link:praxis/apt-mirror/debpartial-mirror.adoc[debpartial-mirror]
.. link:praxis/apt-mirror/reprepro.adoc[reprepro]
. link:praxis/plattenplatz-sparen-mit-der-paketverwaltung.adoc[Plattenplatz sparen mit der Paketverwaltung]
. link:praxis/automatisierte-installation/automatisierte-installation.adoc[Automatisierte Installation]
. link:praxis/automatisierte-aktualisierung/automatisierte-aktualisierung.adoc[Automatisierte Aktualisierung]
. link:praxis/qualitaetskontrolle/qualitaetskontrolle.adoc[Qualitätskontrolle]
.. link:praxis/qualitaetskontrolle/nicht-installierte-pakete-mit-lintian-pruefen/lintian.adoc[Nicht installierte Pakete mit `lintian` prüfen]
.. link:praxis/qualitaetskontrolle/bereits-installierte-pakete-mit-adequate-pruefen/adequate.adoc[Bereits installierte Pakete mit `adequate` prüfen]
.. link:praxis/qualitaetskontrolle/bugreports-anzeigen/bugreports-anzeigen.adoc[Bugreports anzeigen]
... link:praxis/qualitaetskontrolle/bugreports-anzeigen/hintergrundwissen.adoc[Hintergrundwissen]
... link:praxis/qualitaetskontrolle/bugreports-anzeigen/apt-listbugs.adoc[Bugreports mit `apt-listbugs` lesen]
... link:praxis/qualitaetskontrolle/bugreports-anzeigen/apt-listchanges.adoc[Ergänzende Bugreports mit `apt-listchanges` herausfiltern]
... link:praxis/qualitaetskontrolle/bugreports-anzeigen/popbugs.adoc[Release-kritische Fehler mit `popbugs` finden]
... link:praxis/qualitaetskontrolle/bugreports-anzeigen/rc-alert.adoc[Release-kritische Fehler mit `rc-alert` finden]
... link:praxis/qualitaetskontrolle/bugreports-anzeigen/how-can-i-help.adoc[Welche der von mir genutzten Pakete benötigen Hilfe?]
.. link:praxis/qualitaetskontrolle/debian-security-support/debian-security-support.adoc[Auslaufende Sicherheitsaktualisierungen mit `check-support-status` anzeigen]
. link:praxis/versionierte-paketverwaltung.adoc[Versionierte Paketverwaltung]
. link:praxis/snapshots.adoc[Pakete und Patche datumsbezogen auswählen]
. link:praxis/mobile-geraete/mobile-geraete.adoc[Paketverwaltung mit eingeschränkten Ressourcen für Embedded und Mobile Devices]
.. link:praxis/mobile-geraete/localepurge.adoc[localepurge]
. link:praxis/paketverwaltung-ohne-internet/paketverwaltung-ohne-internet.adoc[Paketverwaltung ohne Internet]
.. link:praxis/paketverwaltung-ohne-internet/hintergrund-und-einsatzfelder.adoc[Hintergrund und Einsatzfelder]
.. link:praxis/paketverwaltung-ohne-internet/strategien.adoc[Strategien]
.. link:praxis/paketverwaltung-ohne-internet/werkzeuge.adoc[Werkzeuge]
... link:praxis/paketverwaltung-ohne-internet/offline-verwaltung-mit-apt-get-und-wget.adoc[Offline-Verwaltung mit 'apt-get' und 'wget']
... link:praxis/paketverwaltung-ohne-internet/apt-offline.adoc[Das Projekt 'apt-offline']
.... link:praxis/paketverwaltung-ohne-internet/keryx.adoc[Keryx]
. link:praxis/systeme-mit-schlechter-anbindung-warten/systeme-mit-schlechter-anbindung-warten.adoc[Systeme mit schlechter Internet-Anbindung warten]
.. link:praxis/systeme-mit-schlechter-anbindung-warten/debdelta.adoc[debdelta]
.. link:praxis/systeme-mit-schlechter-anbindung-warten/pdiffs.adoc[PDiffs]
. link:praxis/apt-aptitude-wunschzettel.adoc[Der APT- und `aptitude`-Wunschzettel]
 link:./ausblick/ausblick.adoc[Ausblick]
. link:./quellen/quellen.adoc[Bibliography]
 link:anhang/teil-anhang.adoc[Anhang]
. link:anhang/anhang-debian-architekturen/anhang-debian-architekturen.adoc[Debian-Architekturen]
.. link:anhang/anhang-debian-architekturen/offizielle-architekturen.adoc[Offizielle Architekturen]
.. link:anhang/anhang-debian-architekturen/veraltete-architekturen.adoc[Veraltete Architekturen]
.. link:anhang/anhang-debian-architekturen/architekturen-zukunft.adoc[Architekturen, deren Unterstützung vorgesehen ist]
. link:anhang/anhang-paketkommando/rpm-yum-dpkg.adoc[Kommandos zur Paketverwaltung im Vergleich]
. link:anhang/paketformat-im-einsatz/paketformat-im-einsatz.adoc[Paketformat im Einsatz]
. link:./index/index.adoc[Stichwortverzeichnis]

