// Datei: ./werkzeuge/paketoperationen/pakete-konfigurieren/pakete-konfigurieren.adoc

// Baustelle: Rohtext

[[pakete-konfigurieren]]

=== Pakete konfigurieren ===

// Stichworte für den Index
(((Paket, erneut konfigurieren)))
(((Paket, Konfiguration ändern)))
(((Paket, bestehende Konfiguration anzeigen)))
(((Paket, konfigurieren)))

Im Normalfall liegen die Debianpakete entweder bereits fertig
konfiguriert oder mit einer vorbereiteten Konfiguration auf dem
Spiegelserver. Dafür zeichnet der Paketmaintainer verantwortlich. Mit
verschiedenen Werkzeugen zeigen Sie diese Konfiguration an oder
justieren das Paket neu.

// Bestehende Konfiguration eines Pakets anzeigen
include::bestehende-konfiguration-eines-pakets-anzeigen.adoc[]

// Konfiguration für alle Pakete auslesen
include::konfiguration-fuer-alle-pakete-auslesen.adoc[]

// Bestehende Konfiguration anwenden
include::bestehende-konfiguration-anwenden.adoc[]

[[dpkg-reconfigure]]
==== Konfiguration mit `dpkg-reconfigure` erneut durchführen ====

// Stichworte für den Index
(((debconf)))
(((debconf-get-selections)))
(((Debianpaket, debconf)))
(((Debianpaket, debconf-utils)))
(((Debianpaket, dpkg)))
(((dpkg-reconfigure)))
(((Konfigurationsdatei, /var/cache/debconf)))
(((Paket, erneut konfigurieren)))

* Aufruf: `dpkg-reconfigure Paket`
* konfiguriert ein bereits installiertes Paket erneut
* verwendet wird dazu `debconf`, welches eine Datenbank mit den
Konfigurationseinträgen der Pakete unter `/var/cache/debconf` speichert

* Beispiel:
** locale-Einstellungen (Sprache, Lokalisierung, Zeichensatz)
** Einstellung für die Zeitzone (Paket 'tzdata' <<Debian-Paket-tzdata>>)

// Datei (Ende): ./werkzeuge/paketoperationen/pakete-konfigurieren/pakete-konfigurieren.adoc
