// Datei: ./werkzeuge/paketquellen-und-werkzeuge/am-besten-erreichbaren-paketmirror-finden/apt-spy/apt-spy.adoc

// Baustelle: Rohtext

==== Paketquellen mit `apt-spy` einstellen ====

// Stichworte für den Index
(((apt-spy, Verfügbarkeit)))
(((Debianpaket, apt-spy)))

[NOTE]
.Verfügbarkeit von `apt-spy`
====
`apt-spy` gehört bis einschließlich Debian 7 _Wheezy_ zum festen
Paketbestand. Für Debian 8 _Jessie_ gibt es kein offizielles Paket mehr.
Es steht jedoch weiterhin in _unstable_ zur Verfügung.
====

Das Werkzeug `apt-spy` aus dem gleichnamigen Debian-Paket
<<Debian-Paket-apt-spy>> erstellt eine Liste der Paketquellen für eine
netzbasierte Installation. Basis dafür sind die verfügbaren Paketmirror
und deren Erreichbarkeit.

// Paketquellen nach Bandbreite auswaehlen
include::paketquellen-nach-bandbreite-auswaehlen.adoc[]

// apt-spy konfigurieren
include::apt-spy-konfigurieren.adoc[]

// Schalter und Beispiele
include::schalter-und-beispiele.adoc[]

// Datei (Ende): ./werkzeuge/paketquellen-und-werkzeuge/am-besten-erreichbaren-paketmirror-finden/apt-spy/apt-spy.adoc
