// Datei: ./werkzeuge/paketquellen-und-werkzeuge/am-besten-erreichbaren-paketmirror-finden/apt-spy/paketquellen-nach-bandbreite-auswaehlen.adoc

// Baustelle: Rohtext

[[paketquellen-nach-bandbreite-auswaehlen]]

===== Paketquellen nach Bandbreite auswählen =====

In den meisten Fällen wissen Sie, welche Paketquellen Sie als
Bezugspunkt für ihr Linuxsystem verwenden möchten, sei es aus
Gewohnheit, langjähriger Erfahrung als Systembetreuer oder auf der
Grundlage von Vorgaben für eine bereits bestehende Infrastruktur. Sind
Sie hingegen frei in ihrer Entscheidung, kann Ihnen das Programm
`apt-spy` <<Debian-Paket-apt-spy>> helfen, die Paketquellen für eine
netzbasierte Installation zu ermitteln, die von ihrem Standort aus am
besten erreichbar sind. 

Dazu untersucht `apt-spy` die Paketmirrors für die angefragte Region
bzgl. ihrer Bandbreite, Erreichbarkeit und damit indirekt zur
Verlustrate der übertragenen Netzwerkpakete. Ohne Belang ist dabei, wie
weit der Paketmirror netztechnisch von ihrem Standort aus entfernt ist,
sprich: wieviele Zwischenknoten (Hops) zu berücksichtigen sind. 

Das kann auch dazu führen, dass schwächere, lokale Paketmirrors außen
vor bleiben, wenn ein anderer, erreichbarer Paketmirror schneller und
mit einer höheren Bandbreite verfügbar ist. Um einen Paketmirror
einschätzen zu können, lädt `apt-spy` pro Spiegelserver etwa 10 MB an
Daten herunter. Da die Liste der verfügbaren Paketmirrors mehr als
einhundert Einträge umfasst, können Sie damit durchaus an das Limit
ihrer Transferrate stoßen (wie bei uns im Test geschehen).

Im Ergebnis verringert sich die Bezugszeit von Paketen insgesamt.
Insbesondere bei der Aktualisierung ihres Paketbestands und im Rahmen
eines Distributionsupgrades (siehe ``Distribution aktualisieren'' unter
<<distribution-aktualisieren>>) ist das deutlich spürbar.

// Stichworte für den Index
(((/etc/apt/sources.list.d/apt-spy.list)))
`apt-spy` erzeugt dazu eine spezifische Liste der Paketquellen in der
Datei `/etc/apt/sources.list.d/apt-spy.list`. Den Ausgangspunkt dafür
bildet die aktuelle Liste der Paketmirrors von ftp.debian.org. Jeder
darin enthaltene Eintrag wird von `apt-spy` auf dessen Erreichbarkeit
von ihrem aktuellen Standort aus überprüft. Die vielversprechendsten
Einträge landen in o.g. Liste.

// Datei (Ende): ./werkzeuge/paketquellen-und-werkzeuge/am-besten-erreichbaren-paketmirror-finden/apt-spy/paketquellen-nach-bandbreite-auswaehlen.adoc
