// Datei: ./werkzeuge/paketquellen-und-werkzeuge/am-besten-erreichbaren-paketmirror-finden/apt-spy/schalter-und-beispiele.adoc

// Baustelle: Rohtext

===== Schalter und Beispiele =====

// Stichworte für den Index
(((apt-spy, -a)))
(((apt-spy, -d)))
(((apt-spy, -e)))
(((apt-spy, -p)))
(((apt-spy, -s)))
(((apt-spy, update)))

`apt-spy` versteht eine ganze Reihe von Schaltern zur Konfiguration, von
denen wir Ihnen eine Auswahl vorstellen. Weitere Optionen entnehmen Sie
bitte der Manpage zum Programm.

`-d` 'distribution':: Debian-Veröffentlichung (siehe <<veroeffentlichungen>>), für die die Paketliste erstellt werden soll

`-a` 'area':: geographische Region, aus der die Paketmirrors kommen sollen

`-e` 'Anzahl':: 'early finish' -- legt die Anzahl der Paketmirrors fest,
die Sie abfragen möchten

`-p` 'proxy':: Proxyserver in der Schreibweise `Hostname:Port`

`-s` 'Land':: eine Komma-separierte Liste von Länderkürzeln, aus der die
Paketmirrors kommen sollen

`update`:: Aktualisieren der Liste der Paketmirrors

Nun folgen eine Reihe von Beispielen aus der Praxis. Beispiel 1 zeigt
Ihnen den schnellsten Debian-Paketmirror in Europa für die
Veröffentlichung Debian _stable_:

.Ermittlung der Debian-Paketmirrors für die Region Europa
----
# apt-spy -d stable -a Europe

SERVER:	ftp.at.debian.org
Benchmarking FTP...
		Downloaded 9001094 bytes in 3.22 seconds
		Download speed: 2731.88 kB/sec

SERVER:	debian.sil.at
Benchmarking FTP...
		Downloaded 9001094 bytes in 4.19 seconds
		Download speed: 2096.46 kB/sec

SERVER:	debian.sil.at
Benchmarking FTP...
		Downloaded 9001094 bytes in 3.66 seconds
		Download speed: 2404.31 kB/sec

SERVER:	gd.tuwien.ac.at
Benchmarking HTTP...
		Downloaded 9001094 bytes in 2.31 seconds
		Download speed: 3810.42 kB/sec
...
Writing new sources.list file: /etc/apt/sources.list.d/apt-spy.list
#
----

In Beispiel 2 sehen Sie, wie sie ähnliches für Deutschland ermitteln.
Als Kürzel dient hier `de` für Deutschland:

.Ermittlung der Debian-Paketmirrors für die Region Deutschland
----
# apt-spy -d stable -s de

SERVER:	ftp.de.debian.org
Benchmarking FTP...
		Downloaded 8990025 bytes in 2.75 seconds
		Download speed: 3190.72 kB/sec

SERVER:	debian.inf.tu-dresden.de
Benchmarking FTP...
		Downloaded 8990025 bytes in 3.32 seconds
		Download speed: 2643.16 kB/sec

...
Writing new sources.list file: /etc/apt/sources.list.d/apt-spy.list
#
----

Die dazu von `apt-spy` erzeugte Datei unter
`/etc/apt/sources.list.d/apt-spy.list` sieht bspw. so aus:

.Erzeugte Datei `sources.list` für Deutschland
----
# sources.list generated by apt-spy v3.2.2
#
# Generated using:
#
# apt-spy \
#       -d stable \
#       -s de
#
deb ftp://ftp.uni-erlangen.de/debian/ stable main #contrib non-free
deb-src ftp://ftp.uni-erlangen.de/debian/ stable main #contrib non-free
deb http://security.debian.org/ stable/updates main
----

Bitte beachten Sie, dass die ermittelten Paketmirrors stets von ihrem
aktuellen Standort und der dort vorliegenden Netzwerkanbindung abhängen.
Führen Sie das gleiche Kommando auf ihrem Linuxsystem aus, können die
Ergebnisse von der hier im Buch gezeigten Ausgabe abweichen.

// Datei (Ende): ./werkzeuge/paketquellen-und-werkzeuge/am-besten-erreichbaren-paketmirror-finden/apt-spy/schalter-und-beispiele.adoc
