// Datei: ./anhang/anhang-debian-architekturen/non-linux-architekturen.adoc
// Baustelle: Fertig

[[anhang-non-linux-architekturen]]
=== Architekturen, die nicht den Linux-Kernel verwenden ===

Keine dieser Architekturen ist momentan für stabile Veröffentlichungen
von Debian relevant ("release architecture").

hurd-i386 (i486-gnu)::
32-Bit-PC (i386) mit GNU-Hurd-Kernel (nur in Debian 'unstable').

kfreebsd-amd64 (x86_64-kfreebsd-gnu)::
x86 (PC) 64-Bit mit FreeBSD-Kernel. Technologievorschau, bei Debian 6
_Squeeze_ und Debian 7 _Wheezy_ dabei, mittlerweile nur noch in 'unstable'.

kfreebsd-i386 (i486-kfreebsd-gnu/i586-kfreebsd-gnu):: x86 (PC) 32-Bit
mit FreeBSD-Kernel. Technologievorschau, bei Debian 6 _Squeeze_ und
Debian 7 _Wheezy_ dabei, mittlerweile nur noch in 'unstable'. Seit
2014 nur Pentium-kompatible Hardware, in Debian 6 _Squeeze_ und 7
_Wheezy_ werden auch noch i486 unterstützt.

Diese Architekturen sind gar nicht mehr verfügbar:

netbsd-i386 (i486-netbsd)::
32-Bit-PC (i386). Portierung auf den NetBSD-Kernel.

netbsd-alpha (alpha-netbsd)::
Alpha. Portierung auf den NetBSD-Kernel.

// Datei (Ende): ./anhang/anhang-debian-architekturen/non-linux-architekturen.adoc
