// Datei: ./anhang/anhang-debian-architekturen/offizielle-architekturen.adoc
// Baustelle: Fertig

[[anhang-offizielle-debian-architekturen]]
=== Offizielle Architekturen ===

// Stichworte für den Index
(((Debian, Architekturen)))
(((Prozessorarchitekturen, von Debian offiziell unterstützte)))

Debian 13 _Trixie_ unterstützt die folgenden Architekturen und Plattformen:

amd64 (x86_64)::
x86 (PC) 64-Bit. AMD 64-Bit-CPUs mit AMD64-Erweiterung und Intel CPUs
mit EM64T-Erweiterung.

arm64 (aarch64-linux-gnu)::
ARM 64 Bit. 64-Bit-ARMv8-Architektur, die im Vergleich zu anderen
ARM-Architekturen einen aufgeräumten Befehlssatz hat und auf den
Servermarkt zielt. Hardware-Architektur des iPhone 5.

armel (arm-linux-gnueabi)::
ARM (EABI) <<Debian-Wiki-ARM-EABI-Port>>.

armhf (arm-linux-gnueabihf)::
ARM. Hardware Floating Point ABI, ab Debian 7.0 'Wheezy' unterstützt
<<Debian-Wiki-ARM-EABI-Port>>.

mipsel (mipsel-linux-gnu)::
MIPS (Little Endian).

mips64el (mips64el-linux-gnuabi64)::
64-Bit MIPS (Little Endian) mit der N64 ABI,
Hardware-Fließkommazahlen-Unterstützung und der MIPS64R2
Befehlssatzarchitektur.

ppc64el (powerpc64le-linux-gnu)::
PowerPC 64-Bit (POWER7+, POWER8). Little-Endian-Portierung von ppc64,
nutzt die neue OpenPower-ELFv2-ABI.

riscv64 (riscv64-linux-gnu)::
RISC-V ist eine offene 64-Bit-Befehlssatzarchitektur, die auf dem 
bewährten Design von RISC (Reduced Instruction Set Computer) aufbaut 
und unter einer BSD-Lizenz für jedermann verfügbar ist.

s390x (s390x-linux-gnu)::
IBM S/390 und zSeries, 64-Bit-Userland.

Gegenüber Debian 12 _Bookworm_ kam 'riscv64' zu dieser Liste hinzu.

// Datei (Ende): ./anhang/anhang-debian-architekturen/offizielle-architekturen.adoc
