// Datei: ./anhang/anhang-debian-architekturen/offizielle-architekturen.adoc
// Baustelle: Fertig

[[anhang-offizielle-debian-architekturen]]
=== Offizielle Architekturen ===

// Stichworte für den Index
(((Prozessorarchitekturen, von Debian offiziell unterstützte)))

Debian 13 _Trixie_ unterstützt die folgenden Architekturen und Plattformen:

i386 (i486/i586/i686)::
x86 (PC) 32-Bit. Trotz des Namens ab Debian 8 _Jessie_ nur
Pentium-kompatible und ab Debian 9 _Stretch_ nur noch
Pentium-II-kompatible Hardware. In Debian 6 _Squeeze_ und 7 _Wheezy_
umfasst das noch i486, jedoch bereits keine i486 SX mehr.

amd64 (x86_64)::
x86 (PC) 64-Bit. AMD 64-Bit-CPUs mit AMD64-Erweiterung und Intel CPUs
mit EM64T-Erweiterung.

arm64 (aarch64-linux-gnu)::
ARM 64 Bit. 64-Bit-ARMv8-Architektur, die im Vergleich zu anderen
ARM-Architekturen einen aufgeräumten Befehlssatz hat und auf den
Servermarkt zielt. Hardware-Architektur des iPhone 5.

armel (arm-linux-gnueabi)::
ARM (EABI) <<Debian-Wiki-ARM-EABI-Port>>.

armhf (arm-linux-gnueabihf)::
ARM. Hardware Floating Point ABI, ab Debian 7.0 'Wheezy' unterstützt
<<Debian-Wiki-ARM-EABI-Port>>.

mipsel (mipsel-linux-gnu)::
MIPS (Little Endian).

mips64el (mips64el-linux-gnuabi64)::
64-Bit MIPS (Little Endian) mit der N64 ABI,
Hardware-Fließkommazahlen-Unterstützung und der MIPS64R2
Befehlssatzarchitektur.

ppc64el (powerpc64le-linux-gnu)::
PowerPC 64-Bit (POWER7+, POWER8). Little-Endian-Portierung von ppc64,
nutzt die neue OpenPower-ELFv2-ABI.

riscv64 (riscv64-linux-gnu)::
Portierung für 64-Bit Little Endian RISC-V, eine freie, offene 
RISC-V-Prozessorarchitektur.

s390x (s390x-linux-gnu)::
IBM S/390 und zSeries, 64-Bit-Userland.

Gegenüber Debian 12 _Bookworm_ kam 'riscv64' zu dieser Liste hinzu.

// Datei (Ende): ./anhang/anhang-debian-architekturen/offizielle-architekturen.adoc
