// Datei: ./anhang/anhang-debian-architekturen/veraltete-architekturen.adoc
// Baustelle: Fertig

[[anhang-veraltete-debian-architekturen]]
=== Veraltete Architekturen ===

Folgende Architekturen werden von Debian 10 _Buster_ (und ggf. auch
schon älteren stabilen Debian-Veröffentlichungen) nicht mehr
unterstützt:

alpha (alpha-linux-gnu)::
Alpha. Unterstützt von Debian 2.1 'Slink' bis Debian 6 _Squeeze_.

hppa (hppa-linux-gnu)::
HP PA-RISC. Unterstützt von Debian 3 _Woody_ bis Debian 6 _Squeeze_.

ia64 (ia64-linux-gnu)::
Intel Itanium IA-64. Wurde zeitweise auch in 'unstable' nicht mehr
unterstützt, dann aber doch wiederbelebt.

m68k (m68k-linux-gnu)::
Motorola 68k. Die Unterstützung war komplett eingestellt, wurde aber
wiederbelebt.

powerpc (powerpc-linux-gnu)::
Motorola/IBM PowerPC. Läuft auf vielen der Apple Macintosh
PowerMac-Modelle sowie auf Rechnern der offenen CHRP- und
PReP-Architekturen. Seit Debian 9 _Stretch_ nicht Bestandteil der
stabilen Veröffentlichungen.

Diese Architekturen sind gar nicht mehr verfügbar:

arm (arm-linux-gnu)::
ARM (OABI). Seit Debian 6 _Squeeze_ nicht mehr unterstützt und durch
'armel' ersetzt.

m32::
M32R. Portierung auf die 32-Bit-RISC-Mikroprozessoren von Renesas
Technology.

s390 (s390-linux-gnu)::
IBM S/390 und zSeries. Wird auch in 'unstable' nicht mehr unterstützt
und wurde durch s390x ersetzt.

sparc (sparc-linux-gnu)::
SPARC, 64-Bit-Kernel, 32-Bit-Userland. Nur noch in 'unstable', der ist
Nachfolger 'sparc64'.

// Datei (Ende): ./anhang/anhang-debian-architekturen/veraltete-architekturen.adoc
