// Datei: ./anhang/anhang-debian-architekturen/veraltete-architekturen.adoc
// Baustelle: Fertig

[[anhang-veraltete-debian-architekturen]]
=== Veraltete Architekturen ===

// TODO -> Stretch

Folgende Architekturen werden mit Debian 8 _Jessie_ nicht mehr
unterstützt:

ia64 (ia64-linux-gnu)::
Intel Itanium IA-64. Wird auch in 'unstable' nicht mehr unterstützt.

kfreebsd-amd64 (x86_64-kfreebsd-gnu)::
x86 (PC) 64-Bit mit FreeBSD-Kernel. Technologievorschau, bei Debian 6
_Squeeze_ und Debian 7 _Wheezy_ dabei, mittlerweile nur noch in 'unstable'.

kfreebsd-i386 (i486-kfreebsd-gnu/i586-kfreebsd-gnu):: x86 (PC) 32-Bit
mit FreeBSD-Kernel. Technologievorschau, bei Debian 6 _Squeeze_ und
Debian 7 _Wheezy_ dabei, mittlerweile nur noch in 'unstable'. Seit
2014 nur Pentium-kompatible Hardware, in Debian 6 _Squeeze_ und 7
_Wheezy_ werden auch noch i486 unterstützt.

s390 (s390-linux-gnu)::
IBM S/390 und zSeries. Wird auch in 'unstable' nicht mehr unterstützt
und wurde durch s390x ersetzt.

sparc (sparc-linux-gnu)::
SPARC, 64-Bit-Kernel, 32-Bit-Userland. Nur noch in 'unstable', der
Nachfolger 'sparc64' ist bislang noch nicht fertig.

Die nachfolgenden Architekturen werden von Debian offiziell nicht mehr
unterstützt, aber vom Debian-Ports-Projekt noch am Leben gehalten:

alpha (alpha-linux-gnu)::
Alpha. Unterstützt von Debian 2.1 'Slink' bis Debian 6 _Squeeze_.

hppa (hppa-linux-gnu)::
HP PA-RISC. Unterstützt von Debian 3 _Woody_ bis Debian 6 _Squeeze_.

m68k (m68k-linux-gnu)::
Motorola 68k. Die Unterstützung war komplett eingestellt, wurde aber
wiederbelebt.

Diese Architekturen sind gar nicht mehr verfügbar:

arm (arm-linux-gnu)::
ARM (OABI). Seit Debian 6 _Squeeze_ nicht mehr unterstützt und durch
'armel' ersetzt.

m32::
M32R. Portierung auf die 32-Bit-RISC-Mikroprozessoren von Renesas
Technology.

netbsd-i386 (i486-netbsd)::
32-Bit-PC (i386). Portierung auf den NetBSD-Kernel.

netbsd-alpha (alpha-netbsd)::
Alpha. Portierung auf den NetBSD-Kernel.

// Datei (Ende): ./anhang/anhang-debian-architekturen/veraltete-architekturen.adoc
