// Datei: ./werkzeuge/paketoperationen/bekannte-paketnamen-auflisten.adoc

// Baustelle: Fertig

[[bekannte-paketnamen-auflisten]]

=== Bekannte Paketnamen auflisten ===

// Stichworte für den Index
(((apt-cache, pkgnames)))
(((Paket, bekannte Pakete auflisten)))
(((Paket, verfügbare Pakete anzeigen)))
APT kann Ihnen ausgeben, welche Pakete es überhaupt kennt. Dazu verfügt
das Werkzeug `apt-cache` über das Unterkommando `pkgnames`. Die Ausgabe,
die Sie nach dessen Aufruf erhalten, hängt von den von Ihnen genutzten
Paketquellen und den darüber verfügbaren Paketen ab. 

Die nachfolgende Ausgabe listet die Pakete zusätzlich alphabetisch
aufsteigend sortiert und seitenweise auf. Im Aufruf kommen dazu die
beiden UNIX-Kommandos `sort` und `more` zum Einsatz.

.Seitenweise und alphabetisch sortierte Ausgabe der Paketnamen, die APT kennt
----
$ apt-cache pkgnames | sort | more
0ad
0ad-data
0ad-dbg
2ping
2vcard
3270-common
389-console
3dchess
...
$
----

// Stichworte für den Index
(((apt-cache, pkgnames)))
Kennen Sie jedoch nur ein Fragment eines Paketnamens, gibt es einen
üblichen Weg und eine Abkürzung. Der _übliche Weg_ kombiniert
`apt-cache` und das UNIX-Kommando `grep` über eine Pipe miteinander.
'Muster' bezeichnet hier das Ihnen bereits bekannte Fragment.
Nachfolgend sehen Sie die Recherche nach dem Muster `aptitude`.

.Suche nach dem Muster `aptitude`
----
$ apt-cache pkgnames | grep aptitude
aptitude
aptitude-common
aptitude-doc-cs
aptitude-doc-fi
aptitude-doc-en
aptitude-doc-es
aptitude-doc-fr
aptitude-doc-ja
aptitude-doc-it
aptitude-dbg
$
----

// Stichworte für den Index
(((apt-file)))
(((Debianpaket, debian-goodies)))
(((dglob, -a)))
Die _Abkürzung_ führt über das Werkzeug `dglob` aus dem Paket
'debian-goodies' <<Debian-Paket-debian-goodies>>. Es setzt auf
`apt-file` auf und liefert eine identische Ausgabe – aber der
Tippaufwand ist geringer. Nachfolgende Ausgabe zeigt Ihnen das
Suchergebnis zu den Paketen, die das Muster `ttd` beinhalten. Damit
finden Sie beispielsweise alle Pakete, die zum Spiel Open Transport
Tycoon Deluxe (openttd) gehören.

Die im Aufruf verwendete Option `-a` listet Ihnen alle Pakete in
alphabetisch aufsteigender Reihenfolge auf – unabhängig davon, ob diese
jeweils auf Ihrem System installiert sind oder nicht. Ohne die Option
beschränkt sich `dglob` nur auf die bereits installierten Pakete.

.Rechercheergebnis von `dglob` mit dem Muster `ttd`
----
$ dglob -a ttd
liblttd-dev
liblttd0
openttd
openttd-data
openttd-dbg
openttd-opengfx
openttd-openmsx
openttd-opensfx
$
----

// Datei (Ende): ./werkzeuge/paketoperationen/bekannte-paketnamen-auflisten.adoc
