// Datei: ./werkzeuge/paketoperationen/historie-der-paketoperationen-anzeigen.adoc

// Baustelle: Notizen

[[historie-der-paketoperationen-anzeigen]]

=== Historie der Paketoperationen anzeigen ===

// Stichworte für den Index
(((Historie der Paketaktionen anzeigen)))
(((Nala, Historie der Paketaktionen anzeigen)))
(((Nala, history)))

Nachzuvollziehen, welche Paketaktionen stattfanden, ist sehr nützlich.
Meist entsteht der Bedarf erst, wenn etwas schiefgegangen ist und Sie
verstehen müssen, was zur aktuellen Situation geführt hat. 

Nach unserem Wissensstand gibt es nur ein Werkzeug, welches einen direkten
Zugriff auf die vorangegangen Paketoperationen erlaubt -- Nala (siehe 
<<nala>>). Weder `dpkg`, noch `apt-get`, APT, `aptitude`, Synaptic, `ara` 
und `muon` können in diesem speziellen Fall mithalten.

Nala merkt sich nur die Aktionen, die es selbst ausgeführt hat. Aktionen 
anderer Werkzeuge zur Paketverwaltung "kennt" es nicht. Seine eigene
Historie rufen Sie mittels `nala history` auf. Haben Sie es nie zuvor
benutzt, meldet es sich, wie nachfolgend zu sehen.

.Nala ohne Vergangenheit befragen
----
$ nala history
Fehler: Es existiert kein Verlauf.
$
----

* Ausführung mehrerer Aktionen
** erneuter Aufruf

* wie geht das bei den anderen Werkzeugen:

** `history | grep apt`
** Logfile von `dpkg`, APT oder `aptitude` auswerten

// Datei (Ende): ./werkzeuge/paketoperationen/historie-der-paketoperationen-anzeigen.adoc

