// Datei: ./werkzeuge/paketoperationen/historie-der-paketoperationen-anzeigen.adoc

// Baustelle: Rohtext

[[historie-der-paketoperationen-anzeigen]]

=== Historie der Paketoperationen anzeigen ===

// Stichworte für den Index
(((Historie der Paketaktionen anzeigen)))

Nachzuvollziehen, welche Paketaktionen stattfanden, ist sehr nützlich.
Meist entsteht der Bedarf erst, wenn etwas schiefgegangen ist und Sie
verstehen müssen, was zur aktuellen Situation geführt hat. 

Nach unserem Wissensstand gibt es derzeit nur ein Werkzeug, welches 
einen direkten Zugriff über ein passendes Unterkommando auf die 
vorangegangenen Paketoperationen erlaubt -- Nala (siehe <<nala>> und 
<<historie-der-paketoperationen-anzeigen-nala>>). Weder `dpkg`, noch 
`apt-get`, APT, `aptitude`, Synaptic und `muon` (siehe <<gui-muon>>) 
können in diesem speziellen Fall mithalten. 

[[historie-der-paketoperationen-anzeigen-apt]]
==== Apt ====
// Stichworte für den Index
(((apt, Historie der Paketaktionen anzeigen)))
(((apt, history-info)))
(((apt, history-list)))
(((apt, history-redo)))
(((apt, history-rollback)))
(((apt, history-undo)))

Der Entwickler von `apt` hat im September 2025 angekündigt, dass zukünftige 
Versionen von `apt` zwei neue Unterkommandos enthalten werden:

`history-info`:: die gesamte Historie der Pakettransaktionen auflisten

`history-list`:: detaillierte Informationen über eine bestimmte Pakettransaktion anzeigen

`history-redo`:: Transaktionen wiederholen

`history-rollback`:: Transaktionen wieder rückgängig machen (vorherigen Zustand wiederherstellen

`history-undo`:: Transaktionen rückgängig machen

Ein genauer Zeitpunkt, wann diese Erweiterungen Teil einer stabilen 
Veröffentlichung sein werden, steht derzeit noch nicht fest.

[[historie-der-paketoperationen-anzeigen-nala]]
==== Nala ====
// Stichworte für den Index
(((Nala, Historie der Paketaktionen anzeigen)))
(((Nala, history)))

Nala merkt sich nur die Aktionen, die es selbst ausgeführt hat. Aktionen 
anderer Werkzeuge zur Paketverwaltung "kennt" es nicht. Nalas Historie der 
Aktionen rufen Sie mittels `nala history` auf. Haben Sie es nie zuvor 
benutzt, meldet es sich zunächst so, wie nachfolgend zu sehen.

.Nala ohne bestehende Vergangenheit befragen
----
$ nala history
Fehler: Es existiert kein Verlauf.
$
----

Nala merkt sich alle Installationen, Aktualisierungen und Entfernungen von
Paketen. Diesen Schritten entsprechen die drei Unterkommandos `install`, 
`upgrade` und `remove`. Nachfolgend ersehen Sie aus der Ausgabe, dass das
Paket 'chromium' am 6. Februar 2025 um 8h36 vom Benutzer `root` installiert 
wurde.

.Nala buddelt in seiner Vergangenheit
----
# nala history 
  ID    Command             Date and Time              Altered    Requested-By  
  1     install chromium    2025-02-06 08:36:15 CET          5    root (0)
#
----

[[historie-der-paketoperationen-anzeigen-shell]]
==== Über die Shell ====
// Stichworte für den Index
(((Shell, Historie der Paketaktionen anzeigen)))

Nutzen Sie Nala (siehe <<nala>>) nicht, bleibt Ihnen noch, die passenden 
Logfiles auszuwerten, oder in der Historie ihrer Shell zu graben, bspw. 
mittels `grep` wie folgt:

.In der Historie der Shell stöbern
----
# history | grep apt
 1944  apt-get changelog xpdf
 1945  aptitude changelog xpdf
#
----

// Datei (Ende): ./werkzeuge/paketoperationen/historie-der-paketoperationen-anzeigen.adoc

