// Datei: ./werkzeuge/paketoperationen/inoffizielle-pakete-anzeigen.adoc
// Baustelle: Notizen

[[inoffizielle-pakete-anzeigen]]

=== Liste der installierten, inoffiziellen Pakete anzeigen ===

* installierte Pakete auflisten, die nicht aus einem (offiziellen) Repository stammen
* bspw. selbst übersetzt oder gebaut oder "irgendwoher" heruntergeladen 
* das sind Pakete, zu denen kein Repository als Quelle ermittelt werden kann
* Werkzeuge:
** `apt-cache policy` 'Paketname' (siehe <<aus-welchem-repo-kommen-die-pakete-einzelpaket>>)
** `apt-forktracer` 'Paketname'

==== Recherche mit `apt-forktracer` ====

// Stichworte für den Index
(((apt-forktracer)))
(((Debianpaket, apt-forktracer)))

* Debianpaket 'apt-forktracer' <<Debian-Paket-apt-forktracer>>
* ist dazu gedacht, Pakete zu finden, die sich in einem inkonsistenten 
  Zustand befinden oder in einer anderen Version als der offiziell neuesten 
  installiert sind
* leistet ähnliches wie `apt-show-versions` und `grep-aptavail` (siehe 
  <<paketversionen-anzeigen>>)
* zwei Betriebsmodi:
** einfacher Aufruf zu installierten (Fremd-)Paketen

.Einfacher Aufruf von `apt-forktracer`
----
$ apt-forktracer
hl2250dnlpr (2.1.0-1)
linux-headers-6.1.0-18-amd64 (6.1.76-1)
linux-headers-6.1.0-18-common (6.1.76-1)
linux-headers-6.1.0-23-amd64 (6.1.99-1)
opendataeditor (1.0.0)
$
----

** Ausführlicher Aufruf mit dem Schalter `-v`
*** prüft alle Pakete -- auch reguläre Pakete
*** zeigt das Repo an, aus dem das Paket stammt und welche Version 
    von dort verfügbar ist

// Stichworte für den Index
(((apt-forktracer, -v)))
.Ausführlicher Aufruf von `apt-forktracer`
----
$ apt-forktracer -v
hl2250dnlpr (2.1.0-1)
virtualbox (7.0.12-dfsg-1~fto12+1->7.0.20-dfsg-1~fto12+1) [Debian: 7.0.20-dfsg-1~fto12+1]
xserver-xorg-core (2:21.1.7-3+deb12u7->2:21.1.7-3+deb12u9) [Debian: 2:21.1.7-3+deb12u9 2:21.1.7-3+deb12u9]
linux-headers-6.1.0-18-amd64 (6.1.76-1)
...
$
----

// Datei (Ende): ./werkzeuge/paketoperationen/inoffizielle-pakete-anzeigen.adoc
