// Datei: ./werkzeuge/paketoperationen/installationsgroesse-eines-pakets.adoc

// Baustelle: Fertig

[[installationsgroesse-eines-pakets]]

=== Installationsgröße eines Pakets ===

// Stichworte für den Index
(((Debianpaket, dlocate)))
(((dlocate, -du)))
(((Paket, Installationsgröße anzeigen)))
Die Frage, wieviel Platz ein installiertes Paket auf der Platte belegt,
beantworten Sie am besten mit dem Aufruf `dlocate -du Paketname`
<<Debian-Paket-dlocate>>. Als Ergebnis erhalten Sie eine Auflistung mit
einer Datei pro Zeile, bei der die jeweilige Größe in der ersten Spalte
in Kilobyte angegeben ist. Die letzte Zeile summiert die Einzelwerte
auf. Nachfolgendes Listing zeigt den Aufruf für das Paket 'htop'.

.Ermittlung der Installationsgröße eines Pakets mit `dlocate`
----
$ dlocate -du htop
136	/usr/bin/htop
4	/usr/share/applications/htop.desktop
4	/usr/share/doc/htop/AUTHORS
8	/usr/share/doc/htop/changelog.Debian.gz
8	/usr/share/doc/htop/changelog.gz
4	/usr/share/doc/htop/copyright
4	/usr/share/doc/htop/README
4	/usr/share/man/man1/htop.1.gz
4	/usr/share/menu/htop
4	/usr/share/pixmaps/htop.png
180	insgesamt
$
----

// Stichworte für den Index
(((Debianpaket, aptitude)))
(((aptitude, -Z)))
(((Paket, Installationsgröße anzeigen)))
Möchten Sie den benötigten Speicherplatz bereits vor der Installation
wissen, hilft Ihnen `aptitude` weiter. Mit Hilfe des zusätzlichen
Schalters `-Z` ergänzt `aptitude` die Größenangabe hinter jedem Paket,
hier beispielhaft für 'aptitude-doc-it' und 'aptitude-doc-ru'. Wird ein
'+' vor der Zahl dargestellt, wird dieser Speicherplatz zur Installation
des Paketes benötigt, ein '-' vor der Zahl gibt hingegen den frei
werdenden Platz an, wenn das Paket entfernt wird.

.Ausgabe der Installationsgröße eines Pakets mit `aptitude`
----
# aptitude -Z install aptitude-doc-it aptitude-doc-ru
Die folgenden NEUEN Pakete werden zusätzlich installiert:
   aptitude-doc-it <+1.082 kB>  aptitude-doc-ru <+1.408 kB>  
   0 Pakete aktualisiert, 2 zusätzlich installiert, 0 werden entfernt
   und 14 nicht aktualisiert.
   636 kB an Archiven müssen heruntergeladen werden. Nach dem Entpacken
   werden 2.490 kB zusätzlich belegt sein.
...
#
----

// Datei (Ende): ./werkzeuge/paketoperationen/installationsgroesse-eines-pakets.adoc
