// Datei: ./werkzeuge/paketoperationen/manpages-anzeigen.adoc

// Baustelle: Fertig

[[manpages-anzeigen]]

=== Manpages anzeigen ===

// Stichworte für den Index
(((apropos)))
(((debman, -f)))
(((dlocate)))
(((dlocate, -man)))
(((whereis)))
(((whereis, -m)))
(((Debianpaket, debian-goodies)))
(((Debianpaket, dlocate)))
(((Debianpaket, util-linux)))
(((Dokumentation, Infopages)))
(((Dokumentation, manpages)))
Für die meisten UNIX/Linux-Werkzeuge bestehen Informations- und
Hilfeseiten, auch genannt 'Info und Man(ual) Pages'. Um in Erfahrung zu
bringen, ob diese überhaupt vorhanden und installiert sind, bieten sich
zunächt die beiden UNIX-Kommandos `apropos` und `whereis` (Paket
'util-linux' <<Debian-Paket-util-linux>>) an. Ebenso hilft Ihnen das
bereits mehrfach genutzte Werkzeug `dlocate` <<Debian-Paket-dlocate>>
weiter. 

Manpages aus `deb`-Paketen, die noch nicht auf ihrem System installiert
sind, aber als lokale Datei vorliegen, zeigen Sie mit Hilfe von `debman`
und `debmany` aus dem Paket 'debian-goodies'
<<Debian-Paket-debian-goodies>> an. Liegt das Paket nicht lokal vor,
hilft Ihnen die Manpages-Sammlung des Debian-Projekts weiter
<<Debian-Manpages>>.

==== Manpages erstöbern ====

// Stichworte für den Index
(((apropos)))
(((dlocate, -man)))
(((Dokumentation, manpages)))
Mittels `apropos` 'Paketname' sehen Sie, ob zu dem von Ihnen angefragten
Programm lokal Dokumentation verfügbar ist. Für das Stichwort `aptitude`
sieht das bspw. wie folgt aus:

.Verfügbare Manpages für das Paket 'aptitude' mittels `aptitude` lokalisieren
----
$ apropos aptitude
aptitude (8)         - Benutzerschnittstelle für den Paketmanager
aptitude-curses (8)  - Benutzerschnittstelle für den Paketmanager
aptitude-create-state-bundle (1) - bundle the current aptitude state
aptitude-run-state-bundle (1) - unpack an aptitude state bundle and invoke aptitude on it
$
----

Eine ähnliche Hilfe leistet auch das Kommando `dlocate` mit dem Schalter
`-man` gefolgt vom Paketnamen. Das Ergebnis des Aufrufs sieht für das
Programm `aptitude` sieht wie folgt aus:

.Verfügbare Manpages für das Paket 'aptitude' mittels `dlocate` aufspüren
----
$ dlocate -man aptitude
8 aptitude-curses
$
----

Nun können Sie die Manpage mittels `man aptitude` bzw. `man
aptitude-curses` aufrufen.

// Stichworte für den Index
(((dlocate, -lsman)))
(((whereis, -m)))
Benötigen Sie zusätzlich den exakten Pfad zur Datei, in der die Manpage
liegt, nutzen Sie stattdessen entweder `whereis` mit dem Schalter `-m`
oder `dlocate` mit dem Schalter `-lsman`. 

.Verfügbare Manpages für das Paket 'aptitude' mittels `whereis` lokalisieren
----
$ whereis -m aptitude
aptitude: /usr/share/man/man8/aptitude.8.gz
$
----

Bei letzterem erfahren Sie bspw. aus dem nachfolgenden Aufruf, dass die
Manpage für mehrere Sprachen wie bspw. Deutsch (de), Spanisch (es) und
Polnisch (pl) im Verzeichnis `/usr/share/man` bereitsteht.

.Verfügbare Manpages für das Paket 'aptitude' mit vollständigem Pfad
----
$ dlocate -lsman aptitude
/usr/share/man/cs/man8/aptitude-curses.8.gz
/usr/share/man/es/man8/aptitude-curses.8.gz
/usr/share/man/ja/man8/aptitude-curses.8.gz
/usr/share/man/fr/man8/aptitude-curses.8.gz
/usr/share/man/gl/man8/aptitude-curses.8.gz
/usr/share/man/fi/man8/aptitude-curses.8.gz
/usr/share/man/man8/aptitude-curses.8.gz
/usr/share/man/it/man8/aptitude-curses.8.gz
/usr/share/man/pl/man8/aptitude-curses.8.gz
/usr/share/man/de/man8/aptitude-curses.8.gz
$
----

==== Manpages aus noch nicht installierten Paketen anzeigen ====

// Stichworte für den Index
(((Debianpaket, debian-goodies)))
(((debman, -f)))
(((debman, -p)))
(((debmany)))

Für diesen speziellen Zweck existieren `debman` und `debmany`. Beide
Werkzeuge gehören zum Umfang des Pakets 'debian-goodies' und bieten
Ihnen die Möglichkeit, Manpages von Paketen anzuzeigen, die noch nicht
installiert sind, aber bspw. bereits als lokale Datei vorliegen. Dazu
benötigt `debman` den Schalter `-f`, den Dateinamen und anschließend den
Namen der Manpage. Der nachfolgende Aufruf demonstriert das am Beispiel
von 'htop':

.Aufruf von `debman` zum Paket 'htop'
----
$ debman -f htop_1.0.3-1_amd64.deb htop
...
$
----

Liegt das Paket noch nicht lokal vor, sondern noch auf einem
Paketmirror, können sowohl `debman` als auch `debmany` dieses von dort
beziehen und die Manpage anzeigen. `debman` versteht dazu den Schalter
`-p`. 

// Datei (Ende): ./werkzeuge/paketoperationen/manpages-anzeigen.adoc
