// Datei: ./werkzeuge/paketoperationen/manpages-anzeigen.adoc

// Baustelle: Fertig

[[manpages-anzeigen]]

=== Manpages anzeigen ===

// Stichworte für den Index
(((debman, -f)))
(((dlocate)))
(((dlocate, -man)))
(((whereis)))
(((whereis, -m)))
(((Debianpaket, debian-goodies)))
(((Debianpaket, dlocate)))
(((Debianpaket, util-linux)))
Für die meisten UNIX/Linux-Werkzeuge bestehen Informations- und
Hilfeseiten, auch genannt 'Info und Man(ual) Pages'. Um in Erfahrung zu
bringen, ob diese vorhanden und installiert sind, bieten sich die beiden
UNIX-Kommandos `whereis` aus dem essentiellen Paket 'util-linux'
<<Debian-Paket-util-linux>> sowie das bereits mehrfach genutzte
`dlocate` <<Debian-Paket-dlocate>> an. Manpages aus Paketen, die noch
nicht installiert sind, zeigen Sie mit Hilfe von `debman` und `debmany`
an.

==== Manpages erstöbern ====

Mit der Option `-m` 'Paketname' sucht `whereis` nach den passenden
Hilfeseiten zum genannten Paket. Das Paket muß dabei lokal installiert
sein:

.Verfügbare Manpages für das Paket 'aptitude' mittels `whereis` lokalisieren
----
$ whereis -m aptitude
aptitude: /usr/share/man/man8/aptitude.8.gz
$
----

Ähnliches leistet auch das Kommando `dlocate` mit dem Schalter `-man`
gefolgt vom Paketnamen. Das Ergebnis des Aufrufs für das Programm
`aptitude` sieht wie folgt aus:

.Verfügbare Manpages für das Paket 'aptitude' mittels `dlocate` aufspüren
----
$ dlocate -man aptitude
8 aptitude-curses
$
----

// Stichworte für den Index
(((dlocate, -lsman)))
Benötigen Sie zusätzlich den exakten Pfad zur Manpage, nutzen Sie
stattdessen den Schalter `-lsman`. Damit erfahren Sie bspw. aus dem
nachfolgenden Aufruf, dass die Manpage für mehrere Sprachen wie bspw.
Deutsch (de), Spanisch (es) und Polnisch (pl) im Verzeichnis
`/usr/share/man` bereitsteht.

.Verfügbare Manpages für das Paket 'aptitude' mit vollständigem Pfad
----
$ dlocate -lsman aptitude
/usr/share/man/cs/man8/aptitude-curses.8.gz
/usr/share/man/es/man8/aptitude-curses.8.gz
/usr/share/man/ja/man8/aptitude-curses.8.gz
/usr/share/man/fr/man8/aptitude-curses.8.gz
/usr/share/man/gl/man8/aptitude-curses.8.gz
/usr/share/man/fi/man8/aptitude-curses.8.gz
/usr/share/man/man8/aptitude-curses.8.gz
/usr/share/man/it/man8/aptitude-curses.8.gz
/usr/share/man/pl/man8/aptitude-curses.8.gz
/usr/share/man/de/man8/aptitude-curses.8.gz
$
----

==== Manpages aus noch nicht installierten Paketen anzeigen ====

// Stichworte für den Index
(((Debianpaket, debian-goodies)))
(((debman, -f)))
(((debmany)))

Für diesen speziellen Zweck existieren `debman` und `debmany`. Beide
Werkzeuge gehören zum Umfang des Pakets 'debian-goodies' und bieten
Ihnen die Möglichkeit, Manpages von Paketen anzuzeigen, die noch nicht
installiert sind, aber bspw. bereits als lokale Datei vorliegen. Dazu
benötigt `debman` den Schalter `-f`, den Dateinamen und anschließend den
Namen der Manpage. Der nachfolgende Aufruf demonstriert das am Beispiel
von 'htop':

.Aufruf von `debman` zum Paket 'htop'
----
$ debman -f htop_1.0.3-1_amd64.deb htop
...
$
----


// Datei (Ende): ./werkzeuge/paketoperationen/manpages-anzeigen.adoc
