// Datei: ./werkzeuge/paketoperationen/pakete-konfigurieren.adoc

// Baustelle: Rohtext

[[pakete-konfigurieren]]

=== Pakete konfigurieren ===

// Stichworte für den Index
(((Paket, erneut konfigurieren)))
(((Paket, konfigurieren)))

Im Normalfall liegen die Debianpakete entweder bereits fertig
konfiguriert oder mit einer vorbereiteten Konfiguration auf dem
Spiegelserver. Dafür zeichnet der Paketmaintainer verantwortlich. 

==== Bestehende Konfiguration anzeigen ====

// Stichworte für den Index
(((debconf-show)))
(((Debianpaket, dpkg)))
(((Debianpaket, tzdata)))
(((Paket, die bestehende Konfiguration anzeigen)))
Die bestehende Konfiguration eines Paketes zeigen Sie mit Hilfe des
Kommandos `debconf-show` 'Paketname' an. `debconf-show` ist Bestandteil
des Pakets 'dpkg' <<Debian-Paket-dpkg>> und somit ein essentieller Teil
ihrer Installation. Für das Paket 'tzdata' <<Debian-Paket-tzdata>> sieht
das Ergebnis wie folgt aus, sofern Sie auf ihrem System als Zeitzone
``Europa/Berlin'' eingestellt haben:

.Ausgabe der Konfiguration eines Pakets -- hier 'tzdata'
----
# debconf-show tzdata
  tzdata/Zones/Pacific:
  tzdata/Zones/Arctic:
  tzdata/Zones/Africa:
  tzdata/Zones/Asia:
  tzdata/Zones/US:
* tzdata/Zones/Etc: UTC
  tzdata/Zones/Australia:
* tzdata/Zones/Europe: Berlin
* tzdata/Areas: Europe
  tzdata/Zones/Antarctica:
  tzdata/Zones/SystemV:
  tzdata/Zones/Atlantic:
  tzdata/Zones/Indian:
  tzdata/Zones/America:
#
----

==== Bestehende Konfiguration anwenden ====

Diese Basiseinstellungen funktionieren im Allgemeinen recht gut, haben
aber nicht immer einen Bezug zu ihrem konkreten Einsatzfall. Dieser
lässt sich selten vollständig vorhersehen. Daher folgt im Rahmen der
Paketinstallation ein individuelles Feintuning seitens des
Administrators (Voreinstellungen für alle Benutzer) oder durch Sie als
Benutzer selbst (individuelle, lokale Einstellungen).

Das Anwenden der vorbereiteten Konfiguration umfasst mehrere Schritte --
bspw. das Festlegen von Zugangsdaten (administratives Passwort von
MySQL) oder das Starten von benötigten Diensten, bspw. Exim als Mail
Transfer Agent (MTA). Stellt `dpkg` dabei fest, dass zwischen der
mitgelieferten Konfiguration des neuen Pakets und der bereits
bestehenden Konfiguration Unterschiede vorliegen, werden Sie durch das
Programm gefragt, welche der beiden Einstellungen zukünftig genutzt
werden soll. Das ist sinnvoll und berücksichtigt insbesondere den Fall,
dass das Paket bereits installiert ist und von Ihnen händisch auf ihre
individuellen Gegebenheiten angepasst wurde. Als Möglichkeiten werden
Ihnen angeboten:

* die mitgelieferte Konfiguration des neuen Pakets zu benutzen
* die bestehende Konfiguration des installierten Pakets beibehalten
* sich die Unterschiede zwischen beiden anzeigen zu lassen und
* eine Shell zur individuellen Problembehebung zu öffnen.

Bei letzterem eröffnet sich Ihnen damit die Möglichkeit, bspw. eine
Sicherheitskopie der bestehenden Konfiguration anzulegen, bevor diese
verändert wird. Sollte diese neue Konfiguration nicht ihren Erwartungen
entsprechen, können Sie somit jederzeit auf die Sicherheitskopie
zurückgreifen. Bei diesem Vorgehen haben Sie als Administrator die
Möglichkeit zu sehen, dass Unterschiede bestehen, welche Unterschiede
das konkret sind, Ihre Konfiguration beizubehalten und im Zweifelsfall
die Konfiguration auf neue (Standard)Werte zurückzusetzen.

In seltenen Fällen geht dieser Prozess schief, d.h. das Paket wurde zwar
entpackt, aber nicht konfiguriert. Hintergrund können nicht sauber
aufgelöste Abhängigkeiten sein, aber auch Fehler im Paket selbst. Ist
ein benötigtes Paket nicht konfiguriert und be- bzw. verhindert damit
die Installation und Einrichtung weiterer, davon abhängiger Pakete,
teilt Ihnen `dpkg` das wie folgt mit:

.Fehler in der Konfiguration am Beispiel des Pakets 'mysql-server'
----
...
mysql-server hängt ab von mysql-server-5.5; aber:
  Paket mysql-server-5.5 ist noch nicht konfiguriert.
dpkg: Fehler beim Bearbeiten von mysql-server (--configure):
 Abhängigkeitsprobleme - verbleibt unkonfiguriert
...
Richte docbook-xml ein (4.5-5) ...
update-xmlcatalog: error: entity already registered
dpkg: Fehler beim Bearbeiten von docbook-xml (--configure):
Unterprozess post-installation script gab den Fehlerwert 1 zurück
dpkg: Abhängigkeitsprobleme verhindern Konfiguration von scrollkeeper:
scrollkeeper hängt ab von docbook-xml (>= 4.2-11); aber:
Paket docbook-xml ist noch nicht konfiguriert.
dpkg: Fehler beim Bearbeiten von scrollkeeper (--configure):
 Abhängigkeitsprobleme - lasse es unkonfiguriert
...
----

// Stichworte für den Index
(((dpkg, --audit)))
(((dpkg, -C)))
Hilfreich ist es in diesem Fall, dass Sie zunächst herausbekommen, welche
Pakete unvollständig installiert sind. Dabei hilft Ihnen der Aufruf
`dpkg -C`, wobei `dpkg` für letzteres auch die Langform `--audit` kennt.

.Auflistung der unvollständig installierten Pakete mittels `dpkg`
----
# dpkg --audit
Für die folgenden Pakete fehlt die MD5-Prüfsummen-Datei in der Datenbank,
sie müssen erneut installiert werden:
 slib                 Portable Scheme library
 vifm                 a ncurses based file manager with vi like keybindings
#
----

// Stichworte für den Index
(((dpkg, -a)))
(((dpkg, --configure)))
(((dpkg, --pending))
Als nächsten Schritt schieben Sie die Konfiguration des Pakets an. Für
ein einzelnes Paket gelingt Ihnen das mit dem Aufruf `dpkg --configure
Paketname` und für mehrere Pakete mit `dpkg -a` (Langform `--pending`).

* was passiert da genau (aus der Manpage zu `dpkg`):

----
Die Konfiguration besteht aus folgenden Schritten:

1. Entpacke die Conffiles und sichere gleichzeitig die alten
Conffiles, sodass diese, falls etwas schief geht, wiederhergestellt
werden können.


2. Führe das postinst-Skript aus, falls dies vom Paket bereitgestellt
wird.
----

* konfigurieren vs. erneut konfigurieren
Mit dem Kommando `dpkg-reconfigure` wenden Sie die gleiche Prozedur auf ein
bereits installiertes und konfiguriertes Paket an (siehe dazu
<<dpkg-reconfigure>>).

[[dpkg-reconfigure]]
==== Konfiguration mit `dpkg-reconfigure` erneut durchführen ====

// Stichworte für den Index
(((debconf)))
(((dpkg-reconfigure)))
(((Konfigurationsdatei, /var/cache/debconf)))
(((Paket, erneut konfigurieren)))

* Aufruf: `dpkg-reconfigure Paket`
* konfiguriert ein bereits installiertes Paket erneut
* verwendet wird dazu `debconf`, welches eine Datenbank mit den
Konfigurationseinträgen der Pakete unter `/var/cache/debconf` speichert

* Beispiel:
** locale-Einstellungen (Sprache, Lokalisierung, Zeichensatz)
** Einstellung für die Zeitzone (Paket 'tzdata' <<Debian-Paket-tzdata>>)

// Datei (Ende): ./werkzeuge/paketoperationen/pakete-konfigurieren.adoc
