// Datei: ./werkzeuge/paketoperationen/pakete-downgraden.adoc

// Baustelle: Rohtext

[[pakete-downgraden]]

=== Pakete downgraden ===

// Stichworte für den Index
(((Paket, downgraden)))

Allgemein gesprochen, steht der Begriff 'Downgrade' für einen
Niedergang, eine Abwertung oder einen Rückschritt. Bezogen auf die
Verwaltung von Softwarepaketen umfasst es das Einspielen einer vorherigen
Paketversion. Es stellt damit das Gegenstück zu einer Aktualisierung
mittels `apt-get upgrade` dar (siehe dazu <<pakete-aktualisieren>>).

Ein solcher Rückschritt ist in Betracht zu ziehen, wenn die derzeit
installierte Version eines Softwarepakets nicht das leistet, was sie
verspricht, dabei Fehler auftreten oder Inkompatibilitäten mit anderen
Softwarepaketen deren Benutzung unmöglich machen. Häufig fallen in
letztere Kategorie geänderte Schnittstellen, die noch nicht auf allen
nachfolgenden Ebenen konsequent umgesetzt wurden.

Ein Downgrade wird vom Release-Team von Debian GNU/Linux offiziell nicht
unterstützt. Alle Mechanismen sind auf das Einspielen einer neueren
Version ausgerichtet. Daher verfügt auch keines der hier im Buch
vorgestellten Werkzeuge zur Paketverwaltung bislang über einen
spezifischen Schalter, um ein Downgrade explizit anzustoßen. Es bleibt
daher nur ein Vorgehen über andere Wege, die jedoch auf den bereits
zuvor beschriebenen Mechanismen aufsetzen.

==== Hintergrund und Fragen zum Downgrade ====

// Stichworte für den Index
(((Maintainer-Skripte, postinst)))
(((Maintainer-Skripte, postrm)))
(((Maintainer-Skripte, preinst)))
(((Maintainer-Skripte, prerm)))

Das Einspielen einer neueren Version ist vom prinzipiellen Ablauf her
nicht komplizierter als die Aktualisierung -- es laufen die gleichen
Mechanismen ab. Behalten Sie dabei stets im Hinterkopf, daß es wie das
Fahren entgegen der Fahrtrichtung einer Einbahnstraße ist -- es geht so
lange gut, wie Ihnen keiner entgegenkommt. Schwierigkeiten können Ihnen
nämlich die Maintainerskripte (`postinst`, `preinst`, `postrm`, `prerm`)
bereiten, die das Downgrade im Normalfall nicht unterstützen. Eventuell 
unterstützt der Mechanismus, der sie aufruft, das schon nicht. Kritisch
sind die Fälle, wo eine konzeptuelle Änderung im Paket in der
Rückrichtung nicht zurück umgebaut werden kann (siehe
<<apt-get-update-bug-764503>>).


** nein. Meistens nicht -- vom explizten angeben (dpkg/apt-get) oder
auswählen der Version (aptitude TUI) mal abgesehen.

* ist das mit einer Aktualisierung gleichzusetzen?
** im Prinzip ja, nur mit einer älteren Version als explizite Festlegung
** Vorgang kann ja auch großflächige Änderungen am Restbestand der
Pakete auslösen (kann bei einer Aktualisierung ja auch vorkommen)
** Änderungen sind nicht immer rückwärtskompatibel und lösen Verwicklungen aus
** Aktualisierungen sind bereits hinreichend komplex
* Alternativen und Querverweise:
** apt-pinning bzw. Veröffentlichungen mischen (siehe <<veroeffentlichungen-mischen>>)
** Paket aus den Quellen selbst bauen (``patchen'') und einspielen
* Empfehlung: nur bei Bedarf durchführen

==== Ablauf ====

// Stichworte für den Index
(((apt-cache, showpkg)))
(((apt-get, -t install)))

* vorher nützlich:
** anzeigen, welche Paketversionen überhaupt verfügbar sind
** `apt-cache showpkg Paketname` (siehe auch <<paketstatus-erfragen>>)

* Möglichkeiten, um eine vorhergehende Paketversion einspielen
** über die explizite Angabe der Versionsnummer des Pakets: `apt-get install <package-name>=<package-version-number>`
** über die explizite Angabe der Veröffentlichung: `apt-get -t=<target release> install <package-name>`

// Datei (Ende): ./werkzeuge/paketoperationen/pakete-downgraden.adoc
