// Datei: ./werkzeuge/paketoperationen/paketaktionen-debuggen.adoc

// Baustelle: Notizen

[[paketaktionen-debuggen]]
=== Paketaktionen debuggen ===

In der Regel bearbeiten `dpkg`, APT und `aptitude` unsere Wünsche zur
Änderung des Paketbestandes anstandslos ab. Sei es aus reiner Neugierde 
oder einer Panne heraus, ist es hilfreich, herauszufinden, was alles 
während der Ausführung eines Kommandos zur Paketverwaltung passiert ist.
Das ist bspw. nützlich bei der Installation, Aktualisierung oder 
Entfernung von Softwarepaketen. Die Werkzeuge bringen dazu recht 
unterschiedliche Schalter mit, mit denen Sie hinter die Kulissen schauen 
können.

==== `dpkg` ====

// Stichworte für den Index
(((dpkg, -D)))
(((dpkg, --debug)))
(((Paket, Aktionen debuggen)))

Zur Analyse seiner Arbeitsweise verfügt `dpkg` über den Schalter `-D` 
(Langform `--debug`). Zum Schalter gehört ein Zahlenwert in oktaler
Schreibweise, der ein bestimmtes Debuglevel repräsentiert. Diese 
Zahlenwerte können Sie auch mit Hilfe von bitweisem Oder miteinander 
kombinieren, um ausgewählte, komplexere Zustände zu überprüfen. 
Nachfolgende Auflistung erhalten Sie, indem Sie `dpkg` mit der Option 
`--Dh` (Langform `--debug=help`) aufrufen.

1 ('general') :: allgemein hilfreiche Fortschrittsinformationen
2 ('scripts') :: Aufruf und Status von Betreuer-Skripten
10 ('eachfile') :: Ausgaben zu jeder verarbeiteten Datei
100 ('eachfiledetail') :: viele Ausgaben zu jeder verarbeiteten Datei
20 ('conff') :: Ausgaben zu jeder Konfigurationsdatei
200 ('conffdetail') :: viele Ausgaben zu jeder Konfigurationsdatei
40 ('depcon') :: Abhängigkeiten und Kollisionen
400 ('depcondetail') :: viele Ausgaben zu Abhängigkeiten und Kollisionen
10000 ('triggers') :: Triggeraktivierung und -verarbeitung
20000 ('triggersdetail') :: viele Ausgaben bezüglich Trigger
40000 ('triggersstupid') :: alberne Mengen an Ausgaben bezüglich Trigger
1000 ('veryverbose') :: viel Gefasel, z.B. zum `dpkg`/`info`-Verzeichnis
2000 ('stupidlyverbose') :: irrsinnige Mengen von Gefasel

Möchten Sie alle Optionen miteinander kombinieren, rufen sie `dpkg` mit
der Option `-D77777` auf.

==== APT ====

* Aufruf mit der Option `-o` und dem APT-Schalter

* Schalter (entnommen aus der Manpage)

`Debug::Acquire::cdrom` :: Print information related to accessing cdrom:// sources.

`Debug::Acquire::ftp` :: Print information related to downloading packages using FTP.

`Debug::Acquire::http` :: Print information related to downloading packages using HTTP.

`Debug::Acquire::https` :: Print information related to downloading packages using HTTPS.

`Debug::Acquire::gpgv` :: Print information related to verifying cryptographic signatures using gpg.

`Debug::aptcdrom` :: Output information about the process of accessing collections of packages stored on CD-ROMs.

`Debug::Hashes` :: Output each cryptographic hash that is generated by the apt libraries.

`Debug::IdentCDROM` :: Do not include information from statfs, namely the number of used and free blocks on the CD-ROM filesystem, when generating an ID for a CD-ROM.

`Debug::NoLocking` :: Disable all file locking. For instance, this will allow two instances of `apt-get update` to run at the same time.

`Debug::pkgAcquire` :: Log when items are added to or removed from the global download queue.

`Debug::pkgAcquire::Auth` :: Output status messages and errors related to verifying checksums and cryptographic signatures of downloaded files.

`Debug::pkgAcquire::Diffs` :: Output information about downloading and applying package index list diffs, and errors relating to package index list diffs.

`Debug::pkgAcquire::RRed` :: Output information related to patching apt package lists when downloading index diffs instead of full indices.

`Debug::pkgAcquire::Worker` :: Log all interactions with the sub-processes that actually perform downloads.

`Debug::pkgAutoRemove` :: Log events related to the automatically-installed status of packages and to the removal of unused packages.

`Debug::pkgDepCache::AutoInstall` :: Generate debug messages describing which packages are being automatically installed to resolve dependencies. This corresponds to the initial auto-install pass performed in, e.g., apt-get install, and not to the full apt dependency resolver; see Debug::pkgProblemResolver for that.

`Debug::pkgDepCache::Marker` :: Generate debug messages describing which packages are marked as keep/install/remove while the ProblemResolver does his work. Each addition or deletion may trigger additional actions; they are shown indented two additional spaces under the original entry. The format for each line is MarkKeep, MarkDelete or MarkInstall followed by package-name <a.b.c -> d.e.f | x.y.z> (section) where a.b.c is the current version of the package, d.e.f is the version considered for installation and x.y.z is a newer version, but not considered for installation (because of a low pin score). The later two can be omitted if there is none or if it is the same as the installed version. section is the name of the section the package appears in.

`Debug::pkgDPkgPM` :: When invoking dpkg(1), output the precise command line with which it is being invoked, with arguments separated by a single space character.

`Debug::pkgDPkgProgressReporting` :: Output all the data received from dpkg(1) on the status file descriptor and any errors encountered while parsing it.

`Debug::pkgOrderList` :: Generate a trace of the algorithm that decides the order in which apt should pass packages to dpkg(1).

`Debug::pkgPackageManager` :: Output status messages tracing the steps performed when invoking dpkg(1).

`Debug::pkgPolicy` :: Output the priority of each package list on startup.

`Debug::pkgProblemResolver` :: Trace the execution of the dependency resolver (this applies only to what happens when a complex dependency problem is encountered).

`Debug::pkgProblemResolver::ShowScores` :: Display a list of all installed packages with their calculated score used by the pkgProblemResolver. The description of the package is the same as described in `Debug::pkgDepCache::Marker`

`Debug::sourceList` :: Print information about the vendors read from /etc/apt/vendors.list.

`Debug::RunScripts` :: Display the external commands that are called by apt hooks. This includes e.g. the config options `DPkg::Pre-Invoke`, `DPkg::Post-Invoke`, `APT::Update::Pre-Invoke`, or `APT::Update::Post-Invoke`.

==== Aptitude ====

* Optionen `-v` bis `-vvvvvv`

* Testen der Einstellungen mit Hilfe des Unterkommandos `moo`

----
$ aptitude -v moo
In diesem Programm gibt es wirklich keine Easter Eggs.
$ aptitude -vv moo
Habe ich nicht bereits erklärt, dass es in diesem Programm keine Easter Eggs gibt?
$ aptitude -vvv moo
Hör auf!
$ aptitude -vvvv moo
Okay, wenn ich Dir ein Easter Egg gebe, wirst Du dann aufhören?
$ aptitude -vvvvv moo
Gut, Du hast gewonnen.

                               /----\
                       -------/      \
                      /               \
                     /                |
   -----------------/                  --------\
   ----------------------------------------------
$ aptitude -vvvvvv moo
Was das ist? Natürlich ein Elefant, der von einer Schlange gefressen wurde.
$
----

// Datei (Ende): ./werkzeuge/paketoperationen/paketaktionen-debuggen.adoc
