// Datei: ./werkzeuge/paketoperationen/pakete-downgraden.adoc

// Baustelle: Rohtext

[[pakete-downgraden]]

=== Pakete downgraden ===

// Stichworte für den Index
(((Paket, downgraden)))

Allgemein gesprochen, steht der Begriff 'Downgrade' für einen
Niedergang, eine Abwertung oder einen Rückschritt. Bezogen auf die
Verwaltung von Softwarepaketen umfasst es das Einspielen oder
Zurückgehen zu einer vorherigen Paketversion. Es stellt damit das
Gegenstück zu einer Aktualisierung mittels `apt-get upgrade` dar (siehe
dazu <<pakete-aktualisieren>>).

Ein Downgrade ist in Betracht zu ziehen, wenn die derzeit installierte
Version eines Softwarepakets nicht das leistet, was sie verspricht,
bspw. dabei Fehler auftreten oder Inkompatibilitäten mit anderen
Softwarepaketen deren Benutzung unmöglich machen. Häufig fallen in
letztere Kategorie geänderte Schnittstellen, die noch nicht auf allen
nachfolgenden Ebenen konsequent umgesetzt wurden.

Ein Downgrade wird vom Release-Team von Debian GNU/Linux offiziell nicht
unterstützt. Alle Mechanismen zur Paketverwaltung und Aktualisierung
sind auf das Einspielen einer neueren Version ausgerichtet. Daher
verfügt auch keines der hier im Buch vorgestellten Werkzeuge zur
Paketverwaltung bislang über einen spezifischen Schalter, um ein
Downgrade explizit anzustoßen. Es bleibt daher nur ein Vorgehen über
andere Wege, die jedoch auf den bereits zuvor beschriebenen Mechanismen
aufsetzen.

==== Hintergrund und Fragen zum Downgrade ====

// Stichworte für den Index
(((Maintainer-Skripte, postinst)))
(((Maintainer-Skripte, postrm)))
(((Maintainer-Skripte, preinst)))
(((Maintainer-Skripte, prerm)))

Das Einspielen einer neueren Version ist vom prinzipiellen Ablauf her
nicht anders als die Aktualisierung -- es laufen die gleichen
Mechanismen ab und es kommen die gleichen Werkzeuge zum Einsatz. Der
Unterschied ist jedoch die Komplexität, die hier deutlich höher ist.

Vergleichbar ist der Vorgang wie das Bewegen entgegen der Fahrtrichtung
in einer Einbahnstraße -- es geht so lange gut, wie Ihnen keiner
entgegenkommt. Schwierigkeiten können Ihnen nämlich die
Maintainerskripte (siehe ``Binärpakete'' in
<<aufbau-und-format-binaer>>) bereiten, die das Downgrade im Normalfall
nicht unterstützen. Eventuell ist der Mechanismus, der sie aufruft, auch
nicht darauf vorbereitet. Kritisch sind insbesondere die Fälle, wo eine
konzeptuelle Änderung im Paket in der Rückrichtung nicht umgebaut werden
kann (siehe dazu bspw. den Debian-Bug 764503
<<apt-get-update-bug-764503>>).

Ein Downgrade ist mit einer Aktualisierung gleichzusetzen. Hierbei
benennen Sie jedoch explizit eine ältere Paketversion, die Sie entweder
über einen Parameter -- ``target release'' oder Versionsnummer -- beim
Aufruf von `dpkg` bzw. `apt-get` angeben oder in der Textoberfläche von
Aptitude auswählen. Berechnet die Paketverwaltung nun die Abhängigkeiten
zu den übrigen Paketen, kann am Ende dieses Vorgangs auch eine
großflächige Änderung am Restbestand der Pakete stehen. Dieser Fall ist
nicht ungewöhnlich, denn er kann ebenso bei einer Aktualisierung
vorkommen. Die Wahrscheinlichkeit, daß die Änderungen erheblich sind,
ist sehr groß.

Wie oben schon benannt, sind diese Änderungen nicht immer
rückwärtskompatibel und lösen Verwicklungen aus (Aktualisierungen sind
eigentlich bereits hinreichend komplex). Wir empfehlen Ihnen daher, ein
Downgrade nur bei dem tatsächlichen Bedarf dafür durchzuführen. Prüfen
Sie bitte vorher, ob das Mischen von Veröffentlichungen mittels
`apt-pinning` (siehe <<veroeffentlichungen-mischen>>) oder das
Übersetzen des Pakets aus den Quellen und das nachfolgende Einspielen
des eigenen Binärpakets risikoärmer ist.

==== Ablauf ====

// Stichworte für den Index
(((apt-cache, showpkg)))
(((apt-get, -t install)))
(((Paket, verfügbare Versionen anzeigen)))
(((Pakete aktualisieren, verfügbare Versionen anzeigen)))

Als Schritt eins listen Sie zunächst die Paketversionen auf, welche
überhaupt verfügbar sind (siehe ``Paketstatus erfragen'' in
<<paketstatus-erfragen>>). Dabei hilft ihnen das Werkzeug `apt-cache`
mit dem Schalter `showpkg` und dem Namen des gewünschten Pakets:

----
apt-cache showpkg Paketname
----

* Möglichkeiten, um eine vorhergehende Paketversion einspielen
** über die explizite Angabe der Versionsnummer des Pakets: `apt-get install <package-name>=<package-version-number>`
** über die explizite Angabe der Veröffentlichung: `apt-get -t=<target release> install <package-name>`

// Datei (Ende): ./werkzeuge/paketoperationen/pakete-downgraden.adoc
