// Datei: ./werkzeuge/paketoperationen/paketaktionen-debuggen.adoc

// Baustelle: Rohtext

[[paketaktionen-debuggen]]
=== Paketaktionen debuggen ===

In der Regel bearbeiten `dpkg`, APT und `aptitude` unsere Wünsche zur
Änderung des Paketbestandes anstandslos ab. Sei es aus reiner Neugierde 
oder einer Panne heraus, ist es hilfreich, herauszufinden, was alles 
während der Ausführung eines Kommandos zur Paketverwaltung passiert ist.
Das ist bspw. nützlich bei der Installation, Aktualisierung oder 
Entfernung von Softwarepaketen. Die Werkzeuge bringen dazu recht 
unterschiedliche Schalter mit, mit denen Sie hinter die Kulissen schauen 
können.

==== `dpkg` ====

// Stichworte für den Index
(((dpkg, -D)))
(((dpkg, --debug)))
(((Paket, Aktionen debuggen)))

Zur Analyse seiner Arbeitsweise verfügt `dpkg` über den Schalter `-D` 
(Langform `--debug`). Zum Schalter gehört ein Zahlenwert in oktaler
Schreibweise, der ein bestimmtes Debuglevel repräsentiert. Diese 
Zahlenwerte können Sie auch mit Hilfe von bitweisem Oder miteinander 
kombinieren, um ausgewählte, komplexere Zustände zu überprüfen. 
Nachfolgende Auflistung erhalten Sie, indem Sie `dpkg` mit der Option 
`--Dh` (Langform `--debug=help`) aufrufen.

1 ('general') :: allgemein hilfreiche Fortschrittsinformationen
2 ('scripts') :: Aufruf und Status von Betreuer-Skripten
10 ('eachfile') :: Ausgaben zu jeder verarbeiteten Datei
100 ('eachfiledetail') :: viele Ausgaben zu jeder verarbeiteten Datei
20 ('conff') :: Ausgaben zu jeder Konfigurationsdatei
200 ('conffdetail') :: viele Ausgaben zu jeder Konfigurationsdatei
40 ('depcon') :: Abhängigkeiten und Kollisionen
400 ('depcondetail') :: viele Ausgaben zu Abhängigkeiten und Kollisionen
10000 ('triggers') :: Triggeraktivierung und -verarbeitung
20000 ('triggersdetail') :: viele Ausgaben bezüglich Trigger
40000 ('triggersstupid') :: alberne Mengen an Ausgaben bezüglich Trigger
1000 ('veryverbose') :: viel Gefasel, z.B. zum `dpkg`/`info`-Verzeichnis
2000 ('stupidlyverbose') :: irrsinnige Mengen von Gefasel

Möchten Sie alle Optionen miteinander kombinieren, rufen sie `dpkg` mit
der Option `-D77777` auf.

==== APT ====

// Stichworte für den Index
(((apt, -o)))

APT agiert ähnlich zu `dpkg`. Sie steuern den Aufruf über die Option 
`-o` gefolgt vom passenden Schalter. Die nachfolgende Liste haben wir 
der Manpage zu APT entnommen:

`Debug::Acquire::cdrom` :: gib Informationen aus, die zu Paketquellen 
gehören, die sich auf CDs/DVDs beziehen (Einträge beginnend mit 
`cdrom://`)

`Debug::Acquire::ftp` :: gib Informationen aus, die zu Paketquellen 
gehören, von denen Pakete mittels FTP bezogen werden

`Debug::Acquire::http` :: gib Informationen aus, die zu Paketquellen 
gehören, von denen Pakete mittels HTTP bezogen werden

`Debug::Acquire::https` :: gib Informationen aus, die zu Paketquellen 
gehören, von denen Pakete mittels HTTPS bezogen werden

`Debug::Acquire::gpgv` :: gib Informationen aus, die in Bezug zur 
Überprüfung kryptographischer Signaturen mittels GPG stehen

`Debug::aptcdrom` :: gib Informationen aus, die zu Paketquellen 
gehören, die sich auf CDs/DVDs beziehen (Einträge beginnend mit 
`aptcdrom://`)

`Debug::Hashes` :: gib jeden kryptographischen Hashwert aus, der 
von den APT-Bibliotheken generiert wird

`Debug::IdentCDROM` :: schließe keine Informationen von statfs ein,
insbesondere die Anzahl der verwendeten und noch freien Blöcke auf
Dateisystemen von CDROMs, wenn eine ID für eine CDROM generiert wird

`Debug::NoLocking` :: schalte alle Mechanismen zur Sperrung von Dateien 
aus. Das ermöglicht bspw. zwei parallele Aufrufe von `apt-get update` 

`Debug::pkgAcquire` :: erzeuge einen Logeintrag, wenn Einträge zur 
globalen Bezugswarteschlange hinzugefügt oder davon entfernt werden

`Debug::pkgAcquire::Auth` :: gib Statusinformationen und Fehler aus, 
die in Bezug zur Überprüfung von Checksummen und kryptographischen 
Signaturen bezogener Dateien stehen

`Debug::pkgAcquire::Diffs` :: gib Informationen zum Bezug und der 
Anwendung von Diffs von Paketlisten aus sowie Fehler dazu

`Debug::pkgAcquire::RRed` :: gib Informationen aus, die sich auf das
Patchen von APT-Paketlisten beziehen, wenn Index-Diffs anstatt von
Vollindizes bezogen werden

`Debug::pkgAcquire::Worker` :: Logge alle Interaktionen zu
Unterprozessen mit, die tatsächlich Downloads ausführen

`Debug::pkgAutoRemove` :: Logge alle Ereignisse mit, die im Bezug zum 
Status 'automatisch installiert' von Paketen sowie dem Entfernen nicht
genutzter Pakete stehen

`Debug::pkgDepCache::AutoInstall` :: erzeuge Debugmeldungen, die 
beschreiben, welche Pakete automatisch installiert werden, um 
Abhängigkeiten aufzulösen. Dies entspricht dem anfänglichen 
automatischen Installationsdurchlauf, der z.B. mit `apt-get install` 
durchgeführt wird und nicht dem vollständigen APT-Abhängigkeitsauflöser;
siehe dazu die Option `Debug::pkgProblemResolver`

`Debug::pkgDepCache::Marker` :: Erzeugt Debug-Meldungen, die 
beschreiben, welche Pakete als behalten/installieren/entfernen markiert 
sind, während der ProblemResolver seine Arbeit erledigt. Jede Ergänzung 
oder Entfernung kann zusätzliche Aktionen auslösen; sie werden um zwei 
zusätzliche Leerzeichen unter dem ursprünglichen Eintrag eingerückt. Das 
Format für jede Zeile ist MarkKeep, MarkDelete oder MarkInstall, gefolgt 
von Paketname in der Form 'a.b.c' -> 'd.e.f | x.y.z' (Abschnitt), wobei 
'a.b.c' die aktuelle Version des Pakets darstellt, 'd.e.f' die Version, 
die für die Installation in Frage kommt, und 'x.y.z' eine neuere Version 
ist, die aber nicht für die Installation in Frage kommt (wegen eines 
niedrigen Pin-Wertes). Die letzten beiden Angaben können Sie weglassen,
wenn es keine Werte gibt oder wenn sie mit der installierten Version 
übereinstimmen. 'section' ist der Name des Abschnitts, in dem das Paket 
erscheint.

`Debug::pkgDPkgPM` :: wenn Sie `dpkg` aufrufen, wird die genaue 
Befehlszeile ausgegeben, mit der es aufgerufen wird. Dabei werden die 
Argumente durch ein einzelnes Leerzeichen voneinander getrennt

`Debug::pkgDPkgProgressReporting` :: gib alle von `dpkg` empfangenen 
Daten über den Status-Dateideskriptor und alle beim Parsen aufgetretenen 
Fehler aus

`Debug::pkgOrderList` :: erzeuge eine Ausgabe des Algorithmus, welcher 
die Reihenfolge festlegt, in der APT die Pakete an `dpkg` weiterreicht

`Debug::pkgPackageManager` :: gib die Statusmeldungen aus, die Sie die 
einzelnen Schritte nachvollziehen lassen, die `dpkg` bei seinem Aufruf
ausführt

`Debug::pkgPolicy` :: gib die Priorität jeder einzelnen Paketliste 
beim Start aus

`Debug::pkgProblemResolver` :: verfolgen Sie die Ausführung des 
Abhängigkeitsauflösers. Dies gilt nur für den Fall, dass ein komplexes 
Abhängigkeitsproblem auftritt.

`Debug::pkgProblemResolver::ShowScores` :: zeige eine Liste aller 
installierten Pakete mit ihrer berechneten Punktzahl an, die vom 
Abhängigkeitsauflöser verwendet wird. Die Beschreibung des Pakets ist die 
gleiche, wie in `Debug::pkgDepCache::Marker` beschrieben.

`Debug::sourceList` :: drucke Informationen über die aus der Datei 
`/etc/apt/vendors.list` gelesenen Anbieter aus

`Debug::RunScripts` :: Anzeige der externen Befehle, die von APT-Hooks 
aufgerufen werden. Dazu gehören z.B. die Konfigurationsoptionen 
`DPkg::Pre-Invoke`, `DPkg::Post-Invoke`, `APT::Update::Pre-Invoke` und 
`APT::Update::Post-Invoke` (siehe <<apt-hooks>>).

==== Aptitude ====

// Stichworte für den Index
(((aptitude, moo)))
(((aptitude, -v)))
(((aptitude, -vv)))
(((aptitude, -vvv)))
(((aptitude, -vvvv)))
(((aptitude, -vvvvv)))
(((aptitude, -vvvvvv)))

Aptitude verfügt über die Optionen von `-v` bis `-vvvvvv`. Damit legen
Sie die unterschiedlichen Debuglevel fest. Sie testen die Einstellungen 
mit Hilfe des Unterkommandos `moo`. Nachfolgend sehen Sie die sechs
verschiedenen Debuglevel in Aktion.

.Aptitude-Debuglevel in Aktion
----
$ aptitude -v moo
In diesem Programm gibt es wirklich keine Easter Eggs.
$ aptitude -vv moo
Habe ich nicht bereits erklärt, dass es in diesem Programm keine Easter Eggs gibt?
$ aptitude -vvv moo
Hör auf!
$ aptitude -vvvv moo
Okay, wenn ich Dir ein Easter Egg gebe, wirst Du dann aufhören?
$ aptitude -vvvvv moo
Gut, Du hast gewonnen.

                               /----\
                       -------/      \
                      /               \
                     /                |
   -----------------/                  --------\
   ----------------------------------------------
$ aptitude -vvvvvv moo
Was das ist? Natürlich ein Elefant, der von einer Schlange gefressen wurde.
$
----

// Datei (Ende): ./werkzeuge/paketoperationen/paketaktionen-debuggen.adoc
