// Datei: ./werkzeuge/paketoperationen/paketversionen-anzeigen.adoc

// Baustelle: Fertig

[[paketversionen-anzeigen]]

=== Verfügbare Versionen eines Paketes anzeigen ===

==== `aptitude` verwenden ====

// Stichworte für den Index
(((aptitude, versions)))
(((Paket, verfügbare Versionen anzeigen)))
(((Pakete aktualisieren, verfügbare Versionen anzeigen)))
Um alle verfügbaren Varianten eines Pakets für alle Veröffentlichungen
anzuzeigen, nutzen Sie die `aptitude`-Option `versions`. Nachfolgende
Ausgabe illustriert die Recherche nach den Paketen, in denen die
Zeichenkette 'tzdata' im Paketnamen enthalten ist. Hier werden zudem
ausschließlich Pakete aus der Veröffentlichung _stable_ bezogen. Die
Sortierung erfolgt paketweise, d.h. zunächst erhalten Sie eine Zeile mit
dem Paketnamen und darunter zusätzliche Informationen zur verfügbaren
Version. Die erste Spalte zeigt dabei den Paketstatus an, danach die
Versionsnummer, die Veröffentlichung und als letztes die Priorität
(siehe dazu ``Veröffentlichungen mischen'' in
<<veroeffentlichungen-mischen>>).

.Die verfügbaren Versionen zu den Paketen 'tzdata' anzeigen
----
$ aptitude versions 'tzdata'
Paket tzdata:
p   2015f-0+deb8u1               stable  500 
i   2015g-0+deb8u1               stable- 500 

Paket tzdata-java:
p A 2015f-0+deb8u1               stable  500 
i A 2015g-0+deb8u1               stable- 500
$
----

// Stichworte für den Index
(((aptitude, versions --show-package-names)))
(((aptitude, versions --group-ny)))
(((Paket, verfügbare Versionen anzeigen)))
Wünschen Sie nur eine kompakte Ausgabe zu einem konkreten Paket ohne
Darstellung des Paketnamens, helfen Ihnen die beiden Schalter
`--show-package-names` mit dem Wert `never` und `--group-by` mit dem
Wert `none` weiter. Ersteres blendet den Paketnamen aus, während der
zweite Schalter die Gruppierung in der Ausgabe deaktiviert.
Ausführlicher gehen wir auf die Gruppierung in <<aptitude-gruppierung>>
ein.

.Kompakte Ausgabe ohne Paketname
----
$ aptitude versions 'tzdata-java' --show-package-names=never --group-by=none
p A 2015f-0+deb8u1               stable  500
i A 2015g-0+deb8u1               stable- 500
$
----

==== `apt-show-versions` verwenden ====

// Stichworte für den Index
(((Debianpaket, apt-show-versions)))
(((Debianpaket, base-files)))
(((apt-show-versions)))
Als gleichwertige Alternative zu `aptitude` steht Ihnen auch das Werkzeug 
`apt-show-versions` aus dem gleichnamigen Debianpaket zur Verfügung 
<<Debian-Paket-apt-show-versions>> (siehe auch ``Aus welchem Repo kommen die 
Pakete'' in <<aus-welchem-repo-kommen-die-pakete>>). Dieses Paket gehört 
nicht zur Standardinstallation und ist daher zusätzlich zu installieren.

Die nachfolgende Ausgabe zeigt den Status des Pakets `base-files` an. Daraus
erkennen Sie, daß für dieses ein neueres Paket bereitsteht.

.Kompakte Ausgabe mittels `apt-show-versions`
----
$ apt-show-versions base-files
base-files:amd64/jessie 8+deb8u2 upgradeable to 8+deb8u3
$
----

// Datei (Ende): ./werkzeuge/paketoperationen/paketversionen-anzeigen.adoc

