// Datei: ./werkzeuge/paketoperationen/sourcepakete-beziehen.adoc

// Baustelle: Fertig

[[sourcepakete-beziehen]]

=== Sourcepakete beziehen ===

// Schlagworte für den Index
(((Paketvarianten, Binärpaket)))
(((Paketvarianten, Sourcepaket)))
Die Möglichkeit, auch die Quellpakete (siehe <<sourcepakete>>) zu den
verwendeten Programmen zu erhalten, zählt zu den zentralen Säulen Freier
Software. Neben dem Lerneffekt steht die Befriedigung der Neugierde, zu
sehen, woraus überhaupt ein Debian-Binärpaket (siehe <<binaerpakete>>)
entsteht und aus welchen Komponenten sich dieses zusammensetzt.

Damit erhalten Sie einen Blick hinter die Kulissen und können anhand des
Quellcodes ersehen, wie die Software programmiert wurde. Nur über diesen
Schritt können Sie ganz konkret nachvollziehen, wie diese funktioniert.
Das hilft Ihnen insbesondere auch dabei, die Ursache zu lokalisieren,
wenn ein Programm sich entgegen ihrer Erwartungen verhält. 

Viele Entwickler weisen der Dokumentation ihrer Software häufig einen
niedrigen Stellenwert zu. Es kommt daher vor, dass die Dokumentation
unvollständig, fehlerhaft bzw. veraltet ist oder in einer Sprache
vorliegt, die sie nicht beherrschen. Schwachpunkte sind zudem die
Verfahren, welche implementiert wurden, aber auch die Parameter,
Schalter und Konfigurationsdateien, mit der Sie das Verhalten der
Software steuern und beeinflussen können.

// Stichworte für den Index
(((apt-get, source)))
*Variante 1* ist das Programm `apt-get`. Es bringt hier den Schalter 
`source` mit und erwartet danach die Angabe eines oder mehrerer 
Paketnamen. Damit `apt-get` nach dem Aufruf die Quellpakete auch 
beziehen kann, benötigt es zudem einen entsprechenden Eintrag in der 
Liste der Paketquellen (siehe <<etc-apt-sources.list-verstehen>>). Für 
die Veröffentlichung Debian 9 _Stretch_ sieht ein gültiger Eintrag bspw. 
wie folgt aus:

.Eintrag für Sourcepakete in der Liste der Paketquellen
----
deb-src http://ftp.debian.org/debian/ stretch main 
----

APT wertet die Paketbeschreibung aus, bezieht danach alle Quellpakete
von dem angegebenen Paketmirror -- den Debian Source Code (`dsc`) plus
Paketierung (siehe <<aufbau-und-format-source>>) -- , aus denen das
Binärpaket zusammengebaut wurde und überprüft diese Komponenten (siehe
<<bezogenes-paket-verifizieren>>) anhand deren öffentlichem Schlüssel.
Am Schluss werden die drei Archive `dsc`, `tar` und `diff` im aktuellen
Verzeichnis entpackt. 

Gibt es zusätzliche Änderungen am Quellcode in Form von Patches, werden
diese ebenfalls bezogen und nacheinander auf den entpackten Quellcode
angewendet. Nachfolgendes Beispiel zeigt diesen Vorgang anhand des
Pakets 'libapache2-mod-authn-yubikey' für den Webserver Apache:

// TODO: Hier kommt noch Wheezy in einem Beispiel vor

.Bezug des Sourcepakets 'libapache2-mod-authn-yubikey' mit APT
----
$ apt-get source libapache2-mod-authn-yubikey
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
Es müssen 22,5 kB an Quellarchiven heruntergeladen werden.
Holen: 1 http://ftp.de.debian.org/debian/ wheezy/main libapache2-mod-authn-yubikey 1.0-1 (dsc) [1.891 B]
Holen: 2 http://ftp.de.debian.org/debian/ wheezy/main libapache2-mod-authn-yubikey 1.0-1 (tar) [16,5 kB]
Holen: 3 http://ftp.de.debian.org/debian/ wheezy/main libapache2-mod-authn-yubikey 1.0-1 (diff) [4.115 B]
Es wurden 22,5 kB in 5 s geholt (4.095 B/s).
gpgv: Schlüsselblockhilfsmittel`/home/frank/.gnupg/trustedkeys.gpg': Fehler beim Öffnen der Datei
gpgv: Unterschrift vom Do 17 Feb 2011 16:22:26 CET mittels RSA-Schlüssel ID 8649AA06
gpgv: Unterschrift kann nicht geprüft werden: Öffentlicher Schlüssel nicht gefunden
dpkg-source: Warnung: Fehler beim Überprüfen der Signatur von ./libapache2-mod-authn-yubikey_1.0-1.dsc
dpkg-source: Information: libapache2-mod-authn-yubikey wird nach libapache2-mod-authn-yubikey-1.0 extrahiert
dpkg-source: Information: libapache2-mod-authn-yubikey_1.0.orig.tar.bz2 wird entpackt
dpkg-source: Information: libapache2-mod-authn-yubikey_1.0-1.debian.tar.gz wird entpackt
$
----

// Stichworte für den Index
(((Debianpaket, devscripts)))
(((dget)))
(((dget, -d)))
(((dget, --download-only)))
(((Paket, Quellpaket nur herunterladen)))
*Variante 2* erfolgt mit Hilfe des Werkzeugs `dget` aus dem Paket
'devscripts' <<Debian-Paket-devscripts>>. Zu beachten ist hierbei, dass 
Quellpakete häufig aus mehreren Komponenten bestehen, ebenso müssen Quell-
und Binärpaket nicht namentlich übereinstimmen. Nachfolgend sehen Sie nun 
den Bezug des Quellpakets von 'bash-doc' mittels `dget`, welches hier aus
'bash' abgeleitet wird. Benutzt wird ebenfalls der Parameter 
`--download-only` (Langform für `-d`), welcher `dget` veranlasst, dass das 
Paket nur heruntergeladen wird und so belassen wird, sprich: bspw. nicht
weiter ausgepackt wird.

.Download des Quellpakets von 'bash' mittels `dget`
----
$ dget --download-only http://deb.debian.org/debian/pool/main/b/bash/bash_5.2.15.orig.tar.gz
dget: retrieving http://deb.debian.org/debian/pool/main/b/bash/bash_5.2.15.orig.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 9762k  100 9762k    0     0  3424k      0  0:00:02  0:00:02 --:--:-- 3424k
$
----

// Datei (Ende): ./werkzeuge/paketoperationen/sourcepakete-beziehen.adoc
