// Datei: ./werkzeuge/paketoperationen/verfuegbare-paketversionen-ermitteln.adoc

// Baustelle: Rohtext

[[verfuegbare-paketversionen-ermitteln]]

=== Verfügbare Paketversionen ermitteln ===

// vereinigen mit aus-welchem-repo-kommen-die-pakete

// TODO: Doppelt! Siehe auch werkzeuge/paketoperationen/aus-welchem-repo-kommen-die-pakete.adoc

// Stichworte für den Index
(((apt-cache, madison)))
(((Debianpaket, apt-doc)))
(((Paketversion anzeigen)))
Das Werkzeug `apt-cache` verfügt über das Unterkommando `madison`. Damit
finden Sie heraus, welche Pakete derzeit von den Spiegelservern in einer
neueren Version verfügbar sind. Nachfolgender Ausdruck zeigt das für das
Paket 'apt-doc' <<Debian-Paket-apt-doc>>.

.Ausgabe von `apt-cache` mit dem Unterkommando `madison` für 'apt-doc'
unter Debian 9 _Stretch_ auf einem System mit der Architektur `i386`
----
$ apt-cache madison apt-doc
   apt-doc |      1.4.6 | http://ftp.ch.debian.org/debian stretch/main i386 Packages
       apt |      1.4.6 | http://ftp.ch.debian.org/debian stretch/main Sources
$
----

// Stichworte für den Index
(((rmadison)))
(((Debianpaket, apt-doc)))
(((Debianpaket, devscripts)))
(((Paketversion anzeigen)))
Möchten Sie hingegen wissen, welche Versionen für die jeweiligen
Veröffentlichungen bereitstehen, hilft Ihnen das Werkzeug `rmadison` aus
dem Paket 'devscripts' weiter <<Debian-Paket-devscripts>>. Für das
bereits oben verwendete Paket 'apt-doc' sieht das wie folgt aus:

.Auflistung der verfügbaren Paketversionen mit `rmadison`
----
$ rmadison apt-doc
apt-doc    | 0.9.7.9+deb7u7 | oldoldstable       | all
apt-doc    | 1.0.9.8        | oldstable-kfreebsd | all
apt-doc    | 1.0.9.8.4      | oldstable          | all
apt-doc    | 1.4.6          | stable             | all
apt-doc    | 1.4.6          | testing            | all
apt-doc    | 1.5~beta1      | unstable           | all
$
----

// Stichworte für den Index
(((Debianpaket, base-files)))
(((Paketversion anzeigen, nach Architektur filtern)))
(((Paketversion anzeigen, nach Veröffentlichung filtern)))
Obige Ausgabe umfaßt die vier Spalten Paketname, Versionsnummer,
Veröffentlichung und Architektur. Möchten Sie die Ausgabe hingegen auf
eine bestimmte Veröffentlichung oder Architektur einschränken,
akzeptiert `rmadison` die Schalter `-a` 'Architektur' und `-s`
'Veröffentlichung'. Um zu sehen, welche Version des Paketes 'base-files'
für die Veröffentlichung Debian 9 _Stretch_ und die Architektur 'amd64'
bereitstehen, nutzen Sie den folgenden Aufruf:

.Gefilterte Auflistung der verfügbaren Paketversionen mit `rmadison`
----
$ rmadison -s stretch -a amd64 base-files
base-files | 9.9           | stable     | amd64
$
----

// Stichworte für den Index
(((aptitude, search '~U')))
(((aptitude, search '?upgradable')))
(((Paketversion anzeigen)))
`aptitude` kann Ihnen dieses ebenfalls darstellen. Dazu kennt es den
Suchfilter `search '~U'` bzw. `search '?upgradable'` in der Langform.
Ergebnis ist eine Liste der Pakete, welche den Installationsstatus, den
Paketnamen und die kurze Paketbeschreibung umfasst.

.Ausgabe von `aptitude` zur Liste der aktualisierbaren Pakete
----
$ aptitude search '~U'
i   acpi-support      - Skripte zur Verwaltung von ACPI-Ereignissen           
i   acpi-support-base - Skripte zur Verarbeitung grundlegender ACPI-Ereignisse
i   iceweasel         - Webbrowser auf Basis von Firefox                      
i A libc-bin          - Die »Embedded GNU C Library«: Binärdateien            
i A libc-dev-bin      - Embedded GNU C Library: Entwicklungsbinärdaten        
i   libc6             - Die »Embedded GNU C Library«: Laufzeitbibliotheken    
i A libc6-dev         - Die »Embedded GNU C Library«: Entwicklungsbibliotheken
i   libc6-i686        - »Embedded GNU C Library«: Laufzeitbibliotheken [optimi
i A libmozjs24d       - Mozilla SpiderMonkey JavaScript library               
i A xulrunner-24.0    - XUL + XPCOM application runner
$
----

// Datei (Ende): ./werkzeuge/paketoperationen/verfuegbare-paketversionen-ermitteln.adoc
