// Datei: ./praxis/debtags/debtags-webseite.adoc

// Baustelle: Fertig

[[debtags-webseite]]
=== Webseite zum Projekt ===

// Schlagworte für den Index
(((Debtags, API)))
(((Debtags, Dokumentation)))
(((Debtags, Projektseite)))
(((Debtags, Statistik)))
(((Debtags, Vokabular)))
Koordiniert wird Debtags über die Webseite zum Projekt
<<Debian-Debtags>>. Um ihrerseits am Projekt mitzuwirken, ist ein
SSL-Client-Zertifikat des Debian-Single-Sign-On-Services
<<Debian-SSO>> erforderlich. Jeder Debian-Entwickler hat dort
automatisch ein Benutzerkonto. Externe und angehende Debian-Entwickler
können sich — trotz der Abschaltung der Alioth-Webseiten Anfang 2018 —
auf Anfrage ein Konto im noch laufenden Alioth-LDAP anlegen lassen
<<Debian-SSO-Alioth>> und darüber sich ein Debian-Single-Sign-On
SSL-Client-Zertifikat erstellen lassen.

Auf der Projektseite finden Sie neben den Basisdaten eine ausführliche
Dokumentation inklusive der Informationen zum Application Programming
Interface (API) sowie zum genutzten Vokabular, d.h. den verwendeten
Schlagworten. Weiterhin gehört auch eine statistische Auswertung dazu,
um die Menge und die Verteilung der genutzten Schlagworte nachvollziehen
zu können <<Debian-Debtags-Statistics>>.

// Schlagworte für den Index
(((Debianpaket, debtags)))
(((Debtags, Debtags Editor)))
(((Debtags, Recherche anhand der Schlagworte)))
(((Debtags, paketbezogene Suche)))
Über vorbereitete Formulare recherchieren Sie sowohl paketbezogen als
auch anhand der Schlagworte. Für jedes Paket werden Ihnen diese
angezeigt. Im _Debtags Editor_ können diese von Ihnen ergänzt und
modifiziert werden (siehe <<fig.debtags-gimp>>). Alle darüber
vorgenommenen Änderungen fließen in das genutzte Vokabular und die
Datenbank zur Verwaltung und Speicherung der Schlagworte ein und werden
sofort wirksam. Bei einer späteren Veröffentlichung des 'debtags'-Pakets
sind dann auch Ihre Beiträge ganz offiziell im aktualisierten Paket
enthalten und somit für alle Benutzer verfügbar.

Die Webseite ist hervorragend konzipiert und bildet im Vergleich zu den
später besprochenen graphischen Programmen eine recht einfach zu
bedienende Schnittstelle zu den cleveren Werkzeugen aus dem
'debtags'-Paket. Diese Werkzeuge stellen wir Ihnen in
<<debtags-werkzeuge>> genauer vor.

// Datei (Ende): ./praxis/debtags/debtags-webseite.adoc
