// Datei: ./praxis/automatisierte-installation/automatisierte-installation.adoc

// Baustelle: Notizen

[[automatisierte-installation]]

== Automatisierte Installation ==

// Stichworte für den Index
(((cobbler)))
(((FAI)))
(((jumpstart)))
(((kickstart)))
(((Preseeding)))

Ändert sich ihr Aufgabenbereich von der Betreuung von Einzelsystemen hin zu
ganzen Rechnerverbünden mit weitestgehend ähnlicher oder im Idealfall sogar
identischer Software, müssen Sie sich Gedanken darüber machen, wie Sie diese 
Herde an Systemen in Schach halten -- das heißt diese Softwarelandschaft 
installieren und pflegen (sofern es sich nicht um Wegwerf-Systeme handelt). 
Das können dabei nicht nur Rechner für Schulungs- und Klassenräume sein, 
sondern auch eine Sammlung gefüllter Racks in Rechenzentren umfassen. 

Das Klonen eines bestehenden Systems, d.h. das Erstellen einer Eins-zu-eins-Kopie 
von einem Datenträger, ist möglich, aber hier nicht sinnvoll. Der Aufwand, aus 
dem Klon ein Individualsystem durch nachträgliche Anpassung zu erreichen, ist 
recht hoch. Dabei ist das Ändern des Hostnamens und der Netzwerkeinstellungen 
noch der kleinere Anteil -- aufwendiger wird es bspw. beim Bereinigen von 
Benutzer/Diensten samt deren Einstellungen, Logs und Daten. Eine Installation 
auf der Basis der Softwarepakete samt Voreinstellungen für das neue System ist
einfacher und insbesondere automatisierbar. Diesem Blickwinkel folgen wir hier.

Behalten Sie bei der Auswahl der Lösung auch im Blick, dass es verschiedene 
Rechnerklassen geben kann. Beispiele dafür sind Anwendungsserver 
('application server'), Client ('end user client'), Mailserver und auch 
Fileserver ('storage system'). Begriffe, die hier häufig genutzt werden, 
sind 'Hardware provisioning', 'OS provisioning' und 'Konfigurationsmanagement'. 
Die ersten beiden Begriffe beschreiben das vorherige Auswählen von 
Softwarekomponenten für die im System verbaute Hardware und das darauf 
genutzte Betriebssystem, bspw. das Paket für den passenden Grafiktreiber 
samt Einstellungen plus Linux-Kernel. Konfigurationsmanagement ist das 
Verwalten und Pflegen der definierten Rechnerklassen samt Liste der 
Softwarepakete und den Einstellungen zum jeweiligen Paket.

Als Kriterien für eine passende Lösung sind die nachfolgenden Punkte hilfreich.
Diese haben wir dem Debian-Wiki entnommen (siehe dazu 
<<Debian-Wiki-Automated-Installation>>):

unbeaufsichtigtes Ablaufen :: Installationen sollten ohne oder mit möglichst 
wenig menschlicher Interaktion ablaufen

parallele Installation :: mehrere Systeme werden gleichzeitig installiert

Skalierbarkeit :: neue Klienten und Veröffentlichungen von Betriebssystemn 
können einfach integriert werden

Flexibilität :: eine Konfiguration sollte möglich sein, die viele Eigenschaften
erlaubt

Anpassbarkeit :: es sollte möglich sein, das System nach Bedarf an spezifische 
Umgebungen und Gegebenheiten anzupassen

In der Vergangenheit wurden dafür bereits verschiedene Lösungen entworfen und 
genutzt. Zu den Vertretern gehören bspw. Jumpstart (Sun OS) <<jumpstart>>, 
Kickstart <<kickstart>> und Cobbler <<cobbler>>, FAI <<FAI-Projekt>>, Crowbar 
<<crowbar>>, Foreman <<foreman>>, OpenQRM <<openqrm>> und Spacewalk 
<<spacewalk>>. Debian selbst bringt als Technologie das sogenannte 'Preseeding' 
mit -- das Beantworten der Fragen des Debian Installers im Vorfeld.

=== FAI ===

* Fully-automatic installation (FAI) <<FAI-Projekt>>
* Eintrag im Debian Wiki <<Debian-Wiki-FAI>>
* Beitrag im Linux Magazin 01/09 <<FAI-Bornemann-Karg>>
* FAI 5.2 bringt Cloud-Support <<FAI-Cloud-Support>>

=== Kickstart ===

* https://cobbler.github.io/
* http://www.debian.itopstube.com/2011/11/automating-installation-with-kickstart.html
* https://fak3r.com/2011/08/18/howto-automate-debian-installs-with-preseed/

=== Erfahrungen aus der Praxis ===

ToDo
// Datei (Ende): ./praxis/automatisierte-installation/automatisierte-installation.adoc
