// Datei: ./anhang/paketformat-im-einsatz/paketformat-im-einsatz.adoc
// Baustelle: Rohtext

[[paketformat-im-einsatz]]
== Paketformat im Einsatz ==

=== Embedded-Geräte ===

// Stichworte für den Index
(((Armbian)))
(((DebWRT)))
(((Raspberry Pi OS)))
(((Raspbian)))

Armbian:: 
Debian GNU/Linux für ARM-basierte Geräte, bspw. ein Cubieboard oder Cubietruck
<<Armbian>>

DebWRT::
Debian GNU/Linux auf der Basis von OpenWRT für WLAN-Router. Eingestellt 2010.

Raspbian:: 
Debian GNU/Linux so rekompiliert, dass er mit bestmöglicher Optimierung auch 
auf den schwächsten Raspberry Pis läuft. <<Raspbian>>

Raspberry Pi OS::
Eine auf Raspbian aufsetzende Distribution <<RaspberryPiOS>> der Raspberry Pi 
Foundation <<RaspberryPi>>, die auch nicht-freie, "empfohlene" 
Closed-Source-Software und Dritthersteller-APT-Repositories in der 
Standard-Installation enthält.

=== Bildung ===

// Stichworte für den Index
(((DebianEdu/Skolelinux)))
(((Edubuntu)))
(((LernStick)))
(((Trisquel Sugar TOAST)))

Skolelinux :: früher DebianEdu, für den Einsatz in Schulen <<Skolelinux>>

Edubuntu :: Ubuntu für Schule und Bildung <<Edubuntu>>

LernStick :: Live-Distribution auf einem USB-Stick <<LernStick>>

Trisquel Sugar TOAST :: eine speziell für Schüler angepasste Version von 
Trisquel GNU/Linux <<Trisquel>> mit der Lernumgebung Sugar <<Sugar>>, die
vornehmlich aus dem Projekt One Laptop Per Child (OLPC) bekannt ist

=== Desktop ===

// Stichworte für den Index
(((Deepin)))
(((Emmabuntüs)))
(((Kubuntu)))
(((LiMux)))
(((Linux Mint)))
(((Linux Mint Debian Edition (LMDE))))
(((PureOS)))
(((SpiralLinux)))
(((Ubuntu)))
(((Univention Corporate Server (UCS))))

Deepin:: Angeblich die meistgenutzte Linux-Distribution Chinas <<Deepin>>

Emmabuntüs :: Wurde entwickelt, um Computer neu aufzusetzen, die an
Hilfsorganisationen gespendet wurden und technologisch älter sind. Wird 
gepflegt von der Emmaus-Stiftung aus Frankreich. Emmabuntüs <<Emmabuntus>> 
basiert auf Debian 'stable'.

LiMux:: Linux-Distribution, die im Rahmen der Migration der
Stadtverwaltung München zum Einsatz kam (2009-2020) <<LiMux>>

Linux Mint, Linux Mint Debian Edition (LMDE):: basiert auf Ubuntu bzw. Debian 'testing' <<LinuxMint>>

PureOS:: Linux-Distribution für Smartphones und Notebooks der Firma Purism. <<PureOS>>, <<Purism>>

SpiralLinux :: Debian-Derivat mit Fokus auf Einfachheit und sofortige Benutzung <<<SpiralLinux>>

Ubuntu (und dessen Ableger):: Linux für Einsteiger und den Desktop <<Ubuntu>>

Univention Corporate Server (UCS):: Linux mit integriertem Managementsystem für die zentrale und plattformübergreifende Verwaltung von Servern, Diensten, Clients, Desktops und Benutzern sowie von unter UCS betriebenen virtualisierten Computern <<UCS>>

=== Live-CD ===

// Stichworte für den Index
(((Aptosid)))
(((BackTrack)))
(((Debian Live System)))
(((Finnix)))
(((Grml)))
(((Kali Linux)))
(((Knoppix)))
(((MX Linux)))
(((Siduction)))
(((Slax)))
(((Tails)))

Aptosid:: Linux-Distributionen für Desktop-Computer und Notebooks, basierend auf Debian 'unstable' <<Aptosid>>

BackTrack, Kali Linux:: gedacht zur Netzwerk- und Sicherheitsanalyse. BackTrack <<BackTrack>> wurde im Frühjahr 2013 eingestellt, Kali Linux <<Kali-Linux>> ist dessen Nachfolger

Debian Live System:: Projekt zur Erstellung und Pflege von Debian-basierten Live-Systemen und Debian Live Images <<DebianLiveSystem>>

Finnix:: Debian-Minimalsystem, gedacht für Systemadministratoren zur
Wartung und Reparatur im Rahmen von Notfällen <<Finnix>>

Grml:: textbasiert, gedacht als Rettungssystem und für die Systemanalyse, basiert auf Debian 'unstable' <<Grml>>

Knoppix:: Mutter aller Live-Systeme mit dem Vater Klaus Knopper. Es
basiert auf einer Mischung aus Debian 'stable', 'unstable' und 'testing'
sowie zusätzlichen, nicht-freien Komponenten <<Knoppix>>

MX Linux:: Linux-Distributionen für Desktop-Computer und Notebooks,
basierend auf Debian 'stable' <<MXLinux>>

Siduction:: Linux-Distributionen für Desktop-Computer und Notebooks, basierend auf Debian 'unstable' <<Siduction>>

Slax:: Live-Distribution mit dem Fokus auf Anpassbarkeit an die eigenen
Bedürfnisse <<Slax>>.

Tails:: The Amnesic Incognito Live System (TAILS) <<TAILS>> -- eine
speziell auf Privatsphäre ausgelegte Debian-Distribution. TAILS kommt
beim Tor-Projekt <<TorProject>> zum Einsatz.

Nach aktuellem Stand lassen sich zumindest Aptosid, Siduction, Grml und
Knoppix ebenfalls auf der Festplatte installieren und sind damit nicht
nur Live-CDs.

=== Minimalsysteme ===

// Stichworte für den Index
(((Damn Small Linux (DSL))))
(((Finnix)))
(((Tiny Core Linux)))
(((Trisquel Mini)))

Damn Small Linux :: wird seit Mitte 2012 nicht mehr weiterentwickelt <<DamnSmallLinux>>

Finnix:: Debian-Minimalsystem, gedacht für Systemadministratoren zur
Wartung und Reparatur im Rahmen von Notfällen <<Finnix>>

Tiny Core Linux :: Nachfolger von Damn Small Linux. Die dCore-Variante
basiert auf der Infrastruktur und den Paketen von Debian und Ubuntu
<<TinyCoreLinux>>

Trisquel Mini :: Minimalsystem der Linux-Distribution Trisquel GNU/Linux
<<Trisquel>> unter Verwendung von LXDE als graphische Bedienoberfläche

=== Spieleplattform ===

// Stichworte für den Index
(((Drauger OS)))
(((Steam OS)))

Drauger OS:: Betriebssystem für Linux Desktop Gaming auf der Basis von Ubuntu LTS <<DraugerOS>>

Steam OS:: ausgelegt für Spiele und die Verwendung großer Bildschirme.
Version 1.0 basiert auf Debian 7 _Wheezy_ und Version 2.0 auf Debian 8
_Jessie_. Ab Version 3.0 benutzt Steam OS <<SteamOS>> hingegen Arch Linux
<<ArchLinux>> als Basis.

=== Mobile Architekturen ===

// Stichworte für den Index
(((Droidian)))
(((Liberux)))
(((Maemo)))
(((Meego)))
(((Mobian)))
(((OpenMoko)))
Neben der x86-Architektur kommt das `deb`-Paketformat auf mobilen
Architekturen und Plattformen zum Einsatz. Dazu zählen etwa die
Mobiltelefone Nokia N900 mit Maemo <<Maemo>>, Nokia N9 mit Meego
<<MeeGo>> sowie diverse Distributionen für das OpenMoko <<OpenMoko>>.
Auch der community-getragene, inoffizielle N900-Nachfolger Neo900
<<Neo900>> soll u.a. mit Maemo und damit ebenfalls mit dem
`deb`-Paketformat laufen.

Ebenso existieren die drei Projekte Droidian <<Droidian>>, Mobian 
<<Mobian>> und Liberux <<Liberux>>. Bei ersterem handelt es sich um 
Debian GNU/Linux für mobile Geräte auf der Basis von Android. Es 
setzt bspw. der Hersteller FuriLabs mit seinem Modell FuriPhone FLX1 
ein <<FuriLabs>>. Mobian ist auf ARM64-Hardware schon fast 
vollständig funktionstüchtig, lediglich die Kameras für Vorder- und 
Rückseite der Geräte werden noch nicht unterstützt. Liberux hingegen 
ist zu Ende 2025 noch großtenteils Wunschdenken eines spanischen 
Entwicklerteams und hat via Crowdfunding bereits etwa 10% der 
anvisierten Summe für das Projekt eingespielt. Inwieweit die 
Entwicklung tatsächlich in geplanter Form stattfinden wird, ist 
aktuell unklar.

=== Anstatt Linux ===

// Stichworte für den Index
(((BSD)))
(((Debian GNU/kFreeBSD)))
(((Debian GNU/Hurd)))
(((Dyson OS)))
(((Fink)))
(((Hurd)))
(((Illumian)))
(((DilOS)))
(((Nexenta OS)))
(((StormOS)))
(((UbuntuBSD)))
Auch mit Nicht-Linux-Kerneln wird das Paketformat eingesetzt. Einerseits
gibt es Debian im Rahmen der Debian Ports auch mit BSD- und
GNU-Hurd-Kernel in Form von Debian GNU/kFreeBSD
<<Debian-Wiki-Debian-GNUkFreeBSD>> und Debian GNU/Hurd
<<Debian-Wiki-Debian-GNUHurd>>. Auch von Ubuntu gibt es mittlerweile
unter dem Namen UbuntuBSD <<UbuntuBSD>> eine Variante mit
FreeBSD-Kernel.

Andererseits gibt es außerhalb des Debian-Projektes Portierungen auf
den OpenSolaris bzw. Illumos-Kernel, z.B. Dyson OS <<DysonOS>> und
DilOS <<DilOS>>. Weitere Distributionen mit dieser Kombination waren Nexenta
OS <<NexentaOS-Illumian>> und die damit verwandten StormOS <<StormOS>>
und Illumian <<NexentaOS-Illumian>>. Sie wurden aber allesamt bereits
wieder eingestellt.

Unter Mac OS X existieren mit Fink <<Finkproject>> zusätzliche, freie
Pakete. Diese können Sie über einen Jailbreak auch auf Ihrem iPhone,
iPod und iPad benutzen.

//[TIP] 
//.Mischen von Paketformaten
//====
//`deb`- und `rpm`-Pakete lassen sich in verschiedenen Konstellationen
//miteinander mischen. Wie das im Detail funktioniert, erklären wir Ihnen
//genauer in <<paketformate-mischen>>.
//====

=== Nachbauten und Derivate ===

// Stichworte für den Index
(((ipkg)))
(((OpenWrt)))
(((opkg)))
(((Paketformat, ipkg)))
(((Paketformat, opkg)))
Gerade in der Embedded-Szene, wo es auf Kompaktheit ankommt, sind `dpkg`
und APT oft zu groß und komplex. Dennoch sind die Grundideen von Debians
Paketmanagement-System auch in dieser Community beliebt und werden
genutzt. So ist das _Itsy Package Management System_ (`ipkg`) <<ipkg>>
und später dessen Fork _OpenMoko Package Management System_ (`opkg`)
<<opkg>> entstanden. `opkg` ist heute noch u.a. bei OpenWrt im Einsatz,
einer bekannten Linux-Distribution für WLAN-Router.

// Stichworte für den Index
(((Paketformat, Click-Pakete)))
(((Paketformat, Snappy)))
Auch Canonical – das Unternehmen hinter Ubuntu – versucht sich seit 2013
in einem Derivat von Debians Paketsystem. Ihre sogenannten
'Click-Pakete' (siehe <<Click-Paket-Format>> und <<SingleClickInstall>>)
funktionieren ähnlich wie `deb`-Pakete, jedoch ohne große
Abhängigkeiten, und sind optimiert auf den Einsatz bei mobilen Geräten
von Drittanbietern. Die hervorgehobenen Merkmale sind die direkte
Installation des Pakets aus dem Webbrowser (siehe auch
<<webbasierte-installation-von-paketen-mit-apturl>>) und die geringen
Paketabhängigkeiten. Das Ziel besteht darin, alle benötigten Daten einer
Software in möglichst einem Paket bereitzustellen. 

Wie sich in der Diskussion zeigt, ist der Einsatz der Click-Pakete recht
umstritten (siehe <<Click-Paket-Format-Diskussionen>> und
<<Watson-App-Design>>). Mittlerweise ist dieses Format vor dessen
größerer Verbreitung bereits durch den seit Herbst 2015 verwendeten
Nachfolger Snappy <<Ubuntu-Snappy>> <<Ubuntu-Snappy-Projekt>> überholt.

=== Weitere Debian-Derivate ===

Einen ausführlichen Überblick zu weiteren Debian-Derivaten gibt der
Debian-Derivate-Zensus. Er ist ein Bestandteil des Debian-Wikis
<<DebianDerivativeCensus>>.

// Datei (Ende): ./anhang/paketformat-im-einsatz/paketformat-im-einsatz.adoc
