// Datei: ./praxis/plattenplatz-sparen-mit-der-paketverwaltung/plattenplatz-sparen-mit-der-paketverwaltung.adoc

// Baustelle: Rohtext

[[plattenplatz-sparen-mit-der-paketverwaltung]]
== Plattenplatz sparen mit der Paketverwaltung ==

// Stichworte für den Index
(((Belegten Festplattenplatz minimieren)))
Eine Installation eines Betriebssystems besteht aus vielen einzelnen 
Paketen. Um jegliche Software vorzuhalten, reicht der Speicherplatz 
nicht immer aus, d.h. ist stets in irgendeiner Form begrenzt. 
Einerseits hat das Filesystem Begrenzungen durch die Anzahl der Inodes,
andererseits hat jede Partition eine physische Grenze. Je mehr Platz 
belegt ist, um so langsamer werden die Plattenzugriffe, auch wenn
heutzutage SSDs im Alltagseinsatz dominieren. 

Durchgeführte Experimente -- d.h. das Ausprobieren von neuer Software 
-- hinterlassen ihre Spuren in Form von ``Paketresten'', die hinterher
übriggeblieben sind und trotz aller Vorkehrungen vielleicht doch nicht 
automatisch aufgeräumt wurden. Daher besprechen wir nachfolgend eine
Reihe von Lösungsmöglichkeiten mit Hilfe der Paketverwaltung, um den 
belegten Speicherplatz zu verringern. Welche davon passend sind, kann 
nicht verallgemeinert werden und hängt von ihrem konkreten Einzelfall 
ab.

// Duplikate finden
include::duplikate-finden.adoc[]

// Pfade ausschließen
include::pfade-ausschliessen.adoc[]

// Ungenutzte Lokalisierungen entfernen
include::ungenutzte-lokalisierungen-entfernen.adoc[]

// Ungenutzte Bibliotheken prüfen
include::ungenutzte-bibliotheken-pruefen.adoc[]

// Paketcache aufräumen
include::paketcache-aufraeumen.adoc[]

// Paketcache auf separater Paratition
include::paketcache-auf-separater-partition.adoc[]

// Logfiles begrenzen
include::logfiles-begrenzen.adoc[]

// Syslog deaktivieren
include::syslog-deaktivieren.adoc[]

// Die Größe der Debian-Installation verringern
include::die-groesse-der-debian-installation-verringern.adoc[]

// Mittels Bleachbit aufräumen
include::mittels-bleachbit-aufraeumen.adoc[]

// Datei (Ende): ./praxis/plattenplatz-sparen-mit-der-paketverwaltung/plattenplatz-sparen-mit-der-paketverwaltung.adoc
