// Datei: ./praxis/plattenplatz-sparen-mit-der-paketverwaltung/plattenplatz-sparen-mit-der-paketverwaltung.adoc

// Baustelle: Rohtext

[[plattenplatz-sparen-mit-der-paketverwaltung]]
== Plattenplatz sparen mit der Paketverwaltung ==

// Stichworte für den Index
(((Belegten Festplattenplatz minimieren)))
Eine Installation eines Betriebssystems besteht aus vielen einzelnen 
Paketen. Um jegliche Software vorzuhalten, reicht der Speicherplatz 
nicht immer aus, d.h. ist stets in irgendeiner Form begrenzt. 
Einerseits hat das Filesystem Begrenzungen durch die Anzahl der Inodes,
andererseits hat jede Partition eine physische Grenze. Je mehr Platz 
belegt ist, um so langsamer werden die Plattenzugriffe, auch wenn
heutzutage SSDs im Alltagseinsatz dominieren. 

Durchgeführte Experimente -- d.h. das Ausprobieren von neuer Software 
-- hinterlassen ihre Spuren in Form von ``Paketresten'', die hinterher
übriggeblieben sind und trotz aller Vorkehrungen vielleicht doch nicht 
automatisch aufgeräumt wurden. Daher besprechen wir nachfolgend eine
Reihe von Lösungsmöglichkeiten mit Hilfe der Paketverwaltung, um den 
belegten Speicherplatz zu verringern. Welche davon passend sind, kann 
nicht verallgemeinert werden und hängt von ihrem konkreten Einzelfall 
ab.

// Duplikate finden
include::duplikate-finden.adoc[]

// Pfade ausschließen
include::pfade-ausschliessen.adoc[]

// Ungenutzte Lokalisierungen entfernen
include::ungenutzte-lokalisierungen-entfernen.adoc[]

// Ungenutzte Bibliotheken prüfen
include::ungenutzte-bibliotheken-pruefen.adoc[]

// Paketcache aufräumen
include::paketcache-aufraeumen.adoc[]

// Paketcache auf separater Paratition
[[plattenplatz-sparen-mit-der-paketverwaltung-paketcache-separat]]
=== Paketcache auf separater Paratition ===

// Stichworte für den Index
(((Paketcache, auf separater Partition)))
Ist der Zugriff auf den Paketcache zu langsam, ist die Nutzung von tmpfs
als Dateisystem eine Option. Dabei liegt dieses Dateisystem im RAM. Mit 
Hilfe eines entsprechenden Eintrags in der Datei `/etc/fstab` binden Sie 
das Verzeichnis `/var/cache/apt` ein. Weitere Informationen lesen Sie 
dazu in <<cache-verzeichnis-auf-separater-partition>>.

// Logfiles begrenzen
[[plattenplatz-sparen-mit-der-paketverwaltung-logfiles-begrenzen]]
=== Logfiles begrenzen ===

// Stichworte für den Index
(((Logfiles begrenzen)))
Hierbei hilft Ihnen das Werkzeug `logrotate` aus dem gleichnamigen 
Debianpaket <<Debian-Paket-logrotate>>. Es gehört zur 
Standardinstallation von Debian und es wäre daher ungewöhnlich, wenn
es nicht installiert ist.

`logrotate` sorgt für nicht permanent wachsende Logfiles. Passen Sie
die Konfiguration an, wenn Sie manuell weitere Logfiles in Anwendungen 
ergänzen (bspw. VHosts im Apache).

// Syslog deaktivieren
[[plattenplatz-sparen-mit-der-paketverwaltung-syslog-deaktivieren]]
=== Syslog deaktivieren ===

// Stichworte für den Index
(((Syslog deaktivieren)))
Um die Menge der Logdateien zu verringern, verwenden Sie keinen 
`syslogd` und lassen den Syslog stattdessen nur in einem Ringbuffer 
laufen. Das Default-Paket ist 'rsyslog' -- dieses entfernen Sie 
zunächst. Nutzen Sie Systemd, schauen Sie sich das Logfile danach 
im Ringpuffer mit `journalctl` an, bei SysVInit installieren Sie 
stattdessen das Paket 'busybox-syslogd' und lesen mit Hilfe des
Werkzeugs `logread` den Inhalt des Ringpuffers.

// Die Größe der Debian-Installation verringern
[[plattenplatz-sparen-mit-der-paketverwaltung-debian-installation]]
=== Die Größe der Debian-Installation verringern ===

// Stichworte für den Index
(((Größe der Debian-Installation verringern)))
Eine übliche Installation von Debian GNU/Linux für den Desktop kann 
durchaus mehr als 2000 Pakete umfassen. Um den "Fußabdruck" kleiner
zu machen, bleibt nur, von Anfang an konsequent zu sein:

* installieren Sie nur die Pakete, die Sie tatsächlich benötigen und auch benutzen
* identifizieren Sie unnötige Pakete und entfernen Sie diese, sofern das möglich ist
* vermeiden Sie `tasksel` (siehe <<tasksel>>), auch wenn das Werkzeug noch so toll ist und wählen stattdessen lediglich die Pakete aus, die Sie wirklich benötigen

Eine vollständigere Liste beinhaltet der Abschnitt 'ReduceDebian' im 
Debian Wiki <<ReduceDebian>>. Diese Liste rät u. a. zu den folgenden 
Schritten:

* entfernen Sie nicht-kritische und unnötige Pakete
* konfigurieren Sie Apt so um, dass es nicht automatisch zusätzliche Pakete installiert
* ersetzen Sie Pakete durch kleinere Äquivalente
* entfernen Sie unnötige Spracheinstellungen (Locales), bspw. mittels `localepurge` (siehe <<plattenplatz-sparen-mit-der-paketverwaltung-lokalisierungen>>)
* entfernen Sie unnötige Kernelmodule
* bauen Sie einen kleineren, spezifischeren Linuxkernel

Stehen Softwaretests an, hilft es, diese in Virtuelle Maschinen oder 
Container auszulagern. Damit verringert sich der Ballast, der später 
vielleicht wieder aufgeräumt werden muss, sollte die gerade ausprobierte
Software doch nicht ihren Erwartungen entsprechen.

// Mittels Bleachbit aufräumen
include::mittels-bleachbit-aufraeumen.adoc[]

// Datei (Ende): ./praxis/plattenplatz-sparen-mit-der-paketverwaltung/plattenplatz-sparen-mit-der-paketverwaltung.adoc
