// Datei: ./werkzeuge/paketcache/groesse-des-paketcaches.adoc

// Baustelle: Rohtext

[[groesse-des-paketcaches]]

=== Größe des Paketcaches ===

// Stichworte für den Index
(((Paketcache, /var/cache/apt/archives/)))
(((Paketcache, belegter Speicherplatz)))

==== Wieviel Platz belegt der Paketcache? ====

Diese Information erhalten Sie auf zwei Wegen. *Möglichkeit 1* ist der
Aufruf von `apt-cache stats` in Kombination mit `grep`, wobei Sie die
Zeile "Gesamtmenge an Speicher" aus der Ausgabe von `apt-cache stats`
herausfiltern.

.`apt-cache stats` liefert die Größe des APT-Caches
----
$ apt-cache stats | grep "Gesamtmenge an Speicher"
Gesamtmenge an Speicher: 31,1 M
$
----

Für *Möglichkeit 2* wenden Sie `du` mit den beiden Schaltern `-s`
(Langform: `--summarize`) und `-h` (Langform: `--human-readable`) auf
das Verzeichnis des Paketcaches an. Sofern nicht anders von Ihnen
konfiguriert, ist der Pfad `/var/cache/apt/archives`.

.`du` ermittelt die Größe des Verzeichnisses des Paketcaches
----
$ du -sh /var/cache/apt/archives/
1,4M	/var/cache/apt/archives/
$
----

In unseren Tests liefern beide Kommandos erheblich voneinander
abweichende Werte auf dem gleichen System. Wir können derzeit noch nicht
erklären, warum das so ist und warum bei `apt-cache` der Wert so hoch
ist.

==== Größe des Paketcaches festlegen ====

// Stichworte für den Index
(((apt-config, dump)))
(((APT::Cache-Grow)))
(((APT::Cache-Limit)))
(((APT::Cache-Start)))
(((Paketcache, Größe festlegen)))

Der Defaultwert ist mit 0 festgelegt, d.h. es besteht keine
Größenbegrenzung seitens APT. In diesem Fall ergeben sich die Limits aus
der physikalischen Größe der Partition, der das Verzeichnis für den 
Paketcache zugeordnet ist sowie dem Dateisystem auf der Partition
selbst. Im Dateisystem sind wiederum die Anzahl der Inodes (Einträge)
und die Blockgröße festgelegt, die letzendlich regeln, wieviele Pakete
als Datei gespeichert werden können.

// Datei (Ende): ./werkzeuge/paketcache/groesse-des-paketcaches.adoc
