// Datei: ./werkzeuge/paketcache/paketcache-status.adoc

// Baustelle: Fertig

[[paketcache-status]]

=== Paketcache-Status ===

// Stichworte für den Index
(((apt-cache, stats)))
(((Paketabhängigkeiten, zählen)))
(((Paketcache, Status anzeigen)))
(((Paketcache, Zustand anzeigen)))
(((Paketvarianten, virtuelles Paket)))
Den aktuellen Zustand des Paketcaches erfahren Sie mit Hilfe das
Kommandos `apt-cache stats`. Es wertet den Paketcache hinsichtlich der
gefundenen Symbole aus -- d.h. die Namen, die Varianten und die Bezüge
zwischen den Paketen, die sich derzeit im Cache befinden. 

.Informationen zum Zustand des Paketcache ausgeben
----
$ apt-cache stats
Gesamtzahl an Paketnamen: 47488 (950 k)
Gesamtzahl an Paketstrukturen: 47488 (2.279 k)
  davon gewöhnliche Pakete: 35987
  davon rein virtuelle Pakete: 371
  davon einzelne virtuelle Pakete: 4324
  davon gemischte virtuelle Pakete: 1029
  davon fehlend: 5777
Gesamtzahl an unterschiedlichen Versionen: 37547 (2.403 k)
Gesamtzahl an unterschiedlichen Beschreibungen: 87385 (2.097 k)
Gesamtzahl an Abhängigkeiten: 222388 (6.227 k)
Gesamtzahl an Version/Datei-Beziehungen: 40866 (654 k)
Gesamtzahl an Beschreibung/Datei-Beziehungen: 87385 (1.398 k)
Gesamtzahl an Bereitstellungen: 7563 (151 k)
Gesamtzahl an Mustern: 164 (1.732 )
Gesamtmenge des Abhängigkeits-/Versionsspeichers: 911 k
Gesamtmenge an Slack: 73,0 k
Gesamtmenge an Speicher: 11,8 M
Total buckets in PkgHashTable: 196613
  Unused: 108138
  Used: 88475
  Utilization: 44.9996%
  Average entries: 1.33334
  Longest: 17
  Shortest: 1
Total buckets in GrpHashTable: 196613
  Unused: 101900
  Used: 94713
  Utilization: 48.1723%
  Average entries: 1.3668
  Longest: 7
  Shortest: 1
$
----

Die nachfolgenden Beschreibungen zu den einzelnen Zeilen der Ausgabe
basieren auf der Manpage zu `apt-cache`. In Klammern finden sie die
dazugehörige englische Übersetzung der Schlüsselworte. Findet sich als
Beschreibung die Angabe 'ToDo', liegt noch keine Beschreibung vor --
auch nicht in der Manpage zu `apt-cache`.

Gesamtzahl an Paketnamen ('total package names') :: gibt die Gesamtzahl
der im Paketcache gefundenen Pakete an.

Gesamtzahl an Paketstrukturen ('total package structures') :: ToDo

Gewöhnliche Pakete ('normal packages') :: gibt die Anzahl der regulären, 
gewöhnlichen Paketnamen an. Dieses sind Pakete, für die eine 
Eins-zu-Eins-Entsprechung zwischen ihrem Namen und dem Namen besteht, die 
andere Pakete für ihre Abhängigkeiten benutzen. Die Mehrzahl der Pakete
fällt in diese Kategorie.

Rein virtuelle Pakete ('pure virtual packages') :: gibt die Anzahl der
Pakete an, für die nur ein virtueller Paketname existiert. Das kommt vor, 
wenn Pakete nur den virtuellen Paketnamen 'bereitstellen' und aktuell 
kein Paket diesen Namen benutzt. Zum Beispiel ist 'mail-transport-agent' 
ein rein virtuelles Paket. Mehrere Pakete stellen dieses bereit, aber es 
gibt kein tatsächliches Paket mit dem Namen.

Einzelne virtuelle Pakete ('single virtual packagess') :: gibt die Anzahl 
der Pakete mit nur einem Paket an, das ein bestimmtes virtuelles Paket 
bereitstellt. Beispielsweise ist 'X11-text-viewer' ein solches Paket, 
aber nur das Paket 'xless' stellt dieses bereit.

Gemischte virtuelle Pakete ('mixed virtual packages') :: gibt die Anzahl 
der Pakete an, die entweder ein bestimmtes virtuelles Paket bereitstellen 
oder den virtuellen Paketnamen als Paketnamen haben. Beispielsweise ist 
'debconf' solches Paket, dieses wird aber auch vom Paket 'debconf-tiny' 
bereitgestellt.

Fehlende Pakete ('missing') :: das benennt die Anzahl der Paketnamen, auf 
die eine Abhängigkeit verweist, die aber von keinem Paket bereitgestellt 
werden. Fehlende Pakete könnten auftauchen, wenn nicht auf eine 
vollständige Veröffentlichung zugegriffen oder ein (echtes oder 
virtuelles) Paket aus einer Veröffentlichung gestrichen wurde. 
Normalerweise erfolgt der Bezug in der Paketbeschreibung über die beiden
Schlüsselworte `Conflicts` oder `Breaks` (siehe dazu
<<konzepte-und-ideen-dahinter-binaerpakete>>).

Gesamtzahl an unterschiedlichen Versionen ('total distinct versions') ::
diese Angabe benennt die Anzahl der im Paketcache gefundenen 
Paketversionen. Dieser Wert ist meistens identisch mit der Anzahl der
gesamten Paketnamen. Wenn auf mehr als eine Veröffentlichung zugegriffen
wird -- zum Beispiel 'stable' und 'unstable' zusammen -- , kann dieser
Wert deutlich größer als die gesamte Anzahl der Paketnamen sein.

Gesamtzahl an unterschiedlichen Beschreibungen ('total distinct descriptions') :: Angabe zur Anzahl unterschiedlicher Beschreibungen.

Gesamtzahl an Abhängigkeiten ('total dependencies') :: benennt die Anzahl 
der Abhängigkeitsbeziehungen, den alle Pakete im Paketcache beanspruchen.

Gesamtzahl an Version/Datei-Beziehungen ('total ver/file relations') ::
ToDo

Gesamtzahl an Beschreibung/Datei-Beziehungen ('total desc/file relations') :: ToDo

Gesamtzahl an Bereitstellungen ('total provides mappings') :: ToDo

Gesamtzahl an Mustern ('total globbed strings') :: ToDo

Gesamtmenge des Abhängigkeits-/Versionsspeichers :: ToDo

Gesamtmenge an Slack ('total slack space') :: ToDo

Gesamtmenge an Speicher ('total space accounted for') :: Angabe zur
Gesamtgröße des Paketcaches.

Gesamtzahl der Einträge in der PkgHashTable ('total buckets in PkgHashTable') :: ToDo

Gesamtzahl der Einträge in der GrpHashTable ('total buckets in GrpHashTable') :: ToDo

Ist der Platz auf ihrem Speichermedium knapp, sehen Sie in Zeile
'Gesamtmenge an Speicher' die Angabe, welche Menge durch den Paketcache
gerade belegt wird. Wie Sie darin wieder für Ordnung sorgen, lesen Sie
unter ``Paketcache aufräumen'' in <<paketcache-aufraeumen>> nach.

// Datei (Ende): ./werkzeuge/paketcache/paketcache-status.adoc
