// Datei: ./konzepte/linux-dschungel/welche-unix-artigen-betriebssysteme-verwenden-das.adoc

// Baustelle: Fertig
// Axel: Fertig

[[welche-unix-artigen-betriebssysteme-verwenden-das]]

=== Welche UNIX-artigen Betriebssysteme verwenden das Paketformat und das APT-Paketmanagement ===

// Stichworte für den Index
(((deb-Paketformat)))
(((Paketformat, deb)))
Debian-Binärpakete liegen in einem spezifischen Format vor – dem
`deb`-Paketformat. Sowohl das Format, als auch die dazugehörigen
Werkzeuge haben innerhalb der letzten 20 Jahre bei weitaus mehr
UNIX-artigen Betriebssystemen Einzug gehalten, als es auf den ersten
Blick zu vermuten wäre.

Vereinfacht gesagt, basiert praktisch jedes Debian-Derivat auf den beiden
Konzepten. Die Übersicht in <<paketformat-im-einsatz>> zeigt eine
Auswahl, jeweils ergänzt um den spezifischen Einsatzbereich. Bis auf den
Univention Corporate Server (UCS) sind alle der genannten Derivate
kostenfrei verfügbar.

// Datei (Ende): ./konzepte/linux-dschungel/welche-unix-artigen-betriebssysteme-verwenden-das.adoc
