// Datei: ./werkzeuge/paketquellen-und-werkzeuge/empfehlung-zum-ablauf-fuer-das-hinzufuegen-und-aendern-von-paketquellen.adoc

// Baustelle: Fertig

[[empfehlung-zum-ablauf-fuer-das-hinzufuegen-und-aendern-von-paketquellen]]
=== Empfehlung zum Ablauf für das Hinzufügen und Ändern von Paketquellen ===

// Indexeinträge
(((add-apt-repository)))
(((apt-get, update)))
(((aptitude, update)))
(((/etc/apt/sources.list, Paketquelle nachtragen)))
(((/etc/apt/sources.list.d/, Paketquelle nachtragen)))
Wie bereits in <<paketquellen>> ausgeführt, ist die Datei
`/etc/apt/sources.list` der Dreh- und Angelpunkt für alle verwendeten
Paketquellen. Erfolgen Änderungen in dieser Datei, informieren Sie die
Paketverwaltung danach noch über diese Modifikation. Infolgedessen
synchronisiert sie lokal vorliegende Informationen über verfügbare
Pakete und deren Abhängigkeiten. Wir raten Ihnen hierfür zu folgendem
Ablauf:

. Erstellen Sie zuerst eine Sicherheitskopie der Datei
  `/etc/apt/sources.list`. Gegebenenfalls macht das auch Ihr Texteditor
  automatisch.

. Tragen Sie die neuen oder veränderten Paketquellen in der Datei
  `/etc/apt/sources.list` nach und speichern diese Datei ab. Wenn Sie
  nur neue Paketquellen hinzufügen wollen, können Sie alternativ auch
  eine neue Datei im Verzeichnis `/etc/apt/sources.list.d/` anlegen.
  Der Name dieser Datei muss dann auf `.list` enden.

. Sofern dies keine offiziellen Debian-Repositories sind, verifizieren
  Sie die Paketquelle, die Sie hinzugefügt oder geändert haben. Unter
  ``Paketquelle auf Echtheit überprüfen'' in
  <<paketquelle-auf-echtheit-ueberpruefen>> erfahren Sie, wie das zu
  erfolgen hat.

. Aktualisieren Sie die lokalen Paketlisten mit dem Kommando `apt-get
  update` oder `aptitude update`. Bitte beachten Sie dazu auch unsere
  Anmerkungen unter ``Liste der verfügbaren Pakete aktualisieren'' in
  <<liste-der-verfuegbaren-pakete-aktualisieren>>. Handelt es sich um 
  ein Distributionsupgrade, lesen Sie bitte dazu zusätzlich unter 
  ``Distribution aktualisieren'' in <<distribution-aktualisieren>> nach.

Mit dieser Vorgehensweise ist sichergestellt, dass die Paketverwaltung
über ihre Veränderungen in der Liste der Paketquellen Bescheid weiß. Nun
können Sie die Pakete aus den geänderten oder neuen Paketquellen zu
ihrem System hinzufügen.

Im Bedarfsfall können Sie auch auf den Stand vor Ihren Veränderungen
zurückgreifen. Sollte dies erforderlich sein, restaurieren Sie die im
ersten Schritt angelegte Sicherheitskopie oder -- falls Sie nur eine
neue Datei angelegt haben, löschen Sie diese -- und führen das
Kommando `apt-get update` respektive `aptitude update` erneut aus.

[TIP]
.Mit etwas Automatisierung den Ablauf vereinfachen
====
Möchten Sie diese Schrittfolge automatisieren, hilft Ihnen das
Kommando `add-apt-repository` weiter. Dessen Möglichkeiten besprechen
wir genauer in <<eintraege-mit-add-apt-repository-im-griff-behalten>>.
====

// Datei (Ende): ./werkzeuge/paketquellen-und-werkzeuge/empfehlung-zum-ablauf-fuer-das-hinzufuegen-und-aendern-von-paketquellen.adoc
