// Datei: ./werkzeuge/paketquellen-und-werkzeuge/paketquellen.adoc

// Baustelle: Fertig
// Axel: Fertig

[[paketquellen]]
=== Paketquellen ===

==== Begriff und Hintergrund ====

// Stichworte für den Index
(((Paketmirror)))
(((Paketmirror,Paketspiegel)))
(((Paketquelle)))
(((Paketquelle,APT-Repository)))
(((Paketquelle,Repository)))
(((Paketspiegel,Paketmirror)))
(((Repo,Paketquelle)))
(((Repository,Paketquelle)))
Eine Paketquelle bezeichnet einen Ort, von dem aus Softwarepakete zur
Verfügung stehen. Alternativ und gleichbedeutend werden dafür auch die
Begriffe _APT-Repository_, _Repository_ oder ganz kurz nur _Repo_
benutzt. Der Begriff _Paketmirror_ – oder auch komplett eingedeutscht
als _Paketspiegel_ – wird ebenfalls gerne verwendet. Letzteres
impliziert aber zusätzlich, dass es sich dabei um eine vollständige Kopie
einer offiziellen Paketquelle handelt, also z.B. um einen Spiegelserver
von Debian oder Ubuntu.

// Stichworte für den Index
(((Paketquelle, CD)))
(((Paketquelle, DVD)))
(((Paketquelle, extern)))
(((Paketquelle, lokal)))
(((Paketquelle, Netzwerk)))
(((Paketquelle, Speicherkarte)))
(((Paketquelle, USB-Stick)))
Eine Paketquelle kann dabei aber auch ein externes Speichermedium wie
eine CD, DVD, Blu-ray, eine Speicherkarte oder ein USB-Stick sein, aber
auch ein lokales oder über das Netzwerk angebundenes Verzeichnis auf
einer Festplatte. Waren noch vor wenigen Jahren die erstgenannten,
festen Installationsmedien üblich, werden heute als Paketquelle aufgrund
der weitestgehend flächendeckenden Verfügbarkeit des Internets
stattdessen FTP- und HTTP-Server bevorzugt. Damit sind die von Ihnen
genutzten Paketquellen stets aktuell.

==== Benutzte Paketquellen ====

// Stichworte für den Index
(((Paketquelle, Konfigurationsdatei)))
(((Konfigurationsdatei,/etc/apt/sources.list)))
(((Konfigurationsdatei,/etc/apt/sources.list.d/)))
Welche Paketquellen Sie verwenden, legen Sie bei Debian in der
Datei `/etc/apt/sources.list` (oder alternativ in auf `*.list` endende
Dateien im Verzeichnis `/etc/apt/sources.list.d/`) fest. Diese Dateien
zählen damit zu den zentralen Komponenten des Debian-Paketsystems. An
diesen Einträgen orientieren sich die Werkzeuge zur Paketverwaltung,
wenn es um Änderungen im lokalen Paketbestand und entsprechende
Aktualisierungen der Pakete auf Ihrem System geht.

// Stichworte für den Index
(((Paketquelle,Auswahl)))
(((Paketquelle,Ausfallsicherung)))
(((Paketquelle,mischen)))
(((Paketquelle,primäre)))
Bei der Auswahl der Paketquellen sind Sie nicht auf lediglich eine
dieser o.g. Ressourcen beschränkt. Sie können diese beliebig mischen und
somit auch Konzepte zur Ausfallsicherung umsetzen. Diese Konstellation
kommt genau dann zum Tragen, wenn Ihre primäre Paketquelle nicht in der
gewohnten Art und Weise zur Verfügung steht, bspw. bei einem Ausfall des
Internetzugangs oder der Wartung des bevorzugten Paketspiegels.

==== Aufbau und Struktur einer Paketquelle ====

// Stichworte für den Index
(((Paketquelle,Aufbau)))
Jede Paketquelle folgt einer festgelegten Verzeichnisstruktur
<<Aoki-Debian-Referenz>>, auf die sich die einzelnen Programme zur
Paketverwaltung stützen. Interessant wird diese Struktur genau dann,
wenn Sie eine Paketquelle mit selbsterstellten Paketen oder einen
eigenen Paketmirror aufsetzen und betreiben möchten (siehe
<<eigenen-apt-mirror-aufsetzen>>).

// Datei (Ende): ./werkzeuge/paketquellen-und-werkzeuge/paketquellen.adoc
