// Datei: ./praxis/veroeffentlichungen-mischen/pinning-default.adoc

// Baustelle: Rohtext

[[pinning-default]]
=== Die bevorzugte Veröffentlichung für alle Pakete festlegen ===

// Stichworte für den Index
(((APT-Konfiguration, APT::Default-Release)))
(((APT-Konfiguration, /etc/apt/apt.conf)))
(((APT-Pinning, Target Release)))
Hilfreich ist die Festlegung einer bevorzugten Veröffentlichung -- einer
sogenannten 'target release'. Daran orientiert sich APT und benutzt nur
Pakete dieser Veröffentlichung -- egal, was sonst noch an anderen
Paketversionen existiert.

APT entnimmt die Veröffentlichung der Datei `/etc/apt/apt.conf`.
Sofern diese Datei noch nicht vorhanden ist, legen Sie sie an. In die
Datei tragen Sie die gewünschte Veröffentlichung ein, bspw. Debian
'stable' wie folgt:

.Debian 'stable' als bevorzugte Veröffentlichung festlegen
----
APT::Default-Release "stable";
----

// TODO: Überschreibt Pinning, deswegen mit Vorsicht zu genießen!

// Datei (Ende): ./praxis/veroeffentlichungen-mischen/pinning-default.adoc
