// Datei: ./praxis/veroeffentlichungen-mischen/pinning-apt-get.adoc

// Baustelle: Rohtext

[[pinning-apt-get]]
=== `apt-get` mit expliziter Angabe der Veröffentlichung ===

APT richtet sich nach den festen Einstellungen in den
Konfigurationsdateien. Mit dem Schalter `-t` (Langform
`--target-release` oder `--default-release`) übergehen Sie diese
Festlegung und legen explizit fest, aus welcher Veröffentlichung Sie das
Paket beziehen möchten. Alternativ geben Sie die Veröffentlichung ohne
den Schalter und direkt nach dem Paketnamen an.

Für das Paket 'gdm3' und die Veröffentlichung Debian 'testing' sind die
folgenden beiden Aufrufe zulässig:

.Aufrufe mit expliziter Angabe der Veröffentlichung
----
apt-get -t testing install gdm3
apt-get install gdm3/testing
----

Um dieses Paket einzuspielen, erzeugt APT eine Vorgabe-Pin mit der
Priorität 990 (siehe dazu <<tab.apt-pinning-prioritaeten>>). Daher wird
das Paket installiert, es sei denn, es gibt bereits eine Version, die
zur festgelegten Zielveröffentlichung gehört oder die bereits vorhandene
Version des Pakets ist neuer als das benannte Paket.


// Datei (Ende): ./praxis/veroeffentlichungen-mischen/pinning-apt-get.adoc
