// Datei: ./praxis/veroeffentlichungen-mischen/von-apt-zu-apt-pinning.adoc

// Baustelle: Rohtext

[[von-apt-zu-apt-pinning]]
=== Von APT zu APT-Pinning ===

// Stichworte für den Index
(((Paketverwaltung, Festlegung der Prioritäten für Pakete)))
(((Paketverwaltung, Pins)))

Bisher wurden im Buch alle Pakete gleichwertig behandelt. In der Praxis 
läßt sich das änderen, indem die Pakete nun zusätzlich unterschiedliche 
Prioritäten bekommen. Die Paketverwaltung mit APT überprüft hierzu 
verschiedene ``Schlüsselstellen'' und klärt zunächst, was Sie für das 
jeweilige Paket eingestellt haben. Danach wählt APT für die Installation 
die Version mit der höchsten ``Vorrangstufe'' aus. Liegt keine explizite 
Angabe vor, kommen die Standardeinstellungen zum Tragen (siehe auch
<<aus-welchem-repo-kommen-die-pakete>>).

Die Steuerung der Vorrangstufe erfolgt über einzelne Zahlenwerte, genannt
'Pins'. Anhand dieser wird ausgewählt, aus welchen Paketquellen die Pakete 
bezogen werden. Das ganze kann beliebig verkompliziert werden, da APT über 
den Zahlenwert entscheidet, was es installiert, nicht installiert oder 
aktualisiert (siehe dazu <<tab.apt-pinning-prioritaeten>>).

.Verwendete Prioritäten beim APT-Pinning
[frame="topbot",options="header",cols="2,3",id="tab.apt-pinning-prioritaeten"]
|====
| Priorität	| Bedeutung
| unter 0	| Das Paket wird niemals installiert.
| ab 0 bis einschließlich 99	| Das Paket wird nur dann installiert, wenn noch
keine Version davon auf dem System installiert ist.
| ab 100 bis einschließlich 499	| Das Paket wird installiert, es sei denn, es gibt eine
Version, die zu einer anderen Veröffentlichung gehört, oder die
bereits vorhandene Version ist neuer.
| ab 500 bis einschließlich 989	| Das Paket wird installiert, es sei denn, es gibt eine
Version, die zur festgelegten Zielveröffentlichung gehört, oder die
bereits vorhandene Version ist neuer.
| ab 991 bis einschließlich 999	| Das Paket wird immer installiert, es sei denn,
die bereits vorhandene Version ist neuer.
| größer als 999	| Das Paket wird immer installiert, auch wenn das
ein Downgrade auf eine ältere Version bedeutet.
|====

// Datei (Ende): ./praxis/veroeffentlichungen-mischen/von-apt-zu-apt-pinning.adoc
