// Datei: ./anhang/anhang.paketkommando/rpm-yum-dpkg.adoc
// Baustelle: Rohtext

[[kommandos-zur-paketverwaltung-im-vergleich]]
== Kommandos zur Paketverwaltung im Vergleich ==

=== Zusammenfassung ===

// Stichworte für den Index
(((APT)))
(((Aptitude)))
(((dpkg)))
(((DNF)))
(((FPM)))
(((RPM)))
(((Yellowdog Updater Modified (YUM))))
Hier stellen wir die jeweiligen Kommandos zur Paketverwaltung gegenüber,
wie sie von RPM, Yellowdog Updater Modified (YUM), seinen Nachfolgern
Effing Package Management (FPM) und Dandified YUM (DNF), Debian's
`dpkg`, APT sowie `aptitude` verwendet werden. Wir betrachten dabei
bspw. die Installation und die Entfernung von Paketen, das Auflisten der
installierten und verfügbaren Pakete sowie das Anzeigen von
Paketabhängigkeiten.

Diese Zusammenstellung basiert auf umfangreichen Tests und Recherchen,
bspw. mit Fedora 23, CentOS 6 und 7 sowie Ubuntu 15.10 und Debian 8. Die
Verfügbarkeit der Werkzeuge und deren einzelne Schalter variiert recht
stark <<RPM-Salve>> <<RPM-Gite>> <<RPM-Canepa>> <<YUM-Salve>>
<<dpkg-Kumar>> <<apt-Salve>>.

=== Paket installieren ===

// Stichworte für den Index
(((apt-get, install)))
(((apt-get, --no-download install)))
(((aptitude, install)))
(((Paket, installieren)))
(((rpm, -i)))
(((rpm, -ihv)))
(((yum, install)))
(((yum, localinstall)))
Mit den nachfolgenden Aufrufen installieren Sie ein Softwarepaket über
die Kommandozeile. Unter ``Pakete installieren'' in
<<pakete-installieren>> gehen wir detaillierter auf `dpkg`, APT und
`aptitude` ein. Unter ``Installation zwischengespeicherter Pakete aus
dem Paketcache'' in
<<installation-zwischengespeicherter-pakete-aus-dem-paketcache>>
erfahren Sie mehr darüber, wie Sie Pakete installieren, die bereits im
Paketcache vorliegen.

.Installation eines Pakets
[frame="topbot",options="header",cols="2,4,4",id="tab.paketinstallation"]
|====
| Werkzeug   | Aufruf | Anmerkungen
| `RPM`      | `rpm -i` 'Paketname' | Paket liegt lokal vor
|            | `rpm -ihv` 'Paketname' | Paket liegt lokal vor, Installation mit Kommentaren
| `YUM`      | `yum localinstall` 'Paketname' | Paket liegt lokal vor
|            | `yum install` 'Paketname' | Paket wird dem Paketrepository entnommen
| `dpkg`     | `dpkg -i` 'Paketname' | Paket liegt lokal vor
| APT        | `apt-get install` 'Paketname' | Paket wird dem Paketrepository entnommen
|            | `apt-get --no-download install` 'Paketname' | Paket wird dem Paketcache entnommen und nicht vom Paketmirror bezogen
| `aptitude` | `aptitude install` 'Paketname' | Paket wird dem Paketrepository entnommen
|====

=== Paket löschen / entfernen ===

// Stichworte für den Index
(((apt-get, --purge remove)))
(((apt-get, remove)))
(((aptitude, remove)))
(((dpkg, -r)))
(((Paket, deinstallieren)))
(((Paket, entfernen)))
(((Paket, Konfigurationsdateien löschen)))
(((Paket, löschen)))
(((rpm, -e)))
(((yum, erase)))
(((yum, remove)))
Mit den nachfolgenden Aufrufen entfernen Sie ein Softwarepaket über
die Kommandozeile. Unter ``Pakete deinstallieren'' in
<<pakete-deinstallieren>> gehen wir detaillierter auf `dpkg`, APT und
`aptitude` ein.

.Entfernen eines Pakets
[frame="topbot",options="header",cols="2,4,4",id="tab.paketentfernung"]
|====
| Werkzeug   | Aufruf | Anmerkungen
| `RPM`      | `rpm -e` 'Paketname' | 
| `YUM`      | `yum remove` 'Paketname' | 
|            | `yum erase` 'Paketname' | gleichbedeutend zu `remove`
| `dpkg`     | `dpkg -r` 'Paketname' | 
|  APT       | `apt-get remove` 'Paketname' | Entfernen ohne Konfigurationsdateien des Pakets
|            | `apt-get --purge remove` 'Paketname' | Entfernen inklusive der Konfigurationsdateien des Pakets
| `aptitude` | `aptitude remove` 'Paketname' | 
|====

=== Alle Pakete auflisten ===

// Stichworte für den Index
(((apt-cache, search)))
(((aptitude, search)))
(((dpkg, -l)))
(((Paket, installiertes anzeigen)))
(((Paket, Status anzeigen)))
(((Paket, Zustand anzeigen)))
(((Paketstatus)))
(((Paketzustand)))
(((rpm, -qa)))
(((yum, list all)))
(((yum, list available)))
Mit den nachfolgenden Aufrufen listen Sie die vorhandenen Softwarepakete
über die Kommandozeile auf. Für `dpkg`, APT und `aptitude` besprechen
wir das detaillierter unter ``Liste der installierten Pakete anzeigen
und deuten'' in <<liste-der-installierten-pakete-anzeigen-und-deuten>>
sowie unter ``Aktualisierbare Pakete anzeigen'' in
<<aktualisierbare-pakete-anzeigen>>.

.Softwarepakete auflisten
[frame="topbot",options="header",cols="2,4,4",id="tab.paketeauflisten"]
|====
| Werkzeug   | Aufruf | Anmerkungen
| `RPM`      | `rpm -qa` | alle installierten Pakete auflisten
| `YUM`      | `yum list all` | alle installierten Pakete auflisten
|            | `yum list available` | alle verfügbaren Pakete auflisten,
auch die (noch) nicht installierten Pakete
| `dpkg`     | `dpkg -l` | alle installierten Pakete auflisten
|  APT       | `apt-cache search` 'Paketname' |
| `aptitude` | `aptitude search ~i`| alle installierten Pakete auflisten
| `aptitude` | `aptitude versions` 'Paketname'| alle verfügbaren Pakete
für 'Paketname' auflisten, auch die (noch) nicht installierten Varianten
|====

=== Einzelpaket auflisten ===

// Stichworte für den Index
(((aptitude, show)))
(((dpkg, -l)))
(((dpkg, -s)))
(((Paket, Status anzeigen)))
(((Paket, Zustand anzeigen)))
(((Paketstatus)))
(((Paketzustand)))
(((rpm, -q)))
(((rpm, -qa)))
(((rpm, -qp)))
Mit den nachfolgenden Aufrufen listen Sie die Informationen bzw. den
Installationsstatus zu einem einzelnen Softwarepaket auf. Unter ``Liste
der installierten Pakete anzeigen und deuten'' in
<<liste-der-installierten-pakete-anzeigen-und-deuten>> besprechen wir
das zu `dpkg` und `aptitude` genauer.

.Einzelnes Softwarepaket auflisten
[frame="topbot",options="header",cols="2,4,4",id="tab.paketinfo"]
|====
| Werkzeug   | Aufruf | Anmerkungen
| `RPM`      | `rpm -q` 'Paketname' | Ausgabe des Installationsstatus für 'Paketname'
|            | `rpm -qp` 'Paketname' | ?
| `dpkg`     | `dpkg -l` 'Paketname' | Ausgabe des Installationsstatus
|            | `dpkg -s` 'Paketname' | Ausgabe der Paketinformationen
| `aptitude` | `aptitude show` 'Paketname'|
|====

=== Abhängigkeiten anzeigen ===

// Stichworte für den Index
(((apt-cache, depends)))
(((apt-cache, rdepends)))
(((Paket, Abhängigkeiten anzeigen)))
(((Paket, Rückwärtsabhängigkeiten auflisten)))
(((Paketabhängigkeiten, auflisten)))
(((Paketabhängigkeiten, Rückwärtsabhängigkeiten auflisten)))
(((rpm, -R)))
(((yum, deplist)))
(((yum, info)))
Mit den nachfolgenden Aufrufen zeigen Sie die Abhängigkeiten zu anderen
Paketen an. Für `dpkg` und APT gehen wir dazu genauer in
``Paketabhängigkeiten anzeigen'' in <<paketabhaengigkeiten-anzeigen>>
ein.

.Paketabhängigkeiten anzeigen
[frame="topbot",options="header",cols="2,4,4",id="tab.paketabhaengigkeiten"]
|====
| Werkzeug   | Aufruf | Anmerkungen
| `RPM`      | `rpm -R` 'Paketname' |
| `YUM`      | `yum deplist` 'Paketname' |
|            | `yum info` 'Paketname' |
| APT        | `apt-cache depends` 'Paketname' |
|            | `apt-cache rdepends` 'Paketname' | umgekehrte Abhängigkeiten anzeigen
|====

=== Paketsignatur überprüfen ===

// Stichworte für den Index
(((Paket, auf Veränderungen prüfen)))
(((Paket, auf Vertrauenswürdigkeit prüfen)))
(((Paket, Signatur überprüfen)))
(((Paket, verifizieren)))
(((Paketsignatur, überprüfen)))
(((rpm, -K)))
Mit den nachfolgenden Aufrufen überprüfen Sie die Signatur eines Pakets.
Sie stellen damit sicher, dass das Paket unverändert vom Paketmirror zu
Ihnen übertragen wurde und auf dem Transportweg keine inhaltlichen
Veränderungen stattgefunden haben. Für Debianpakete widmen wir uns dem
Thema in ``Paket verifizieren'' in <<bezogenes-paket-verifizieren>> und
``Paket auf Veränderungen prüfen'' in
<<paket-auf-veraenderungen-pruefen>>.

.Paketsignatur überprüfen
[frame="topbot",options="header",cols="2,4,4",id="tab.paketsignatur"]
|====
| Werkzeug   | Aufruf | Anmerkungen
| `RPM`      | `rpm -K` 'Paketname' |
| `YUM`      | |
| APT        | |
|====

// Datei (Ende): ./anhang/anhang.paketkommando/rpm-yum-dpkg.adoc
