// Datei: ./praxis/fehlende-pakete-bei-bedarf-hinzufuegen/fehlende-pakete-bei-bedarf-hinzufuegen.adoc

// Baustelle: Rohtext

[[fehlende-pakete-bei-bedarf-hinzufuegen]]
== Fehlende Pakete bei Bedarf hinzufügen ==

// Schlagworte für den Index
(((Softwarepakete, bei Bedarf hinzfügen)))
Bisher haben wir reguläre Debian-Installationen betrachtet. Hierbei 
ist der Bestand installierter Software statisch in dem Sinne, dass 
nur Sie als Systemadministrator entscheiden, wenn Pakete erneuert,
hinzugefügt oder entfernt werden. Ist ein Paket nicht installiert,
können Programme daraus nicht benutzt werden und ihre Shell macht 
Sie darauf mit einem passenden Hinweis aufmerksam.

Ändert sich der Bedarf, bspw. indem neue Hardware hinzukommt, wäre es
cool, wenn das Debian-System diesen Bedarf erkennen würde und 
zumindest passend darauf reagieren könnte. Gleiches gilt für Software, 
deren Fehlen im laufenden Betrieb bemerkt wird, bspw. indem ihnen das 
entsprechende Paket vorgeschlagen wird, in welchem sich die Software 
befindet. Womit beide Szenarien umsetzbar sind, lesen Sie nachfolgend.

// - bei neuer Hardware
include::neue-hardware.adoc[]

// - bei fehlender Software
include::neue-software.adoc[]

// Datei (Ende): ./praxis/fehlende-pakete-bei-bedarf-hinzufuegen/fehlende-pakete-bei-bedarf-hinzufuegen.adoc
