// Datei: ./praxis/fehlende-pakete-bei-bedarf-hinzufuegen/neue-software.adoc

// Baustelle: Notizen

[[neue-software]]

=== Neue Software ===

==== Ausgangssituation ====

Das Setup auf ihrem Linux-System umfasst stets nur eine Auswahl an 
Paketen. Wie Sie wissen, installieren Sie fehlende Pakete bei Bedarf
einfach über die Werkzeuge zur Paketverwaltung nach.

Geht es hingegen um unbekannte oder fehlende Werkzeuge, ist nicht 
immer sofort klar, über welches Debianpaket diese bereitgestellt 
werden. Wie Sie eine manuelle Suche anstoßen, erklären wir Ihnen 
ausführlich unter 'Paket zu Datei finden' in <<paket-zu-datei-finden>>.

Diesen Schritt zu automatisieren, kann den Prozess der Verwaltung von
Software vereinfachen und Zeit sparen. Wir klären nachstehend, wie Sie 
fehlende Pakete identifizieren und diese einspielen lassen.

==== Empfehlungen mittels `command-not-found` ====

// Stichworte für den Index
(((Debianpaket, command-not-found)))
(((Hinweis zu fehlender Software)))

* Wer nicht gleich das Paket installiert haben will, sondern nur beim
  Aufruf auf der Kommandozeile den Hinweis bekommen, welches Paket 
  noch zusätzlich installiert werden müsste, für den ist das Paket
  'command-not-found' <<Debian-Paket-command-not-found>> das richtige.

* was macht das genau?
** sucht nach aktuell nicht installierten, aber in den Repositories verfügbaren Programmen
** benutzt dafür eine eigene Datenbank 
** funktioniert automatisch für die Bash und die Zsh 
** benutzt die Funktion `command_not_found_handle`

* was braucht das?
** `apt-file`, Python 3
** Aktualisierung der internen Werkzeugdatenbank nach der Installation, hier am Beispiel der Suche nach `yum`:

.Erster Aufruf nach der Installation des Paketes 'command-not-found'
----
$ yum
command-not-found Datenbank konnte nicht gefunden werden. Führen Sie »sudo apt update« aus, um sie zu füllen.
yum: Befehl nicht gefunden.
$
----

** nach der Aktualisierung der Paketliste mittels `apt update`

.Ausgabe von 'command-not-found' nach der Aktualisierung
----
$ yum
Der Befehl 'yum' wurde nicht gefunden, meinten Sie:
  Befehl 'uum' aus dem deb freewnn-jserver
  Befehl 'num' aus dem deb quickcal
  Befehl 'zum' aus dem deb perforate
  Befehl 'sum' aus dem deb coreutils
Versuche: apt install <deb name>
$
----

* Nachteile
** es entsteht eine kurze Verzögerung, nachdem Sie einen unbekannten 
   Befehl eingegeben haben. Dies beruht darauf, dass das Durchsuchen 
   der Datenbank von `command-not-found` einen kurzen Moment benötigt. 
   Gerade bei langsameren Systemen erfolgt dadurch eine spürbare 
   Verzögerung. 

==== Fehlendes sofort installieren ====

// Stichworte für den Index
(((Automatische Installation fehlender Software)))
(((Debianpaket, packagekit-command-not-found)))

* Installation bei Benennung: 'packagekit-command-not-found' <<Debian-Paket-packagekit-command-not-found>>

// Datei (Ende): ./praxis/fehlende-pakete-bei-bedarf-hinzufuegen/neue-software.adoc
