// Datei: ./praxis/fehlende-pakete-bei-bedarf-hinzufuegen/neue-hardware.adoc

// Baustelle: Notizen

[[neue-hardware]]

=== Neue Hardware ===

// Stichworte für den Index
(((Debianpaket, isenkram)))
(((Debianpaket, isenkram-cli)))
(((isenkram, Integration in tasksel)))
(((isenkram-autoinstall-firmware)))
(((isenkram-lookup)))
(((isenkram-pkginstall)))

Die Auswahl der installierten Pakete auf Ihrem System orientiert sich 
an den Hardwarekomponenten, die im System verbaut wurden und in 
Benutzung sind. Ändert sich daran etwas -- bspw. Hardware wird 
ausgetauscht oder hinzugefügt -- werden mitunter auch andere 
Kernelmodule zur Unterstützung dieser neuen Komponenten benötigt. 

Etwas mühselig ist es, durch eigene Experimente Gewissheit zu 
bekommen, welche Pakete aufgrund des Komponentenwechsels entfernt und 
ergänzt werden müssen. In diesem Fall kommen die beiden Pakete 
'isenkram' <<Debian-Paket-isenkram>> und 'isenkram-cli'
<<Debian-Paket-isenkram-cli>> des norwegischen Entwicklers Petter
Reinholdtsen ins Spiel. Dieses hat zwar bereits den Status 'stable',
steht aber unter sehr aktiver Entwicklung.
// <<Isenkram-Reinholdtsen>>. 

Hinter Isenkram verbirgt sich eine Art Benachrichtigungsdienst, der
überprüft, ob die benötigten Pakete für die neue Hardware bereits auf
ihrem System installiert sind. Falls nicht, wird dieses (automatisch)
nachgezogen. Dazu klinkt es sich als zusätzliches Modul in die
Konfiguration von 'tasksel' ein (siehe <<tasksel>>).

ToDo:

* wie funktioniert das
** wie klinkt es sich in 'tasksel' ein
* was macht das alles
* wie benutzt man das

Das Werkzeug `isenkram-lookup` aus dem Paket 'isenkram-cli' 
<<Debian-Paket-isenkram-cli>> gleicht die Hardware ihres Systems mit 
den Einträgen in den Paketlisten ab und sucht daraus die Pakete 
heraus, die für ihre Maschine relevant sind. Ein Durchlauf auf einem
Lenovo ThinkPad unter Debian 12.6 'Bookworm' brachte nachfolgende 
Liste hervor.

* Umgang mit dem Ergebnis:
** wie kommt die Auswahl der Pakete zustande?
** wie ist diese Liste zu lesen?

.Module mit `isenkram-lookup` finden
----
$ isenkram-lookup
bluez
cheese
ethtool
gkrellm-thinkbat
hdapsd
media-player-info
pidgin-blinklight
thinkfan
tlp
tp-smapi-dkms
tpb
$
----

** Werkzeug `isenkram-autoinstall-firmware`
*** aus der Manpage: "user desktop background process to handle new hardware dongles"
*** zuerst mit `isenkram-lookup` passende Kernelmodule/Software identifizieren
*** danach mit `isenkram-autoinstall-firmware` diese Module nachinstallieren
** Werkzeug `isenkram-pkginstall`
*** aus der Manpage: "locate and install hardware specific packages suitable for the current machine"

* unter Linux laufende ... 
** Hardware herausfinden: http://linux-hardware.org/
** Drucker identifizieren: https://openprinting.github.io/

// Datei (Ende): ./praxis/fehlende-pakete-bei-bedarf-hinzufuegen/neue-hardware.adoc
