// Datei: ./praxis/fehlende-pakete-bei-bedarf-hinzufuegen/neue-hardware.adoc

// Baustelle: Notizen

[[neue-hardware]]

=== Neue Hardware ===

// Stichworte für den Index
(((Debianpaket, isenkram)))
(((Debianpaket, isenkram-cli)))
(((isenkram, Integration in tasksel)))

Die Auswahl der installierten Pakete auf Ihrem System orientiert sich an
den Hardwarekomponenten, die im System verbaut wurden und in Benutzung
sind. Ändert sich daran etwas -- bspw. Hardware wird ausgetauscht oder
hinzugefügt -- werden mitunter auch andere Module zur Unterstützung 
dieser neuen Komponenten benötigt. 

Etwas mühselig ist es, durch eigene Experimente Gewissheit zu bekommen,
welche Pakete aufgrund des Komponentenwechsels entfernt und ergänzt
werden müssen. In diesem Fall kommen die beiden Pakete 'isenkram'
<<Debian-Paket-isenkram>> und 'isenkram-cli'
<<Debian-Paket-isenkram-cli>> des norwegischen Entwicklers Petter
Reinholdtsen ins Spiel. Dieses hat zwar bereits den Status 'stable',
steht aber unter sehr aktiver Entwicklung.
// <<Isenkram-Reinholdtsen>>. 

Hinter Isenkram verbirgt sich eine Art Benachrichtigungsdienst, der
überprüft, ob die benötigten Pakete für die neue Hardware bereits auf
ihrem System installiert sind. Falls nicht, wird dieses (automatisch)
nachgezogen. Dazu klinkt es sich als zusätzliches Modul in die
Konfiguration von 'tasksel' ein (siehe <<tasksel>>).

ToDo:

* wie funktioniert das
** wie klinkt es sich in 'tasksel' ein
* was macht das alles
* wie benutzt man das
** Benutzerschnittstelle: Paket 'isenkram-cli' <<Debian-Paket-isenkram-cli>>

// Datei (Ende): ./praxis/fehlende-pakete-bei-bedarf-hinzufuegen/neue-hardware.adoc
