// Datei: ./praxis/fehlende-pakete-bei-bedarf-hinzufuegen/neue-hardware.adoc

// Baustelle: Notizen

[[neue-hardware]]

=== Neue Hardware ===

// Stichworte für den Index
(((Debianpaket, isenkram)))
(((Debianpaket, isenkram-cli)))
(((isenkram, Integration in tasksel)))
(((isenkram-autoinstall-firmware)))
(((isenkram-lookup)))
(((isenkram-pkginstall)))

Die Auswahl der installierten Pakete auf Ihrem System orientiert sich 
an den Hardwarekomponenten, die im System verbaut wurden und in 
Benutzung sind. Ändert sich daran etwas -- bspw. Hardware wird 
ausgetauscht oder hinzugefügt -- werden mitunter auch andere 
Kernelmodule zur Unterstützung dieser neuen Komponenten benötigt. 

Etwas mühselig ist es, durch eigene Experimente Gewissheit zu 
bekommen, welche Pakete aufgrund des Komponentenwechsels entfernt und 
ergänzt werden müssen. In diesem Fall kommen die beiden Pakete 
'isenkram' <<Debian-Paket-isenkram>> und 'isenkram-cli'
<<Debian-Paket-isenkram-cli>> des norwegischen Entwicklers Petter
Reinholdtsen ins Spiel. Dieses hat zwar bereits den Status 'stable',
steht aber unter sehr aktiver Entwicklung.
// <<Isenkram-Reinholdtsen>>. 

Hinter Isenkram -- dänisch und norwegisch für Eisenwaren ('Hardware') 
-- verbirgt sich eine Art Benachrichtigungsdienst, der überprüft, ob 
die benötigten Pakete für die neue Hardware bereits auf ihrem System 
installiert sind. Falls nicht, wird dieses (automatisch) nachgezogen. 
Dazu klinkt es sich als zusätzliches Modul in die Konfiguration von 
'tasksel' ein (siehe <<tasksel>>).

ToDo:

* wie funktioniert das
** wie klinkt es sich in 'tasksel' ein
* was macht das alles
* wie benutzt man das

==== Passende Pakete mit `isenkram-lookup` finden ====

Das Werkzeug `isenkram-lookup` aus dem Paket 'isenkram-cli' 
<<Debian-Paket-isenkram-cli>> gleicht die Hardware ihres Systems mit 
den Einträgen in den Paketlisten ab und sucht daraus die Pakete 
heraus, die für ihre Maschine relevant sind. Ein Durchlauf auf einem
Lenovo ThinkPad unter Debian 12.6 'Bookworm' brachte nachfolgende 
Liste hervor, die bspw. Pakete wie 'tpb' <<Debian-Paket-tbp>>, 
'thinkfan' <<Debian-Paket-thinkfan>> und 'gkrellm-thinkbat' 
<<Debian-Paket-gkrellm-thinkbat>> zur Steuerung ThinkPad-spezifischer
Komponenten beinhaltet.

.Module mit `isenkram-lookup` finden
----
$ isenkram-lookup
bluez
cheese
ethtool
gkrellm-thinkbat
hdapsd
media-player-info
pidgin-blinklight
thinkfan
tlp
tp-smapi-dkms
tpb
$
----

* Umgang mit dem Ergebnis:
** wie kommt die Auswahl der Pakete zustande?
*** `isenkram-lookup` liest zuerst alle Werte von `modalias` aus dem 
Verzeichnis `/proc` und versucht danach, passende Pakete zu diesen 
`modalias`-Werten zu finden <<modalias>>
** wie ist diese Liste zu lesen?
*** ist alphabetisch anhand der Pakete sortiert
*** keine Angabe, was das jeweilige Paket macht

==== Hardware-spezifische Pakete mit `isenkram-pkginstall` lokalisieren ====

* Werkzeug `isenkram-pkginstall`
** aus der Manpage: "locate and install hardware specific packages suitable for the current machine"

==== Fehlende Firmware mit `isenkram-autoinstall-firmware` nachziehen ====

Mit dem Werkzeug `isenkram-autoinstall-firmware` gleichen Sie den 
laufenden Linuxkernel mit der Hardware ihres Systems ab und 
installieren fehlende Pakete für die Komponenten nach. Im folgenden 
Beispiel ist es das Paket 'firmware-misc-nonfree' 
<<Debian-Paket-firmware-misc-nonfree>> und daraus das Modul 
'firmware-realtek-rtl8723cs-bt' für den Realtek-Chipsatz.

.Nachinstallation von Paketen nach Ausführung von `isenkram-autoinstall-firmware`
----
# isenkram-autoinstall-firmware 
info: looking for firmware file iwl-debug-yoyo.bin requested by kernel
info: looking for firmware file iwl-debug-yoyo.bin requested by kernel
...
info: locating packages with the requested firmware files
info: determining whether enabling other components is required
info: trying to install firmware-misc-nonfree
firmware-realtek-rtl8723cs-bt
Vormals nicht ausgewähltes Paket firmware-misc-nonfree wird gewählt.
(Lese Datenbank ... 419694 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../firmware-misc-nonfree_20230210-5_all.deb ...
Entpacken von firmware-misc-nonfree (20230210-5) ...
Vormals nicht ausgewähltes Paket firmware-realtek-rtl8723cs-bt wird gewählt.
Vorbereitung zum Entpacken von .../firmware-realtek-rtl8723cs-bt_20181104-2_all.deb ...
Entpacken von firmware-realtek-rtl8723cs-bt (20181104-2) ...
firmware-misc-nonfree (20230210-5) wird eingerichtet ...
firmware-realtek-rtl8723cs-bt (20181104-2) wird eingerichtet ...
Trigger für initramfs-tools (0.142) werden verarbeitet ...
update-initramfs: Generating /boot/initrd.img-6.1.0-23-amd64
#
----

==== Passende Hardware identifizieren ====

Nicht immer ist es einfach, herauszufinden, ob eine gewünschte 
Hardware auf einem Linux-System unterstützt wird. Die folgenden 
beiden Projekte helfen Ihnen bei der Vorauswahl:

* passende Hardware herausfinden: Linux-Hardware <<LinuxHardware>>
* passende Drucker identifizieren: OpenPrinting <<Openprinting>>

// Datei (Ende): ./praxis/fehlende-pakete-bei-bedarf-hinzufuegen/neue-hardware.adoc
