// Datei: ./praxis/apt-und-aptitude-mischen/was-ist-zu-beachten-wenn-sie-das-machen.adoc

// Baustelle: Fertig

=== Was ist zu beachten, wenn Sie das machen ===

Unkritisch sind in jedem Fall alle Paketoperationen, bei denen Sie nur
'lesend' auf den Paketbestand zugreifen, d.h. es in diesem nicht zu
einer Veränderung kommt. Dazu zählen z.B. das Erfragen des Paketstatus
(siehe <<paketstatus-erfragen>>), die Liste der installierten Pakete
anzeigen und deuten (siehe
<<liste-der-installierten-pakete-anzeigen-und-deuten>>), die neuen
Pakete anzeigen (siehe <<neue-pakete-anzeigen>>), die Pakete nach
Prioritäten finden (siehe <<pakete-nach-prioritaeten-finden>>), die
Installationsgröße eines Paketes bestimmen (siehe
<<installationsgroesse-eines-paketes>>), die Paketabhängigkeiten
anzeigen (siehe <<paketabhaengigkeiten-anzeigen>>), die Herkunft der
Pakete klären (siehe <<aus-welchem-repo-kommen-die-pakete>>) und über
den Paketinhalt suchen (siehe dazu <<paket-zu-datei-finden>> und
<<paketinhalte-anzeigen-apt-file>>).

Definitiv als bedenklich schätzen wir ein, wenn Sie APT und `aptitude`
im fliegenden Wechsel für alle Paketoperationen benutzen, bei denen der
Paketbestand 'verändert wird' oder entsprechende Vormerkungen dazu
getroffen werden. Weiterhin treten Seiteneffekte auf, wenn mehrere
Programme zur Paketverwaltung gleichzeitig geöffnet sind, bspw.
`aptitude`, Synaptic und SmartPM. Jedes der genannten Werkzeuge
versucht, für die einzelnen Aktionen die Paketdatenbank exklusiv nutzen.
Funken an dieser Stelle andere Programme dazwischen, entstehen Konflikte
mit unvorhersagbarem Ergebnis.

Um Letzteres zu verhindern, raten wir Ihnen zur konsequenten Benutzung
des gleichen Werkzeugs. Zu den Operationen zählen z.B. das Beziehen und
Installieren eines Pakets (siehe <<paketdatei-nur-herunterladen>>,
<<installation-zwischengespeicherter-pakete-aus-dem-paketcache>> und
<<pakete-installieren>>) sowie das Ändern der Paketversion (siehe
<<pakete-aktualisieren>> und <<pakete-downgraden>>) und Deinstallieren
bestehender Pakete (siehe <<pakete-deinstallieren>> und
<<umgang-mit-waisen>>).

Im Alltag hat sich besipielsweise bewährt, dass Sie zunächst über die
Textoberfläche von `aptitude` oder die Debian-Webseite nach dem
passenden Paket suchen. In Folge installieren Sie die konkreten,
gewünschten Pakete via `apt-get` oder `apt` nach. Damit kombinieren Sie
eine graphische bzw. textbasierte Oberfläche mit der unmißverständlichen
Direktheit einer Kommandozeile.

// Datei (Ende): ./praxis/apt-und-aptitude-mischen/was-ist-zu-beachten-wenn-sie-das-machen.adoc
