// Datei: ./praxis/apt-cache/approx.adoc

// Baustelle: Notizen

[[approx]]

=== Approx ===

==== Überblick ====

// Stichworte für den Index
(((APT-Cache)))
(((Debianpaket, approx)))
(((Paketcache)))
(((Paketproxy, approx)))

Approx <<Debian-Paket-approx>> ist ein Proxyserver für Debianpakete und
dient als Paketcache zwischen einem Paketmirror und Debian-basierten
Clients. Mit Approx halten Sie Debianpakete vor, die von den Clients zur
lokalen Installation oder Aktualisierung angefragt werden und liefern
diese aus dem Paketcache an die Clients aus.

Gemäß der Selbstbeschreibung von Approx sind lediglich die Repositorys
in den Konfigurationsdateien von Approx anzupassen, jedoch nicht die
Konfigurationsdateien jedes Clients selbst (bspw.
`/etc/apt/sources.list`). In der Realität sieht es jedoch etwas anders 
aus und es sind ebenfalls Änderungen in den Clients notwendig, damit 
diese mit dem Paketproxy kommunizieren (siehe 
<<approx-Konfiguration-Client>>).

Approx präsentiert sich als Alternative zu APT Cacher (siehe
<<apt-cacher>>) und APT Cacher-NG (siehe <<apt-cacher-ng>>), dem
Nachfolger von APT Cacher.

[[approx-Setup]]
==== Setup und Installation ====

// Stichworte für den Index
(((Approx, Installation)))
Als *ersten Schritt* laden Sie das Paket 'approx' <<Debian-Paket-approx>>
herunter und installieren es, bspw. mittels `apt-get` wie folgt:

.Installation von Approx mit `apt-get`
----
apt-get install approx
----

Das Paket 'approx' ist rund 1.5 MB groß und belegt nach dem Entpacken
des Softwarearchivs etwa 6.6 MB Platz in ihrem System. Weitere Pakete
sind zur Installation nicht erforderlich. Die *Schritte 2 und 3*
beinhalten nun die Konfiguration des Approx-Serverdienstes (siehe
<<approx-Konfiguration-Server>> und der Clients (siehe
<<approx-Konfiguration-Client>>).

[[approx-Konfiguration]]
==== Konfiguration ====

[[approx-Konfiguration-Server]]
===== Server =====

// Stichworte für den Index
(((Approx, /etc/approx/approx.conf)))
(((Approx, Serverkonfiguration)))
Hierzu passen Sie die Datei `/etc/approx/approx.conf` auf ihre
eigenen Bedürfnisse an. Approx versteht dazu eine Reihe von Variablen in
Form von Paaren aus einem Namen und Wert, über die Sie die
Funktionalität des Service steuern. Nachfolgend listen wir diese
Variablen samt deren Bedeutung in alphabetischer Reihenfolge auf.

`$cache` :: legt den Pfad fest, den Approx für seinen eigenen Paketcache
verwendet. Der *Defaultwert* ist `/var/cache/approx`.

`$curl_path` :: legt den Pfad zum Programm `curl` fest. Der
*Defaultwert* ist `/usr/bin/curl`.

`$debug` :: legt fest, ob Logeinträge zur erweiterten Fehlersuche
erstellt werden sollen. Der *Defaultwert* ist `false` und somit
ausgeschaltet.

`$group` :: legt den Namen der Gruppe fest, dem die Dateien im
Cacheverzeichnis von Approx gehören. Der *Defaultwert* ist `approx`.

`$interval` :: gibt die Zeitdauer in Minuten an, nach der eine Datei im
Cache als zu alt angesehen wird, um noch sofort von Approx ausgeliefert
zu werden. Ist das Intervall überschritten, schaut Approx zuerst auf dem
Paketmirror nach, ob es zwischenzeitlich eine neuere Version gibt. Der
*Defaultwert* ist 60 für 60 Minuten.

`$max_rate` :: legt die Obergrenze für die Breite des Datenstroms in
Bytes pro Sekunde fest, mit der Daten vom Paketmirror bezogen werden.
Der *Defaultwert* ist `unlimited` für unbegrenzte Bandbreite. Geben Sie
stattdessen einen Zahlenwert an und ergänzen ihn mit `K`, `M` oder `G`,
begrenzen Sie die Bandbreite auf den entsprechenden Wert in Kilobyte,
Megabyte oder Gigabyte pro Sekunde.

`$max_redirects` :: legt die maximale Anzahl von HTTP-Weiterleitungen
('HTTP redirects') fest, denen gefolgt wird, wenn ein Paket
heruntergeladen wird. Der *Defaultwert* ist 5.

`$max_wait` :: gibt an, wieviele Sekunden der Prozess von Approx im
Falle eines konkurrierenden Downloads wartet, bevor es die Datei selbst
bezieht. Der *Defaultwert* ist 10 für 10 Sekunden.

`$offline` :: gibt an, ob Approx auch möglicherweise veraltete Dateien
ausliefern soll, wenn keine Verbindung zum Paketmirror zustandekommt.
Der *Defaultwert* ist `false` und diese Funktionalität ist somit
ausgeschaltet.

`$pdiffs` :: legt fest, ob IndexFile Diffs genutzt werden sollen. Der
*Defaultwert* steht auf `true` für 'eingeschaltet'.

`$syslog` :: legt das Verhalten von 'syslog' fest, wenn mit Logdateien
umgegangen wird. Der *Defaultwert* ist `daemon`.

`$user` :: legt den Namen des Benutzers fest, dem die Dateien im
Cacheverzeichnis von Approx gehören. Der *Defaultwert* ist `approx`.

`$verbose` :: legt fest, ob ausführlichere Logeinträge erstellt werden
sollen. Der *Defaultwert* ist `false` und somit ausgeschaltet.

Alle weiteren Einträge bezeichnen den Namen und die URL eines
Paketmirrors, von denen Approx im Falle einer Anfrage nach passenden
Softwarepaketen suchen soll.

* Inhalt (beispielhaft):

----
interval 120
max_wait 10
debian       http://http.uk.debian.org/debian
security     http://security.debian.org/debian-security
non-us       http://non-us.debian.org/debian-non-US
----

* `approx` neustarten

----
/etc/init.d/approx restart
----

* Approx lauscht nun auf Port 9999 für Anfragen von Clients

[[approx-Konfiguration-Client]]
===== Client =====

// Stichworte für den Index
(((Approx, Clientkonfiguration)))
* anpassen der Datei `/etc/hosts` -- ergänzen des Approx-Servers mit
IP-Adresse und Hostname

----
1.2.3.4 approx-server
----

* ergänzen der Datei `/etc/apt/sources.list` um Verweise auf den
Approx-Server

----
deb http://approx-server:9999/debian stable main contrib non-free
deb-src http://approx-server:9999/debian stable main contrib non-free
deb http://approx-server:9999/security stable/updates main contrib non-free
----

* die Paketliste aktualisieren mittels `apt-get update`

==== Beobachtungen aus dem Alltag ====

* Verzögerungen einplanen, bis Pakete im Approx-Cache gelandet sind


// Datei (Ende): ./praxis/apt-cache/approx.adoc
