// Datei: ./praxis/apt-cache/apt-cacher-ng.adoc

// Baustelle: Rohtext

[[apt-cacher-ng]]

=== apt-cacher-ng ===

// Stichworte für den Index
(((Debianpaket, apt-cacher-ng)))
(((Paketcache, apt-cacher-ng)))
(((Paketproxy, apt-cacher-ng)))

==== Werkzeugbeschreibung ====

Das Werkzeug `apt-cacher-ng` steht über das gleichnamige Paket
'apt-cacher-ng' <<Debian-Paket-apt-cacher-ng>> bereit. Es ist fester
Bestandteil der Debian-Paketliste. Ausführliche Informationen zum
Projekt finden Sie auf der Projektwebseite
<<apt-cacher-ng-Projektseite>>.

`apt-cacher-ng` sieht sich selbst als Proxyserver zum Zwischenspeichern
von Softwaredepots und lädt Pakete von Softwaredepots im Debian-Stil 
(oder möglicherweise von anderen Typen) herunter. Es wurde von Grund auf 
neu als Ersatz für `apt-cacher` entwickelt (siehe <<apt-cacher>>) und
soll gleichzeitig `apt-proxy` <<apt-proxy>> und `approx` (siehe 
<<approx>>) ersetzen, ohne die Datei `/etc/apt/sources.list` der Clients
ändern zu müssen.

Im laufenden Betrieb speichert `apt-cacher-ng` eine Kopie aller Nutzdaten, 
die über ihn laufen.

==== Einrichtung und Betrieb ====

* ToDo

// Datei (Ende): ./praxis/apt-cache/apt-cacher-ng.adoc
