// Datei: ./praxis/apt-cache/apt-cacher.adoc

// Baustelle: Notizen

[[apt-cacher]]

=== apt-cacher ===

// Stichworte für den Index
(((apt-cacher, /etc/default/apt-cacher)))
(((Debianpaket, apt-cacher)))
(((Paketcache, apt-cacher)))
(((Paketproxy, apt-cacher)))

Das Werkzeug `apt-cacher` steht über das gleichnamige Paket 
'apt-cacher' <<Debian-Paket-apt-cacher>> bereit. Es ist fester 
Bestandteil der Debian-Paketliste.

Netztechnisch klemmt sich die Software zwischen dem (öffentlichen)
Paketmirror und den anfragenden Clients. Es ist interessant für kleine
und auch größere Netzwerke, die einen weitestgehend identischen
Softwarebestand besitzen. `apt-cacher` ermöglicht einen Paketcache, d.h.
es merkt sich, welche Pakete bereits angefragt wurden und liefert diese
an den Anfragenden aus dem Paketcache, sofern sich das Paket bereits
darin befindet, ansonsten holt es das Paket zuvor vom Paketmirror.

* Beispiel:
** 'apt-mirror' und 'apt-cacher': <<apt-mirror-ubuntu2>>

* empfohlene Schritte, um das zu nutzen:
** Server konfigurieren, sprich: der Rechner, der den Paketcache
bereitstellt
*** Installation der Pakete 'apt-cacher', idealerweise in Kombination mit
einem APT-Proxy wie 'apt-proxy' <<apt-proxy>> oder 'approx' <<approx>>
*** Service aktivieren durch Anpassung der Datei
`/etc/default/apt-cacher` und Änderung des Wertes für
`AUTOSTART`: `AUTOSTART=0` in `AUTOSTART=1`
*** `apt-cacher` neu starten mittels `/etc/init.d/apt-cacher restart`
** Clients konfigurieren, d.h. Bezugsadresse für Pakete ändern
*** neuen Service erzeugen und dazu die Datei `/etc/apt/apt.conf.d/90-apt-proxy.conf` anlegen
*** die Datei um den Eintrag ergänzen: `Acquire::http::Proxy
"http://repository-cache:3142";`
*** `repository-cache` bezeichnet den Rechnernamen, der den Paketcache
bereitstellt

// Datei (Ende): ./praxis/apt-cache/apt-cacher.adoc
