// Datei: ./praxis/apt-cache/apt-cacher.adoc

// Baustelle: Notizen

[[apt-cacher]]

=== apt-cacher ===

// Stichworte für den Index
(((apt-cacher, /etc/default/apt-cacher)))
(((Debianpaket, apt-cacher)))
(((Paketcache, apt-cacher)))
(((Paketproxy, apt-cacher)))

==== Werkzeugbeschreibung ====

Das Werkzeug `apt-cacher` steht über das gleichnamige Paket 
'apt-cacher' <<Debian-Paket-apt-cacher>> bereit. Es ist fester 
Bestandteil der Debian-Paketliste.

Netztechnisch klemmt sich die Software zwischen dem (öffentlichen)
Paketmirror und den anfragenden Clients. Es ist interessant für kleine
und auch größere Netzwerke, die einen weitestgehend identischen
Softwarebestand besitzen. `apt-cacher` ermöglicht einen Paketcache, d.h.
es merkt sich, welche Pakete bereits angefragt wurden und liefert diese
an den Anfragenden aus dem Paketcache, sofern sich das Paket bereits
darin befindet, ansonsten holt es das Paket zuvor vom Paketmirror.

* Beispiel:
** 'apt-mirror' und 'apt-cacher': <<apt-mirror-ubuntu2>>

==== Einrichtung und Benutzung ====

Die Einrichtung unterteilt sich in zwei Schritte -- die Konfiguration
des Servers und der Clients. Der Server ist hierbei der Rechner, der 
den Paketcache später bereitstellt.

==== Serverkonfiguration ====

Zunächst installieren Sie das Paket 'apt-cacher' auf dem Server, 
idealerweise in Kombination mit einem APT-Proxy wie 'apt-proxy' 
<<apt-proxy>> oder 'approx' <<approx>>. Danach aktivieren Sie den Dienst
zum automatischen Start von `apt-cacher`, indem Sie eine kleine Änderung
in der Konfigurationssatei `/etc/default/apt-cacher` vornehmen. Ändern
Sie darin diese Zeile wie folgt von

----
`AUTOSTART`: `AUTOSTART=0` 
----

in

----
`AUTOSTART`: `AUTOSTART=1`
----

Nachdem Sie die Konfigurationsdatei gespeichert haben, starten Sie
`apt-cacher` neu, bspw. mittels `/etc/init.d/apt-cacher restart`.

==== Client anpassen ====

Auf einem Clients ändern Sie nun die Bezugsadresse für Softwarepakete.
Dazu legen Sie einen neuen Service an -- die Datei namens
`/etc/apt/apt.conf.d/90-apt-proxy.conf`. Diese Datei ergänzen Sie um den
folgenden Eintrag, indem Sie damit auf ihren APT-Cache verweisen:

----
Acquire::http::Proxy "http://repository-cache:3142";
----

Hier bezeichnet `repository-cache` den Rechnernamen, der den Paketcache
bereitstellt. Die Angabe `3142` bezeichnet den Port, auf dem der
Paketcache auf die Anfragen des Clients lauscht.

// Datei (Ende): ./praxis/apt-cache/apt-cacher.adoc
