// Datei: ./praxis/apt-cache/begriff.adoc

// Baustelle: Rohtext

[[apt-cache-begriff]]

=== Begriff ===

// Stichworte für den Index
(((Paketcache, APT-Cache)))
(((Paketcache, Bezug eines Softwarepaketes)))
(((Paketcache, Cache)))
(((Paketmirror)))
Im Allgemeinen bezeichnet ein 'Cache' einen Datenpuffer oder
Zwischenspeicher, der Daten weiter vorhält und auf den im Bedarfsfall
zurückgegriffen wird, wenn die gleichen Daten erneut angefordert oder
ausgetauscht werden. In unserem speziellen Fall beinhaltet der Cache
keine beliebigen Daten, sondern Softwarepakete. Diese werden darin von
der Paketverwaltung gespeichert, sobald sie das erste Mal vom 
Paketmirror bezogen wurden. Das passiert beispielsweise bei der 
Installation oder Aktualisierung eines Softwarepakets. 

Der Cache macht sich insbesondere dann deutlich bemerkbar, wenn mehrere
Rechner -- bspw. aus dem gleichen Netzwerk oder Rechnerverbund -- die 
gleichen Softwarepakete beziehen und dazu diesen Cache verwenden. 
Anwendungsfälle aus der Praxis sind Schulungsräume und Cluster, die aus 
identischen Knoten bestehen. Bei Anfragen nach den Softwarepaketen durch 
die Paketverwaltung verringert sich ab der zweiten Anfrage die Bezugszeit 
der Pakete zum jeweiligen Rechner und somit auch der gesamte Vorgang der
Pflege des Softwarebestands im Netzwerk oder Rechnerverbund.

Nachfolgend bezeichnen wir diesen Cache schlicht als 'APT-Cache', da wir
ihn in Zusammenhang mit APT als Bestandteil der Debian-Paketverwaltung
benutzen. Sofern wir nicht explizit darauf hinweisen, kommt der
APT-Cache auch zum Einsatz, wenn Sie andere Werkzeuge zur
Paketverwaltung einsetzen, bspw. Aptitude oder Synaptic. Hintergrund ist,
dass alle Werkzeuge auf die gleichen Konfigurationsdateien zur
Paketverwaltung zurückgreifen.

// Datei (Ende): ./praxis/apt-cache/begriff.adoc
