// Datei: ./praxis/apt-cache/begriff.adoc

// Baustelle: Rohtext

[[begriff]]

=== Begriff ===

// Stichworte für den Index
(((Paketcache, APT-Cache)))
(((Paketcache, Bezug eines Softwarepaketes)))
(((Paketcache, Cache)))
(((Paketmirror)))
Im Allgemeinen bezeichnet ein 'Cache' einen Datenpuffer oder
Zwischenspeicher, der Daten weiter vorhält und auf den im Bedarfsfall
zurückgegriffen wird, wenn die gleichen Daten erneut angefordert oder
ausgetauscht werden. Hier beinhaltet der Cache wiederholt benötigte
Softwarepakete. Diese werden darin gespeichert, sobald sie das erste Mal
vom Paketmirror bezogen wurden, beispielsweise bei der Installation oder
Aktualisierung eines Softwarepakets. 

Der Cache macht sich insbesondere dann deutlich bemerkbar, wenn mehrere
Rechner diesen Cache verwenden und daraus die gleichen Softwarepakete
beziehen. Bei nachfolgenden Anfragen nach den Softwarepaketen verringert
sich die Bezugszeit der Pakete und somit auch der gesamte Vorgang.

Nachfolgend bezeichnen wir diesen Cache schlicht als 'APT-Cache', da wir
ihn in Zusammenhang mit APT als Bestandteil der Debian-Paketverwaltung
benutzen. Sofern wir nicht explizit darauf hinweisen, kommt der
APT-Cache auch zum Einsatz, wenn Sie andere Werkzeuge zur
Paketverwaltung einsetzen, bspw. Aptitude oder Synaptic. Hintergrund ist,
dass alle Werkzeuge auf die gleichen Konfigurationsdateien zur
Paketverwaltung zurückgreifen.

// Datei (Ende): ./praxis/apt-cache/begriff.adoc
