// Datei: ./praxis/apt-cache/begriff.adoc

// Baustelle: Rohtext

[[begriff]]

=== Begriff ===

// Stichworte für den Index
(((Paketcache, APT-Cache)))
(((Paketcache, Bezug eines Softwarepaketes)))
(((Paketcache, Cache)))
(((Paketmirror)))
Im Allgemeinen bezeichnet ein 'Cache' einen Datenpuffer oder
Zwischenspeicher, der Daten weiter vorhält und auf den im Bedarfsfall
zurückgegriffen wird, wenn die gleichen Daten erneut angefordert oder
ausgetauscht werden. Hier beinhaltet der Cache wiederholt benötigte
Softwarepakete. Diese werden darin gespeichert, sobald sie das erste Mal
vom Paketmirror bezogen wurden, beispielsweise bei der Installation oder
Aktualisierung eines Softwarepakets.

Das macht sich insbesondere dann deutlich bemerkbar, wenn mehrere
Rechner diesen Cache verwenden und daraus die gleichen Softwarepakete
beziehen. Bei nachfolgenden Anfragen nach den Softwarepaketen sind diese
in deutlich kürzerer Zeit verfügbar und die benötigte Zeit für den
gesamten Vorgang verringert sich.

// Datei (Ende): ./praxis/apt-cache/begriff.adoc
