// Datei: ./praxis/apt-cache/begriff.adoc

// Baustelle: Rohtext

[[apt-cache-begriff]]

=== Begriff ===

// Stichworte f체r den Index
(((Paketcache, APT-Cache)))
(((Paketcache, Bezug eines Softwarepaketes)))
(((Paketcache, Cache)))
(((Paketmirror)))
Im Allgemeinen bezeichnet ein 'Cache' einen Datenpuffer oder
Zwischenspeicher, der Daten weiter vorh채lt und auf den im Bedarfsfall
zur체ckgegriffen wird, wenn die gleichen Daten erneut angefordert oder
ausgetauscht werden. In unserem speziellen Fall beinhaltet der Cache
keine beliebigen Daten, sondern Softwarepakete. Diese werden darin von
der Paketverwaltung gespeichert, sobald sie das erste Mal vom 
Paketmirror bezogen wurden. Das passiert beispielsweise bei der 
Installation oder Aktualisierung eines Softwarepakets. 

Der Cache macht sich insbesondere dann deutlich bemerkbar, wenn mehrere
Rechner diesen Cache verwenden und daraus die gleichen Softwarepakete
beziehen. Bei nachfolgenden Anfragen nach den Softwarepaketen verringert
sich die Bezugszeit der Pakete und somit auch der gesamte Vorgang.

Nachfolgend bezeichnen wir diesen Cache schlicht als 'APT-Cache', da wir
ihn in Zusammenhang mit APT als Bestandteil der Debian-Paketverwaltung
benutzen. Sofern wir nicht explizit darauf hinweisen, kommt der
APT-Cache auch zum Einsatz, wenn Sie andere Werkzeuge zur
Paketverwaltung einsetzen, bspw. Aptitude oder Synaptic. Hintergrund ist,
dass alle Werkzeuge auf die gleichen Konfigurationsdateien zur
Paketverwaltung zur체ckgreifen.

// Datei (Ende): ./praxis/apt-cache/begriff.adoc
