// Datei: ./praxis/apt-cache/besonderheiten-apt-cache.adoc

// Baustelle: Rohtext

[[besonderheiten-apt-cache]]

=== Besonderheiten des APT-Cache ===

// Stichworte für den Index

Der APT-Cache funktioniert ähnlich wie der Puffer aus <<paketcache>>,
ist allerdings nicht rechnerspezifisch, sondern eher als Vorstufe für
ein Netzwerk mit mehreren Clients gedacht und liegt meist auf einer
eigenen Hardware (oder als Virtuelle Maschine) vor. Besonders zum Tragen
kommt dieser Puffer bei einer von der Bandbreite her eher dünnen und
stark schwankenden oder nur zeitweise verfügbaren Netzwerkanbindung.
Erfolgt die Abrechnung Ihrer Internetanbindung entsprechend des
transportierten Datenvolumens (sogenannte 'trafficbasierte Abrechnung'),
ermöglicht der APT-Cache eine Verringerung der Last nach außen und spart
Ihnen somit bares Geld. Zudem wird die Bezugszeit von Softwarepaketen
deutlich kleiner, was Ihre Produktivität steigern kann. Da auch ein
externer Paketmirror ausfallen kann, lässt sich mit einem Paketcache die
lokale Ausfallrate verringern.

.Schematische Darstellung mit Paketcache in der Netzwerkinfrastruktur
----
* ToDo: Bild
----

Vor der Einrichtung ist zwischen einem Paketcache und dem eigenem
Paketmirror abzuwägen (siehe <<eigenen-apt-mirror-aufsetzen>>). Während
letzterer stets alle Softwarepakete der Veröffentlichung vorhält -- also
auch die, die Sie nicht benötigen -- landen im Paketcache hingegen nur
die Pakete, die bisher tatsächlich angefragt wurden.

Abzuschätzen ist zudem der Betreuungsaufwand, der bei beiden Varianten
einzuplanen ist.

* ToDo: Betreuungsaufwand abschätzen
// Datei (Ende): ./praxis/apt-cache/besonderheiten-apt-cache.adoc
