// Datei: ./praxis/apt-cache/besonderheiten-apt-cache.adoc

// Baustelle: Rohtext

[[besonderheiten-apt-cache]]

=== Besonderheiten des APT-Cache ===

// Stichworte für den Index
(((Paketcache, Optimierungspotential)))
Der APT-Cache funktioniert ähnlich wie der Puffer aus <<paketcache>>,
ist allerdings nicht rechnerspezifisch, sondern separat und als
Ergänzung für ein Netzwerk mit mehreren Knoten gedacht. Daher liegt er
einmalig vor, bspw. auf einer eigenen Hardware, als Virtuelle Maschine 
oder auch in einer Docker-Instanz.

.Schematische Darstellung mit Paketcache in der Netzwerkinfrastruktur
----
* ToDo: Bild
----

Neben dem geringeren Bedarf an Speicherplatz ergibt sich weiteres 
Potential zur Einsparung bzgl. des Datenvolumens des Netzwerks: die 
Netzwerklast nach außen verringert sich. Bemerkbar macht sich das 
insbesondere dann, wenn die Abrechnung ihrer Internetanbindung 
entsprechend des transportierten Datenvolumens (sogenannte 
'trafficbasierte Abrechnung') erfolgt. Das spart Ihnen auf Dauer 
somit bares Geld.

Werden beispielsweise einer oder mehrere Knoten im Netzwerk aktualisiert,
landen die neuen Softwarepakete zunächst im APT-Cache. Ab dem zweiten
Zugriff liegt das benötigte Paket bereits im APT-Cache vor und wird
daraus entnommen, anstatt es erneut vom externen Paketmirror zu beziehen
und wiederholt die Leitung zu belasten. Das verringert ebenso die
Bezugszeit der Softwarepakete, steigert ihre Produktivität im Netzwerk
und kann auch als Failover angesehen werden: fällt der externe
Paketmirror oder gar der Internetzugang aus, stehen ihnen immer noch die
Pakete aus dem APT-Cache zur Verfügung.

// Stichworte für den Index
(((Paketcache, Abgrenzung zum eigenen Paketmirror)))
Vor der Einrichtung ist zwischen einem APT-Cache und einem eigenem
Paketmirror abzuwägen (siehe <<eigenen-apt-mirror-aufsetzen>>). Während
letzterer stets alle Softwarepakete der Veröffentlichung vorhält -- also
auch die, die Sie nicht benötigen -- landen im APT-Cache hingegen nur
die Pakete, die bisher tatsächlich von einem der Netzwerkknoten
angefragt wurden. Er ist daher auch schlanker als ein eigener,
vollständiger Paketmirror.

Nachteilig ist, dass die Softwarepakete im APT-Cache nicht automatisch 
aufgeräumt werden, wenn diese veralten oder auf keinem Knoten im
Netzwerk mehr benötigt werden. Die Softwarepakete auf dem Paketmirror
spiegeln hingegen stets den aktuellen Veröffentlichungsstand der
Distribution wieder.

// Abzuschätzen ist zudem der Betreuungsaufwand, der bei beiden Varianten
// einzuplanen ist.

* ToDo: Betreuungsaufwand abschätzen

Nachfolgend stellen wir Ihnen unterschiedliche Lösungen vor, mit denen
Sie einen Paketcache einrichten und betreiben können.

// Datei (Ende): ./praxis/apt-cache/besonderheiten-apt-cache.adoc
