// Datei: ./praxis/mobile-geraete/mobile-geraete.adoc

// Baustelle: Rohtext

[[paketverwaltung-mit-eingeschraenkten-ressourcen-fuer-embedded-und-mobile-devices]]

== Paketverwaltung mit eingeschränkten Ressourcen für Embedded und Mobile Devices ==

// Stichworte für den Index
(((Paketverwaltung, für Embedded und mobile Geräte)))

Die Idee und Anregung für diese Thematik kommt dankenswerter Weise von
Werner Heuser <<Sentinel4Mobile>>, einem langjährigen Berliner
Spezialisten für Linux auf mobilen Geräten. Den Hintergrund bildet die
Frage, welche Programme und Methoden optimal für mobile Geräte sind, um
einerseits eine möglichst lange Nutzungsdauer zu ermöglichen und
andererseits dabei nur so viel Ressourcen zu verbrauchen, wie unbedingt
erforderlich sind. Wir betrachten das daher nachfolgend anhand der
Richtgrößen Batterielaufzeit, belegter Speicherplatz, Bildschirmgröße
und die Erfordernisse an die CPU.

[[mobile-geraete-batterie]]
=== Batterielaufzeit ===

// Stichworte für den Index
(((Debianpaket, acpitool)))
(((Debianpaket, tlp)))
Die Batterielaufzeit gehört neben dem Netzwerk zu den kritischsten 
Aspekten bei der Nutzung mobiler Geräte. Während andere Kriterien 
häufig eher nachrangig sind, geht ohne die beiden gar nichts. In unser
Blickfeld sind diese Werkzeuge geraten:

* 'acpitool' <<Debian-Paket-acpitool>>
* 'tlp' <<Debian-Paket-tlp>>

[[mobile-geraete-speicherplatz]]
=== Speicherplatz === 

Der Kampf um Speicherplatz wird wohl nie zu Ende gehen, egal, wie groß 
die Speichermedien auch werden. Eine ganze Reihe unterschiedlicher 
Pakete tritt an, ihnen in der Situation zu helfen. Dazu gehören bspw. 
'docpurge' <<docpurge>>, 'eatmydata' <<Debian-Paket-eatmydata>> und 
'localepurge' <<localpurge>>, die wir ihnen nachfolgend genauer 
vorstellen.

include::docpurge.adoc[]

include::eatmydata.adoc[]

include::localepurge.adoc[]

[[mobile-geraete-bildschirmgroesse]]
=== Bildschirmgröße ===

Todo

[[mobile-geraete-cpu]]
=== Erfordernisse an die CPU ===

* Debdelta // gehört hier erwähnt, bzw. systeme-mit-schlechter-anbindung-warten.adoc
* dietlibc über das Paket 'dietlibc-dev' <<Debian-Paket-dietlibc-dev>>

// Datei (Ende): ./praxis/mobile-geraete/mobile-geraete.adoc
