// Datei: ./praxis/mobile-geraete/mobile-geraete.adoc

// Baustelle: Rohtext

[[paketverwaltung-mit-eingeschraenkten-ressourcen-fuer-embedded-und-mobile-devices]]

== Paketverwaltung mit eingeschränkten Ressourcen für Embedded und Mobile Devices ==

// Stichworte für den Index
(((Paketverwaltung, für Embedded und mobile Geräte)))

Die Idee und Anregung für diese Thematik kommt dankenswerter Weise von
Werner Heuser <<Sentinel4Mobile>>, einem langjährigen Berliner
Spezialisten für Linux auf mobilen Geräten. Den Hintergrund bildet die
Frage, welche Programme und Methoden optimal für mobile Geräte sind, um
einerseits eine möglichst lange Nutzungsdauer zu ermöglichen und
andererseits dabei nur so viel Ressourcen zu verbrauchen, wie unbedingt
erforderlich sind. Wir betrachten das daher nachfolgend anhand der
Richtgrößen Batterielaufzeit, belegter Speicherplatz, Bildschirmgröße
und die Erfordernisse an die CPU.

[[mobile-geraete-batterie]]
=== Batterielaufzeit ===

// Stichworte für den Index
(((Mobile Geräte, Batterielaufzeit)))
(((Debianpaket, acpitool)))
(((Debianpaket, tlp)))
Die Batterielaufzeit gehört neben dem Netzwerk zu den kritischsten 
Aspekten bei der Nutzung mobiler Geräte. Während andere Kriterien 
häufig eher nachrangig sind, geht ohne die beiden gar nichts. In unser
Blickfeld sind diese Werkzeuge geraten:

* 'acpitool' <<Debian-Paket-acpitool>>
** Anzeige von Batterie- und Temperaturstatus, Ruhe-/Schlafstatus
** Erweiterungen für Notebooks von Toshiba, ASUS und IBM/Lenovo ThinkPads

* 'tlp' <<Debian-Paket-tlp>>
** optimierte Ansteuerung der Batterie(n)
** Abstimmung für Aufladung und Performance separat für Batterie- 
   und Netzbetrieb
** vorbereitete Profile für IBM/Lenovo ThinkPads
** Ein-/Ausschalten von Bluetooth, NFC, Wlan und Radio

[[mobile-geraete-speicherplatz]]
=== Speicherplatz === 

// Stichworte für den Index
(((Mobile Geräte, Speicherplatz)))
Der Kampf um Speicherplatz wird wohl nie zu Ende gehen, egal, wie groß 
die Speichermedien auch werden. Eine ganze Reihe unterschiedlicher 
Pakete tritt an, ihnen in der Situation zu helfen. Dazu gehören bspw. 
'docpurge' <<docpurge>>, 'eatmydata' <<Debian-Paket-eatmydata>> und 
'localepurge' <<localpurge>>, die wir ihnen nachfolgend genauer 
vorstellen.

include::docpurge.adoc[]

include::eatmydata.adoc[]

include::localepurge.adoc[]

[[mobile-geraete-bildschirmgroesse]]
=== Bildschirmgröße ===

// Stichworte für den Index
(((Mobile Geräte, Bildschirmgröße)))

Unter bestimmten Bedingungen sind die Größe und Auflösung des 
Bildschirms relevant, wenn auch nicht so vordergündig. Weniger 
Bildschirmgröße resultiert in weniger Gewicht und einem 
geringeren Stromverbrauch des Gerätes, was sich direkt in der
Nutzbarkeit ihres Akkus wiederspiegelt.

Hinzukommt eine kleinere Darstellung der Bedienoberflächen der 
Werkzeuge, was je nach Situation und Nutzer als Vor- oder Nachteil 
eingeschätzt wird. Mit Hilfe der Werkzeuge `xrandr` 
<<Debian-Paket-x11-server-utils>>, `arandr` <<Debian-Paket-arandr>>
und `lxrandr` <<Debian-Paket-lxrandr>> stellen Sie die gewünschte 
bzw. für Sie passende Auflösung und Helligkeit ein. Während 
ersteres ein Kommandozeilenwerkzeug ist, beglücken Sie die beiden 
Letztgenannten mit einer graphischen Bedienoberfläche.

[[mobile-geraete-cpu]]
=== Erfordernisse an die CPU ===

// Stichworte für den Index
(((Debianpaket, debdelta)))
(((Debianpaket, dietlibc-dev)))
(((Mobile Geräte, CPU)))
* Debdelta:
** siehe <<systeme-mit-schlechter-internet-anbindung-warten>>
** siehe <<systeme-mit-schlechter-anbindung-warten-debdelta>>
* dietlibc über das Paket 'dietlibc-dev' <<Debian-Paket-dietlibc-dev>>

// Datei (Ende): ./praxis/mobile-geraete/mobile-geraete.adoc
