// Datei: ./werkzeuge/dokumentation/weitere-buecher.adoc

// Baustelle: Fertig

[[weitere-buecher]]

=== Weitere Bücher ===

// Stichworte für den Index
(((APT)))
(((aptitude)))
(((dpkg)))
(((synaptic)))
Neben bereits oben besprochenen Dokumenten existieren viele thematisch
breiter angelegte Werke und Veröffentlichungen. Diese verschaffen dem
Neueinsteiger eine sehr gute Einordnung des Themas Paketmanagement im
Kontext der Einführung in den Umgang mit Linux als Betriebssystem sowie
der allgemeinen Betreuung von Rechnern und ganzen Rechnerverbünden. Auch
als dauerhaftes Nachschlagewerk sind diese Bücher wirklich zu empfehlen,
denn diese Bücher haben Substanz – auch wenn diese zum Teil bereits etwas
älter sind. Die meisten Autoren konzentrieren sich dabei auf das Basiswissen
mit `dpkg` in Kombination mit APT, `aptitude` oder `synaptic`:

* Frank Ronneburg ``Das Debian-Anwenderhandbuch'' – 1999 bis 2008 als
Buch aufgelegt und danach nur noch als Online-Dokumentation weitergeführt
<<Debian-Anwenderhandbuch>>. Fokussiert ausschließlich auf Debian
GNU/Linux.

* Martin F. Krafft ``Das Debian-System. Konzepte und Methoden'' – 2006
als Buch auf der Basis von Debian 3.1 _Sarge_ veröffentlicht. Eine
Fortsetzung und Aktualisierung ist bislang nicht erfolgt
<<Krafft-Debian-System>>. Fokussiert ausschließlich auf Debian
GNU/Linux.

// Stichworte für den Index
(((RPM, Dokumentation)))

* Michael Kofler ``Linux – das umfassende Handbuch'' –
Erstveröffentlichung 1995 mit jährlicher Aktualisierung. Nicht
distributionsspezifisch, sondern für `deb`- und `rpm`-basierte
Linux-Distributionen gleichermaßen gut geeignet <<Kofler-Linux-2013>>.

* Heike Jurzik ``Debian GNU/Linux: Das umfassende Handbuch'' –
Erstveröffentlichung als Buch 2006 zu Debian 3.1 _Sarge_, danach
regelmäßige Aktualisierung und Erweiterung <<Jurzik-Debian-Handbuch>>.
Das Buch richtet sich an Ein- und Umsteiger, die ihr Wissen Stück für
Stück erweitern – vom Einstieg über die Installation bishin zum Betrieb
eigener Dienste und Server. Fokussierung auf `deb`-basierte
Distributionen mit dem Schwerpunkt Debian GNU/Linux.

* Eric Amberg ``Linux-Server mit Debian 6 GNU/Linux: Das umfassende
Praxishandbuch'' – erschienen 2012 zu Debian 5 _Lenny_ und Debian 6
_Squeeze_, im Februar 2014 fortgesetzt mit einer aktualisierten Fassung
für Debian 7 _Wheezy_ <<Amberg-Linux-Server-Praxishandbuch>>. Fokussiert
ausschließlich auf Debian GNU/Linux.

// Datei (Ende): ./werkzeuge/dokumentation/weitere-buecher.adoc
