// Datei: ./werkzeuge/paketquellen-und-werkzeuge/etc-apt-sources.list-verstehen/beispieleintraege-fuer-offizielle-pakete.adoc

// Baustelle: Fertig

==== Beispieleinträge für offizielle Pakete ====

// Indexeinträge
(((/etc/apt/sources.list,Einträge für offizielle Pakete)))
(((/etc/apt/sources.list,Wechsel der Veröffentlichung)))
Der Standardeintrag für den Bezug von stabilen Debianpaketen aus dem
Bereich _main_ mit dem deutschen Spiegelserver als Paketquelle sieht
folgendermaßen aus:

----
deb http://ftp.de.debian.org/debian/ stable main
----

Mit diesem Eintrag beziehen Sie stets nur Pakete aus der aktuellen,
stabilen Veröffentlichung. Erscheint eine neue Veröffentlichung, sind
Sie damit auf der sicheren Seite und wechseln automatisch zum
Nachfolger.

Tragen Sie hingegen anstatt von _stable_ den entsprechenden Aliasnamen
der Veröffentlichung in Kleinbuchstaben wie bspw. _bullseye_ oder _bookworm_
ein, nutzen Sie ausschließlich Pakete aus der damit spezifizierten
Veröffentlichung, die diesen Aliasnamen trägt. Möchten Sie später von
dieser auf eine andere Veröffentlichung wechseln, passen Sie zunächst
den Aliasnamen im Eintrag entsprechend an und aktualisieren nachfolgend
die lokale Paketdatenbank (siehe ``Distribution aktualisieren'' in
<<distribution-aktualisieren>>).

Um hingegen zusätzlich die Pakete aus weiteren Paketbereichen wie bspw.
_contrib_ und _non-free_ zu verwenden, ändern Sie den Eintrag auf das
Folgende, hier wiederum mit expliziter Angabe des Aliasnamens _bookworm_:

----
deb http://ftp.de.debian.org/debian/ bookworm main contrib non-free non-free-firmware
----

In welcher Reihenfolge Sie die einzelnen, gewünschten Paketbereiche
angeben, spielt keine Rolle. Üblich ist jedoch die Abfolge anhand des
Freiheitsgrades der Softwarelizenz in der Form von _main contrib
non-free_.

[TIP]
.Auswahl eines Paketmirrors
====
Mehr Informationen zur Auswahl eines für Sie am besten geeigneten
Paketmirrors erfahren Sie unter ``Geeigneten Paketmirror auswählen'' in 
<<geeigneten-paketmirror-auswaehlen>>. Mit dieser Angabe beeinflussen
Sie die Bezugszeiten für Aktualisierungen der Paketlisten und der Pakete
erheblich zu ihren Gunsten.
====

// Datei (Ende): ./werkzeuge/paketquellen-und-werkzeuge/etc-apt-sources.list-verstehen/beispieleintraege-fuer-offizielle-pakete.adoc
