// Datei: ./werkzeuge/paketquellen-und-werkzeuge/etc-apt-sources.list-verstehen/eintraege-fuer-quellpakete.adoc

// Baustelle: Fertig

[[eintraege-fuer-quellpakete]]
==== Einträge für Quellpakete ====

// Indexeinträge
(((/etc/apt/sources.list,Einträge für Quellpakete)))
(((Paketvarianten, Quellpaket)))
(((Paketvarianten, Sourcepaket)))
Um Debian-Quellpakete (siehe <<sourcepakete>>) zu nutzen, benötigen Sie
eine weitere Zeile in ihrer Paketliste. Im Vergleich zu Binärpaketen
ändert sich lediglich das Schlüsselwort am Anfang eines Eintrags von
`deb` auf `deb-src`. Danach erwartet APT wie gewohnt den Eintrag der
Paketquelle. Für die offiziellen Quellpakete sieht der Eintrag wie folgt
aus, hier am Beispiel des deutschen Paketmirrors für Debian 9 _Stretch_:

//.Paketeintrag für die Quellpakete zu Debian 9 _Stretch_
----
deb-src http://ftp.de.debian.org/debian/ stretch main
----

// Datei (Ende): ./werkzeuge/paketquellen-und-werkzeuge/etc-apt-sources.list-verstehen/eintraege-fuer-quellpakete.adoc
