// Datei: ./werkzeuge/paketquellen-und-werkzeuge/etc-apt-sources.list-verstehen/eintraege-fuer-sicherheitsaktualisierungen.adoc

// Baustelle: Fertig

==== Einträge für Sicherheitsaktualisierungen ====

// Indexeinträge
(((/etc/apt/sources.list,Einträge für Sicherheitsaktualisierungen)))
(((Debian Security Team)))
(((Paketquelle, Security Updates)))
(((Paketquelle, Sicherheitsaktualisierungen)))
(((Security Updates)))
Häufig, aber in unregelmäßigen Abständen – d.h. wenn es erforderlich
ist – kündigt das Debian Security-Team <<Debian-Security>>
Sicherheitsaktualisierungen an und stellt diese bereit. Um von diesen
Aktualisierungen zu profitieren, ergänzen Sie die Datei
`/etc/apt/sources.list` um den folgenden Eintrag:

----
deb http://security.debian.org/ stretch/updates main contrib non-free
----

Obige Angabe beinhaltet beispielhaft wiederum die explizite Angabe des
Aliasnamens der Veröffentlichung Debian 9 _Stretch_. Dieser Name wird
gefolgt vom Unterverzeichnis `updates` und den daraus gewünschten
Distributionsbereichen _main_, _contrib_ und _non-free_.

// Datei (Ende): ./werkzeuge/paketquellen-und-werkzeuge/etc-apt-sources.list-verstehen/eintraege-fuer-sicherheitsaktualisierungen.adoc
