// Datei: ./werkzeuge/paketquellen-und-werkzeuge/etc-apt-sources.list-verstehen/eintraege-fuer-sicherheitsaktualisierungen.adoc

// Baustelle: Fertig

[[etc-apt-sources.list-verstehen-sicherheitsaktualisierungen]]
==== Einträge für Sicherheitsaktualisierungen ====

// Indexeinträge
(((/etc/apt/sources.list,Einträge für Sicherheitsaktualisierungen)))
(((Debian Security Team)))
(((Paketquelle, Security Updates)))
(((Paketquelle, Sicherheitsaktualisierungen)))
(((Security Updates)))
(((Sicherheitsaktualisierungen)))
Häufig, aber in unregelmäßigen Abständen – d.h. wenn es erforderlich ist – 
kündigt das Debian Security-Team <<Debian-Security>> diese 
Sicherheitsaktualisierungen an und stellt diese bereit. Um von diesen
Aktualisierungen zu profitieren, braucht es einen entsprechenden Eintrag 
in der Datei `/etc/apt/sources.list`.

Typischerweise wird dieser bereits zum Installationzeitpunkt vom Debian 
Installer angelegt, falls Sie die entsprechende Frage während der
Einrichtung mit ``Ja'' beantwortet haben. Hatten Sie während der 
Installation bei der Frage nach Sicherheitsaktualisierungen hingegen 
``Nein'' ausgewählt, oder fehlt der Eintrag aus sonstigen Gründen, so 
können Sie diesen jederzeit manuell nachtragen.

An dieser Stelle ist darauf zu achten, dass sich das Format des Eintrages 
zwischen Debian 10 _Buster_ und Debian 11 _Bullseye_ leicht geändert hat.

.`sources.list`-Eintrag für Sicherheitsaktualisierungen bis Debian 10
----
deb http://security.debian.org/ <veröffentlichungsname>/updates <archivbereiche>
----

.`sources.list`-Eintrag für Sicherheitsaktualisierungen ab Debian 11
----
deb http://security.debian.org/ <veröffentlichungsname>-security <archivbereiche>
----

Entsprechend folgen nun Beispiele für Debian 10 _Buster_, Debian 11
_Bullseye_ und Debian 12 _Bookworm_:

.`sources.list`-Eintrag für Sicherheitsaktualisierungen in Debian 10 _Buster_
----
deb http://security.debian.org/ buster/updates main contrib non-free
----

.`sources.list`-Eintrag für Sicherheitsaktualisierungen in Debian 11 _Bullseye_
----
deb http://security.debian.org/ bullseye-security main contrib non-free
----

.`sources.list`-Eintrag für Sicherheitsaktualisierungen in Debian 12 _Bookworm_
----
deb http://security.debian.org/ bookworm-security main contrib non-free non-free-firmware
----

Obige Angaben beinhalten wiederum die empfohlene explizite Verwendung des 
Aliasnamens der Veröffentlichung anstatt des Suite-Namens. Dieser Name 
wird gefolgt vom Unterverzeichnis `updates` und den daraus gewünschten 
Distributionsbereichen _main_, _contrib_ und _non-free_ sowie ab Debian 12 
_Bookworm_ auch _non-free-firmware_. Je nach System nicht benötigte 
Archiv-Bereiche (z.B. _non-free_ oder _non-free-firmware_) können Sie 
einfach weglassen.

// Datei (Ende): ./werkzeuge/paketquellen-und-werkzeuge/etc-apt-sources.list-verstehen/eintraege-fuer-sicherheitsaktualisierungen.adoc
