// Datei: ./werkzeuge/paketquellen-und-werkzeuge/etc-apt-sources.list-verstehen/format-eines-eintrags.adoc

// Baustelle: Fertig

[[format-eines-eintrags]]
==== Format eines Eintrags ====

// Indexeinträge
(((/etc/apt/sources.list, Felder eines Eintrags)))
Jeder Eintrag in der Datei `/etc/apt/sources.list` folgt einem
festen Muster mit einer genauen Abfolge von definierten Feldern:

----
Art_der_Quelle URI Distribution [Komponente 1] [Komponente 2] [...]
----

// Stichworte für den Index
(((debtorrent)))
(((Paketvarianten, Binärpaket)))
(((Paketvarianten, Sourcepaket)))
(((/var/cache/apt/archives/)))
Jedes dieser Felder hat eine bestimmte Funktion und erlaubt nur
ausgewählte Inhalte:

Art der Quelle:: 
bezeichnet den verwendeten Pakettyp. Zulässig sind entweder `deb` für
Debian-Binärpakete und `deb-src` für Debian-Quellpakete. Genauer gehen
wir dazu unter ``Debians Paketvarianten'' in <<debian-pakete-varianten>>
und ``Debian-Paketformat'' im Detail in <<debian-paketformat-im-detail>>
ein.

URI:: 
legt die Art der Installationsquelle fest. Hierbei sind diese Angaben
zulässig:
* `file`: die Installationsquelle ist ein Verzeichnis. Dieses kann
sowohl lokal vorliegen, als auch von extern eingebunden sein, bspw. über
ein Netzwerkdateisystem wie AFS, NFS oder SMB
* `cdrom`: genutzt wird eine CD, eine DVD oder eine Blu-ray als Installationsmedium
* `http`: die Installationsquelle ist ein HTTP-Server
* `https`: die Installationsquelle ist ein HTTPS-Server
* `ftp`: die Installationsquelle ist ein FTP-Server
* `copy`: identisch zum Eintrag `file`, aber die bezogenen Debianpakete
werden zusätzlich im lokalen Verzeichnis `/var/cache/apt/archives/`
abgelegt
* `mirror`: Auswahl einer Installationsquelle anhand der GeoIP des
Servers (siehe <<paketquellen-ueber-geoip-auswaehlen>>)
* `debtorrent`: die Pakete werden über DebTorrent auf der Basis des
BitTorrent-Protokolls bezogen <<Debian-Wiki-DebTorrent>>. Die Grundlage
dafür bildet das Debianpaket 'apt-transport-debtorrent'
<<Debian-Paket-apt-transport-debtorrent>>, welches installiert sein
muss.

Distribution:: 
benennt die Veröffentlichung (siehe <<veroeffentlichungen>>), aus der
Pakete installiert werden sollen. Typisch ist hier die Angabe des
Entwicklungsstands (siehe
<<bedeutung-der-verschiedenen-entwicklungsstaende>>) wie bspw. _stable_,
_unstable_ oder _testing_ sowie die Nennung des alternativen
Distributionsnamens wie bspw. _Buster_, _Bullseye_ oder _Sid_ (siehe
<<alias-namen>>).
+
Bitte beachten Sie bei Debian und Ubuntu die vollständige
Kleinschreibung des Namens. Nicht-offizielle Paketquellen können an
dieser Stelle jedoch auch sonstige Zeichenketten bis hin zu einem _._
verlangen.

Komponente:: 
bestimmt den Distributionsbereich, d.h. bspw. bei Debian _main_,
_contrib_ oder _non-free_. Ausführlicher gehen wir darauf in
<<distributionsbereiche>> ein.

// Datei (Ende): ./werkzeuge/paketquellen-und-werkzeuge/etc-apt-sources.list-verstehen/format-eines-eintrags.adoc
