// Datei: ./kann-denn-paketmanagement-spass-machen/zum-buch/autoren.adoc

// Baustelle: Fertig
// Axel: Fertig

==== Über die Autoren ====

*Dipl.-Inf. Axel Beckert* <<Beckert-Webseite>> hat Informatik mit
Nebenfach Biologie an der Universität des Saarlandes studiert. Er
arbeitet als u.a. Linux-Systemadministrator an der ETH Zürich, ist im
Vorstand der Linux User Group Switzerland (LUGS) und Mitglied des
Debian-Projekts. Er benutzt `aptitude` seit über 15 Jahren und ist seit
der Neuformierung des `aptitude`-Teams zum Jahreswechsel 2011/2012 als
Mentor, Versuchskaninchen für neue Versionen und Paketsponsor bei
`aptitude` mit an Bord. Seit 2015 ist er auch offiziell einer der
Maintainer des Pakets `aptitude` und kümmert sich primär um die
Paketierung.

*Dipl.-Inf. Frank Hofmann* hat Informatik mit Nebenfach Englisch an der
Technischen Universität Chemnitz studiert. Er bevorzugt das Arbeiten von
unterwegs aus als Entwickler, Trainer und Autor. Nach Berlin und Kapstadt
arbeitet er derzeit in Besançon (Franche-Comté). Seit Sommer 2013 ist er 
Mitglied im Debtags-Projekt <<Debian-Debtags>>, das sich die 
Verschlagwortung der einzelnen Debian-Pakete zum Ziel gesetzt hat.

// Datei (Ende): ./kann-denn-paketmanagement-spass-machen/zum-buch/autoren.adoc
