// Datei: ./kann-denn-paketmanagement-spass-machen/zum-buch/danksagung.adoc

// Baustelle: Rohtext
// Axel: Moving-Target

[[danksagung]]

=== Danksagung ===

Eine Reihe von Menschen haben uns bei der Realisierung dieses Buches
direkt oder indirekt unterstützt, sei es in Form von Anregungen, Kritik,
Vorschlägen zur Ergänzung oder Fach- und Verständnisfragen. Diesen
Menschen gebührt unser Dank:

* Elmar Heeb (für `aptitude-robot` und viele interessante Diskussionen)
* Dirk Deimeke (für Tipps zum Autor-Werden) <<Hackerfunk>>
* Arne Wichmann (für das Diagramm der Vertrauenskette in Debian – unter GPL)
* Annette Kalbow (für inhaltliche Vorschläge mit `apt-file`, `dpkg -l`
  und `dpkg -L`, die graphische Umsetzung der Landkarte sowie die vielen
Anregungen zum Aufsetzen und Betreiben eines Proxies <<http-proxy>>)
* Mechtilde Stehmann (für die Sprachkorrekturen und die Vorschläge für die FAQ)
* Marco Uhl (für die Idee zum FAQ-Eintrag über 'Debian Snapshots' <<Debian-Snapshots>> bei Testing- vs. Produktiv-Umgebung)
* Werner Heuser (für die Installation und den Umgang auf Embedded und Mobile Devices)
* Claude Becker (für Ideen, Korrekturlesen rund um das Parsen von
  Debian-Versionsnummern und APT-Pinning sowie Konsistenzprüfung)
* Christoph Berg (für Tipps und Tricks rund um `reprepro` und seine
Erfahrungen mit `apt.postgresql.org`) <<APT-Repo-PostgreSQL>>
* Dr. Thomas Fricke (für Ergänzungen rund um die Verteilung von Paketen auf mehrere Maschinen)
* Jens Wilke (Konfigurationsmanagement)
* Martin Schütte (`reprepro`)
* Michael Vogt (für Erklärungen rund um APTs `mirror://` Methode und 'gdebi')
* David Kalnischkies (für viele Detailerklärungen – z.B. zur
Parameterverarbeitung von `apt-get` – und die endlosen Diskussionen
darüber, die dennoch meist irgendwann in Erleuchtung endeten)
* Albrecht Barthel (für die vielen Infos und Einblicke zum Univention
Corporate Server, UCS)
* Martin 'Venty' Ebnöther (für ein weiteres paar Augen und Ohren zum
  Thema Paketmanagement)
* Dr. Markus Wirtz für die lange Unterstützung und Hilfe, das Buch auf
  seinen Weg zu bringen, für den Klappentext sowie fürs Lektorat der
  Einleitung und dem erstem Kapitel.
* Oliver Rath für seine Vorschläge zur besseren Lesbarkeit von Programmcode
* Karsten Merker für viele kleine Korrekturen
* Wolfram Schneider für den Hinweis zu `dh-make-perl` als spezialisierte
Variante von `checkinstall` sowie zum Aktualisieren von LTS-Versionen (siehe <<umgang-mit-lts>>)
* Jörg Brühe für die Anregungen zu den Paketabhängigkeiten
* Sebastian Andres für seine Anregungen zu Debian Backports

Nicht zu vergessen sind die Probeleser, die sich durch unser Manuskript
gekämpft haben: Arne Wichmann, Thomas Winde, Jana Pirat, Jörg Dölz,
Hagen Sankowski und Eberhard Hofmann. Vielen Dank für Eure Mühe und
Geduld!

// Datei (Ende): ./kann-denn-paketmanagement-spass-machen/zum-buch/danksagung.adoc
