// Datei: ./kann-denn-paketmanagement-spass-machen/zum-buch/dokumentation-deb-vs-rpm.adoc

// Baustelle: Fertig
// Axel: Fertig

==== Dokumentation `deb` vs. `rpm` ====

(((Dokumentation,aptitude)))
(((aptitude,Dokumentation)))
Trotz vieler Fortschritte sind manche Programme zur Paketverwaltung und
Hinweise zum Zusammenspiel von `dpkg`, APT und `aptitude` nur
bruchstückhaft oder gar nicht beschrieben – oder sie sind über viele
Köpfe und Online-Ressourcen hinweg verstreut. Auch an Übersetzungen
mangelt es: So liegt trotz des hohen Nutzungsgrades beispielsweise die
`aptitude`-Dokumentation bisher nicht in deutscher Sprache vor.

// Schlagworte für den Index
(((RPM,Dokumentation)))
Im Vergleich steht das Paketformat RPM etwas besser da. In seinem Buch
``Maximum RPM'' <<Bailey-Maximum-RPM>> hat Edward C. Bailey im Jahr
2000 die Regieanweisungen für den Umgang mit diesem Format
veröffentlicht. Aktueller sind der ``RPM Guide'' des
Fedora-Projekts <<Foster-Johnson-RPM-Guide>> und weiterführende
Dokumentationen auf der `rpm`-Projektseite <<RPM-Webseite>>.

Ein vergleichbares Buch zur Debian-basierten Paketverwaltung fehlte
bislang. Viele hervorragende Kompendien (siehe dazu <<weitere-buecher>>)
behandeln zwar die einzelnen Kommandozeilenwerkzeuge `dpkg`, APT,
`aptitude` oder Synaptic, aber meist fehlt der (entscheidende) Entwurf
eines Gesamtbildes, das sich erst aus der geschickten Kombination dieser
Werkzeuge ergibt.

// Datei (Ende): ./kann-denn-paketmanagement-spass-machen/zum-buch/dokumentation-deb-vs-rpm.adoc
