// Datei: ./kann-denn-paketmanagement-spass-machen/zum-buch/grundlagenwissen-fuer-administratoren.adoc

// Baustelle: Fertig
// Axel: Fertig

==== Grundlagenwissen für Administratoren ====

// Stichworte für den Index
(((Werkzeuge,Grundwissen)))
Der sichere Umgang mit der Paketverwaltung zählt zu Ihrem Grundwissen
als Administrator, um ein UNIX-/Linux-System einrichten und in Bezug auf
die eingesetzte Software betreuen zu können. Betreiben Sie Ihre Systeme
als Benutzer in Eigenverantwortung, sind diese Kenntnisse für Sie im
Alltag ebenso unverzichtbar.

// Schlagworte für den Index
(((LPI,Grundwissen)))
(((LPI,Material)))
(((LPI,Vorbereitung)))
(((LPI,Zertifizierung)))
Unabdingbar ist die Auseinandersetzung mit dem Paketmanagement für
Zertifizierungen. Die Prüfungen des Linux Professional Institutes (LPI), 
der Linux Foundation (LFC) <<lfc>> sowie die Linux+-Prüfung von CompTIA 
<<comptia-linux>> widmen dem Thema einen eigenen Schwerpunkt mit hoher 
Gewichtung (für LPIC-1 siehe <<lpic-101>>).

[TIP]
.Material für Ihre LPIC-Prüfungen
======
Ihre Vorbereitung auf die anspruchsvollen Tests des LPI ergänzen Sie
am besten mit dem Buch ``LPIC-1. Sicher zur erfolgreichen 
Linux-Zertifizierung'' von Harald Maaßen <<Maassen-LPIC-1>>.
======

// Datei (Ende): ./kann-denn-paketmanagement-spass-machen/zum-buch/grundlagenwissen-fuer-administratoren.adoc
