// Datei: ./kann-denn-paketmanagement-spass-machen/zum-buch/vorausgesetztes-wissen-des-lesers.adoc

// Baustelle: Fertig

[[vorausgesetztes-wissen-des-lesers]]
==== Vorkenntnisse ====

// Stichworte für den Index
(((Buch, Kommandozeile)))
(((Buch, Shell)))
Der Umgang mit der _Kommandozeile_ sollte Ihnen vertraut sein. Wir legen
uns nicht auf eine bestimmte Shell oder eine Terminalemulation fest.
Alle Beispiele wurden unter `bash` getestet, funktionieren aber auch
unter anderen Shells, wie z.B. der `zsh` (Axel nutzt auf einigen seiner
Systeme die `zsh` als Login-Shell für den Benutzer `root`, wie es auch
auf der Linux-Live-CD Grml gehandhabt wird). Die von uns ausgewählten
und hier abgedruckten Ausgaben im Terminal sind unabhängig von der
verwendeten Shell.

// Stichworte für den Index
(((Buch, graphische Werkzeuge)))
_Graphische Werkzeuge_ spielen hier nur eine untergeordnete Rolle. Sie
kommen nur dann zum Einsatz, wenn etwas nicht anders möglich ist oder es
um genau deren Besonderheiten geht. Wir gehen davon aus, dass Sie auf
einem Serversystem arbeiten und dieses ggf. sogar aus der Ferne
betreuen. In dieser Konstellation bilden graphische Werkzeuge die
absolute Ausnahme.

//Stichworte, Index
(((Filesystem Hierarchy Standard (FHS))))
Für Teil 1 ('Konzepte') ist Linux-Grundwissen unabdingbar: neben der
Arbeit auf der Kommandozeile also auch grundlegende Kenntnisse über den
_Filesystem Hierarchy Standard_ (FHS), der die Struktur der
Hauptverzeichnisse und deren Inhalte definiert (siehe dazu
<<FHS-Linux-Foundation>> und <<Debian-Wiki-FHS>>).

Teil 2 ('Werkzeuge') bespricht neben Strukturen zur Paketverwaltung alle
Paketoperationen im Alltag und setzt dafür zumindest das Wissen aus Teil
1 voraus. Um manche Beispiele oder vorgestellte Konzepte leichter
nachvollziehen zu können, ist mehrjährige Erfahrung mit Linux oder als
UNIX-Systemadministrator von Nutzen.

Teil 3 ('Praxis') beleuchtet ausschließlich konkrete, komplexere
Anwendungsfälle aus dem Alltag. Voraussetzung dafür ist eine
Vertrautheit mit den Werkzeugen zur Paketverwaltung, da es in diesem
Abschnitt ``ans Eingemachte'' geht.

Hilfreich sind darüber hinaus _Englischkenntnisse_: Viele
Bildschirmausgaben sind englisch, nicht zuletzt weil die Lokalisierung
der einzelnen Pakete bislang unvollständig ist. Die verwendenten Ausgaben 
auf dem Bildschirm und die Screenshots stammen hierbei von ganz 
unterschiedlichen Linux-Varianten -- Debian GNU/Linux, Ubuntu, Xubuntu 
und Linux Mint. Die dabei eingestellten Lokalisierungen sind Deutsch oder
Englisch.

// Stichworte für den Index
(((Buch, administrative Benutzerrechte)))
(((Werkzeuge,su)))
(((Werkzeuge,sudo)))
Sie müssen auf Ihrem System über _administrative Benutzerrechte_
verfügen, um einen Großteil der Beispiele nachvollziehen zu können. Wir 
weisen nicht jedes Mal explizit darauf hin{empty}footnote:[Sie erlangen 
diese Berechtigung je nach Konfiguration Ihres Systems über die Kommandos 
`su` oder `sudo` – oder indem Sie sich als Benutzer `root` auf Ihrem 
System anmelden.]. In den Beispielen für die Kommandozeile erkennen Sie 
anhand des verwendeten Prompt-Zeichens, ob dafür administrative Rechte 
notwendig sind oder nicht: `#` bedeutet hierbei ja und `$` bedeutet nein. 
Auf Ausnahmen weisen wir Sie an der betreffenden Stelle explizit hin.

// Stichworte für den Index
(((Werkzeuge,Administratorrechte-Umgebung)))
(((Werkzeuge,chroot-Umgebung)))
Auch wenn `dpkg`, APT und `aptitude` stabil und zuverlässig
funktionieren – gerade in der Rolle und mit den Berechtigungen eines
Administrators können falsche Befehle viel kaputt machen. Wir empfehlen
Ihnen darum, die vorgestellten Beispiele zunächst auf einem separaten
_Testsystem_ auszuprobieren – sei dies ein eigener Rechner, eine
virtuelle Maschine oder auch nur eine `chroot`-Umgebung
<<Debian-Wiki-chroot>>.

Dabei spielt es kaum eine Rolle, welches APT-basierte System Sie
verwenden. Begonnen haben wir das Buch zu dem Zeitpunkt, als Debian 7
'Wheezy' die stabile Debian-Veröffentlichung war. Daher stammen 
viele Beispiele im Buch aus diesem Zeitraum. Spätere Inhalte setzen 
auf dem Nachfolgern Debian 8 'Jessie', Debian 9 'Stretch', Debian 10
'Buster' und Debian 11 'Bullseye' auf. Alle Ausnahmen sind
entsprechend gekennzeichnet, bspw.  wenn wir zur Illustration auf ein
Derivat wie Ubuntu zurückgegriffen haben.

// Datei (Ende): ./kann-denn-paketmanagement-spass-machen/zum-buch/vorausgesetztes-wissen-des-lesers.adoc
