// Datei: ./kann-denn-paketmanagement-spass-machen/zum-buch/was-ist-das-buch.adoc

// Baustelle: Fertig
// Axel: Fertig

[[was-ist-das-buch]]

==== Was ist das Buch – und was nicht ... ====

Wir stellen `dpkg`, APT und `aptitude` mit den zugrundeliegenden
Mechanismen in den Mittelpunkt. Wir erläutern die Unterschiede und
ordnen die Werkzeuge anhand konkreter Aufgabenstellungen in den realen
Einsatzkontext ein. Diesem problemorientierten Ansatz folgend, werden
Sie die Programme künftig effizienter einsetzen und Paketmanagement als
ebenso hilfreichen wie angenehmen Teil der Administration der Ihnen
anvertrauten Systeme erleben.

Gedacht ist das Buch als Nachschlagewerk und Lernmedium für den Alltag.
Es hilft Ihnen, (typische) Fehler oder Umwege zu vermeiden, und räumt
mit zahlreichen Missverständnissen auf, die beim Thema Paketmanagement
immer noch kursieren.

Unser Buch ist kein allgemeines Linux-Einsteiger-Buch in der
Geschmacksrichtung ``Debian GNU/Linux'', sondern widmet sich mit der
Paketverwaltung bei Debian-Systemen einem speziellen Teilaspekt der
Systembetreuung. Folglich spielen andere Paketformate als `deb`
allenfalls eine Nebenrolle (siehe
<<varianten-und-formate-fuer-softwarepakete>>). Andere Debian-Derivate
(siehe <<welche-unix-artigen-betriebssysteme-verwenden-das>>) und
Linux-Distributionen haben vieles von Debian GNU/Linux übernommen, und
die Rezepte lassen sich daher oft in gleicher Weise anwenden. Wir können
jedoch nicht garantieren, dass wirklich alle Ausführungen
uneingeschränkt für andere Distributionen gelten. Sofern uns gravierende
Abweichungen vom Debian-Standard bekannt sind, benennen wir diese und
erklären, wie Sie in einem solchen Fall am besten verfahren.

Weiterhin ist dieses Werk kein Entwicklerhandbuch, aus dem Sie erfahren,
wie Sie `deb`-Pakete bauen und diese in Debian einbringen. Dieses Thema
würde den Rahmen des vorliegenden Werkes um ein Mehrfaches sprengen
und bleibt daher außen vor.

// *Teil 1 ('Konzepte')* ist als Rundgang angelegt. Neben dem Paketaufbau,
// deren Varianten und deren Sortierung lernen Sie zunächst die einzelnen
// Werkzeugebenen und deren Funktion kennen. Der *Teil 2 ('Werkzeuge')*
// beschreibt die einzelnen Programme zur Paketverwaltung im Detail. Der
// *Teil 3 ('Praxis')* zeigt Ihnen anhand von typischen, durchaus komplexeren
// Szenarien, wie Sie die einzelnen Werkzeuge effektiv nutzen. Ebenso
// finden Sie darin die erprobten Tipps aus der Praxis für Einzelsysteme
// und ganze Rechnernetze.

// Datei (Ende): ./kann-denn-paketmanagement-spass-machen/zum-buch/was-ist-das-buch.adoc
