// Datei: ./praxis/http-proxy/anwendungen.adoc

// Baustelle: Notizen

[[http-proxy-anwendungen]]
=== Einen Proxy in Anwendungen konfigurieren ===

// Stichworte für den Index
(((Proxy, in Anwendungen konfigurieren)))
(((Proxy Server, in Anwendungen konfigurieren)))

Sie werden sich sicher fragen, was dieser Aspekt in diesem Buch zu
suchen hat. Wichtig wird das genau dann, wenn Sie hinter einem Proxy
Server sitzen und dieser ihnen den direkten Weg zum Paketmirror und 
zu dringend benötigten Informationsseiten versperrt. Dann wird die
Recherche und der Bezug passender `deb`-Pakete nämlich etwas hakelig. 
Mehrfach waren wir in der Situation. Wir fügen das hier ein, damit 
Sie es leichter haben, aus der Situation herauszukommen.

==== Mittels wget ====

Das Werkzeug `wget` <<Debian-Paket-wget>> agiert wie ein fensterloser
Webbrowser und bezieht die Daten von im Aufruf angegebenen URL. `wget`
respektiert Proxy Server und wertet dazu die Umgebungsvariablen
`http_proxy`, `https_proxy`, `ftp_proxy` und `no_proxy` aus, falls diese
vorhanden sind. 

Der nachfolgende Aufruf demonstriert, wie Sie das Paket 'mc' via `wget`
vom Paketmirror `ftp.de.debian.org` beziehen. Das Paket finden Sie dann
als Datei `mc_4.8.26-1.1_amd64.deb` im lokalen Verzeichnis.

.Bezug des Paketes 'mc' vom Paketmirror `ftp.de.debian.org` via `wget`
----
$ wget http://ftp.de.debian.org/debian/pool/main/m/mc/mc_4.8.26-1.1_amd64.deb
--2023-06-12 22:07:02--  http://ftp.de.debian.org/debian/pool/main/m/mc/mc_4.8.26-1.1_amd64.deb
Auflösen des Hostnamen »ftp.de.debian.org (ftp.de.debian.org)«... 141.76.2.4
Verbindungsaufbau zu ftp.de.debian.org (ftp.de.debian.org)|141.76.2.4|:80... verbunden.
HTTP-Anforderung gesendet, warte auf Antwort... 200 OK
Länge: 534020 (522K) [application/vnd.debian.binary-package]
In »»mc_4.8.26-1.1_amd64.deb«« speichern.

mc_4.8.26-1.1_amd64.deb     100%[==========================================>] 521,50K   488KB/s   in 1,1s   

2023-06-12 22:07:04 (488 KB/s) - »»mc_4.8.26-1.1_amd64.deb«« gespeichert [534020/534020]
$
----

In Bezug auf Proxy Server verfügt `wget` über einige nützliche Kommandozeilenoptionen:

`--no-proxy-server`:: keinen Proxy Server verwenden, auch wenn dieser
systemweit konfiguriert ist

`--proxy_user` :: sich beim Proxy Server mit dem angegebenen Benutzer authentifizieren

`--proxy_password` :: sich beim Proxy Server mit dem angegebenen Passwort authentifizieren

==== Mittels curl ====

Was mit `wget` gelingt, geht auch mit `curl` (Debianpaket 'curl'
<<Debian-Paket-curl>>) -- `curl` kann nur deutlich mehr. Nützlich ist
hier zunächst der Schalter `-x` (Langversion: `--proxy`), mit dem Sie
zunächst den Proxy Server benennen. Der darauffolgende Wert repräsentiert
das Login `benutzer` mit dem Passwort `passwort` und dem Proxyserver mit
der IP-Adresse 127.0.0.1 und dem Port 1234.

.Bezug der Datei über einen Proxy mittels `curl`
----
curl --proxy "http://benutzer:passwort@127.0.0.1:1234" "http://webseite.org/datei"
curl --proxy "benutzer:passwort@127.0.0.1:1234" "http://webseite.org/datei"
----

Sind die beiden Umgebungsvariablen `http_proxy` und `https_proxy`
gesetzt, wertet `curl` diese aus. Dann vereinfacht sich der Aufruf zu:

.Bezug der Datei über einen Proxy mittels `curl` (vereinfachter Aufruf)
----
curl "http://webseite.org/datei"
----


==== Webbrowser Firefox ==== 

* nur über Dialogfenster
* frühe Versionen ignorieren Umgebungsvariablen
* keine Kommandozeilenoptionen

==== Webbrowser Chromium ====

* Systemeinstellungen

----
Bei der Ausführung von Google Chrome in einer unterstützten Desktop-Umgebung werden die Proxy-Einstellungen des Systems verwendet.
----

* Kommandozeilenparameter

`--proxy-server` :: Proxy Server benutzen

----
Specify the HTTP/SOCKS4/SOCKS5 proxy server to use for requests. This 
overrides any environment variables or settings picked via the options 
dialog.  An individual proxy server is specified using the format:

[<proxy-scheme>://]<proxy-host>[:<proxy-port>]

Where <proxy-scheme> is the protocol of the proxy server, and is one of:

"http", "socks", "socks4", "socks5".

If the <proxy-scheme> is omitted, it defaults to "http". Also note that 
"socks" is equivalent to "socks5".

Examples:

--proxy-server="foopy:99"
  Use the HTTP proxy "foopy:99" to load all URLs.

--proxy-server="socks://foobar:1080"
  Use the SOCKS v5 proxy "foobar:1080" to load all URLs.

--proxy-server="socks4://foobar:1080"
  Use the SOCKS v4 proxy "foobar:1080" to load all URLs.

--proxy-server="socks5://foobar:66"
  Use the SOCKS v5 proxy "foobar:66" to load all URLs.

It is also possible to specify a separate proxy server for different URL 
types, by prefixing the proxy server specifier with a URL specifier:

Example:

--proxy-server="https=proxy1:80;http=socks4://baz:1080"
  Load https://* URLs using the HTTP proxy "proxy1:80". And load http://*
  URLs using the SOCKS v4 proxy "baz:1080".
----

`--no-proxy-server`:: keinen Proxy Server verwenden, auch wenn
systemweit konfiguriert

`--proxy-auto-detect` :: automatische Erkennung des Proxy Servers

`--proxy-pac-url` :: legt die URL der automatischen Konfiguration
zur Erkennung des Proxy Servers fest

// Datei (Ende): ./praxis/http-proxy/anwendungen.adoc
