// Datei: ./praxis/http-proxy/anwendungen.adoc

// Baustelle: Notizen

[[http-proxy-anwendungen]]
=== Einen Proxy in Anwendungen konfigurieren ===

// Stichworte für den Index
(((Proxy, in Anwendungen konfigurieren)))
(((Proxy Server, in Anwendungen konfigurieren)))

* warum schauen wir uns das hier an:
** Recherche zu Paketen über den Webbrowser
** Herunterladen von `deb`-Paketen, wenn man hinter einem Proxy sitzt

==== Mittels wget ====

* benutzt die Umgebungsvariablen `http_proxy`, `https_proxy`,
`ftp_proxy` und `no_proxy`, falls vorhanden

==== Mittels curl ====

* Kommandozeilenschalter `-x` und `--proxy`

==== Webbrowser Firefox ==== 

* nur über Dialogfenster
* frühe Versionen ignorieren Umgebungsvariablen
* keine Kommandozeilenoptionen

==== Webbrowser Chromium ====

* Systemeinstellungen

----
Bei der Ausführung von Google Chrome in einer unterstützten Desktop-Umgebung werden die Proxy-Einstellungen des Systems verwendet.
----

* Kommandozeilenparameter

`--proxy-server` :: Proxy Server benutzen

----
Specify the HTTP/SOCKS4/SOCKS5 proxy server to use for requests. This 
overrides any environment variables or settings picked via the options 
dialog.  An individual proxy server is specified using the format:

[<proxy-scheme>://]<proxy-host>[:<proxy-port>]

Where <proxy-scheme> is the protocol of the proxy server, and is one of:

"http", "socks", "socks4", "socks5".

If the <proxy-scheme> is omitted, it defaults to "http". Also note that 
"socks" is equivalent to "socks5".

Examples:

--proxy-server="foopy:99"
  Use the HTTP proxy "foopy:99" to load all URLs.

--proxy-server="socks://foobar:1080"
  Use the SOCKS v5 proxy "foobar:1080" to load all URLs.

--proxy-server="socks4://foobar:1080"
  Use the SOCKS v4 proxy "foobar:1080" to load all URLs.

--proxy-server="socks5://foobar:66"
  Use the SOCKS v5 proxy "foobar:66" to load all URLs.

It is also possible to specify a separate proxy server for different URL 
types, by prefixing the proxy server specifier with a URL specifier:

Example:

--proxy-server="https=proxy1:80;http=socks4://baz:1080"
  Load https://* URLs using the HTTP proxy "proxy1:80". And load http://*
  URLs using the SOCKS v4 proxy "baz:1080".
----

`--no-proxy-server`:: keinen Proxy Server verwenden, auch wenn
systemweit konfiguriert

`--proxy-auto-detect` :: automatische Erkennung des Proxy Servers

`--proxy-pac-url` :: legt die URL der automatischen Konfiguration
zur Erkennung des Proxy Servers fest

// Datei (Ende): ./praxis/http-proxy/anwendungen.adoc
