// Datei: ./praxis/http-proxy/einen-proxy-konfigurieren.adoc

// Baustelle: Rohtext

// Einen Proxy konfigurieren

[[http-proxy-konfigurieren]]
=== Einen Proxy konfigurieren ===

// Stichworte für den Index
(((Proxy, unter Debian konfigurieren)))
(((Proxy Server, unter Debian konfigurieren)))
Üblicherweise kommt eine frische Debian-Installation ohne einen
konfigurierten Proxy Server daher. Ihr System kommuniziert direkt mit
den Diensten in der Netzwerkumgebung. Einen Proxy Server ergänzen Sie
nachträglich selbst.

Im Debian-Ökosystem gibt es unterschiedliche Stellen, an denen Sie die
Benutzung eines Proxy Servers hinterlegen. Dazu zählen zunächst die
allgemeinen Umgebungsvariablen (siehe ``Einen Proxy mittels
Umgebungsvariablen konfigurieren'' in
<<http-proxy-umgebungsvariablen>>), danach folgen die Einstellungen des 
Desktop-Environments und der Anwendungen, wie bspw. im Webbrowser
Firefox (siehe ``Einen Proxy in Anwendungen konfigurieren'' in
<<http-proxy-anwendungen>>). Für die Paketverwaltung kommem die Einträge
in der Datei `/etc/apt/apt.conf` bzw. der modularisierten Variante unter
`/etc/apt/apt.conf.d/70debconf` ins Visier (siehe dazu ``APT über
HTTP-Proxy'' in <<http-proxy-ueber-apt>>).

// Datei (Ende): ./praxis/http-proxy/einen-proxy-konfigurieren.adoc
