// Datei: ./praxis/http-proxy/http-proxy.adoc

// Baustelle: Rohtext

[[http-proxy]]

== Paketverwaltung hinter einem http-Proxy ==

// Rohmaterial von Annette -- so eine Art hübsche Einleitung zum Thema

Oftmals wird in größeren Netzen der Zugang zum Internet über einen Proxy
geregelt. Ein Proxy ist so eine Art Pförtner, der den Datenfluss
zwischen Subnetzen steuert. 

// ToDo: Bild ergänzen

Es gibt unterschiedliche Arten von Proxies und Gründe warum diese
betrieben werden. Einerseits möchten Sie z.B. Traffic oder
Übertragungszeit sparen. Dabei werden Dateien nach der ersten Anfrage
zwischengespeichert (gecached) und somit nicht erneut langwierig oder
kostenverursachend aus dem Internet geladen. Werden diese Daten erneut
angefordert, geht es schneller.

Andererseits möchten Sie sicherstellen, dass nur bestimmte Internetseiten 
besucht oder gar nur von berechtigen Nutzen abgerufen werden dürfen.
Hier werden dann in der Regel auch Authentifizierungsdaten benötigt, um
auf den Proxy zuzugreifen.

Neben transparenten Proxies, von denen der Benutzer in der Regel nichts
mitbekommen sollte, gibt es protokollabhängige Installationen wie
HTTP-Proxies oder FTP-Proxies. Diese werde nur für bestimmte
Transportprotokolle eingesetzt. Allgemeinere Varianten wie die SOCKS4-
und SOCKS5-Proxies[1] agieren hingegen protokollunabhängig. Ein
Spezialfall ist [[Apt-Cacher-ng]] -- das ist ein Proxy für Debianpakete.
Er behält die bereits angefragten Pakete im Cache, um sie schneller an
weitere Clients im Netz weitergeben zu können.

Im Debian-Ökosystem gibt es unterschiedliche Stellen, wo hinterlegt
werden kann, dass ein Proxy benutzt werden soll. Dies sind zunächst die
allgemeinen Umgebungsvariablen [...export bzw .profile ...], danach
folgen die Einstellungen des Desktop-Environments [...][2] und die der
Anwendungen, wie z.B. in Firefox. Für die Paketverwaltung kommt die
apt.conf [0,4].

Links:

* [1] https://de.wikipedia.org/wiki/SOCKS
* [1b] https://tools.ietf.org/html/rfc1928
* [2] https://wiki.archlinux.org/index.php/Proxy_settings siehe den Abschnit zu Gnome etc.
* [3] https://wiki.debian.org/AptConf
* [4] man apt.conf  (da einfach mal nach proxy suchen)

// weiteres Material

* wo trage ich das für apt ein
** Datei `/etc/apt/apt.conf.d/70debconf`

.Beispiel für einen Rechner `proxyserver` auf Port 8080
----
Acquire::http::Proxy "http://proxyserver:8080";
----

* was trage ich ein
** Nutzername
** Passwort (steht dann im Klartext in der Konfigurationsdatei)
** Rechner
** Port

.Beispiel mit Zugangsdaten für Nutzer `pakete`
----
Acquire::http::Proxy "pakete:geheim@http://proxyserver:8080";
----

* welche Umgebungsvariablen brauche ich
** `http_proxy`

* Parameter / Schalter im direkten Aufruf für apt-get

// Aufruf noch überprüfen, ob das so geht
.Beispielaufruf zur Installation von `mc` via Proxy
----
# apt-get -o http::Proxy="http://proxyserver:8080" install mc 
----

* Konfigurationsdialog bei Synaptic
** Einstellungen -> Netzwerk -> Proxy
** ToDo: Bild vom Dialogfenster

* aus der Manpage zu `apt.conf` (Ausschnitt):

----
http::Proxy ist der zu benutzende Standard-HTTP-Proxy. Er wird
standardmäßig in der Form http://[[Anwender][:Passwort]@]Rechner[:Port]/
angegeben. Durch Rechner-Proxies kann außerdem in der Form
http::Proxy::<host> mit dem speziellen Schlüsselwort DIRECT angegeben
werden, dass keine Proxies benutzt werden. Falls keine der obigen
Einstellungen angegeben wurde, wird die Umgebungsvariable http_proxy
benutzt.
----

* Material:
** Setting up apt-get to use a http-proxy (https://help.ubuntu.com/community/AptGet/Howto#Setting_up_apt-get_to_use_a_http-proxy)
** Proxyserver (https://wiki.ubuntuusers.de/Proxyserver/)
** AptConf im Debian Wiki (https://wiki.debian.org/AptConf)

// Datei (Ende): ./praxis/http-proxy/http-proxy.adoc
