// Datei: ./praxis/eigenes-apt-repository-anlegen/mini-dinstall.adoc

// Baustellenstatus: Notizen

[[eigenes-apt-repository-anlegen-mini-dinstall]]
=== mini-dinstall ===

// Stichworte für den Index
(((APT-Repository, eigenes erstellen)))
(((Debian Archive Kit (dak))))
(((Debianpaket, mini-dinstall)))
(((Paket, bereitstellen)))
(((Paketquelle, APT-Repository)))
(((Paketquelle, lokal)))

Das Projekt _mini-dinstall_ verfolgt den gleichen Zweck wie _minidak_: eine
kleinere Version von _dak_ und zielt auf das Betreiben eigener APT-Repositories
ab. Daher ist es mit weniger Automatismen und Komfort als die größeren 
Varianten ausgelegt. Es steht als gleichnamiges Debianpaket für die aktuelle, 
stabile Veröffentlichung von Debian bereit <<Debian-Paket-mini-dinstall>>. 
Abhängig is es vom Paket _dput_ <<Debian-Paket-dput>>, welches dazu dient, 
Softwarepakete auf Übereinstimmung mit den Debian-Richtlinien zu prüfen und 
diese dann in ein Repository hochzuladen.

* Voraussetzungen
** Webserver
** Verzeichnis mit Paketen

* Ergänzungen
** cron oder daemon

* Einrichtung
** Konfigurationsdatei
** gpg-Schlüssel zum Signieren der bereitgestellten Pakete

* Creating a Package Repository for APT (see https://debian-handbook.info/browse/stable/sect.setup-apt-package-repository.html)

// Datei (Ende): ./praxis/eigenes-apt-repository-anlegen/mini-dinstall.adoc
