// Datei: ./praxis/eigenes-apt-repository-anlegen/mini-dinstall.adoc

// Baustellenstatus: Rohtext

[[eigenes-apt-repository-anlegen-mini-dinstall]]
=== mini-dinstall ===

// Stichworte für den Index
(((APT-Repository, eigenes erstellen)))
(((Debian Archive Kit (dak))))
(((Debianpaket, dput)))
(((Debianpaket, mini-dinstall)))
(((Paket, bereitstellen)))
(((Paketquelle, APT-Repository)))
(((Paketquelle, lokal)))

Das Projekt _mini-dinstall_ verfolgt den gleichen Zweck wie _minidak_: eine
kleinere Version von _dak_ und zielt auf das Betreiben eigener APT-Repositories
ab. Daher ist es mit weniger Automatismen und Komfort als die größeren 
Varianten ausgelegt. Es steht als gleichnamiges Debianpaket für die aktuelle, 
stabile Veröffentlichung von Debian bereit <<Debian-Paket-mini-dinstall>>. 
Abhängig ist es vom Paket _dput_ <<Debian-Paket-dput>>, welches dazu dient, 
Softwarepakete auf Übereinstimmung mit den Debian-Richtlinien zu prüfen und 
diese dann in das bereits von ihnen vorbereitete APT-Repository hochzuladen.

Bislang ist die Dokumentation zu `mini-dinstall` recht überschaubar. Eine 
Übersicht zur Benutzung anhand von Beispielen sowie den einzelnen Einträgen in 
der Konfigurationsdatei findet sich in der beigefügten Dokumentation zum Paket 
_mini-dinstall_ sowie in der Manpage des Programms. Für die nachfolgende 
Beschreibung hat auch das intensive Lesen und Vergleichen verschiedener 
Blogbeiträge sehr viel geholfen.

[[mini-dinstall-vorausetzungen]]
==== Voraussetzungen ====

Die grundlegende Voraussetzung ist ein Verzeichnis für das APT-Repository -- 
sprich: wo möchten Sie ihre Pakete ablegen. `mini-dinstall` ist da recht 
flexibel und folgt ihren Angaben. Soll das APT-Repository lediglich lokal 
bereitstehen, genügt ein Pfad wie bspw. `/opt/paketarchiv` vollkommen. Soll 
das APT-Repository hingegen auch von anderen Rechnern aus via HTTP oder HTTPS 
erreichbar sein, benötigen Sie neben einem Webserver wie Apache oder Nginx auch 
einen Pfad unterhalb des Wurzelverzeichnisses des Webservers, bspw. 
`/var/www/debian`. Genau diesen Fall zeigen wir hier.

[[mini-dinstall-einrichtung]]
==== Einrichtung ====

Als nächstes legen Sie zwei Konfigurationsdateien an -- eine für `mini-dinstall`
selbst und eine weitere für `dput`. Übliche Namen sind `.mini-dinstall.conf` 
und `.dput.cf` in dem Home-Verzeichnis des Benutzers, der die Pakete später in 
das APT-Repository hochlädt. Eine Konfigurationsdatei `.mini-dinstall.conf` für 
ein APT-Repository, welches später via HTTP oder HTTPS erreichbar sein wird, 
sieht wie folgt aus:

.Basiseinstellungen zu `mini-dinstall`
----
[DEFAULT]
archivedir = /var/www/debian
archive_style = flat
architectures = all, amd64
mail_on_success = false
----

Damit liegt das APT-Repository unter `/var/www/debian` mit einer flachen 
Struktur (alle Binärpakete landen im gleichen Unterverzeichnis) und
Unterverzeichnisse werden nur für die beiden Architekturen 'amd64' und 'all'
angelegt. Es erfolgt keine Benachrichtigung bei einem erfolgreichen Upload.
Die Einstellungen gelten für alle Archive (Abschnitt `DEFAULT`).

[NOTE]
====
Eine Übersicht zu den Schaltern und zulässigen Einträgen in der Konfigurationsdatei 
finden Sie unter <<mini-dinstall-schalter-und-konfiguration>>.
====

* Einrichtung
** gpg-Schlüssel zum Signieren der bereitgestellten Pakete

[[mini-dinstall-laufender-betrieb]]
==== Laufender Betrieb ====

* Ergänzungen
** cron oder daemon

[[mini-dinstall-schalter-und-konfiguration]]
==== Schalter und Konfiguration ====

`mini-dinstall` kommt mit einer ganzen Reihe von Schaltern daher. Auch die 
Einträge für die Konfigurationsdatei sind etwas länger. Als **Schalter** 
unterstützt `mini-dinstall` die folgenden:

`-b` (Langform `--batch`) :: laufe im Stapelmodus ('batch mode')

`-c` (Langform `--config=file`) :: benutze `file` als Konfigurationsdatei. Der
Standardwert ist `~/.mini-dinstall.conf`

`-d` (Langform `--debug`) :: Gib zusätzliche Debuginformationen im Terminal 
und dem Logfile aus

`-k` (Langform `--kill`) :: beende den laufenden Daemon sofort

`-n` (Langform `--no-act`) :: führe keine Änderungen aus. Der Schalter ist 
nützlich in Kombination mit dem Schalter `-v`

`-q` (Langform `--quiet`) :: zeige so wenig Informationen an, wie nur möglich

`-r` (Langform `--run`) :: teile dem aktuell laufenden Daemon mit, dass er die
Abarbeitungsschlange sofort bearbeiten soll

`-v` (Langform `--verbose`) :: zeige ausführliche Informationen an

`--help` :: zeige eine kurze Liste der Schalter an

`--no-db` :: schalte das Nachschauen in der Paketdatenbank ab. `apt-ftparchive`
läuft ohne den Schalter `--db`.

`--no-log` :: schreibe kein Logfile

`--version` :: zeige die Version von `mini-dinstall` an

In der **Konfigurationsdatei** sind die folgenden Einträge zulässig:

`archivedir` :: The root of the mini-dinstall archive. Must be set, either here or on the command line.

`extra_keyrings` :: Additional GnuPG keyrings to use for signature verification.

`incoming_permissions` :: The permissions for the incoming directory. mini-dinstall will attempt to set the directory's permissions at startup. A value of zero (´'0´' or ´'0000´') will disable permission setting. Doing this, you MUST set permission for incoming by hand! Defaults to 0750.

`keyrings` :: GnuPG keyrings to use for signature verification of changes files. Setting this  parameter will modify the default list; it is generally better to modify `extra_keyrings` instead. Defaults to the keyrings from the debian-keyring package.

==== Lesematerial ====

* Creating a Package Repository for APT (see https://debian-handbook.info/browse/stable/sect.setup-apt-package-repository.html)

// Datei (Ende): ./praxis/eigenes-apt-repository-anlegen/mini-dinstall.adoc
