// Datei: ./praxis/eigenes-apt-repository-anlegen/mini-dinstall.adoc

// Baustellenstatus: Rohtext

[[eigenes-apt-repository-anlegen-mini-dinstall]]
=== mini-dinstall ===

// Stichworte für den Index
(((APT-Repository, eigenes erstellen)))
(((Debian Archive Kit (dak))))
(((Debianpaket, dput)))
(((Debianpaket, mini-dinstall)))
(((Paket, bereitstellen)))
(((Paketquelle, APT-Repository)))
(((Paketquelle, lokal)))

Das Projekt _mini-dinstall_ verfolgt den gleichen Zweck wie _minidak_: eine
kleinere Version von _dak_ und zielt auf das Betreiben eigener APT-Repositories
ab. Daher ist es mit weniger Automatismen und Komfort als die größeren 
Varianten ausgelegt. Es steht als gleichnamiges Debianpaket für die aktuelle, 
stabile Veröffentlichung von Debian bereit <<Debian-Paket-mini-dinstall>>. 
Abhängig ist es vom Paket _dput_ <<Debian-Paket-dput>>, welches dazu dient, 
Softwarepakete auf Übereinstimmung mit den Debian-Richtlinien zu prüfen und 
diese dann in das vorbereitete APT-Repository hochzuladen.

Bislang ist die Dokumentation zu `mini-dinstall` recht überschaubar. Eine 
Übersicht zur Benutzung anhand von Beispielen sowie den einzelnen Einträgen in 
der Konfigurationsdatei findet sich in der beigefügten Dokumentation zum Paket 
_mini-dinstall_ sowie in der Manpage des Programms. Für die nachfolgende 
Beschreibung hat auch das intensive Lesen und Vergleichen verschiedener 
Blogbeiträge sehr viel geholfen.

==== Voraussetzungen ====

Voraussetzung ist ein Verzeichnis für das APT-Repository -- sprich: wo möchten
Sie die Pakete ablegen. `mini-dinstall` ist da flexibel und folgt ihren 
Vorgaben. Soll das APT-Repository lediglich lokal bereitstehen, genügt ein 
Pfad wie bspw. `/opt/paketarchiv` vollkommen. Soll das APT-Repository hingegen 
auch von anderen Rechnern aus via HTTP oder HTTPS erreichbar sein, benötigen 
Sie neben einem Webserver wie Apache oder Nginx auch einen Pfad unterhalb des 
Wurzelverzeichnisses des Webservers, bspw. `/var/www/debian`. Die nachfolgenden
Beispiele zeigen letzteres.

==== Einrichtung ====

Als nächstes legen Sie zwei Konfigurationsdateien an -- eine für `mini-dinstall`
und eine weitere für `dput`. Üblich sind `.mini-dinstall.conf` und `.dput.cf`
in ihrem Home-Verzeichnis bzw. dem Home-Verzeichnis des Benutzers, der die 
Pakete später in das APT-Repository hochlädt. Eine Konfigurationsdatei 
`.mini-dinstall.conf` für ein APT-Repository, welches später via HTTP oder 
HTTPS erreichbar sein wird, sieht wie folgt aus:

.Basiseinstellungen zu `mini-dinstall`
----
[DEFAULT]
archivedir = /var/www/debian
archive_style = flat
architectures = all, amd64
mail_on_success = false
----

Damit liegt das APT-Repository unter `/var/www/debian` mit einer flachen 
Struktur (alle Binärpakete landen im gleichen Unterverzeichnis) und
Unterverzeichnisse werden nur für die beiden Architekturen 'amd64' und 'all'
angelegt. Es erfolgt keine Benachrichtigung bei einem erfolgreichen Upload.
Die Einstellungen gelten für alle Archive (`DEFAULT`).

* Einrichtung
** gpg-Schlüssel zum Signieren der bereitgestellten Pakete

==== Laufender Betrieb ====

* Ergänzungen
** cron oder daemon

==== Schalter und Konfiguration ====

Weitere Schalter sind:

`archivedir` :: The root of the mini-dinstall archive. Must be set, either here or on the command line.

`extra_keyrings` :: Additional GnuPG keyrings to use for signature verification.

`incoming_permissions` :: The permissions for the incoming directory. mini-dinstall will attempt to set the directory's permissions at startup. A value of zero (´'0´' or ´'0000´') will disable permission setting. Doing this, you MUST set permission for incoming by hand! Defaults to 0750.

`keyrings` :: GnuPG keyrings to use for signature verification of changes files. Setting this  parameter will modify the default list; it is generally better to modify `extra_keyrings` instead. Defaults to the keyrings from the debian-keyring package.

==== Lesematerial ====

* Creating a Package Repository for APT (see https://debian-handbook.info/browse/stable/sect.setup-apt-package-repository.html)

// Datei (Ende): ./praxis/eigenes-apt-repository-anlegen/mini-dinstall.adoc
