// Datei: ./praxis/paketformate-mischen/alien.adoc

// Baustelle: Rohtext

[[fremdformate-mit-alien-hinzufuegen]]

=== Fremdformate mit `alien` hinzufügen ===

==== Einführung ====

// Stichworte für den Index
(((Debianpaket, alien)))
Den Begriff 'alien' übersetzen Sie am ehesten mit 'fremd', 'Fremdling'
oder 'Ausländer'. So heißt auch das gleichnamige Debianpaket
<<Debian-Paket-alien>>, welches Ihnen hilft, eine Software, welche nicht
als `deb`-Paket vorliegt, entsprechend umzuwandeln und für Ihre
Debian-Installation vorzubereiten.

Wie bereits in ``Gestaltwandler. Programmpakete richtig konvertieren''
<<Hofmann-Osterried-Alien-LinuxUser>> beschrieben, sollten bei der
Umwandlung des Pakets nach Möglichkeit die folgenden Bestandteile
erhalten bleiben:

* die Paketbeschreibungen. Damit erkennen Sie später über die
Paketverwaltung, um was für eine Software es sich handelt, wer der Autor
ist oder wo sich die dazugehörige Homepage des Projekts befindet.

* die Informationsdateien. Diese beschreiben, wie Sie das Paket wieder
entfernen oder aktualisieren. Häufig befinden sich auch Hinweise dabei,
die benennen, was dabei gegebenenfalls zu beachten ist.

* die Informationen über Abhängigkeiten zu anderer Software

* die Angabe der Prozessorarchitektur im Dateinamen, wie etwa 'amd64'
bei `deb`-Paketen und 'x86_64' bei `rpm`-Archiven.

Bei der Umwandlung des Paketformats bestehen mehrere Fallstricke. Diese
führen regelmäßig dazu, dass die gewünschte Software nicht wie erhofft
funktioniert:

* die referenzierten Bibliotheken passen nicht oder sind nicht
auffindbar
* die angegebenen Pfade im Originalpaket stimmen nicht mit Ihrer lokalen
Verzeichnisstruktur überein
* der Binärcode passt nicht zu Ihrer genutzten Plattform und Architektur
* das Format der Konfiguration sorgt für Ärger, bspw. die verfügbaren
Optionen und Schalter
* es bestehen Konflikte mit anderer, bereits installierter Software

Verwenden Sie daher möglichst die Version der Software, die auch zu
Ihrer Distribution und Architektur passt. Diese lässt sich i.d.R. am
einfachsten in Ihren Softwarebestand integrieren. Weitere Informationen
dazu finden auf der Projektwebseite von `alien` <<alien>>.

==== Pakete umwandeln ====

Damit Ihnen das Umwandeln von Paketen gelingt, müssen ein paar
Voraussetzungen erfüllt sein. Für `alien` benötigen Sie:

* Perl <<Debianpaket-perl>>)
* die Werkzeuge `rpm` bzw. `yum` aus den gleichnamigen Debianpaketen für
die Konvertierung von `rpm`-Paketen (<<Debianpaket-rpm>> und <<Debianpaket-yum>>)

* die Werkzeuge `dpkg`, `dpkg-dev` und `debhelper` aus den gleichnamigen
Paketen <<Debian-Paket-dpkg>>, <<Debian-Paket-dpkg-dev>> und
<<Debian-Paket-debhelper>> zur Erzeugung von Debianpaketen

Hilfreich sind außerdem der GNU-C-Compiler und `make`, sofern Software
aus dem Quellcode zu übersetzen ist (Pakete <<Debian-Paket-gcc>> und
<<Debian-Paket-make>>).

* Optionen für Debian/deb-basierte Systeme
** `--patch=Datei`, `--anypatch` und `--nopatch`: zum automatischen Anpassen von Startup-Skripten und Pfaden gemäß dem File Hierarchy Standard (FHS) 
** `-c`: Bestehende Pre- und Post-Install- sowie Remove-Skripte bleiben erhalten
** `--generate` und `--veryverbose`: Optionen zur Fehlersuche

* Paket überprüfen, ob es zur bestehenden Installation passt

==== Umgewandelte Pakete einspielen ====

* Einspielen des erzeugten deb-Pakets mit `dpkg` an APT und `aptitude` vorbei
** Aufruf: `dpkg -i neuespaket.deb`

* was ist da zu beachten:
** alles geht glatt und das Paket funktioniert
** alles geht glatt und das Paket funktioniert nicht

// Datei (Ende): ./praxis/paketformate-mischen/alien.adoc
