// Datei: ./praxis/paketformate-mischen/alien.adoc

// Baustelle: Rohtext

[[fremdformate-mit-alien-hinzufuegen]]

=== Fremdformate mit `alien` hinzufügen ===

==== Einführung ====

// Stichworte für den Index
(((Debianpaket, alien)))
(((Fremdformate hinzufügen)))
Den Begriff 'alien' übersetzen Sie am ehesten mit 'fremd', 'Fremdling'
oder 'Ausländer'. So heißt auch das gleichnamige Debianpaket
<<Debian-Paket-alien>>. Es hilft Ihnen, eine Software, welche nicht
als `deb`-Paket vorliegt, entsprechend umzuwandeln und für Ihre
Debian-Installation vorzubereiten.

Wie bereits in ``Gestaltwandler. Programmpakete richtig konvertieren''
<<Hofmann-Osterried-Alien-LinuxUser>> beschrieben, sollten bei der
Umwandlung des Pakets nach Möglichkeit die folgenden Bestandteile
erhalten bleiben:

die Paketbeschreibungen :: damit erkennen Sie später über die
Paketverwaltung, um was für eine Software es sich handelt, wer der Autor
ist oder wo sich die dazugehörige Homepage des Projekts befindet.

die Informationsdateien :: diese beschreiben, wie Sie das Paket wieder
entfernen oder aktualisieren. Häufig befinden sich auch Hinweise dabei,
die benennen, was dabei gegebenenfalls zu beachten ist.

Paketabhängigkeiten :: die Informationen über Abhängigkeiten zu anderer 
Software.

Architektur oder Plattform :: die Angabe der Prozessorarchitektur im 
Dateinamen, wie etwa 'amd64' bei `deb`-Paketen und 'x86_64' bei 
`rpm`-Archiven.

Bei der Umwandlung des Paketformats bestehen mehrere Fallstricke. Diese
führen regelmäßig dazu, dass die gewünschte Software nicht wie erhofft
funktioniert:

* die referenzierten Bibliotheken passen gar nicht, nicht mehr (sind
bspw. veraltet) oder sind nicht auffindbar (sind bspw. nicht installiert
oder haben einen anderen Paketnamen)
* die angegebenen Pfade im Originalpaket stimmen nicht mit Ihrer lokalen
Verzeichnisstruktur oder der von Debian genutzten Struktur überein
* der Binärcode passt nicht zu Ihrer genutzten Plattform und Architektur
* das Format der Konfiguration sorgt für Ärger, bspw. die verfügbaren
Optionen und Schalter
* es bestehen Konflikte mit anderer, bereits installierter Software

Verwenden Sie daher möglichst die Version der Software, die auch zu
Ihrer Distribution und Architektur passt. Diese lässt sich i.d.R. am
einfachsten in Ihren Softwarebestand integrieren. Weitere Informationen
dazu finden auf der Projektwebseite von 'alien' <<alien>>.

==== Pakete umwandeln ====

===== Voraussetzungen =====

// Stichworte für den Index
(((Debianpaket, alien)))
(((Debianpaket, debhelper)))
(((Debianpaket, dpkg)))
(((Debianpaket, dpkg-dev)))
(((Debianpaket, gcc)))
(((Debianpaket, make)))
(((Debianpaket, perl)))
(((Debianpaket, rpm)))
(((Debianpaket, yum)))
(((Filesystem Hierarchy Standard (FHS))))
(((Paket, mit alien umwandeln)))
Damit Ihnen das Umwandeln von bestehenden Paketen in das `deb`-Format
gelingt, müssen ein paar Voraussetzungen erfüllt sein. Für `alien`
benötigen Sie:

* Perl <<Debian-Paket-perl>> -- weil `alien` ein Perl-Skript ist

* die Werkzeuge `rpm` bzw. `yum` aus den gleichnamigen Debianpaketen für
die Konvertierung von `rpm`-Paketen nach `deb` (<<Debian-Paket-rpm>> und
<<Debian-Paket-yum>>)

* die Werkzeuge `dpkg`, `dpkg-dev` und `debhelper` aus den Paketen 
<<Debian-Paket-dpkg>>, <<Debian-Paket-dpkg-dev>> und 
<<Debian-Paket-debhelper>> zur Erzeugung von Debianpaketen

* den GNU-C-Compiler `gcc` und `make` (<<Debian-Paket-gcc>> und
<<Debian-Paket-make>>), sofern Software aus dem Quellcode zu übersetzen ist

Die beiden Pakete `perl` und `dpkg` gehören zu den essentiellen Paketen
und sind auf ihrer Debian-Installation vorhanden. Die anderen genannten
Pakete könnten noch fehlen. Falls letzteres zutrifft, installieren Sie
diese über die Paketverwaltung nach (siehe ``Pakete installieren'' in
<<pakete-installieren>>).

===== Durchführung =====

// Stichworte für den Index
(((alien, -d)))
(((alien, -p)))
(((alien, -r)))
(((alien, -t)))
(((alien, --to-deb)))
(((alien, --to-pkg)))
(((alien, --to-rpm)))
(((alien, --to-slp)))
(((alien, --to-tgz)))

Die Umwandlung eines `rpm`-Pakets in ein `deb`-Paket erfolgt mittels
`alien` und der Angabe des Paketformats über den Schalter `-d` (Langform
`--to-deb`). Nachfolgend demonstrieren wir Ihnen das anhand des Pakets
'mc' für den Midnight Commander:

.Umwandlung eines `rpm`-Pakets in ein `deb`-Paket
----
# alien -d mc-4.8.22-1.mga7.x86_64.rpm
mc_4.8.22-2_amd64.deb generated
#
----

Der Schalter `-d` ist der Standardfall und kann im Aufruf weggelassen
werden. `alien` unterstützt noch die folgenden, weiteren Schalter zur 
Umwandlung in andere Formate:

`-r` (Langform `--to-rpm`) :: Umwandlung in ein RPM

`-t` (Langform `--to-tgz`) :: Umwandlung in ein mit `gzip` komprimiertes
`tar`-Archiv (`tar.gz`)

`--to-slp` (keine Kurzform) :: Umwandlung nach Stampede

`-p` (Langform `--to-pkg`) :: Umwandlung zu (Open)Solaris-Paketen (pkg)

// Stichworte für den Index
(((dpkg, -c)))
(((dpkg, --contents)))
(((dpkg, --info)))
Am Ende überprüfen Sie das Paket, um sicherzugehen, dass es auch
tatsächlich zu ihrer bestehenden Installation passt. Dabei hilft Ihnen
der Schalter `-c` (Langform `--contents`) von `dpkg`, um zu erkennen, an
welche Stellen die Komponenten des neuen Pakets installiert werden. Mit
`--info` sehen Sie, welche Paketabhängigkeiten bestehen und erfüllt sein
müssen. 

.Informationen zu einem umgewandelten Paket
----
# dpkg --info mc_4.8.22-2_amd64.deb 
 neues Debian-Paket, Version 2.0.
 Größe 1722852 Byte: control-Archiv= 9580 Byte.
     231 Byte,    11 Zeilen      conffiles            
     662 Byte,    15 Zeilen      control              
   21102 Byte,   317 Zeilen      md5sums              
 Package: mc
 Version: 4.8.22-2
 Architecture: amd64
 Maintainer: Frank Hofmann <frank@fehmarn.efho.local>
 Installed-Size: 7436
 Depends: libc6 (>= 2.15), libglib2.0-0 (>= 2.35.9), libgpm2 (>= 1.20.4), libslang2 (>= 2.2.4), libssh2-1 (>= 1.2.8)
 Section: alien
 Priority: extra
 Description: A user-friendly file manager and visual shell
  Midnight Commander is a visual shell much like a file manager, only with way
  more features.  It is text mode, but also includes mouse support if you are
  running GPM.  Its coolest feature is the ability to ftp, view tar, zip
  files, and poke into RPMs for specific files.
  .
  (Converted from a rpm package by alien version 8.92.)
#
----

===== Besonderheiten bei der Umwandlung =====

// Stichworte für den Index
(((alien, -c)))
(((alien, -g)))
(((alien, -k)))
(((alien, --anypatch)))
(((alien, --generate)))
(((alien, --keep-version)))
(((alien, --nopatch)))
(((alien, --patch)))
(((alien, --scripts)))
(((alien, --veryverbose)))

`deb`-basierte Systeme haben ihre Eigenheiten. Die folgenden Schalter
von `alien` helfen Ihnen bei der Paketumwandlung:

* `--patch=Datei`, `--anypatch` und `--nopatch` zum automatischen Anpassen von Startup-Skripten und Pfaden gemäß dem File Hierarchy Standard (FHS)
* `-c` (Langform `--scripts`) um bestehende Pre- und Post-Install- sowie Remove-Skripte zu erhalten
* `-k` (Langform `--keep-version`), um die Versionsnummer beizubehalten -- normalerweise zählt alien diese um eins hoch
* `-g` (Langform `--generate`) und `--veryverbose` um die Fehlersuche zu erweitern
* `-g` (Langform `--generate`), um das Paket vor der Umwandlung zu bearbeiten
** erzeugt ein Verzeichnis mit dem Paketinhalt
** ermöglich Ihnen die Ergänzung und Korrektur des Paketinhalts

==== Pakete umwandeln und einspielen ====

// Stichworte für den Index
(((alien, -i)))
(((alien, --install)))

* Paket von rpm nach deb umwandeln und gleich einspielen (Kurzform)

----
alien -i paket.rpm
----

==== Umgewandelte Pakete einspielen ====

// Stichworte für den Index
(((apt-get, install -f)))
(((dpkg, -i)))
(((dpkg, --install)))
Haben Sie das Paket erfolgreich in das `deb`-Format umgewandelt, spielen
Sie dieses mittels `dpkg -i` 'paketname.deb' ein. APT und `aptitude`
bekommen von der Aktion erstmal nichts mit, stören sich aber nicht
daran, dass das Paket eingespielt ist.

Dabei können mehrere Ergebnisse eintreten -- alles geht glatt und das Paket
funktioniert, alles geht glatt und das Paket funktioniert nicht, oder
das Einspielen geht schief. Da bleibt nur manuelle Nacharbeitung.
Abhängigkeitsprobleme beheben Sie mit dem Aufruf von `apt-get install
-f`. Mit dem Schritt löst APT alle bestehenden Abhängigkeiten auf.

// * was ist da zu tun?
// * woran kann das hängen? (Ursachenforschung)

// Datei (Ende): ./praxis/paketformate-mischen/alien.adoc
