// Datei: ./praxis/paketformate-mischen/alien.adoc

// Baustelle: Rohtext

[[fremdformate-mit-alien-hinzufuegen]]

=== Fremdformate mit `alien` hinzufügen ===

==== Einführung ====

// Stichworte für den Index
(((Debianpaket, alien)))
(((Fremdformate hinzufügen)))
Den Begriff 'alien' übersetzen Sie am ehesten mit 'fremd', 'Fremdling'
oder 'Ausländer'. So heißt auch das gleichnamige Debianpaket
<<Debian-Paket-alien>>, welches Ihnen hilft, eine Software, welche nicht
als `deb`-Paket vorliegt, entsprechend umzuwandeln und für Ihre
Debian-Installation vorzubereiten.

Wie bereits in ``Gestaltwandler. Programmpakete richtig konvertieren''
<<Hofmann-Osterried-Alien-LinuxUser>> beschrieben, sollten bei der
Umwandlung des Pakets nach Möglichkeit die folgenden Bestandteile
erhalten bleiben:

* die Paketbeschreibungen. Damit erkennen Sie später über die
Paketverwaltung, um was für eine Software es sich handelt, wer der Autor
ist oder wo sich die dazugehörige Homepage des Projekts befindet.

* die Informationsdateien. Diese beschreiben, wie Sie das Paket wieder
entfernen oder aktualisieren. Häufig befinden sich auch Hinweise dabei,
die benennen, was dabei gegebenenfalls zu beachten ist.

* die Informationen über Abhängigkeiten zu anderer Software.

* die Angabe der Prozessorarchitektur im Dateinamen, wie etwa 'amd64'
bei `deb`-Paketen und 'x86_64' bei `rpm`-Archiven.

Bei der Umwandlung des Paketformats bestehen mehrere Fallstricke. Diese
führen regelmäßig dazu, dass die gewünschte Software nicht wie erhofft
funktioniert:

* die referenzierten Bibliotheken passen gar nicht, nicht mehr (sind
bspw. veraltet) oder sind nicht auffindbar (sind bspw. nicht installiert
oder haben einen anderen Paketnamen)
* die angegebenen Pfade im Originalpaket stimmen nicht mit Ihrer lokalen
Verzeichnisstruktur überein
* der Binärcode passt nicht zu Ihrer genutzten Plattform und Architektur
* das Format der Konfiguration sorgt für Ärger, bspw. die verfügbaren
Optionen und Schalter
* es bestehen Konflikte mit anderer, bereits installierter Software

Verwenden Sie daher möglichst die Version der Software, die auch zu
Ihrer Distribution und Architektur passt. Diese lässt sich i.d.R. am
einfachsten in Ihren Softwarebestand integrieren. Weitere Informationen
dazu finden auf der Projektwebseite von `alien` <<alien>>.

==== Pakete umwandeln ====

// Stichworte für den Index
(((Debianpaket, alien)))
(((Debianpaket, debhelper)))
(((Debianpaket, dpkg)))
(((Debianpaket, dpkg-dev)))
(((Debianpaket, gcc)))
(((Debianpaket, make)))
(((Debianpaket, perl)))
(((Debianpaket, rpm)))
(((Debianpaket, yum)))
(((Filesystem Hierarchy Standard (FHS))))
(((Paket, mit alien umwandeln)))
Damit Ihnen das Umwandeln von bestehenden Paketen in das `deb`-Format
gelingt, müssen ein paar Voraussetzungen erfüllt sein. Für `alien`
benötigen Sie:

* Perl <<Debian-Paket-perl>>
* die Werkzeuge `rpm` bzw. `yum` aus den gleichnamigen Debianpaketen für
die Konvertierung von `rpm`-Paketen (<<Debian-Paket-rpm>> und <<Debian-Paket-yum>>)

* die Werkzeuge `dpkg`, `dpkg-dev` und `debhelper` aus den gleichnamigen
Paketen <<Debian-Paket-dpkg>>, <<Debian-Paket-dpkg-dev>> und
<<Debian-Paket-debhelper>> zur Erzeugung von Debianpaketen

Die Pakete `perl` und `dpkg` sind essentielle Pakete und auf ihrer
Debian-Installation vorhanden. Sollten die anderen genannten Pakete
nocht nicht vorhanden sein, installieren Sie diese über die
Paketverwaltung nach.

Hilfreich sind außerdem der GNU-C-Compiler `gcc` und `make`, sofern
Software aus dem Quellcode zu übersetzen ist. Dazu benötigen Sie die
beiden Pakete `gcc` <<Debian-Paket-gcc>> und `make`
<<Debian-Paket-make>>.

// Stichworte für den Index
(((alien, --anypatch)))
(((alien, -c)))
(((alien, -g)))
(((alien, --generate)))
(((alien, --nopatch)))
(((alien, --patch)))
(((alien, --scripts)))
(((alien, --veryverbose)))
`deb`-basierte Systeme haben ihre Eigenheiten. Die folgenden Schalter
von `alien` helfen Ihnen bei der Paketumwandlung:

* `--patch=Datei`, `--anypatch` und `--nopatch` zum automatischen Anpassen von Startup-Skripten und Pfaden gemäß dem File Hierarchy Standard (FHS)
* `-c` (Langform `--scripts`) um bestehende Pre- und Post-Install- sowie Remove-Skripte zu erhalten
* `-g` (Langform `--generate`) und `--veryverbose` um die Fehlersuche zu erweitern

Am Ende überprüfen Sie das Paket, um sicherzugehen, ob es auch
tatsächlich zu ihrer bestehenden Installation passt.

==== Umgewandelte Pakete einspielen ====

// Stichworte für den Index
(((dpkg, -i)))

Haben Sie das Paket erfolgreich in das `deb`-Format umgewandelt, spielen
Sie dieses mittels `dpkg -i paketname.deb` ein. APT und `aptitude`
bekommen von der Aktion erstmal nichts mit, stören sich aber nicht
daran. 

Dabei können zwei Ergebnisse eintreten -- alles geht glatt und das Paket
funktioniert, oder alles geht glatt und das Paket funktioniert nicht. Im
zweiten Fall müssen Sie manuell nacharbeiten:

* was ist da zu tun?
* woran kann das hängen? (Ursachenforschung)

// Datei (Ende): ./praxis/paketformate-mischen/alien.adoc
