// Datei: ./praxis/paketformate-mischen/apt4rpm.adoc

// Baustelle: Rohtext

[[deb-pakete-in-rpm-strukturen]]
==== `deb`-Pakete in `rpm`-Strukturen

// Stichworte für den Index
(((alien, --to-rpm)))
(((alien, -r)))
(((apt4rpm)))
(((apt-rpm)))
(((pacapt)))

Auch für Linux-Distributionen, die auf dem `rpm`-Paketformat aufsetzen,
können Sie `deb`-Pakete einspielen und benutzen. Diese Möglichkeiten 
sind uns bekannt:

`alien` mit dem Schalter `-r` (Langform `--to-rpm`) :: Umwandlung eines
`deb`-Paketes in ein `rpm`-Paket.

Projekt 'apt4rpm' <<apt4rpm>> :: stammt im Original von Conectiva Linux.
Releases und entsprechende Pakete waren von der jeweiligen Webseite des 
Projekts verfügbar. Das Projekt wurde bereits 2012 eingestellt.

Projekt 'apt-rpm' <<apt-rpm>> :: stammt aus der Feder von RedHat. Das
Projekt wurde leider bereits 2008 eingestellt.

Projekt 'pacapt' <<Arch-Linux-pacapt>> :: Werkzeug unter Arch Linux. Es
spricht die unterschiedlichen Paketmanager auf den einzelnen Plattformen
an. Derzeit verarbeitet es neben `dpkg` und `apt-get` auch `pacman`
(Arch Linux, ArchBang), `homebrew` (Mac OS X), `yum`/`rpm` (RedHat,
CentOS, Fedora) und `portage` (Gentoo). Es steht ebenfalls als Paket für
Ubuntu bereit <<Ubuntu-Paket-pacapt>>.

// Datei (Ende): ./praxis/paketformate-mischen/apt4rpm.adoc
