// Datei: ./praxis/paketformate-mischen/apt4rpm.adoc

// Baustelle: Rohtext

[[deb-pakete-in-rpm-strukturen]]
=== `deb`-Pakete in `rpm`-Strukturen ===

// Stichworte für den Index
(((alien, --to-rpm)))
(((alien, -r)))
(((apt4rpm)))
(((apt-rpm)))
(((pacapt)))
(((RPM-Paket installieren)))
(((yum, localinstall)))

Auch für Linux-Distributionen, die auf dem `rpm`-Paketformat aufsetzen,
können Sie `deb`-Pakete einspielen und benutzen. Es gelten dabei die 
gleichen Hinweise wie bereits oben genannt -- es ist nicht garantiert,
dass das Paket in ihr System passt und erwartungsgemäß funktioniert. 
Diese Möglichkeiten sind uns bekannt:

`alien` mit dem Schalter `-r` (Langform `--to-rpm`) :: Umwandlung eines
`deb`-Paketes in ein `rpm`-Paket. Haben Sie das Paket erfolgreich 
umgewandelt, installieren Sie es bspw. wie folgt mittels `yum` auf ihrem 
System:
+
.Installation des umgewandelten Pakets mittels `yum`
----
# yum localinstall paket.rpm
...
#
----
+
Das Unterkommando `localinstall` veranlasst `yum`, nicht in den hinterlegten
Repositories zu suchen, sondern das Paket aus dem lokalen Verzeichnis zu 
verwenden. Die Vorgehensweise ist vergleichbar mit dem Aufruf von `dpkg -i`.

Projekt 'apt4rpm' <<apt4rpm>> :: stammt im Original von Conectiva Linux 
<<Conectiva>>. Es erstellt aus einem APT-Repository ein lokales RPM-Repository, 
so dass die Pakete für `yum` verfügbar werden. Leider wird das Projekt seit 
2012 nicht mehr weiterentwickelt.

Projekt 'apt-rpm' <<apt-rpm>> :: war offizieller Bestandteil RedHat und später
Conectiva <<Conectiva>>. Das Projekt und dessen Weiterentwicklung wurde leider 
bereits 2008 eingestellt. Verwendet wird es jedoch bis heute als Werkzeug bei den 
beiden Linux-Distributionen ALT Linux <<altLinux>> und PCLinuxOS <<PCLinuxOS>>.

Projekt 'pacapt' <<Arch-Linux-pacapt>> :: Werkzeug unter Arch Linux. Es
spricht die unterschiedlichen Paketmanager auf den einzelnen Plattformen
an. Derzeit verarbeitet es neben `dpkg` und `apt-get` auch `pacman`
(Arch Linux, ArchBang), `homebrew` (Mac OS X), `yum`/`rpm` (RedHat,
CentOS, Fedora) und `portage` (Gentoo). Es steht ebenfalls als Paket für
Ubuntu bereit <<Ubuntu-Paket-pacapt>> und wird aktiv gepflegt.

// Datei (Ende): ./praxis/paketformate-mischen/apt4rpm.adoc
