// Datei: ./praxis/paketformate-mischen/apt4rpm.adoc

// Baustelle: Notizen

[[deb-pakete-in-rpm-strukturen]]
==== `deb`-Pakete in `rpm`-Strukturen

// - RPM-basierte Linux-Distributionen mit
//   link:http://apt4rpm.sourceforge.net/[apt4rpm] (Original für
//   Conectiva geschrieben) bzw. link:http://apt-rpm.org/[APT-RPM]
//   (RedHat)

Auch für Linux-Distributionen, die auf dem `rpm`-Paketformat aufsetzen,
können Sie `deb`-Pakete einspielen und nutzen. Möglich machen das die
beiden Projekte 'apt4rpm' <<apt4rpm>> bzw. 'apt-rpm' <<apt-rpm>>. Während
ersteres im Original von Conectiva stammt, steuerte RedHat das zweitgenannte
bei.

Releases und entsprechende Pakete beziehen Sie von der jeweiligen
Webseite des Projekts. Leider gibt es seit längerem keine neueren
Veröffentlichungen mehr -- 'apt4rpm' schweigt seit 2005, 'apt-rpm' seit
2008. 2012 verkündete 'apt4rpm', dass es die weitere Entwicklung
einstellt.

// - Entwicklungsstand
// -- letzte Release von 2005 (apt4rpm) bzw. 2008 (apt-rpm)
// -- apt4rpm: Last Update: 2012-10-08, "As of 2012-12-11, this project is no longer
//    under active development."
// -- apt-rpm: unklar

- wie gut ist das dann überhaupt?
- wann braucht man das? wann kann das nützlich sein?
- wer kümmert sich darum?

[TIP]
====
Wie Sie die beiden Werkzeuge verwenden können, entnehmen Sie bitte
der Dokumentation der Werkzeuge. 
====

[TIP]
====
Für Arch Linux existiert 'pacapt' <<Arch-Linux-pacapt>>, welches die
unterschiedlichen Paketmanager auf den einzelnen Plattformen anspricht.
Derzeit verarbeitet es neben `dpkg` und `apt-get` auch `pacman` (Arch
Linux, ArchBang), `homebrew` (Mac OS X), `yum`/`rpm` (RedHat, CentOS,
Fedora) und `portage` (Gentoo).
====


// Datei (Ende): ./praxis/paketformate-mischen/apt4rpm.adoc
