// Datei: ./ausblick/ausblick.adoc

// Baustelle: Notizen

[[part.Teil_Ausblick]]
[[ausblick]]

= Ausblick

== Notizen ==

TODO: Wollen wir hier ein wenig über die Zukunft von Paketmanagement
unter Debian orakeln? CUPT könnte man hier nochmals erwähnen. Das
web-basierte Zeugs vielleicht auch (Stichworte Tablets und
Smartphones).

* welche Fragen blieben bislang offen und unbeantwortet
* hat Paketmanagement -- so wie es jetzt vorliegt und verwendet wird -- überhaupt eine Zukunft
** Modell und Struktur wird langsam volljährig
** falls ja, was spricht denn dafür
** falls nein, was wäre denn eine geeignete Alternative dazu
*** gibt es vllt. schon kreative Ansätze, die langsam vor sich hin köcheln
*** was ist mit den Containerformaten wie Flatpak, Open Container Format
(OCF), App Container Image (ACI) und Docker?
* welche Punkte sind zu verbessern bzw. zu ergänzen
** an welchen Punkten hakelt es immer wieder
** hat das Modell Risiken und Schwachstellen
** was wird derzeit nicht abgedeckt
** Anwendungsfälle
* was sind die häufigsten Vorkommnisse, an denen etwas schiefgeht
* welche der im Buch vorgestellten Ansätze und Lösungen haben Potential
für die Zukunft

[[pakete-selber-bauen]]
== Pakete selber bauen ==

* TODO: Evtl. woanders hin?

* Beispiel: anhand des deb-Pakets für das vorliegende Buch
** weil (1): ist komplett
** weil (2): ist in den Quellen für das Buch gleich dabei
** weil (3): hängt von keinen weiteren Paketen ab
** weil (4): ist überschaubar
** weil (5): damit können wir testen, ob wir unser Paket für das Buch
richtig bauen bzw. ob noch etwas fehlt

[[ein-eigenes-debian-repository-aufbauen]]
== Ein eigenes Debian-Repository aufbauen ==

* siehe dazu: Michael Stapelberg: Kurz-Howto: Eigenes Debian-Repository
aufbauen <<Stapelberg-Debian-Repo>>

[[zukunft-von-apt]]
== Zukunft von APT, `dpkg` und Freunden ==

TODO: Drei-Weg-Konfigdatei-Mergen, siehe
http://community.libelektra.org/wp/?p=145 (Libelektra ist IIRC eine
generische Konfigdatei-Parser-Bibliothek) und
https://bugs.debian.org/32877

== Fazit / Zusammenfassung ==

TODO: Mehr und Aufsplitten

[[ausblick-empfehlung-fuer-einsteiger]]
=== Empfehlungen für Einsteiger ===

==== Mit welchem Programm zur Paketverwaltung soll ich anfangen? ====

Das hängt sehr davon ab, welche Art von Benutzerschnittstelle Sie
bevorzugen -- oder auch, in welcher Situation (Desktop, Server via ssh)
Sie gerade sind:

* Kommandozeile: `apt`. Es ist einfach und intuitiv, schnell getippt,
  hat angenehme farbliche Hervorhebungen in der Ausgabe und kann
  praktisch alles, womit Sie im Alltag zu tun haben. Bei älteren
  Veröffentlichungen ohne `apt` als Befehl weichen Sie auf die Befehle
  `apt-get` und `apt-cache` aus, aber die Nachteile sind nur
  geringfügig. Im wesentlichen umfaßt das mehr Tippen, je nach Aufgabe
  das passende Programm auswählen und keine Farbe in der
  Standard-Einstellung.

* Interaktiver Textmodus: `aptitude`. Nicht nur, weil es auch das
  einzige Programm mit dieser Benutzerschnittstelle ist, sondern auch,
  weil es einem sehr viele Informationen und Möglichkeiten bietet. Diese
  Darstellung in der Gesamtheit auf der Kommandozeile zu erreichen,
  gelingt nur mit einem Dutzend parallel geöffneter Terminalfenster.

* Graphische Benutzerschnittstelle: Synaptic (siehe <<gui-synaptic>>).
  Es bildet unserer Meinung nach das Debian-Paketsystem am besten ab
  und reduziert es nicht auf einen ``App-Store''.

// Datei (Ende): ./ausblick/ausblick.adoc
