// Datei: ./praxis/snapshots/snapshots.adoc

// Baustelle: Rohtext

[[pakete-und-patche-datumsbezogen-auswaehlen]]
== Pakete und Patche datumsbezogen auswählen ==

// Stichworte für den Index
(((Paket, ausgewählte Version installieren)))
(((Paket, datumsbezogen aktualisieren)))
(((Paket, datumsbezogen einspielen)))
(((Paket, datumsbezogen installieren)))
Bisher haben wir im Buch nur besprochen, wie Sie bereits installierte 
Pakete bspw. mit `apt-get install` 'Paketname' oder `apt-get upgrade` 
'Paketname' auf den neuesten Stand bringen (siehe 'Pakete aktualisieren' 
unter <<pakete-aktualisieren>> auch mit den Angaben zu Apt und Aptitude). 
Diese Schritte spielen stets die zuletzt vom Paketmirror verfügbare 
Version des Pakets ein, unabhängig davon, seit wann diese Version oder 
Aktualisierung bereitsteht.

Ebenfalls erlauben Apt und Aptitude, eine gewünschte Version zum Paket 
mittels `apt-get install` 'paketname=version' anzugeben -- dann wird nur 
die genannte Version installiert. 

Offen ist die Frage, ob es möglich ist, eine Aktualisierung eines oder
mehrerer Pakete bis zu einem bestimmten Bereitstellungsdatum einzuspielen.
Selten ist diese Situation nicht, da für ein Projekt oder einen Server 
üblicherweise Entwicklungs-, Test- und Produktivumgebungen bestehen. 
Während die Entwicklungsumgebungen stets auf dem aktuellsten Stand sind, 
trifft das eher nicht auf Test- und Produktivumgebungen zu. Diese werden 
erst auf der Testumgebung installiert und dort getestet und erst nach 
einer Freigabe auf der Produktivumgebung eingespielt. Nicht unüblich ist, 
dass zwischen dem Vorbereiten der Testumgebung und deren Freigabe 
(Übertragung in das Produktivsystem) mehrere Tage oder Wochen vergehen. 
Um die Produktivumgebung auf den Freigabestand zu heben, müssten 
Paketaktualisierungen bis zum Freigabezeitpunkt erfolgen. Nachfolgende
Aktualisierungen durchlaufen den gleichen Kreislauf, so dass stets 
sichergestellt ist, dass das Produktivsystem getestet ist.

* Gedanken zur Antwort:

** Problem tritt sehr häufig auf, bspw. in der Entwicklung. Ein Softwarestand
wird zusammengestellt, ausführlich getestet und -- falls alles gutgeht und
freigegeben wurde -- auf dem Produktivsystem ausgerollt.

** Variante 1 zur Lösung: Zustand des Testsystems mit allen Paketen und den
Konfigurationsdateien wird gesichert/gemerkt, bspw. über eine Paketliste oder
über Puppet, `rsync` o.ä.

** Variante 2: eine Art 'Package Freeze'. Das Datum, bis zu dem noch
Aktualisierungen von Paketen einfließen können, wird festgelegt. Das Zauberwort
heißt http://snapshot.debian.org/ <<Debian-Snapshots>>. In der
`/etc/apt/sources.list` stehen dann Einträge der Form:

----
deb http://snapshot.debian.org/archive/20091004T111800Z/debian lenny main
----

** zwei mögliche Zeitangaben:

** exakter Zeitstempel :: Der Zeitstring `20091004T121501Z` folgt der Form 
`yyyymmddThhmmssZ` oder vereinfacht `yyyymmdd`. Steht für ein angegebenes 
Datum kein Snapshot bereit, wird der zeitlich entsprechend vorherige 
ausgewählt.

*** wofür steht das `Z` in `yyyymmddThhmmssZ` ? Für Zeitzone? Falls ja, 
welche anderen Buchstaben gehen noch?

** relativer Zeitstempel:: Angabe des Zeitstempels als ein Wert, den das 
`date`-Kommando verarbeiten kann, bspw `yesterday` (für gestern), `2-days-ago`
(für: zwei Tage alt) oder `last-week` (für letzte Woche)

----
deb http://snapshot.debian.org/archive/date/yesterday/debian bookworm main
deb http://snapshot.debian.org/archive/date/2-days-ago/debian bookworm main
deb http://snapshot.debian.org/archive/date/last-week/debian bookworm main
----

// Datei (Ende): ./praxis/snapshots/snapshots.adoc
