// Datei: ./praxis/snapshots/snapshots.adoc

// Baustelle: Rohtext

[[pakete-und-patche-datumsbezogen-auswaehlen]]
== Pakete und Patche datumsbezogen auswählen ==

=== Ausgangssituation ===

// Stichworte für den Index
(((Paket, datumsbezogen aktualisieren)))
(((Paket, datumsbezogen einspielen)))
(((Paket, datumsbezogen installieren)))
Bisher haben wir im Buch nur besprochen, wie Sie bereits installierte 
Pakete bspw. mit `apt-get install` 'Paketname' oder `apt-get upgrade` 
'Paketname' auf den neuesten Stand bringen (siehe 'Pakete aktualisieren' 
unter <<pakete-aktualisieren>> -- auch mit den Angaben zu Apt und 
Aptitude). Diese Schritte spielen stets die zuletzt vom Paketmirror 
verfügbare Version des Pakets ein, unabhängig davon, seit wann diese 
Version oder Aktualisierung tatsächlich bereitsteht.

// Stichworte für den Index
(((Paket, ausgewählte Version installieren)))
Ebenfalls erlauben Apt und Aptitude, eine gewünschte Version zum Paket 
mittels `apt-get install` 'paketname=version' anzugeben -- dann wird nur 
die genannte Version installiert. Die Versionsangabe sagt selten etwas
darüber aus, wann die Version verfügbar war.

Offen ist die Frage, ob es möglich ist, eine Aktualisierung eines oder
mehrerer Pakete bis zu einem bestimmten Bereitstellungsdatum einzuspielen.
Selten ist diese Situation nicht, da für ein Projekt oder einen Server 
üblicherweise Entwicklungs-, Test- und Produktivumgebungen bestehen. 
Während die Entwicklungsumgebungen stets auf dem aktuellsten Stand sind, 
trifft das eher nicht auf Test- und Produktivumgebungen zu. Diese werden 
erst auf der Testumgebung installiert und dort getestet und erst nach 
einer Freigabe auf der Produktivumgebung eingespielt. Nicht unüblich ist, 
dass zwischen dem Vorbereiten der Testumgebung und deren Freigabe 
(Übertragung in das Produktivsystem) mehrere Tage oder Wochen vergehen. 
Um die Produktivumgebung auf den Freigabestand zu heben, müssten 
Paketaktualisierungen bis zum Freigabezeitpunkt erfolgen. Darausfolgende
Aktualisierungen durchlaufen den gleichen Kreislauf, so dass stets 
sichergestellt ist, dass sich das Produktivsystem nicht in einem 
ungetesteten Zustand befindet.

=== Lösungswege ===

==== Variante 1: Systemkopie oder Wiederherstellpunkt ====

Bei dieser Variante merken Sie sich den Zustand des Testsystems mit allen 
Paketen und den dazugehörigen Konfigurationsdateien. Sie erstellen eine Art
Sicherungspunkt mit den Beschreibungsdateien dazu. Als Werkzeuge eignen 
sich hierür bspw. die Werkzeuge `rsync` oder Puppet <<Puppet>>.

==== Variante 2: Package Freeze mit Debian Snapshots ====

// Stichworte für den Index
(((Paket, datumsbezogen aktualisieren)))
(((Paket, datumsbezogen einspielen)))
(((Paket, datumsbezogen installieren)))
(((Debian Snapshots)))
Dieser Weg entspricht einer Art 'Package Freeze', sprich: einem Einfrieren
des Paketstatus. Debian GNU/Linux nennt dieses Konzept 'Debian Snapshots' 
<<Debian-Snapshots>>. Sie spezifizieren hier einen Zeitpunkt als 
Obergrenze, bis zu dem Sie noch Aktualisierungen von Paketen akzepktieren. 
Über spezielle Einträge legen Sie das in der Datei `/etc/apt/sources.list` 
fest. Nachfolgendes Beispiel legt die Grenze auf den 25. Mai 2025, 12h00 für
die Veröffentlichung 'bookworm/main'.

----
deb http://snapshot.debian.org/archive/20250515T120000Z/debian bookworm main
----

** zwei mögliche Zeitangaben:

** exakter Zeitstempel :: Der Zeitstring `20091004T121501Z` folgt der Form 
`yyyymmddThhmmssZ` oder vereinfacht `yyyymmdd`. Steht für ein angegebenes 
Datum kein Snapshot bereit, wird der zeitlich entsprechend vorherige 
ausgewählt.

*** wofür steht das `Z` in `yyyymmddThhmmssZ` ? Für Zeitzone? Falls ja, 
welche anderen Buchstaben gehen noch?

** relativer Zeitstempel:: Angabe des Zeitstempels als ein Wert, den das 
`date`-Kommando verarbeiten kann, bspw `yesterday` (für gestern), `2-days-ago`
(für: zwei Tage alt) oder `last-week` (für letzte Woche)

----
deb http://snapshot.debian.org/archive/date/yesterday/debian bookworm main
deb http://snapshot.debian.org/archive/date/2-days-ago/debian bookworm main
deb http://snapshot.debian.org/archive/date/last-week/debian bookworm main
----

// Datei (Ende): ./praxis/snapshots/snapshots.adoc
