// Datei: ./praxis/umgang-mit-lts/umgang-mit-lts.adoc

// Baustelle: Rohtext

[[umgang-mit-lts]]

== Umgang mit LTS ==

// Stichworte für den Index
(((Veröffentlichung, Entwicklungsstand)))
(((Veröffentlichung, Langzeitunterstützung)))
(((Veröffentlichung, LTS)))
(((Veröffentlichung, oldoldstable)))

Wie wir bereits in ``Bedeutung der verschiedenen Entwicklungsstände''
(siehe <<bedeutung-der-verschiedenen-entwicklungsstaende>>) beleuchtet
haben, ist LTS eine Abkürzung und steht für 'long-term support' -- auf
deutsch 'Langzeitunterstützung'. Damit pflegt das Debianprojekt ältere
Veröffentlichungen über bis zu fünf Jahre nach dem Ende des
Releasezyklus <<Plura-lts>>. Zur Kennzeichnung einer Veröffentlichung in
diesem Entwicklungsstand benutzt Debian den Bezeichner 'oldoldstable'.

Betreiben Sie eine solche, ältere Debianinstallation, erreichen Sie
irgendwann einen Punkt, an dem keine weiteren Aktualisierungen der
verwendeten Softwarepakete mehr möglich sind. Versuchen Sie diesen
Schritt trotzdem, meldet sich der Paketmirror mit dem Fehler ``Release
file expired'' bei Ihnen zurück. Zu diesem Zeitpunkt ist die LTS-Version
``abgelaufen'', d.h. die weitere Pflege der Versionen aus dieser
Veröffentlichung durch die Paketmaintainer ist eingestellt.

// Stichworte für den Index
(((apt-get, Acquire::Check-Valid-Until)))

Können Sie die bislang verwendete Veröffentlichung nicht wechseln,
stellt sich die Frage, ob -- und wenn ja wie -- Sie die bestehende
Installation trotzdem noch weiter betreiben können. APT liefert dazu den
Schalter `Acquire::Check-Valid-Until`, mit dem Sie die Überprüfung auf
das Ende der Langzeitunterstützung überspringen und bei Bedarf auch
vollständig abschalten können.

=== Kurzzeitiges Abschalten der Gültigkeitsüberprüfung des Release Files ===

// Stichworte für den Index
(((Abschalten der Gültigkeitsüberprüfung des Release Files, einmalig)))
(((apt-get, -o)))
(((apt-get, Acquire::Check-Valid-Until)))
(((apt-get, update)))

Um die Überprüfung auf Gültigkeit des Release File einmalig zu
ignorieren, rufen Sie `apt-get` mit dem Schalter `-o
Acquire::Check-Valid-Until=false` auf. In Folge aktualisiert `apt-get`
ihre Paketdatenbank anstandslos.

.Deaktivieren der Gültigkeitsüberprüfung des Release Files beim Aufruf von `apt-get`
----
# apt-get -o Acquire::Check-Valid-Until=false update
----

Da Aptitude und `apt` den Schalter ebenfalls verstehen, können Sie den 
Aufruf somit auch mit diesen beide Werkzeugen durchführen.

=== Dauerhaftes Abschalten der Gültigkeitsüberprüfung des Release Files ===

// Stichworte für den Index
(((Abschalten der Gültigkeitsüberprüfung des Release Files, dauerhaft)))
Brauchen Sie das Abschalten häufiger -- bspw. bis zum geplanten,
tatsächlichen Versionswechsel -- legen Sie am besten eine Datei im
Verzeichnis `/etc/apt/apt.conf.d/` mit dem entsprechenden Schalter an.
Mit dem nachfolgenden Aufruf erzeugen Sie eine Datei
`/etc/apt/apt.conf.d/10no-check-valid-until` und setzen den Schalter
dauerhaft <<Stackexchange-LTS>>:

.Dauerhaftes Deaktivieren der Gültigkeitsüberprüfung des Release Files 
----
# echo "Acquire::Check-Valid-Until=False;" > /etc/apt/apt.conf.d/10no-check-valid-until
----

// Datei (Ende): ./praxis/umgang-mit-lts/umgang-mit-lts.adoc
