// Datei: ./praxis/umgang-mit-lts/umgang-mit-lts.adoc

// Baustelle: Notizen

[[umgang-mit-lts]]

== Umgang mit LTS ==

// Stichworte für den Index
(((Veröffentlichung, Entwicklungsstand)))
(((Veröffentlichung, Langzeitunterstützung)))
(((Veröffentlichung, LTS)))
(((Veröffentlichung, oldoldstable)))

Wie wir bereits in 'Bedeutung der verschiedenen Entwicklungsstände'
(siehe <<bedeutung-der-verschiedenen-entwicklungsstaende>>) beleuchtet
haben, ist LTS eine Abkürzung und steht für 'long-term support' -- auf
deutsch 'Langzeitunterstützung'. Damit pflegt das Debianprojekt ältere
Veröffentlichungen über bis zu fünf Jahre nach dem Ende des
Releasezyklus.

Betreiben Sie eine solche, ältere Debianinstallation, erreichen Sie
irgendwann einen Punkt, an dem keine weiteren Aktualisierungen der
verwendeten Softwarepakete mehr möglich sind. Versuchen Sie diesen
Schritt trotzdem, meldet sich der Paketmirror mit dem Fehler ``Release
file expired'' bei Ihnen zurück. Zu diesem Zeitpunkt ist die LTS-Version
``abgelaufen'', d.h. die weitere Pflege der Versionen der
Veröffentlichung durch die Paketmaintainer ist eingestellt.

** wie kann man die Installation trotzdem noch weiter betreiben?

=== kurzzeitig (einmalig) ===
* Aufruf von `apt-get` mit dem Schalter 'Acquire::Check-Valid-Until=false'

----
# apt-get -o Acquire::Check-Valid-Until=false update
----

* dieser Aufruf überspringt/ignoriert die Prüfung, ob das Release File
noch gültig ist

=== dauerhaft (bis zum tatsächlichen Update) ===

* anlegen eines Options-Files, um den Schalter dauerhaft zu nutzen,
bspw. in `/etc/apt/apt.conf.d/`

----
# echo "Acquire::Check-Valid-Until=False;" > /etc/apt/apt.conf.d/10no-check-valid-until
----

* Quelle: http://unix.stackexchange.com/questions/2544/how-to-work-around-release-file-expired-problem-on-a-local-mirror

// Datei (Ende): ./praxis/umgang-mit-lts/umgang-mit-lts.adoc
