// Datei: ./praxis/umgang-mit-lts/umgang-mit-lts.adoc

// Baustelle: Notizen

[[umgang-mit-lts]]

== Umgang mit LTS ==

// Stichworte für den Index
(((Veröffentlichung, Entwicklungsstand)))
(((Veröffentlichung, LTS)))
(((Veröffentlichung, oldoldstable)))

Wie bereits in 'Bedeutung der verschiedenen Entwicklungsstände'
(siehe <<bedeutung-der-verschiedenen-entwicklungsstaende>>) beleuchtet,
ist LTS eine Abkürzung und steht für 'long-term support'. Damit
unterstützt das Debianprojekt ältere Veröffentlichungen über bis zu fünf
Jahre nach dem Ende des Releasezyklus.

* der Paketmirror meldet "Release file expired" zurück
** LTS-Version ist "abgelaufen", d.h. wird nicht weiter gepflegt
** wie kann man die Installation trotzdem noch weiter betreiben?

=== kurzzeitig (einmalig) ===
* Aufruf von `apt-get` mit dem Schalter 'Acquire::Check-Valid-Until=false'

----
# apt-get -o Acquire::Check-Valid-Until=false update
----

* dieser Aufruf überspringt/ignoriert die Prüfung, ob das Release File
noch gültig ist

=== dauerhaft (bis zum tatsächlichen Update) ===

* anlegen eines Options-Files, um den Schalter dauerhaft zu nutzen,
bspw. in `/etc/apt/apt.conf.d/`

----
# echo "Acquire::Check-Valid-Until=False;" > /etc/apt/apt.conf.d/10no-check-valid-until
----

* Quelle: http://unix.stackexchange.com/questions/2544/how-to-work-around-release-file-expired-problem-on-a-local-mirror

// Datei (Ende): ./praxis/umgang-mit-lts/umgang-mit-lts.adoc
