// Datei: ./praxis/umgang-mit-lts/umgang-mit-lts.adoc

// Baustelle: Notizen

[[umgang-mit-lts]]

== Umgang mit LTS ==

// Stichworte für den Index
(((Veröffentlichung, Entwicklungsstand)))
(((Veröffentlichung, Langzeitunterstützung)))
(((Veröffentlichung, LTS)))
(((Veröffentlichung, oldoldstable)))

Wie wir bereits in 'Bedeutung der verschiedenen Entwicklungsstände'
(siehe <<bedeutung-der-verschiedenen-entwicklungsstaende>>) beleuchtet
haben, ist LTS eine Abkürzung und steht für 'long-term support' -- auf
deutsch 'Langzeitunterstützung'. Damit pflegt das Debianprojekt ältere
Veröffentlichungen über bis zu fünf Jahre nach dem Ende des
Releasezyklus <<Plura-lts>>.

Betreiben Sie eine solche, ältere Debianinstallation, erreichen Sie
irgendwann einen Punkt, an dem keine weiteren Aktualisierungen der
verwendeten Softwarepakete mehr möglich sind. Versuchen Sie diesen
Schritt trotzdem, meldet sich der Paketmirror mit dem Fehler ``Release
file expired'' bei Ihnen zurück. Zu diesem Zeitpunkt ist die LTS-Version
``abgelaufen'', d.h. die weitere Pflege der Versionen aus dieser
Veröffentlichung durch die Paketmaintainer ist eingestellt.

Können Sie die bislang verwendete Veröffentlichung nicht wechseln,
stellt sich die Frage, ob -- und wenn ja wie -- Sie die bestehende
Installation trotzdem noch weiter betreiben können. APT liefert dazu den
Schalter `Acquire::Check-Valid-Until`, mit dem Sie die Überprüfung auf
das Ende der Langzeitunterstützung überspringen und bei Bedarf auch
vollständig abschalten können.

=== Kurzzeitiges Abschalten ===

// Stichworte für den Index
(((apt-get, -o)))
(((apt-get, update)))

Um die Überprüfung auf Gültigkeit des Release File einmalig zu
ignorieren, rufen Sie `apt-get` mit dem Schalter '-o
Acquire::Check-Valid-Until=false' auf. In Folge aktualisiert `apt-get`
ihre Paketdatenbank anstandslos.

----
# apt-get -o Acquire::Check-Valid-Until=false update
----

=== Dauerhaftes Abschalten ===

(bis zum tatsächlichen Update)
* anlegen eines Options-Files, um den Schalter dauerhaft zu nutzen,
bspw. in `/etc/apt/apt.conf.d/`

----
# echo "Acquire::Check-Valid-Until=False;" > /etc/apt/apt.conf.d/10no-check-valid-until
----

* Quelle: http://unix.stackexchange.com/questions/2544/how-to-work-around-release-file-expired-problem-on-a-local-mirror

// Datei (Ende): ./praxis/umgang-mit-lts/umgang-mit-lts.adoc
