// Datei: ./werkzeuge/paketquellen-und-werkzeuge/am-besten-erreichbaren-paketmirror-finden/am-besten-erreichbaren-paketmirror-finden.adoc

// Baustelle: Rohtext

[[am-besten-erreichbaren-paketmirror-finden]]
=== Am besten erreichbaren Paketmirror finden ===

// Stichworte für den Index
(((Paketmirror, Auswahl)))
(((Paketmirror, Leistungskriterien)))
Jeder Paketmirror hat eine spezifische Leistungsfähigkeit, die sich an
den beiden Kriterien Netzanbindung und Hardwareausstattung messen lässt.
Auf diese Merkmale haben Sie zwar nur begrenzt Einfluss, steuern jedoch
über die Einträge in der Datei `/etc/apt/sources.list` (siehe
<<etc-apt-sources.list-verstehen>>), welchen verfügbaren Paketmirror Sie
benutzen.

// Stichworte für den Index
(((Debianpaket, netselect)))
(((Debianpaket, netselect-apt)))
Anstatt diese Schritte aufwendig über die Kombination einzelner
Werkzeuge wie `ping` oder `traceroute` zu ermitteln, sind hier die
beiden Programme `netselect` <<Debian-Paket-netselect>> und
`netselect-apt` <<Debian-Paket-netselect-apt>> die besseren Mittel der
Wahl. Damit finden Sie den Paketmirror heraus, der netztechnisch von
ihrem aktuellen Standort aus am besten erreichbar ist.

// Stichworte für den Index
(((Debianpaket, apt-spy)))
Bis einschließlich Debian 7 _Wheezy_ war das Programm `apt-spy`
<<Debian-Paket-apt-spy>> fester Bestandteil der Veröffentlichung. Es
wurde nicht in Debian 8 _Jessie_ übernommen, steht jedoch weiterhin für
_unstable_ zur Verfügung.

// netselect und netselect-apt
include::netselect.adoc[]

// apt-spy
include::apt-spy.adoc[]

// Datei (Ende): ./werkzeuge/paketquellen-und-werkzeuge/am-besten-erreichbaren-paketmirror-finden/am-besten-erreichbaren-paketmirror-finden.adoc
