// Datei: ./praxis/pakete-bauen-mit-checkinstall/vor-und-nachteile.adoc

// Baustelle: Notizen

=== Vor- und Nachteile ===

Erwartungsgemäß wird die Verwendung von `checkinstall` im Alltag von
Entwicklern, Paketmaintainern und Benutzern recht unterschiedlich
bewertet. 

'Entwickler' und 'Paketmaintainer' sehen das Werkzeug überwiegend
positiv -- haben Sie darüber nämlich die Möglichkeit, auszutesten, ob
sich die von Ihnen verwendete Entwicklerversion nahtlos in das
bestehende Debian-Ökosystem einspielen läßt und mit den anderen Paketen
harmoniert. Die Paketverwaltung hat eine Information darüber, daß Sie
ein zusätzliches Paket als solches installiert haben. Sollte das Paket
unerwartete Querschläger produzieren, kratzen Sie es auch wieder ohne
viel Aufwand und vorallem restefrei vom System herunter. Das erlaubt
Ihnen automatisierte Integrationstests im Rahmen der Qualitätssicherung.

Verschwiegen werden sollen jedoch nicht die Nachteile. Ein mittels
`checkinstall` generiertes und eingespieltes Paket unterläuft die
strenge Qualitätskontrolle von Debian. Die übliche Validierung durch
andere Tester und Benutzer sowie eine Erzeugung von Prüfsummen findet
ebenfalls nicht statt. Die Paketabhängigkeiten werden nur bedingt
validiert, d.h. nur auf dem System, auf dem das Paket erzeugt und
eingespielt wurde. Das Ergebnis -- sprich das erzeugte `deb`-Paket --
ist nicht unbedingt portabel und stets eins-zu-eins auf andere
Debian-Installationen übertragbar. Berichtet wird ebenfalls, daß
`checkinstall` nicht bei Programmen funktioniert, die statisch gegen die
`libc` linken, oder bei solchen, bei denen das SUID/GUID-Bit gesetzt ist
(siehe <<Drilling-Checkinstall-LinuxUser>>). Ebenso sind Probleme mit
den `preinstall`- und `postinstall`-Skripten bekannt (siehe
<<Schnober-Checkinstall-LinuxUser>>).

==== Weitere noch unbearbeitete Notizen ====

// Stichworte für den Index
(((Maintainer-Skripte, postinst)))
(((Maintainer-Skripte, preinst)))

* Vorteile:
** installiert automatisch die zusätzlichen, bisher noch nicht installierten Header-Files nach
*** stimmt das?

* Empfehlung: 
** überprüfen, ob ein Stapel Software ``baut'', sich ein Paket daraus
bauen läßt und dieses mit dem restlichen Debian-Ökosystem
zusammenarbeitet. Kann die Basis dafür sein, dann daraus ein richtiges
Paket entsprechend den Debian-Paket-Standards zu bauen.
** Nutzung nur für lokale Rechner und Einzelsysteme
(``Testinstallationen''), kein Alltagsbetrieb
** Verwendung in Kombination mit 'auto-apt' (siehe Fehlende Pakete bei Bedarf hinzufügen unter <<fehlende-pakete-bei-bedarf-hinzufuegen>>)


// Datei (Ende): ./praxis/pakete-bauen-mit-checkinstall/vor-und-nachteile.adoc
