// Datei: ./praxis/pakete-bauen-mit-checkinstall/vor-und-nachteile.adoc

// Baustelle: Notizen

=== Vor- und Nachteile ===

Erwartungsgemäß wird die Verwendung von `checkinstall` im Alltag von
Entwicklern, Paketmaintainern und Benutzern recht unterschiedlich
bewertet. 

'Entwickler' und 'Paketmaintainer' sehen das Werkzeug überwiegend
positiv -- haben Sie darüber nämlich die Möglichkeit, auszutesten, ob
sich die von Ihnen verwendete Entwicklerversion nahtlos in das
bestehende Debian-Ökosystem einspielen läßt und mit den anderen Paketen
harmoniert. Die Paketverwaltung hat eine Information darüber, daß Sie
ein zusätzliches Paket als solches installiert haben. Sollte das Paket
unerwartete Querschläger produzieren, kratzen Sie es auch wieder ohne
viel Aufwand und vorallem restefrei vom System herunter. Das erlaubt
Ihnen automatisierte Integrationstests im Rahmen der Qualitätssicherung.

* Vorteile:
** installiert automatisch die zusätzlichen, bisher noch nicht installierten Header-Files nach
*** stimmt das?

// Stichworte für den Index
(((Maintainer-Skripte, postinst)))
(((Maintainer-Skripte, preinst)))

* Nachteile:
** Paket unterläuft die Qualitätskontrolle von Debian -- die Kontrolle
findet nicht statt
** Prüfung der Paketabhängigkeiten findet nur bedingt statt, d.h.
Ergebnis ist nicht unbedingt portabel
** Das Skript funktioniert nicht bei Programmen, die statisch gegen die
Libc linken, oder bei solchen, bei denen das SUID/GUID-Bit gesetzt ist
(Quelle: <<Drilling-Checkinstall-LinuxUser>>)
** Probleme mit `preinstall`- und `postinstall`-Skripten (Quelle:
<<Schnober-Checkinstall-LinuxUser>>)
** Einschätzung aus dem Ubuntu-Wiki: ``Technisch betrachtet gilt die
Verwendung von checkinstall als "quick & dirty", da nicht alle
Möglichkeiten durch die herkömmliche Paketerstellung gegeben sind
(beispielsweise Prüfsummen, Maintainer-Skripte oder Modifikationen beim
Kompiliervorgang). Dadurch sind die mit checkinstall erstellten Pakete
von niedrigerer Qualität, als die herkömmlich Erstellten. Zur Weitergabe
sollte man deswegen unbedingt den herkömmlichen Weg vorziehen.''

* Empfehlung: 
** überprüfen, ob ein Stapel Software ``baut'', sich ein Paket daraus
bauen läßt und dieses mit dem restlichen Debian-Ökosystem
zusammenarbeitet. Kann die Basis dafür sein, dann daraus ein richtiges
Paket entsprechend den Debian-Paket-Standards zu bauen.
** Nutzung nur für lokale Rechner und Einzelsysteme
(``Testinstallationen''), kein Alltagsbetrieb
** Verwendung in Kombination mit 'auto-apt' (siehe Fehlende Pakete bei Bedarf hinzufügen unter <<fehlende-pakete-bei-bedarf-hinzufuegen>>)


// Datei (Ende): ./praxis/pakete-bauen-mit-checkinstall/vor-und-nachteile.adoc
