// Datei: ./ausblick/empfehlungen-fuer-einsteiger/empfehlungen-fuer-einsteiger.adoc

// Baustelle: Rohtext

[[ausblick-empfehlungen-fuer-einsteiger]]
=== Empfehlungen für Einsteiger ===

[[ausblick-einstieg-zur-paketverwaltung]]
==== Mit welchem Programm zur Paketverwaltung gelingt der Einstieg am leichtesten? ====

// Stichworte für den Index
(((appnr)))
(((apt)))
(((apt-cache)))
(((apt-get)))
(((aptitude)))
(((Synaptic)))
Eine richtige Antwort darauf fällt schwer, weil das a) von ihrem
Wissensstand abhängt, b) darauf basiert, welche Art von
Benutzerschnittstelle Sie bevorzugen und c) in welcher Situation Sie
sich gerade befinden, sprich: ob Sie lokal arbeiten oder auf einem
entfernten Rechner eingeloggt sind. Es macht dabei einen großen
Unterschied, ob Sie einen Desktop mit graphischer Oberfläche vor sich
haben oder bspw. über 'ssh' mit einem Server verbunden sind. Von daher
geben wir Ihnen drei Empfehlungen -- eine für die Kommandozeile, eine
für den interaktiven Textmodus und eine für die graphische
Benutzerschnittstelle.

Kommandozeile::
`apt` (siehe <<apt>>). Es ist einfach und intuitiv, schnell getippt, hat
angenehme farbliche Hervorhebungen in der Ausgabe und kann praktisch
alles, womit Sie im Alltag zu tun haben. 

Steht ihnen auf einer älteren Installation `apt` als Befehl nicht zur
Verfügung, weichen Sie auf die beiden Werkzeuge `apt-get` und
`apt-cache` aus. Die Nachteile sind dabei nur geringfügig, da `apt`
mittlerweile mit nahezu allen Unterkommandos von `apt-get` und
`apt-cache` umgehen kann. Im wesentlichen umfaßt das mehr Tippen, je
nach Aufgabe die Auswahl des passenden Programms und den Verzicht auf
farbliche Hervorhebung in der Ausgabe.

Interaktiver Textmodus::
`aptitude` (siehe <<aptitude>>). Nicht nur, weil es auch das einzige
Programm mit dieser Benutzerschnittstelle ist, sondern auch, weil es
Ihnen sehr viele Informationen und Möglichkeiten zu den einzelnen
Paketen und deren Status bietet. Diese Darstellung in der Gesamtheit auf
der Kommandozeile zu erreichen, gelingt nur mit einem Dutzend parallel
geöffneter Terminalfenster.

Graphische Benutzerschnittstelle und webbasierte Lösungen:: 
Synaptic (siehe <<gui-synaptic>>). Es bildet unserer Meinung nach das
Debian-Paketsystem am besten ab und reduziert es nicht auf einen
``App-Store''. Von webbasierten Lösungen wie Appnr (siehe
<<webbasierte-programme-appnr>>) sind wir bislang nicht überzeugt und
raten Ihnen daher nicht zu diesen.

[[ausblick-auswahl-des-installationsmediums]]
==== Installations-CD/DVD oder Netzwerkinstallation? ====

Die Ausgangsposition ist hier, ob der Rechner, auf dem Debian GNU/Linux
installiert und zukünftig gepflegt werden soll, überwiegend über eine
verläßliche Internetverbindung verfügt oder nicht. Daraus leitet sich
ab:

* falls ja, dann ist eine Netzwerkinstallation die richtige Auswahl
(Erfahrungswert). Das erleichtert insbesondere die spätere Aktualisierung.
Physische Medien oder Installationsabbilder sind hierbei nicht
vorzuhalten. Bitte beachten Sie, daß bei einer Unterbrechung der
Internetanbindung des Rechners eine Aktualisierung oder Änderung des
Paketbestands nur mit größerem Aufwand möglich ist.

* falls nein, bleibt nur die Benutzung einer oder mehrerer
Installations-CDs/DVDs oder Installationsabbilder. Diese müssen zur
späteren Installation oder Entfernung von Paketen bereitliegen, um den
Bestand der installierten Pakete konsistent zu halten. Der Rechner muss
zudem über eine Möglichkeit verfügen, die Medien oder
Installationsabbilder auch einbinden und benutzen zu können. Infrage
kommen bspw. ein CD/DVD-Laufwerk, ein USB-Port oder ein Slot für eine
Speicherkarte, auf dem sich ein Installationsabbild befindet.

// Datei (Ende): ./ausblick/empfehlungen-fuer-einsteiger/empfehlungen-fuer-einsteiger.adoc
