// Datei: ./praxis/fremdpakete-nutzen/fremdpakete-nutzen.adoc
// Baustelle: Rohtext

[[fremdpakete-nutzen]]
== Fremdpakete nutzen ==

Vielfach stehen Pakete im `deb`-Format über unterschiedlichste Quellen 
bereit, auch von privaten Webseiten und Repositories auf GitHub. Sie 
selbst dürfen das selbstverständlich auch tun. Das ist toll und vergrößert 
die Menge verfügbarer Software nochmals. Nur, wie zuverlässig sind die 
darüber bereitgestellten Pakete überhaupt? Bei eigenen Paketen wissen Sie 
es vorab, aber können Sie auch bei fremden Quellcode so sicher sein? 
Nachfolgend versuchen wir eine Antwort darauf zu geben, wie Sie am besten 
mit der Situation umgehen.

[[fremdpakete-nutzen-und-einbinden]]
=== Fremdpakete einbinden ===

// Stichworte für den Index
(((Debian Debian Free Software Guidelines (DFSG))))
(((Debian, Debian Free Software Guidelines (DFSG))))
(((DFSG)))
(((Fremdpakete einbinden)))
Ist das erlaubt? Ja, klar -- hier bestehen keine Einschränkungen. Niemand
hindert Sie daran, Software in Form von Debianpaketen einzuspielen, wenn 
Sie das möchten.

Sollten Sie das tun? Nein. Aber es geht doch. Ja klar, trotzdem sollten 
Sie das nicht einfach so machen! Falls doch, sind ein paar Regeln 
hilfreich, die die damit verbundenen Risiken minimieren. Hier folgen nun
zunächst ein paar Gründe, welche Risiken bei Fremdpaketen überhaupt 
bestehen, die ``einfach so von irgendwoher'' heruntergeladen werden:

* nicht alles, was (technisch) geht, ist auch sinnvoll und sollten Sie 
  durchführen
* Fremdpakete unterliegen keiner vorherigen Qualitätsprüfung, da kein 
  offizieller Debian-Maintainer zugeordnet ist und prüft, ob das Paket den 
  Qualitätsvorgaben der Debian-Distribution entspricht, bspw. den 
  DFSG-Richtlinien (siehe dazu <<was-ist-debian>> und 
  <<distributionsbereiche>>). Das heißt nicht, daß ein solches Paket per 
  se von minderer Qualität ist, sondern nur, daß es die Qualitätskontrolle
  von Debian nicht durchlaufen hat
* keine vorherige Prüfung auf Paketabhängigkeiten. Das Paket mag auf dem
  Buildsystem des Entwicklers funktionieren, es besteht jedoch keine
  Garantie für das Funktionieren bei regulären Veröffentlichungen
* keine Eintragung in die Liste bereitgestellter Pakete, d.h. zukünftig 
  ist mehr Arbeit für Sie als Systembetreuer notwendig. Es steht jeweils 
  eine manuelle Aktualisierung des Pakets an, sprich: alles das, was ein 
  Maintainer machen würde

Aber ich brauche dieses Paket unbedingt! Falls das der Fall ist, prüfen
Sie bitte vorab noch diese Punkte:

alternative Pakete :: schauen Sie bitte vorher noch nach Alternativen mit
den gleichen Eigenschaften oder Funktionsumfang

Bezug aus vertrauenswürdiger Quelle :: steht das Paket auf einem 
Paketmirror bereit und ist dieser vertrauenswürdig (siehe ``Paketquelle
auf Echtheit überprüfen'' in <<paketquelle-auf-echtheit-ueberpruefen>>), 
ergänzen Sie dessen Angaben zur Liste ihrer Paketquellen (siehe 
<<empfehlung-zum-ablauf-fuer-das-hinzufuegen-und-aendern-von-paketquellen>>)

Verfügbarkeit des Pakets aus einem anderen Veröffentlichungszweig :: prüfen 
Sie ebenfalls, ob ihre Software vielleicht schon in im Distributionsbereich 
'unstable' oder 'testing' liegt. Falls das nicht der Fall ist, beherzigen 
Sie die Schritte zur Aufnahme des Pakets in die Liste der offiziellen 
Pakete (siehe <<fremdpakete-nutzen-aufnahme-als-offizielles-paket>>).

[[fremdpakete-nutzen-werkzeuge]]
=== Werkzeuge ===

[[fremdpakete-nutzen-werkzeuge-dpkg]]
==== Mit `dpkg` ====

// Stichworte für den Index
(((dpkg, -i)))
(((dpkg, --install)))
(((Paket, installieren)))

Um mit Hilfe von `dpkg` Pakete lokal zu installieren, laden Sie dieses
Paket samt der dazugehörigen Prüfsumme zuvor herunter, bspw. über ihren 
Webbrowser, mittels `curl` oder auch `wget`. Nachdem Sie dieses Paket 
geprüft haben und für sauber befinden, spielen Sie dieses mittels 
`dpkg -i` 'Dateiname' ein. 

Bei einfachen Paketen ohne weitere Abhängigkeiten mag das problemlos 
gehen, praktisch und zeitgemäß ist es jedoch nicht. Je stärker das Paket 
von weiteren Paketen abhängt, umso aufwendiger wird das ganze Prozedere.
Hier greifen Ihnen `apt` und Aptitude unter die Arme und nehmen Ihnen 
potentielle Stolperfallen ab (siehe <<pakete-installieren>>).

[[fremdpakete-nutzen-werkzeuge-deb-get]]
==== Mit `deb-get` ====

// Stichworte für den Index
(((Paketverwaltung, deb-get)))

`deb-get` <<deb-get>> ist ein Werkzeug, welches dafür gedacht ist, Pakete 
von nicht-offiziellen Repositories und Webseiten zu beziehen, bspw. direkt
von GitHub. Es liegt selbst nicht als offizielles Debianpaket vor -- 
empfohlen wird der Download via `curl` bzw. `wget` von der Projektseite.

Bei der Anwendung von `deb-get install` 'Paketname' findet keine 
Authentizitätsprüfung der bezogenen Pakete statt, was in der heutigen Zeit 
als grob fahrlässig einzustufen ist. Keiner weiß, was Ihnen da als 
Software untergejubelt wird. 

Ebenso erfolgt eine Installation an der Paketverwaltung vorbei. Das halst 
Ihnen in Zukunft möglicherweise viel zusätzliche Betreuung des Pakets auf, 
insbesondere bei der Installation und Aktualisierung dieses oder anderer 
Pakete. 

Von daher raten wir Ihnen von der Benutzung von `deb-get` ab, sofern Ihnen
die Sicherheit ihrer Linuxinstallation wichtig ist.

[[fremdpakete-nutzen-werkzeuge-alien]]
==== Mit `alien` ====

// Stichworte für den Index
(((Debianpaket, alien)))
(((Paketverwaltung, alien)))
Mitunter liegt das Paket in einem anderen Paketformat vor, bspw. RPM. Das
Werkzeug `alien` wandelt diese Datei in ein `deb`-Paket um. Ausführlicher
gehen wir darauf in <<fremdformate-mit-alien-hinzufuegen>> ein.

[[fremdpakete-nutzen-aufnahme-als-offizielles-paket]]
=== Aufnahme des Pakets in die Liste der offiziellen Debianpakete ===

// Stichworte für den Index
(((Debian, Request for Package)))
(((Debianpaket, reportbug)))
(((Paket in den offiziellen Paketbestand aufnehmen)))
(((reportbug)))
(((RFP)))
Was soll ich tun, dass das von mir genutzte Paket endlich in Debian als 
offizielles Paket verfügbar wird? Wir sehen zwei Möglichkeiten zur 
Lösung:

* das Debian-Projekt lebt von der Mitwirkung vieler Menschen. Paketieren
  Sie das Paket selbst, sofern Sie diese Schritte beherrschen. 

* stellen Sie einen Request for Package (RFP) <<Debian-RFP>>, bspw. mit
  Hilfe des Werkzeugs `reportbug` <<Debian-Paket-reportbug>>.

Ein Paket geht mitunter einen recht langen Weg, bevor es den oben 
genannten Status erreicht. Der Status ist somit als Auszeichnung und 
Qualitätsmerkmal einzustufen. 

// Datei (Ende): ./praxis/fremdpakete-nutzen/fremdpakete-nutzen.adoc
