// Datei: ./praxis/fremdpakete-nutzen/fremdpakete-nutzen.adoc
// Baustelle: Notizen

[[fremdpakete-nutzen]]
== Fremdpakete nutzen ==

Vielfach stehen `deb`-Pakete über unterschiedlichste Quellen bereit, auch 
von privaten Webseiten und Repositories auf GitHub. Auch Sie dürfen das
selbstverständlich tun. Das ist toll und vergrößert die Menge verfügbarer 
Software nochmals. Nur, wie zuverlässig sind die darüber bereitgestellten 
Pakete überhaupt? Bei eigenen Paketen wissen Sie es vorab, aber können Sie
auch bei fremden Quellcode so sicher sein? Nachfolgend versuchen wir eine 
Antwort darauf zu geben, wie Sie am besten mit der Situation umgehen.

[[fremdpakete-nutzen-und-einbinden]]
=== Fremdpakete einbinden ===

// Stichworte für den Index
(((Debian Debian Free Software Guidelines (DFSG))))
(((Debian, Debian Free Software Guidelines (DFSG))))
(((DFSG)))
Ist das erlaubt? Ja, klar -- hier bestehen keine Einschränkungen. Niemand
hindert Sie daran, Software in Form von Debianpaketen einzuspielen, wenn 
Sie das möchten.

Sollten Sie das tun? Nein. Aber es geht doch. Ja klar, trotzdem sollten 
Sie das nicht machen! Hier nur ein paar Gründe, warum Fremdpakete mit 
Risiken daherkommen:

* nicht alles, was (technisch) geht, sollten Sie durchführen
* Fremdpakete unterliegen keiner vorherigen Qualitätskontrolle, da kein 
  Maintainer zugeordnet ist und prüft, ob das Paket den Qualitätsvorgaben
  von Debian entspricht, bspw. den DFSG-Richtlinien (siehe dazu 
  <<was-ist-debian>> und <<distributionsbereiche>>)
* keine vorherige Prüfung auf Paketabhängigkeiten
* keine Eintragung in die interne Paketverwaltung, d.h. zukünftig ist mehr
  Arbeit für Sie als Systembetreuer notwendig -- es steht jeweils eine 
  manuelle Aktualisierung an (alles das, was ein Maintainer machen würde)

Aber ich brauche dieses Paket unbedingt! Falls das der Fall ist, schauen
Sie bitte vorher noch nach Alternativen. Prüfen Sie ebenfalls, ob ihre 
Software vielleicht schon in im Distributionsbereich 'unstable' oder 
'testing' liegt. Falls noch nicht, beherzigen Sie die Schritte zur Aufnahme
des Pakets in die Liste der offiziellen Pakete (siehe 
<<fremdpakete-nutzen-aufnahme-als-offizielles-paket>>).

[[fremdpakete-nutzen-werkzeuge]]
=== Werkzeuge ===

[[fremdpakete-nutzen-werkzeuge-dpkg]]
==== Mit `dpkg` ====

// Stichworte für den Index
(((dpkg, -i)))
(((dpkg, --install)))
* Paket zuvor herunterladen, bspw. über den Webbrowser, mittels `curl` 
  oder `wget`
* Paket überprüfen
* falls sauber, dann das Datei/Paket mittels `dpkg -i` 'Dateiname' 
  einzuspielen

[[fremdpakete-nutzen-werkzeuge-deb-get]]
==== Mit `deb-get` ====

// Stichworte für den Index
(((Paketverwaltung, deb-get)))

* `deb-get` <<deb-get>>
* Werkzeug, welches dafür gedacht ist, Pakete von nicht-offiziellen
  Repositories und Webseiten zu beziehen
** dabei keine Authentizitätsprüfung der Pakete
** Installation an der Paketverwaltung vorbei

[[fremdpakete-nutzen-werkzeuge-alien]]
==== Mit `alien` ====

// Stichworte für den Index
(((Debianpaket, alien)))
(((Paketverwaltung, alien)))
Mitunter liegt das Paket in einem anderen Paketformat vor, bspw. RPM. Das
Werkzeug `alien` wandelt diese Datei in ein `deb`-Paket um. Ausführlicher
gehen wir darauf in <<fremdformate-mit-alien-hinzufuegen>> ein.

[[fremdpakete-nutzen-aufnahme-als-offizielles-paket]]
=== Aufnahme des Pakets in die Liste der offiziellen Debianpakete ===

// Stichworte für den Index
(((Paket in den offiziellen Paketbestand aufnehmen)))
(((Debian, Request for Package)))
(((Debianpaket, reportbug)))
(((RFP)))
(((reportbug)))
Was soll ich tun, dass das von mir genutzte Paket endlich in Debian als 
offizielles Paket verfügbar wird? Wir sehen zwei Möglichkeiten zur 
Lösung:

* das Debian-Projekt lebt von der Mitwirkung vieler Menschen. Paketieren
  Sie das Paket selbst, sofern Sie diese Schritte beherrschen. 

* stellen Sie einen Request for Package (RFP) <<Debian-RFP>>, bspw. mit
  Hilfe des Werkzeugs `reportbug` <<Debian-Paket-reportbug>>.

Ein Paket geht mitunter einen recht langen Weg, bevor es den oben 
genannten Status erreicht. Der Status ist somit als Auszeichnung und 
Qualitätsmerkmal einzustufen. 

// Datei (Ende): ./praxis/fremdpakete-nutzen/fremdpakete-nutzen.adoc
