// Datei: ./praxis/qualitaetskontrolle/bereits-installierte-pakete-mit-adequate-pruefen/adequate.adoc

// Baustelle: Rohtext

[[qualitaetskontrolle-adequate]]
=== Bereits installierte Pakete mit `adequate` prüfen ===

// Stichworte für den Index
(((adequate)))
(((adequate, Debian Policy Manual)))
(((Debianpaket, adequate)))
(((lintian)))

Im Gegensatz zu `lintian` (siehe <<bugreports-lintian>>) validieren Sie mit
`adequate` <<Debian-Paket-adequate>> die Pakete, die bereits auf ihrem
System installiert sind. `adequate` steht Ihnen ab Debian 8 'Jessie' bereit
und führt einen rigorosen Qualitätstest gemäß des Debian Policy Manuals 
<<Debian-Policy-Manual>> durch.

// Stichworte für den Index
(((adequate, --all)))
(((adequate, Paketname)))
(((adequate, --tags broken-symlink)))
(((adequate, --tags missing-copyright-file)))
(((adequate, --tags program-name-collision)))

Zur Paketanalyse versteht es die folgenden Schalter (Auswahl):

'Paketname'::
Überprüfung des von Ihnen angegebenen Debianpakets. Dieses muss dazu
bereits installiert sein.

`--all`::
Überprüfung aller Pakete, die auf ihrem Debian-System derzeit installiert 
sind.

`--tags` 'Tag1','Tag2'::
Beschränkung der Ausgabe auf die angegebenen Fehlerwerte ('Tags') zu 
'Tag1' und 'Tag2'. Alle angegebenen Fehlerwerte trennen Sie durch ein 
Komma in einer Liste.

`--tags` '-Tag1','Tag2'::
Beschränkung der Ausgabe auf die angegebenen Fehlerwerte ('Tags') *ohne* 
'Tag1' und 'Tag2'. Alle angegebenen Fehlerwerte trennen Sie durch ein
Komma in einer Liste. 

Als Tags sind zulässig <<adequateByfeld>>:

* 'bin-or-sbin-binary-requires-usr-lib-library'
* 'broken-binfmt-detector'
* 'broken-binfmt-interpreter'
* 'broken-symlink'
* 'incompatible-licenses'
* 'library-not-found'
* 'missing-alternative'
* 'missing-copyright-file'
* 'missing-symbol-version-information'
* 'obsolete-conffile'
* 'program-name-collision'
* 'py-file-not-bytecompiled'
* 'pyshared-file-not-bytecompiled'
* 'symbol-size-mismatch'
* 'undefined-symbol'

Weitere Schalter und die vollständige Liste der Tags entnehmen Sie bitte
der Manpage zum Programm.

Im ersten Beispiel sehen Sie das Ergebnis der Validierung des Pakets
'pdfstudio', welches aus einer nicht-Debian-eigenen Paketquelle stammt.
In diesem Fall hat `adequate` entdeckt, dass die Informationen zum
Copyright des Werkzeugs fehlen.

.Überprüfung des Pakets 'pdfstudio' mit Fehlermeldung
----
$ adequate pdfstudio
pdfstudio: missing-copyright-file /usr/share/doc/pdfstudio/copyright
$
----

// Stichworte für den Index
(((adequate, --all)))

Die Validierung ihres gesamten Systems erfolgt mit Hilfe des Schalters
`--all` und wird durchaus etwas mehr Zeit in Anspruch nehmen.
Nachfolgend sehen Sie einen Ausschnitt des Ergebnisses für ein
Desktopsystem auf der Basis von Debian 12 'Bookworm', welches sich bereits
über eine längere Zeit in Verwendung befindet.

.Überprüfung des gesamten Paketbestands (Ausschnitt)
----
$ adequate --all
libclang-common-15-dev: broken-symlink /usr/lib/clang/15/lib -> ../../llvm-15/lib/clang/15.0.7/lib
libclang-common-15-dev: broken-symlink /usr/lib/clang/15.0.7/lib -> ../../llvm-15/lib/clang/15.0.7/lib
unknown-horizons: broken-symlink /usr/share/unknown-horizons/content/fonts/Unifont.ttf -> ../../../fonts/truetype/unifont/unifont.ttf
moka-icon-theme: broken-symlink /usr/share/icons/Moka/16x16/apps/org.gnome.Builder.png -> builder.png
moka-icon-theme: broken-symlink /usr/share/icons/Moka/16x16/apps/org.gnome.Maps.png -> gnome-maps.png
...
$
----

// Datei (Ende): ./praxis/qualitaetskontrolle/bereits-installierte-pakete-mit-adequate-pruefen/adequate.adoc
