// Datei: ./praxis/qualitaetskontrolle/bereits-installierte-pakete-mit-adequate-pruefen/adequate.adoc

// Baustelle: Rohtext

[[qualitaetskontrolle-adequate]]
=== Bereits installierte Pakete mit `adequate` prüfen ===

// Stichworte für den Index
(((adequate)))
(((adequate, Debian Policy Manual)))
(((Debianpaket, adequate)))
(((lintian)))

Im Gegensatz zu `lintian` (siehe <<bugreports-lintian>>) validieren Sie mit
`adequate` <<Debian-Paket-adequate>> die Pakete, die bereits auf ihrem
System installiert sind. `adequate` steht Ihnen ab Debian 8 'Jessie' bereit
und führt einen rigorosen Qualitätstest gemäß des Debian Policy Manuals 
<<Debian-Policy-Manual>> durch. Es prüft dabei lediglich, ob das Paket den 
darin genannten Richtlinien folgt. Nicht gewünschte oder nicht empfohlene
Praktiken zur Paketstruktur bemängelt es nicht.

// Stichworte für den Index
(((adequate, --all)))
(((adequate, --debconf)))
(((adequate, --fail)))
(((adequate, Paketname)))
(((adequate, --tags broken-symlink)))
(((adequate, --tags missing-copyright-file)))
(((adequate, --tags program-name-collision)))

Zur Paketanalyse versteht es die folgenden Schalter (Auswahl):

'Paketname'::
Überprüfung des von Ihnen angegebenen Debianpakets. Dieses muss dazu
bereits auf ihrem System installiert sein.

`--all`::
Überprüfung aller Pakete, die auf ihrem Debian-System derzeit installiert 
sind.

`--debconf`::
Melde Auffälligkeiten via `debconf`.

`--fail`::
Beende die Validierung mit dem Rückgabewert 2, falls mindestens ein Tag ausgelöst hat.

`--tags` 'Tag1','Tag2'::
Beschränkung der Ausgabe auf die angegebenen Fehlerwerte ('Tags') zu 
'Tag1' und 'Tag2'. Alle angegebenen Fehlerwerte trennen Sie jeweils durch 
ein Komma in der Liste.

`--tags` '-Tag1','Tag2'::
Beschränkung der Ausgabe auf die angegebenen Fehlerwerte ('Tags') *ohne* 
'Tag1' und 'Tag2'. Alle angegebenen Fehlerwerte trennen Sie jeweils durch 
ein Komma in der Liste. 

Weitere Schalter entnehmen Sie bitte der Manpage zum Programm. Als Tags 
sind zulässig <<adequateByfeld>>:

`bin-or-sbin-binary-requires-usr-lib-library` :: Die Binärdatei im Verzeichnis `/bin` oder `/sbin`, die eine Bibliothek in `/usr/lib` erfordert. Es ist nicht möglich, diese Binärdatei zu benutzen, bevor das Verzeichnis `/usr` gemounted ist.

`broken-binfmt-detector` :: Der Detector, der zuvor mit `update-binfmts` registriert wurde, existiert nicht.

`broken-binfmt-interpreter` :: Der Interpreter, der zuvor mit `update-binfmts` registriert wurde, existiert nicht.

`broken-symlink` :: Ein symbolischer Link zeigt auf einen Datei, die nicht existiert.

`incompatible-licenses` :: Die Lizenzen der Bibliotheken, zu dem die Binärdatei verlinkt wurde, sind inkompatibel zueinander.

`ldd-failure` :: Der Aufruf von `ldd -r` auf die Datei ging unerwartet schief.

`library-not-found` :: Eine Bibliothek fehlt, vermutlich aufgrund eines defekten symbolischen Links.

`missing-alternative` :: Dieser Paketmanager bietet einen Terminalemulator an, aber dieser ist nicht als alternatives oder virtuelles Paket registriert.

`missing-copyright-file` :: Es wurde keine Copyright-Datei bereitgestellt.

`missing-pkgconfig-dependency` :: Die Abhängigkeit von einer Datei `pkg-config` (`.pc`) ist nicht gegeben.

`missing-symbol-version-information` :: Die Bibliothek der Binärdatei bietet nur unversionierte Symbole.

`obsolete-conffile` :: Die Konfigurationsdatei, die früher mit dem Paket geliefert wurde, ist in der aktuellen Version nicht mehr enthalten, aber die Konfigurationsdatei wurde nicht entfernt oder aktualisiert.

`program-name-collision` :: Das Paket hat den gleichen Namen Namen wie ein anderes Programm. 

`py-file-not-bytecompiled` :: Das Paket liefert Pythonmodule, die nicht byte-compiliert sind.

`pyshared-file-not-bytecompiled` :: Das Paket liefert Pythonmodule im Verzeichnis `/usr/share/pyshared` die nicht byte-compiliert sind.

`symbol-size-mismatch` :: Das Symbol hat die Größe geändert, seitdem das Paket gebaut wurde.

`undefined-symbol` :: Das Symbol konnte nicht in den Bibliotheken gefunden werden, gegen die die Binärdatei gelinkt wurde.

Im ersten Beispiel sehen Sie das Ergebnis der Validierung des Pakets
'pdfstudio', welches aus einer nicht-Debian-eigenen Paketquelle stammt.
In diesem Fall hat `adequate` entdeckt, dass die Informationen zum
Copyright des Werkzeugs fehlen.

.Überprüfung des Pakets 'pdfstudio' mit Fehlermeldung
----
$ adequate pdfstudio
pdfstudio: missing-copyright-file /usr/share/doc/pdfstudio/copyright
$
----

// Stichworte für den Index
(((adequate, --all)))

Die Validierung ihres gesamten Systems erfolgt mit Hilfe des Schalters
`--all` und wird durchaus etwas mehr Zeit in Anspruch nehmen.
Nachfolgend sehen Sie einen Ausschnitt des Ergebnisses für ein
Desktopsystem auf der Basis von Debian 12 'Bookworm', welches sich bereits
über eine längere Zeit in Verwendung befindet.

.Überprüfung des gesamten Paketbestands (Ausschnitt)
----
$ adequate --all
libclang-common-15-dev: broken-symlink /usr/lib/clang/15/lib -> ../../llvm-15/lib/clang/15.0.7/lib
libclang-common-15-dev: broken-symlink /usr/lib/clang/15.0.7/lib -> ../../llvm-15/lib/clang/15.0.7/lib
unknown-horizons: broken-symlink /usr/share/unknown-horizons/content/fonts/Unifont.ttf -> ../../../fonts/truetype/unifont/unifont.ttf
moka-icon-theme: broken-symlink /usr/share/icons/Moka/16x16/apps/org.gnome.Builder.png -> builder.png
moka-icon-theme: broken-symlink /usr/share/icons/Moka/16x16/apps/org.gnome.Maps.png -> gnome-maps.png
...
$
----

// Datei (Ende): ./praxis/qualitaetskontrolle/bereits-installierte-pakete-mit-adequate-pruefen/adequate.adoc
