// Datei: ./praxis/qualitaetskontrolle/bereits-installierte-pakete-mit-adequate-pruefen/adequate.adoc

// Baustelle: Rohtext

[[qualitaetskontrolle-adequate]]
=== Bereits installierte Pakete mit `adequate` prüfen ===

// Stichworte für den Index
(((adequate)))
(((adequate, Debian Policy Manual)))
(((Debianpaket, adequate)))
(((lintian)))

Im Gegensatz zu `lintian` (siehe <<bugreports-lintian>>) validieren Sie mit
`adequate` <<Debian-Paket-adequate>> die Pakete, die bereits auf ihrem
System installiert sind. `adequate` steht Ihnen ab Debian 8 'Jessie' bereit
und führt einen rigorosen Qualitätstest gemäß des Debian Policy Manuals 
<<Debian-Policy-Manual>> durch. Es prüft dabei lediglich, ob das Paket den 
darin genannten Richtlinien folgt. Nicht gewünschte oder nicht empfohlene
Praktiken zur Paketstruktur bemängelt es nicht.

// Stichworte für den Index
(((adequate, --all)))
(((adequate, --debconf)))
(((adequate, --fail)))
(((adequate, Paketname)))
(((adequate, --tags broken-symlink)))
(((adequate, --tags missing-copyright-file)))
(((adequate, --tags program-name-collision)))

Zur Paketanalyse versteht es die folgenden Schalter (Auswahl):

'Paketname'::
Überprüfung des von Ihnen angegebenen Debianpakets. Dieses muss dazu
bereits auf ihrem System installiert sein.

`--all`::
Überprüfung aller Pakete, die auf ihrem Debian-System derzeit installiert 
sind.

`--debconf`::
Melde Auffälligkeiten via `debconf`.

`--fail`::
Beende die Validierung mit dem Rückgabewert 2, falls mindestens ein Tag ausgelöst hat.

`--tags` 'Tag1','Tag2'::
Beschränkung der Ausgabe auf die angegebenen Fehlerwerte ('Tags') zu 
'Tag1' und 'Tag2'. Alle angegebenen Fehlerwerte trennen Sie jeweils durch 
ein Komma in der Liste.

`--tags` '-Tag1','Tag2'::
Beschränkung der Ausgabe auf die angegebenen Fehlerwerte ('Tags') *ohne* 
'Tag1' und 'Tag2'. Alle angegebenen Fehlerwerte trennen Sie jeweils durch 
ein Komma in der Liste. 

Als Tags sind zulässig <<adequateByfeld>>:

'bin-or-sbin-binary-requires-usr-lib-library' :: The binary in `/bin` or `/sbin` that requires a library in `/usr/lib`. It is impossible to use this binary before `/usr` is mounted.

'broken-binfmt-detector' :: The detector registered with `update-binfmts`(8) does not exist.

'broken-binfmt-interpreter' :: The interpreter registered with `update-binfmts`(8) does not exist.

'broken-symlink' :: A symlink points to a nonexistent file.

'incompatible-licenses' :: The licenses of the libraries the binary is linked to are incompatible.

'ldd-failure' :: Running `ldd -r` on the file failed unexpectedly.

'library-not-found' :: Library missing, possibly because of a broken symlink.

'missing-alternative' :: This package manager provides a terminal emulator, but it is not registered as an alternative or a virtual package.

'missing-copyright-file' :: No copyright file provided.

'missing-pkgconfig-dependency' :: Dependency of a `pkg-config` (`.pc`) file not provided.

'missing-symbol-version-information' :: The binary's library provides only unversioned symbols.

'obsolete-conffile' :: The conffile that previously shipped with the package is no longer included in the current version, but the conffile has not been removed or updated.

'program-name-collision' :: This package has the same name as another program.

'py-file-not-bytecompiled' :: This package ships Python modules that are not byte-compiled.

'pyshared-file-not-bytecompiled' :: This package ships Python modules in `/usr/share/pyshared` that are not byte compiled.

'symbol-size-mismatch' :: The symbol has changed size since the package was built.

'undefined-symbol' :: The symbol has not been found in the libraries linked with the binary.

Weitere Schalter entnehmen Sie bitte der Manpage zum Programm.

Im ersten Beispiel sehen Sie das Ergebnis der Validierung des Pakets
'pdfstudio', welches aus einer nicht-Debian-eigenen Paketquelle stammt.
In diesem Fall hat `adequate` entdeckt, dass die Informationen zum
Copyright des Werkzeugs fehlen.

.Überprüfung des Pakets 'pdfstudio' mit Fehlermeldung
----
$ adequate pdfstudio
pdfstudio: missing-copyright-file /usr/share/doc/pdfstudio/copyright
$
----

// Stichworte für den Index
(((adequate, --all)))

Die Validierung ihres gesamten Systems erfolgt mit Hilfe des Schalters
`--all` und wird durchaus etwas mehr Zeit in Anspruch nehmen.
Nachfolgend sehen Sie einen Ausschnitt des Ergebnisses für ein
Desktopsystem auf der Basis von Debian 12 'Bookworm', welches sich bereits
über eine längere Zeit in Verwendung befindet.

.Überprüfung des gesamten Paketbestands (Ausschnitt)
----
$ adequate --all
libclang-common-15-dev: broken-symlink /usr/lib/clang/15/lib -> ../../llvm-15/lib/clang/15.0.7/lib
libclang-common-15-dev: broken-symlink /usr/lib/clang/15.0.7/lib -> ../../llvm-15/lib/clang/15.0.7/lib
unknown-horizons: broken-symlink /usr/share/unknown-horizons/content/fonts/Unifont.ttf -> ../../../fonts/truetype/unifont/unifont.ttf
moka-icon-theme: broken-symlink /usr/share/icons/Moka/16x16/apps/org.gnome.Builder.png -> builder.png
moka-icon-theme: broken-symlink /usr/share/icons/Moka/16x16/apps/org.gnome.Maps.png -> gnome-maps.png
...
$
----

// Datei (Ende): ./praxis/qualitaetskontrolle/bereits-installierte-pakete-mit-adequate-pruefen/adequate.adoc
