// Datei: ./werkzeuge/werkzeuge-zur-paketverwaltung-ueberblick/fuer-die-kommandozeile/dpkg.adoc

// Baustelle: Fertig

[[dpkg]]

==== `dpkg` ====

// Stichworte für den Index
(((Debianpaket, dpkg)))
(((dpkg)))
`dpkg` ist das Debian-Programm für grundlegende Paketoperationen und
bildet in Bezug auf Funktionsumfang und Handhabung das Äquivalent zu
`rpm` auf RedHat-basierten Linuxsystemen. Es kürzt den Namen 'Debian
GNU/Linux package manager' ab. Im Anhang unter ``Kommandos zur
Paketverwaltung im Vergleich`` (siehe
<<kommandos-zur-paketverwaltung-im-vergleich>>) stellen wir die
verschiedenen Schalter zu den beiden Kommandos `dpkg` und `rpm`
gegenüber.

`dpkg` agiert nur mit Paketen, die schon auf ihrem Linuxsystem lokal
vorliegen -- entweder als `deb`-Datei in einem Verzeichnis oder als
bereits installiertes Paket. `dpkg` kann keine Pakete von einem
Paketmirror beziehen.

Sie erreichen `dpkg` ausschließlich über die Kommandozeile und starten
es mit diversen Schaltern und Optionen. Die wichtigsten Parameter für
den Gebrauch im Alltag sind{empty}footnote:[Weitere Optionen zu `dpkg`
entnehmen Sie bitte der Manpage zum Programm]:

// Stichworte für den Index
(((dpkg, -c)))
(((dpkg, --contents)))
(((dpkg, -l)))
(((dpkg, --list)))
(((dpkg, -L)))
(((dpkg, --listfiles)))
(((dpkg, -s)))
(((dpkg, --status)))
(((dpkg, -S)))
(((dpkg, --search)))
(((dpkg, --configure)))

* Paketliste ausgeben mittels `dpkg -l` (siehe <<liste-der-installierten-pakete-anzeigen-und-deuten>>)

* Paketstatus erfragen mit `dpkg -s` 'Paketname' (siehe <<paketstatus-erfragen>>)

* Inhalt eines installierten Pakets anzeigen mit `dpkg -L` 'Paketname' (siehe <<paketinhalte-anzeigen-apt-file>>)

* Inhalt eines nicht installierten Pakets anzeigen (siehe <<paketinhalte-anzeigen-apt-file>>) mit `dpkg -c` 'Paketname'

* Paket zu Datei finden (siehe <<paket-zu-datei-finden>>) mit `dpkg -S` 'Dateiname' und

* Pakete konfigurieren (siehe <<pakete-konfigurieren>>) (Option `--configure`)

Mit `dpkg` zeigen Sie die installierten Pakete und deren Zustand an, suchen
nach Paketinhalten und konfigurieren im Bedarfsfall ein Paket nach.

Für alle anderen Aktionen sind hingegen die Werkzeuge `apt-get` (<<apt>>),
`apt-cache`, `aptitude` (<<aptitude>>) und `apt-file` oder die 
Benutzeroberflächen via Ncurses oder GTK besser geeignet (siehe
<<ncurses-basiert>> und <<gui-zur-paketverwaltung>>). Diese fassen viele
Einzelschritte von `dpkg` zusammen und vereinfachen Ihnen die Wartung
ihres Systems erheblich.

// Datei (Ende): ./werkzeuge/werkzeuge-zur-paketverwaltung-ueberblick/fuer-die-kommandozeile/dpkg.adoc
