// Datei: ./werkzeuge/paketquellen-und-werkzeuge/am-besten-erreichbaren-paketmirror-finden/netselect/liste-generieren-lassen.adoc

// Baustelle: Rohtext

[[liste-der-paketquellen-mit-netselect-apt-generieren-lassen]]
===== Liste der Paketquellen mit `netselect-apt` generieren lassen =====

// Stichworte für den Index
(((netselect-apt, -o)))
(((netselect-apt, --outfile)))
Wie bereits in <<netselect-und-netselect-apt>> angesprochen, erzeugt
`netselect-apt` eine Datei `sources.list` im aktuellen Verzeichnis. Es
verfügt zudem über den Schalter `-o` (Langform `--outfile`), mit dem Sie
die entsprechende Ausgabedatei angeben und eine passende Liste darin
generieren lassen. `netselect-apt` akzeptiert für die Wahl der
Veröffentlichung auch Angaben wie _stable_ oder _unstable_, aber auch
die Alternativnamen der Veröffentlichung wie _Bookworm_ oder _Sid_ (siehe
``Veröffentlichungen'' in <<veroeffentlichungen>>).

// Stichworte für den Index
(((netselect-apt, -a)))
(((netselect-apt, --arch)))
(((netselect-apt, -c)))
(((netselect-apt, --country)))
(((netselect-apt, -f)))
(((netselect-apt, --ftp)))
(((netselect-apt, -n)))
(((netselect-apt, --nonfree)))
(((netselect-apt, -o)))
(((netselect-apt, --outfile)))
(((netselect-apt, -s)))
(((netselect-apt, --sources)))
Insgesamt kennt `netselect-apt` diese Schalter zur Steuerung der Liste:

`-a` (Langform `--arch`):: Erzeugung der Liste für die angegebene
Prozessorarchitektur. Eine Übersicht zu den von Debian unterstützten
Architekturen finden Sie unter ``Debian-Architekturen'' in
<<anhang-debian-architekturen>>. Geben Sie keinen Wert an, benutzt
`netselect-apt` den Wert, den `dpkg` als Architektur zurückliefert.

`-c` (Langform `--country`):: Die Einträge kommen nur aus dem
angegebenen Land.

`-f` (Langform `--ftp`):: Benutze FTP-Quellen anstatt von HTTP-Quellen.

`-n` (Langform `--nonfree`):: Ergänzung der Einträge um den
Distributionsbereich `nonfree` (siehe ``Distributionsbereiche'' in
<<distributionsbereiche>>).

`-o` (Langform `--outfile`):: Speichere die erzeugte Liste in der
angegebenen Datei.

`-s` (Langform `--sources`):: zusätzliche Erzeugung von Einträgen für
den Bezug von Quellpaketen (siehe ``Sourcepakete'' in <<sourcepakete>>
und ``Einträge für Quellpakete'' in <<eintraege-fuer-quellpakete>>).

Im nachfolgenden Beispiel kommt zunächst lediglich der Schalter `-o`
'test.list' zum Einsatz. `netselect-apt` erzeugt die Liste der
ermittelten Paketmirrors in der Datei 'test.list' im lokalen
Verzeichnis.

.Speicherung der ermittelten Paketmirrors in einer separaten Datei
----
# netselect-apt stable -o test.list
Using distribution stable.
Retrieving the list of mirrors from www.debian.org...

--2014-02-13 14:55:02--  http://www.debian.org/mirror/mirrors_full
Auflösen des Hostnamen »www.debian.org (www.debian.org)«... 5.153.231.4, 130.89.148.14, 2001:610:1908:b000::148:14, ...
Verbindungsaufbau zu www.debian.org (www.debian.org)|5.153.231.4|:80... verbunden.
HTTP-Anforderung gesendet, warte auf Antwort... 200 OK
Länge: 338381 (330K) [text/html]
In »»/tmp/netselect-apt.WrCIoS«« speichern.

100%[============================================================>] 338.381      959K/s   in 0,3s    

2014-02-13 14:55:03 (959 KB/s) - »»/tmp/netselect-apt.WrCIoS«« gespeichert [338381/338381]

Choosing a main Debian mirror using netselect.
netselect: 347 (23 active) nameserver request(s)...       
Duplicate address 218.100.43.30 (http://ftp.au.debian.org/debian/, http://mirror.waia.asn.au/debian/); keeping only under first name.
netselect: 343 (23 active) nameserver request(s)...       
Duplicate address 195.222.33.229 (http://ftp.ba.debian.org/debian/, http://mirror.debian.com.ba/debian/); keeping only under first name.
...
Running netselect to choose 10 out of 333 addresses.
...
The fastest 10 servers seem to be:

	http://artfiles.org/debian/
	http://ftp.plusline.de/debian/
	http://ftp5.gwdg.de/pub/linux/debian/debian/
	http://debian.netcologne.de/debian/
	http://ftp.uni-erlangen.de/debian/
	http://deb-mirror.de/debian/
	http://mirror.de.leaseweb.net/debian/
	http://mirror.1und1.de/debian/
	http://deb-mirror.de/debian/
	http://ftp.uni-bayreuth.de/debian/

Of the hosts tested we choose the fastest valid for HTTP:
        http://artfiles.org/debian/

Writing test.list.
Done.
#
----

Das zweite Beispiel kommt aus dem Alltag. Wir kombinieren die vier
Schalter `-c`, `-t`, `-n` und `-a`, um die besten fünf Paketmirror für
die Architektur `amd64` in Frankreich zu finden:

.Ermittlung der besten fünf Paketmirror
----
# netselect-apt -c france -t 5 -a amd64 -n stable
Using distribution stable.
Retrieving the list of mirrors from www.debian.org...

--2019-01-09 11:47:21--  http://www.debian.org/mirror/mirrors_full
Auflösen des Hostnamen »www.debian.org (www.debian.org)«... 130.89.148.14, 5.153.231.4, 2001:41c8:1000:21::21:4, ...
Verbindungsaufbau zu www.debian.org (www.debian.org)|130.89.148.14|:80... verbunden.
HTTP-Anforderung gesendet, warte auf Antwort... 302 Found
Platz: https://www.debian.org/mirror/mirrors_full[folge]
--2019-01-09 11:47:22--  https://www.debian.org/mirror/mirrors_full
Verbindungsaufbau zu www.debian.org (www.debian.org)|130.89.148.14|:443... verbunden.
HTTP-Anforderung gesendet, warte auf Antwort... 200 OK
Länge: 189770 (185K) [text/html]
In »»/tmp/netselect-apt.Kp2SNk«« speichern.

/tmp/netselect-apt.Kp2SNk     100%[================================================>] 185,32K  1,19MB/s   in 0,2s   

2019-01-09 11:47:22 (1,19 MB/s) - »»/tmp/netselect-apt.Kp2SNk«« gespeichert [189770/189770]

Choosing a main Debian mirror using netselect.
(will filter only for mirrors in country france)
netselect: 19 (19 active) nameserver request(s)...      
Duplicate address 212.27.32.66 (http://debian.proxad.net/debian/, http://ftp.fr.debian.org/debian/); keeping only under first name.
Running netselect to choose 5 out of 18 addresses.       
..................................................................................................................................
The fastest 5 servers seem to be:

	http://debian.proxad.net/debian/
	http://debian.mirror.ate.info/
	http://debian.mirrors.ovh.net/debian/
	http://ftp.rezopole.net/debian/
	http://mirror.plusserver.com/debian/debian/

Of the hosts tested we choose the fastest valid for HTTP:
        http://debian.proxad.net/debian/

Writing sources.list.
Done.
#
----

Die von `netselect-apt` erzeugte Datei enthält neben den Paketmirrors
auch eine ganze Reihe Kommentare. Diese helfen Ihnen dabei, zu
verstehen, wofür jeder einzelne Eintrag gedacht ist.

.Inhalt der automatisch generierten Liste der Paketmirrors
----
# Debian packages for stable
deb http://artfiles.org/debian/ stable main contrib
# Uncomment the deb-src line if you want 'apt-get source'
# to work with most packages.
# deb-src http://artfiles.org/debian/ stable main contrib

# Security updates for stable
deb http://security.debian.org/ stable-security main contrib
----

// Datei (Ende): ./werkzeuge/paketquellen-und-werkzeuge/am-besten-erreichbaren-paketmirror-finden/netselect/liste-generieren-lassen.adoc

