// Datei: ./praxis/aehnliche-pakete-finden/aehnliche-pakete-finden.adoc
// Baustelle: Rohtext

[[aehnliche-pakete-finden]]
== Ähnliche Pakete finden ==

=== Allgemeines ===
// Stichworte für den Index
(((ähnliche Pakete finden)))

Debian stellt über seine offziellen Paketquellen mehr als 60.000 Pakete 
bereit. Darunter befinden sich Pakete, die Werkzeuge mit ähnlicher 
Funktionalität bereitstellen, sprich: die das gleiche oder etwas ziemlich 
ähnliches machen. Diese Vielfalt an geprüfter und gepflegter Software ist
bemerkenswert.

Wir besprechen hier, wie Sie diese Pakete finden, da die Namen der Pakete 
doch recht Unterschiedlich sein können. Motivation für die Vorgehensweise 
ist die Lösung dieser Situation:

* Werkzeug A wird benutzt, löst aber ein Problem nicht vollständig, passt 
  nicht mehr zum Arbeitsablauf, kann zu wenig oder gefällt einfach nicht 
  mehr

* wie identifiziere ich im Paketbestand mögliche Alternativen B, C und D, 
  die ebenfalls über die offiziellen Paketquellen bereitstehen? Damit läßt
  sich Werkzeug A möglicherweise ersetzen

Zur Recherche stehen Ihnen mehrere Möglichkeiten zur Verfügung -- eine 
Suche anhand der Paketkategorien, der Paketabhängigkeiten, über die 
Paketbeschreibung selbst sowie über die Paketklassifikation mittels 
Debtags und über die Manpages.

=== Suche anhand der Paketkategorien ===

* Paketverwaltung hat Kategorien, in denen die Pakete einsortiert sind
* siehe <<sortierung-der-pakete-nach-verwendungszweck>>

=== Suche anhand der Paketabhängigkeiten ===

* allgemein gehaltene Abhängigkeiten, bspw. 'pdf-viewer'

=== Suche über die Paketbeschreibung ===

* Suche anhand von Begriffen bzw. Worten, die in der Paketbeschreibung 
  vorkommen

=== Suche über Debtags ===

* Debtags, siehe <<erweiterte-paketklassifikation-mit-debtags>>

=== Suche über Manpages ===

* in vielen Manpages ist ein Abschnitt enthalten, in dem auf ähnliche
  Werkzeuge verwiesen wird
* wie verläßlich ist das?
  
// Datei (Ende): ./praxis/aehnliche-pakete-finden/aehnliche-pakete-finden.adoc
