// Datei: ./praxis/aehnliche-pakete-finden/aehnliche-pakete-finden.adoc
// Baustelle: Rohtext

[[aehnliche-pakete-finden]]
== Ähnliche Pakete finden ==

=== Allgemeines ===
// Stichworte für den Index
(((ähnliche Pakete finden)))
(((Suche im Paketbestand)))

Debian stellt über seine offziellen Paketquellen derzeit mehr als 60.000 
Pakete bereit. Darunter befinden sich Pakete, die Werkzeuge mit ähnlicher 
Funktionalität bereitstellen, sprich: die das gleiche oder etwas ziemlich 
ähnliches machen, aber nur auf eine andere Art und Weise. Diese Vielfalt 
an geprüfter und gepflegter Software ist bemerkenswert.

Wir besprechen hier, wie Sie diese Pakete finden, da die Namen der Pakete 
doch recht unterschiedlich sein können. Motivation für die Vorgehensweise 
ist die Lösung dieser Situation:

* Werkzeug A wird benutzt, löst aber ein Problem nicht vollständig, passt 
  nicht mehr zum Arbeitsablauf, kann zu wenig oder gefällt einfach nicht 
  mehr

* wie identifiziere ich im Paketbestand mögliche Alternativen B, C und D, 
  die ebenfalls über die hinterlegten Paketquellen bereitstehen? Damit 
  läßt sich Werkzeug A möglicherweise vollständig durch Werkzeug B, C oder
  D ersetzen

Zur Recherche stehen Ihnen mehrere Möglichkeiten zur Verfügung -- eine 
Suche anhand der Paketkategorien, der Paketabhängigkeiten, über die 
Paketbeschreibung selbst sowie über die Paketklassifikation mittels 
Debtags und über die Manpages.

=== Suche anhand der Paketkategorien ===

Die Paketverwaltung hat die Debianpakete in verschiedene Kategorien 
einsortiert (siehe <<sortierung-der-pakete-nach-verwendungszweck>>). Für
ähnliche Pakete hilft ein Blick in die jeweilige Kategorie.

==== Über die Kommandozeile ====

// Stichworte für den Index
(((apt-cache, show)))
Schritt 1 beinhaltet, die Paketkategorie zu ermitteln, in der das Paket 
einsortiert wurde. Dazu verfügt jedes Paket in der Paketbeschreibung über
einen Eintrag zur Kategorie, das Schlüsselwort heißt `Section`. Von 
Nutzen sind hier die beiden Werkzeuge `apt-cache` und `apt` in Kombination
mit `sed`. Unerheblich ist, ob das Paket bereits installiert ist, oder 
nicht.

Nach dem Paket 'bash' suchen Sie mittels `apt-cache` und `sed` wie folgt
(*Variante 1*):

.Ermittlung der Paketkategorie mittels `apt-cache`
----
$ apt-cache show bash | sed -ne '/^Section: /{s/Section: //p;}'
shells
$
----

`sed` berücksichtigt in der Ausgabe von `apt-cache` nur die Zeilen, die mit 
der Zeichenkette `Section:` beginnen und ersetzt darin `Section:` durch 
nichts -- löscht also die Zeichenkette. Übrig bleibt die Bezeichnung der 
Paketkategorie.

// Stichworte für den Index
(((apt, show)))
*Variante 2* verwendet `apt` mit dem Unterkommando `show` in Kombination 
mit `tail` und `sed`. Der Zwischenschritt über `tail` ist hier notwendig,
da die Ausgabe von `apt` mit zusätzlichen Zeilen beginnt, die wir nicht 
benötigen. Für das Paket `cleo` sieht der Aufruf wie folgt aus:

.Ermittlung der Paketkategorie mittels `apt`
----
$ apt show cleo 2>1 | tail -n+4 | sed -ne '/^Section: /{s/Section: //p;}'
shells
$
----

* Schritt 2: Ermittlung der Pakete aus der Kategorie, hier am Beispiel 
der Kategorie 'shell'

** Variante 1: mittels `apt` (ohne Leerzeichen zwischen `~s` und der 
Kategorie), Kombination mit `tail`, `awk` und `sort`

.Alle Pakete der Kategorie 'shell' mittels `apt` ausgeben
----
$ apt list '~sshell' 2>1 | tail -n+2 | awk -F '/' '{ print $1 }' | sort -u
ash
autojump
bash
bash-completion
bash-static
bats
busybox-static
...
$
----

** Variante 2: mittels `aptitude` (zulässig ist die Schreibweise mit und 
ohne Leerzeichen zwischen `~s` und der Kategorie) und den Werkzeugen `awk`,
`sed` und `sort`

.Alle Pakete der Kategorie 'shell' mittels `aptitude` ausgeben
----
$ aptitude search '~sshell' | awk '{ print $2 }' | sed -e 's/:.*//p' | sort -u
----


==== Über eine GUI ====

Todo

==== Über einen Webbrowser ====

* Paketsuche über packages.debian.org

=== Suche anhand der Paketabhängigkeiten ===

* allgemein gehaltene Abhängigkeiten, bspw. 'pdf-viewer'

=== Suche über die Paketbeschreibung ===

* Suche anhand von Begriffen bzw. Worten, die in der Paketbeschreibung 
  vorkommen

=== Suche über Debtags ===

* Debtags, siehe <<erweiterte-paketklassifikation-mit-debtags>>

=== Suche über Manpages ===

* in vielen Manpages ist ein Abschnitt enthalten, in dem auf ähnliche
  Werkzeuge verwiesen wird
* wie verläßlich ist das?
  
// Datei (Ende): ./praxis/aehnliche-pakete-finden/aehnliche-pakete-finden.adoc
