// Datei: ./praxis/aehnliche-pakete-finden/allgemeines.adoc
// Baustelle: Rohtext

=== Allgemeines ===
// Stichworte für den Index
(((ähnliche Pakete finden)))
(((Suche im Paketbestand)))

Debian stellt über seine offziellen Paketquellen derzeit mehr als 60.000 
Pakete bereit. Darunter befinden sich Pakete, die Werkzeuge mit ähnlicher 
Funktionalität bereitstellen, sprich: die das gleiche oder etwas ziemlich 
ähnliches machen, jedoch nur auf eine andere Art und Weise. Ebenso weichen
häufig die Nutzergruppe und der Anwendungsfall voneinander ab. Bestes 
Beispiel hierzu sind Betrachter für Dokumente im PDF-Format mit den 
Vertretern Evince, Okular, MuPDF, xpdf und Zathura. Während Okular auch
mit PDF-Formularen umgehen kann, sind die anderen Werkzeuge schlanker und
beschränken sich "nur" auf die Anzeige des Dateiinhalts.

Wir besprechen hier, wie Sie diese sich ähnelnden Pakete finden, da die 
Namen der Pakete doch recht unterschiedlich sein können. Ähnliche Pakete
über den Paketnamen aufzustöbern, gelingt nicht zuverlässig. Motivation 
für die Vorgehensweise ist die Lösung dieser Situation:

* Werkzeug A wird bislang benutzt, löst aber ein Problem nicht (mehr) 
  vollständig, passt nicht mehr zum bisherigen Arbeitsablauf, hat einen 
  zu geringen Funktionsumfang oder gefällt einfach nicht mehr

* wie identifiziere ich mögliche Alternativen B, C und D, um Werkzeug A 
  möglicherweise vollständig durch eine der Alternativen zu ersetzen?

Um eine solche Entscheidung treffen zu können, setzt es sinnvolle 
Vergleichskriterien für eine Recherche voraus. Zur Verfügung stehen ihnen
mehrere Möglichkeiten -- eine Suche anhand der Paketkategorien (siehe 
<<aehnliche-pakete-finden-paketkategorien>>) oder der Paketabhängigkeiten 
(siehe <<aehnliche-pakete-finden-paketabhaengigkeiten>>), über die 
Paketbeschreibung selbst (siehe 
<<aehnliche-pakete-finden-paketbeschreibung>>) sowie mit Hilfe der
Paketklassifikation auf der Basis von Debtags (siehe 
<<aehnliche-pakete-finden-debtags>>). In manchen Fällen hilft auch das 
Studium der Manpages (siehe <<aehnliche-pakete-finden-manpages>>) und 
spezialisierter Webseiten (siehe <<aehnliche-pakete-finden-webseiten>>) 
weiter.

// Datei (Ende): ./praxis/aehnliche-pakete-finden/allgemeines.adoc
