// Datei: ./praxis/aehnliche-pakete-finden/suche-anhand-der-paketabhaengigkeiten.adoc
// Baustelle: Notizen

[[aehnliche-pakete-finden-paketabhaengigkeiten]]
=== Suche anhand der Paketabhängigkeiten ===

// Stichworte für den Index
(((ähnliche Pakete finden, Suche anhand der Paketabhängigkeiten)))
(((apt-cache)))
(((apt-rdepends, -r)))
Für jedes Debianpaket ist in der Paketbeschreibung angegeben, ob und zu 
welchen anderen Debianpaketen Abhängigkeiten bestehen, damit die volle 
Funktionstüchtigkeit gewährleistet ist. Das können konkrete Pakete sein, 
aber auch virtuelle Pakete (siehe <<virtuelle-pakete>>). Beispiele für
Letztere sind 'adventure' für Spiele, 'base' für die Basiskomponenten von
Debian GNU/Linux sowie 'pdf-viewer', welches auf eine Auswahl von 
Programmen für das Anzeigen von PDF-Dokumenten verweist. Nachfolgend 
nutzen wir das Paket 'pdf-viewer' als Grundlage für die weiteren 
Betrachtungen. Nach unserer Erfahrung besitzen Pakete, die auf den 
gleichen virtuellem Paketen aufbauen bzw. davon abhängen, eine hohe 
Ähnlichkeit zueinander.

Die Abhängigkeiten zwischen den Debianpaketen zeigen Sie u.a. mit den 
Werkzeugen `dpkg-deb`, `apt-cache`, `aptitude` und `apt-rdepends` an 
(siehe <<paketabhaengigkeiten-anzeigen>>). Unser Ziel ist, alle Pakete 
aufzulisten, die vom virtuellen Paket 'pdf-viewer' abhängen. Dieses 
Vorgehen ist unter dem Begriff 'Auflösen der umgekehrten Abhängigkeiten' 
bekannt (siehe <<paketabhaengigkeiten-anzeigen-rueckwartsabhaengigkeiten>>).

Angedacht ist hierfür der Einsatz der beiden Werkzeuge `apt-cache` und 
`apt-rdepends`. Bislang liefern `apt-cache` und `apt-rdepends` nur recht
unbefriedigende Ergebnisse.

.Ausgabe von `apt-cache` zum Paket 'pdf-viewer'
----
$ apt-cache rdepends pdf-viewer
<pdf-viewer>
$
----

.Ausgabe von `apt-rdepends` zum Paket 'pdf-viewer'
----
$ apt-rdepends -r pdf-viewer
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
pdf-viewer
  Reverse Depends: cinnamon-desktop-environment (5.6.0)
  Reverse Depends: muttprint-manual (0.73-11)
cinnamon-desktop-environment
  Reverse Depends: task-cinnamon-desktop (3.73)
task-cinnamon-desktop
  Reverse Depends: live-task-cinnamon (12.0.2)
live-task-cinnamon
muttprint-manual
$
----

// Datei (Ende): ./praxis/aehnliche-pakete-finden/suche-anhand-der-paketabhaengigkeiten.adoc
