// Datei: ./praxis/aehnliche-pakete-finden/suche-ueber-die-paketbeschreibung.adoc
// Baustelle: Rohtext

[[aehnliche-pakete-finden-paketbeschreibung]]
=== Suche über die Paketbeschreibung ===

// Stichworte für den Index
(((ähnliche Pakete finden, Suche über die Paketbeschreibung)))
(((apt-cache, search)))
(((aptitude, search)))
(((grep-available)))
Eine Suche anhand von Begriffen bzw. Worten, die in der Paketbeschreibung 
vorkommen, gelingt Ihnen mit Hilfe von `apt-cache search`, 
`aptitude search` und `grep-available`. In 
<<pakete-ueber-die-paketbeschreibung-finden>> beleuchten wir das Vorgehen
ausführlich.

Eine erfolgreiche Recherche folgt den gleichen Prinzipien, die der 
Benutzung einer Suchmaschine zugrundeliegen, jedoch in vereinfachter Form. 
Hier findet keine komplexe Vorverarbeitung ihrer Anfrage und Auswertung der
Ergebnisse im Hintergrund statt. Die Suchbegriffe formulieren Sie in der
Anfrage als reguläre Ausdrücke. 

Mit Hilfe von Parametern legen Sie eine Verfeinerung der Suche fest -- 
entweder erfolgt die Suche nur über die Kurzbeschreibung oder bezieht 
sowohl die Kurz-, als auch Langbeschreibung mit ein. Das nachfolgende 
Beispiel zeigt eine Recherche nach dem Begriff 'pdf-viewer' mittels 
`apt-cache search` und findet auch Bibliotheken. Die gesamte Ausgabe 
enthält in jeder Zeile den Paketnamen gefolgt von der Kurzbeschreibung des
Pakets. Die Ausgabe ist nicht alphabetisch sortiert.

.Suche nach dem Begriff `pdf-viewer` mit Hilfe von `apt-cache`
----
$ apt-cache search 'pdf-viewer'
atril - MATE-Dokumentenbetrachter
evince - Dokumentenbetrachter für PostScript und PDF
gv - PostScript- und PDF-Betrachter für X
libpodofo-dev - PoDoFo - Bibliothek zum Arbeiten mit dem Dateiformat PDF - Entwicklungsdateien
libpodofo-utils - PoDoFo - Bibliothek zum Arbeiten mit dem Dateiformat PDF - Dienstprogramme
libpodofo0.9.8 - PoDoFo - Bibliothek zum Arbeiten mit dem Dateiformat PDF
mupdf - Genügsamer PDF-Betrachter
okular - Universal-Dokumentenbetrachter
prerex - LaTeX/TikZ-Editor für die grafische Darstellung von Kursvoraussetzungen
qpdfview - Dokumentbetrachter mit Reitern
xpdf - Motif-basierter PDF-Reader mit der Poppler-Bibliothek
zathura-pdf-poppler - PDF-Unterstützung für zathura
apvlv - PDF viewer with Vim-like behaviour
claws-mail-pdf-viewer - PDF and PostScript attachment viewer for Claws Mail
viewpdf.app - Portable Document Format (PDF) viewer for GNUstep
$
----

// Stichworte für den Index
(((ähnliche Pakete finden, Suche über die Paketbeschreibung)))
(((apt-cache, search --names-only)))
(((apt-cache, search -n)))
Mit Hilfe der Option `-n` (Langform `--names-only`) berücksichtigt 
`apt-cache` bei der Recherche lediglich den Paketnamen. Die Basis bilden 
alle Pakete, die über die Paketlisten zugänglich sind. Zudem sorgt `sort` 
dafür, daß die Ausgabe alphabetisch aufsteigend sortiert wird.

.Spezifische Suche nach dem Begriff `pdf-viewer` mit Hilfe von `apt-cache`
----
$ apt-cache -n search 'pdf-viewer' | sort
apvlv - PDF viewer with Vim-like behaviour
atril - MATE-Dokumentenbetrachter
claws-mail-pdf-viewer - PDF and PostScript attachment viewer for Claws Mail
evince - Dokumentenbetrachter für PostScript und PDF
gv - PostScript- und PDF-Betrachter für X
mupdf - Genügsamer PDF-Betrachter
okular - Universal-Dokumentenbetrachter
qpdfview - Dokumentbetrachter mit Reitern
viewpdf.app - Portable Document Format (PDF) viewer for GNUstep
xpdf - Motif-basierter PDF-Reader mit der Poppler-Bibliothek
zathura-pdf-poppler - PDF-Unterstützung für zathura
$
----

Geht es Ihnen lediglich um eine Auflistung der Paketnamen ohne zusätzliche 
Angaben, kommen Ihnen `awk` und `sed` zu Hilfe, die die Ausgabe von 
`apt-cache` passend aufbereiten. `apt-cache` selbst bietet bislang keinen 
Schalter an, um die Ausgabe noch stärker zu begrenzen. Das nächste Beispiel 
zeigt die Einbeziehung von `awk`, wie es zunächst als Trennzeichen ` -` 
festlegt und danach lediglich die erste Spalte jeder Zeile ausgibt.

.Suche mit Begrenzung der Ausgabe auf den Paketnamen mit Hilfe von `awk`
----
$ apt-cache search -n pdf-viewer | awk -F ' -' '{ print $1 }' | sort
apvlv
atril
claws-mail-pdf-viewer
evince
gv
mupdf
okular
qpdfview
viewpdf.app
xpdf
zathura-pdf-poppler
$
----

Sagt Ihnen `sed` mehr zu, hilft der nachfolgend gezeigte Aufruf. In 
jeder Zeile der Ausgabe von `apt-cache` ersetzt `sed` alle Zeichenketten,
die mit einem Leerzeichen und einem Bindestrich beginnen, durch Nichts.

.Suche mit Begrenzung der Ausgabe auf den Paketnamen mit Hilfe von `sed`
----
$ apt-cache search -n pdf-viewer | sed -ne 's/ - .*$//p' | sort
apvlv
atril
claws-mail-pdf-viewer
evince
gv
mupdf
okular
qpdfview
viewpdf.app
xpdf
zathura-pdf-poppler
$
----
// Datei (Ende): ./praxis/aehnliche-pakete-finden/suche-ueber-die-paketbeschreibung.adoc
