// Datei: ./praxis/aehnliche-pakete-finden/suche-anhand-der-paketabhaengigkeiten.adoc
// Baustelle: Notizen

[[aehnliche-pakete-finden-paketabhaengigkeiten]]
=== Suche anhand der Paketabhängigkeiten ===

// Stichworte für den Index
(((ähnliche Pakete finden, Suche anhand der Paketabhängigkeiten)))
Für jedes Debianpaket ist in der Paketbeschreibung angegeben, ob und zu 
welchen anderen Debianpaketen Abhängigkeiten bestehen, damit die volle 
Funktionstüchtigkeit gewährleistet ist. Das können konkrete Pakete sein, 
aber auch virtuelle Pakete (siehe <<virtuelle-pakete>>). Beispiele für
Letztere sind 'adventure' für Spiele, 'base' für die Basiskomponenten von
Debian GNU/Linux sowie 'pdf-viewer', welches auf eine Auswahl von 
Programmen für das Anzeigen von PDF-Dokumenten verweist.

* welches Programm/Werkzeug erlaubt eine Suche anhand der Abhängigkeiten?

** Abhängigkeiten anzeigen: geht u.a. mit `dpkg-deb`, `apt-rdepends`, 
   `apt-cache` und `aptitude` (siehe <<paketabhaengigkeiten-anzeigen>>)

** Idee: zeige alle Pakete, die vom virtuellen Paket 'xyz' abhängen

** zu prüfen: ist eine Suche über die 'reverse dependencies' erfolgreich?
   (siehe <<paketabhaengigkeiten-anzeigen-rueckwartsabhaengigkeiten>>)

** prinzipiell bzw. unbewiesene Theorie: Pakete, die auf den gleichen 
   Paketen aufbauen bzw. davon abhängen, besitzen eine hohe Ähnlichkeit

// Datei (Ende): ./praxis/aehnliche-pakete-finden/suche-anhand-der-paketabhaengigkeiten.adoc
