// Datei: ./praxis/aehnliche-pakete-finden/suche-anhand-der-paketabhaengigkeiten.adoc
// Baustelle: Notizen

[[aehnliche-pakete-finden-paketabhaengigkeiten]]
=== Suche anhand der Paketabhängigkeiten ===

// Stichworte für den Index
(((ähnliche Pakete finden, Suche anhand der Paketabhängigkeiten)))
Für jedes Debianpaket ist in der Paketbeschreibung angegeben, ob und zu 
welchen anderen Debianpaketen Abhängigkeiten bestehen, damit die volle 
Funktionstüchtigkeit gewährleistet ist. Das können konkrete Pakete sein, 
aber auch virtuelle Pakete (siehe <<virtuelle-pakete>>). Beispiele für
Letztere sind 'adventure' für Spiele, 'base' für die Basiskomponenten von
Debian GNU/Linux sowie 'pdf-viewer', welches auf eine Auswahl von 
Programmen für das Anzeigen von PDF-Dokumenten verweist. Nachfolgend 
nutzen wir das Paket 'pdf-viewer' als Grundlage für die weiteren 
Betrachtungen.

Die Abhängigkeiten zwischen den Debianpaketen zeigen Sie u.a. mit den 
Werkzeugen `dpkg-deb`, `apt-cache`, `aptitude` und `apt-rdepends` an 
(siehe <<paketabhaengigkeiten-anzeigen>>). Unser Ziel ist, alle Pakete 
aufzulisten, die vom virtuellen Paket 'pdf-viewer' abhängen. Dieses 
Vorgehen ist unter dem Begriff 'Auflösen der umgekehrten Abhängigkeiten' 
bekannt (siehe <<paketabhaengigkeiten-anzeigen-rueckwartsabhaengigkeiten>>)
und gelingt mit Hilfe von `apt-cache` und `apt-rdepends`.

* prinzipiell bzw. unbewiesene Theorie: Pakete, die auf den gleichen 
   Paketen aufbauen bzw. davon abhängen, besitzen eine hohe Ähnlichkeit

// Datei (Ende): ./praxis/aehnliche-pakete-finden/suche-anhand-der-paketabhaengigkeiten.adoc
