// Datei: ./praxis/debian-backports/debian-backports.adoc
// Baustelle: Rohtext

[[debian-backports]]

== Backports ==

// Stichworte für den Index
(((Debian Backports)))
(((Paket, Rückportierung)))

----
Der Beitrag erschien ursprünglich unter http://www.wizards-of-foss.de/de/weblog/2013/03/08/debian-backports-verwenden/ und wurde von uns überarbeitet.
----

// Ausgangssituation

include::ausgangssituation.adoc[]

// Gegenüberstellung der verschiedenen Lösungsansätze

include::loesungsansaetze.adoc[]

// Debian Backports

include::backports-intro.adoc[]

// Welche Pakete gibt es als offiziellen Backport?

include::pakete.adoc[]

// Welche Versionen gibt es als offizielle Backports?

include::versionen.adoc[]

=== Einbindung in den Paketbestand ===

Backports sind nicht von Hause aus aktiviert und Sie müssen diese in der
Paketverwaltung explizit ergänzen. Dazu fügen Sie in der Liste der
Paketquellen unter `/etc/apt/sources.list` (siehe dazu
<<etc-apt-sources.list-verstehen>>) einen entsprechenden Eintrag für die
passenden Backports ihrer Distribution hinzu. Für Debian 8 'Jessie' und
Debian 7 'Wheezy' mit den dem Distributionsbereich 'main' sieht der
jeweilige Eintrag wie folgt aus:

.Eintrag zu Debian Backports für Debian 8 'Jessie'
----
# Backports
deb http://ftp.debian.org/debian jessie-backports main
----

.Eintrag zu Debian Backports für Debian 7 'Wheezy'
----
# Backports
deb http://httpredir.debian.org/debian wheezy-backports main
----

Wie bereits oben erwähnt, findet sich das APT-Repository für die
Backports für Debian 6 'Squeeze' in einem getrennten Spiegelnetzwerk.
Deswegen ist dort die kanonische Mirror-Adresse eine leicht andere:

.Eintrag zu Debian Backports für Debian 6 'Squeeze'
----
# Backports
deb http://httpredir.debian.org/debian-backports squeeze-backports main contrib non-free
----

Nach der Aktualisierung der Paketquellen -- bspw. mittels `apt-get
update` -- stehen Ihnen die zusätzlichen Pakete bereits zur Verfügung.
Diese werden jedoch nicht automatisch berücksichtigt und installiert,
sondern dazu bedarf es noch eines expliziten Aufrufs mit zusätzlichen
Schaltern. `apt-get` und `aptitude` benutzen dazu den Schalter `-t`
gefolgt vom Namen des Backports-Archivs.

Das Paket 'asciidoc' steht bspw. nicht für Debian 7 'Wheezy' bereit,
existiert jedoch in den Backports. Um dieses aus den Backports
nachzuziehen, geben Sie auf der Kommandozeile folgendes ein:

.Installation eines Pakets mit expliziter Angabe der Distribution 'wheezy-backports'
----
# apt-get -t wheezy-backports install asciidoc
...
#
----

Alternativ können Sie auch mittels Pinning paketweise bestimmen
(siehe <<pinning-paketweise-festlegen>>), bei welchen Paketen Backports
verwendet werden sollen.

=== Weiterführende Dokumentation ===

Die offizielle Dokumentation auf Englisch gibt es auf der
Backports-Projektseite <<Debian-Backports>>. Eine deutschsprachige
Anleitung finden Sie im Wiki von debianforum.de
<<Debianforum-Wiki-Backports>>.

=== Backports bei Ubuntu ===

// Stichworte für den Index
(((Veröffentlichung, Entwicklungsstand)))
(((Veröffentlichung, Langzeitunterstützung)))
(((Veröffentlichung, LTS)))

Auch bei Ubuntu gibt es Backports. Diese funktionieren nach ähnlichen
Regeln wie bei Debian. Da es bei Ubuntu aber keinen 'testing'-Zweig wie
bei Debian gibt und die Veröffentlichungen wesentlich häufiger
passieren, werden Backports dort üblicherweise von der aktuellen
Veröffentlichung zur vorherigen Veröffentlichung oder zur vorherigen
LTS-Veröffentlichung gemacht.

=== Wichtige Fragen, die sich bei Backports ergeben ===

* wie kommt ein Backport-Paket zustande? Sicher gibt es dazu einen definierten Arbeitsablauf
* Laufen die Pakete außerhalb des üblichen Validierungsprozesses (ähnlich wie Ubuntu PPAs)
* wann ist die Installation eines Backport-Pakets sinnvoll, wann nicht?
* kann bei Backports was schiefgehen? Wenn ja, was? Kann ich das vorher irgendwie testen?
* Gibt es Updates dazu? Pflege ich die über den üblichen `apt-get update`-Prozess ein, oder geht das anders, bspw. manuell?
** Pakete werden wie ein normales Paket ausgewählt und gepflegt
* Wie entferne ich ein Backport-Paket wieder (`apt-get remove Paketname`)?
** ja
* Oder meintest Du "Wie downgrade ich ein Backport-Paket wieder?"

// Datei (Ende): ./praxis/debian/backports/debian-backports.adoc
