// Datei: ./praxis/paketkonfiguration-sichern.adoc

// Baustelle: Notizen

[[paketkonfiguration-sichern]]
== Paketkonfiguration sichern ==

// Stichworte für den Index
(((debconf-get-selections)))
(((debconf-set-selections)))
(((Debianpaket, debconf)))
(((Debianpaket, debconf-utils)))
(((Paketkonfiguration, bestehende Konfiguration sichern)))
(((Paketkonfiguration, debconf-get-selections)))
(((Paketkonfiguration, debconf-set-selections)))
(((Paketkonfiguration, Konfiguration einspielen)))

Hier gehen wir der Frage nach, wie Sie die bestehende Paketkonfiguration
sichern und wieder einspielen, um bspw. ein System zu klonen. Alle
Informationen dazu stehen in der Debconf-Datenbank. Zum Auslesen nutzen
Sie das Werkzeug `debconf-get-selections` aus dem Paket 'debconf-utils'
<<Debian-Paket-debconf-utils>>. Ausführlicher ist der Vorgang bereits unter
'Konfiguration für alle Pakete auslesen' in 
<<konfiguration-fuer-alle-pakete-auslesen>> beschrieben.

Die Ausgabe von `debconf-get-selections` erfolgt auf der Standardausgabe
(`stdout`) und ist nachfolgend als Ausschnitt dargestellt.

.Auslesen der bestehenden Paketkonfiguration aus der Debconf-Datenbank (Ausschnitt)
----
# debconf-get-selections
...
# Nicht zugestellte E-Mails im »spool«-Verzeichnis löschen?
exim4-base	exim4/purge_spool	boolean	false
# Soll smb.conf automatisch konfiguriert werden?
samba-common	samba-common/do_debconf	boolean	true
# Schriftgröße:
# Choices: 
console-setup	console-setup/fontsize-text47	select	8x16
...
#
----

// Stichworte für den Index
(((debconf-set-selections, -c)))
(((debconf-set-selections, -v)))
(((debconf-set-selections, --checkonly)))
(((debconf-set-selections, --verbose)))

* wie spiele ich das lokal wieder ein
** `debconf-set-selections` (Paket 'debconf' <<Debian-Paket-debconf>>))
** Schalter `-c` (Langformat `--checkonly`): Eingabedatei nur auf Fehler prüfen
** Schalter `-v` (Langformat `--verbose`): ausführliche Ausgabe beim Einspielen

=== `apt-clone` ===

// Stichworte für den Index
(((apt-clone)))
(((Debianpaket, apt-clone)))
(((Ubuntupaket, apt-clone)))

* Werkzeug/Paket: 'apt-clone' 
** für Debian <<Debian-Paket-apt-clone>>
** für Ubuntu <<Ubuntu-Paket-apt-clone>>
* Projektseite im Launchpad
* Aufgabe: "Script to create state bundles"
* Kurzbeschreibung: "This package can be used to clone/restore the packages on a apt based system. It will save/restore the packages, sources.list, keyring and automatic-installed states. It can also save/restore no longer downloadable packages using dpkg-repack. "

// Datei (Ende): ./praxis/paketkonfiguration-sichern.adoc
