// Datei: ./praxis/plattenplatz-sparen-mit-der-paketverwaltung.adoc

// Baustelle: Rohtext

[[plattenplatz-sparen-mit-der-paketverwaltung]]

== Plattenplatz sparen mit der Paketverwaltung ==

Eine Installation eines Betriebssystems besteht aus vielen einzelnen 
Paketen. Um jegliche Software vorzuhalten, reicht der Speicherplatz 
nicht immer aus, d.h. ist stets in irgendeiner Form begrenzt. 
Einerseits hat das Filesystem Begrenzungen durch die Anzahl der Inodes,
andererseits hat jede Partition eine physische Grenze. Je mehr Platz 
belegt ist, um so langsamer werden die Plattenzugriffe, auch wenn
heutzutage SSDs im Alltagseinsatz dominieren. 

Durchgeführte Experimente -- d.h. das Ausprobieren von neuer Software 
-- hinterlassen ihre Spuren in Form von ``Paketresten'', die hinterher
übriggeblieben sind und trotz aller Vorkehrungen vielleicht doch nicht 
automatisch aufgeräumt wurden. Daher besprechen wir nachfolgend eine
Reihe von Lösungsmöglichkeiten mit Hilfe der Paketverwaltung, um den 
belegten Platz zu verringern. Welche davon passend sind, kann nicht
verallgemeinert werden und hängt vom konkreten Einzelfall ab.

=== Duplikate finden ===

// Stichworte für den Index
(((Debianpaket, util-linux)))
* Duplikate sind Dateien mit gleichem Namen und Inhalt
** welche Pakete legen diese an?
** wie kommen diese durch die Paketverwaltung zustande?
* Werkzeug `hardlink` aus dem Debianpaket 'util-linux' <<Debian-Paket-util-linux>>
** warum ist das besser als manuelles Suchen?
* Dateien in `/usr/share/doc/` prüfen 
* siehe <<Beckert-Blog-Hardlinking-Duplicate-Files>>

=== Pfade ausschließen ===

* `dpkg --path-exclude=…`

=== Ungenutzte Lokalisierungen entfernen ===

// Stichworte für den Index
(((Debianpaket, localepurge)))
* Paket 'localepurge' <<localepurge>>
* momentan noch beschrieben unter <<paketverwaltung-mit-eingeschraenkten-ressourcen-fuer-embedded-und-mobile-devices>>

=== Ungenutzte Bibliotheken prüfen ===

* ungenutzte Bibliotheken prüfen, denen aber das ``Automatisch installiert''-Flag fehlt 
* siehe <<Beckert-Blog-Finding-Libraries>>

=== Paketcache aufräumen ===

* siehe dazu <<paketcache-aufraeumen>>

=== Paketcache auf separater Paratition ===

* Verzeichnis `/var/cache/apt` auf tmpfs 
* siehe <<cache-verzeichnis-auf-separater-partition>>

=== Logfiles begrenzen ===

* Werkzeug `logrotate` (sollte eigentlich installiert sein)
* sorgt aber für nicht permanent wachsende Logfiles. Seine 
  Konfiguration sollte angepasst werden, wenn man manuell weitere 
  Logfiles in Anwendungen (VHosts im Apache z.B.) konfiguriert.

=== Syslog deaktivieren ===

* keinen Syslogd verwenden und Syslog nur in einen Ringbuffer 
  laufen lassen
* Default-Paket ist 'rsyslog', dieses entfernen
** bei systemd: mit `journalctl` das Log im Ringbuffer anschauen
** bei sysvinit: Paket 'busybox-syslogd' installieren und mit 
   `logread` den Inhalt des Ringbuffers anschauen.
* gehört eigentlich nicht zur Paketverwaltung... Kann man 
  entsprechend zum Kürzen wieder rauskippen

=== Die Größe der Debian-Installation verringern ===

* siehe ReduceDebian -- Reducing the size of the Debian Installation
unter Footprint unter https://wiki.debian.org/ReduceDebian
** nicht-kritische Pakete entfernen
** apt umkonfigurieren, so dass es nicht automatisch zusätzliche Pakete installiert
** Pakete durch kleinere Äquivalente ersetzen
** unnötige Pakete entfernen
** unnötige Locales entfernen, bspw. mittels localepurge
** unnötige Kernelmodule entfernen

=== Mittels Bleachbit aufräumen ===

// Stichworte für den Index
(((Bleachbit)))
* bleachbit <<bleachbit>>

// Datei (Ende): ./praxis/plattenplatz-sparen-mit-der-paketverwaltung.adoc
