// Datei: ./praxis/plattenplatz-sparen-mit-der-paketverwaltung.adoc

// Baustelle: Notizen

[[plattenplatz-sparen-mit-der-paketverwaltung]]

== Plattenplatz sparen mit der Paketverwaltung ==

Eine Installation eines Betriebssystems besteht aus vielen einzelnen 
Paketen. Um jegliche Software vorzuhalten, reicht der Speicherplatz 
nicht immer aus, d.h. ist stets in irgendeiner Form begrenzt. 
Einerseits hat das Filesystem Begrenzungen durch die Anzahl der Inodes,
andererseits hat jede Partition eine physische Grenze. Je mehr Platz 
belegt ist, um so langsamer werden die Plattenzugriffe, auch wenn
heutzutage SSDs im Alltagseinsatz dominieren. 

Durchgeführte Experimente -- d.h. das Ausprobieren von neuer Software 
-- hinterlassen ihre Spuren in Form von ``Paketresten'', die hinterher
übriggeblieben sind und trotz aller Vorkehrungen vielleicht doch nicht 
automatisch aufgeräumt wurden. Daher besprechen wir nachfolgend eine
Reihe von Lösungsmöglichkeiten mit Hilfe der Paketverwaltung, um den 
belegten Platz zu verringern. Welche davon passend sind, kann nicht
verallgemeinert werden und hängt vom konkreten Einzelfall ab.



* Lösungsmöglichkeiten
** Hardlink über `/usr/share/doc/` laufen lassen <<Beckert-Blog-Hardlinking-Duplicate-Files>>
** `dpkg --path-exclude=…`
** Paket 'localepurge', momentan noch unter <<paketverwaltung-mit-eingeschraenkten-ressourcen-fuer-embedded-und-mobile-devices>>
** Ungenutzte Bibliotheken, denen aber das ``Automatisch installiert''-Flag fehlt <<Beckert-Blog-Finding-Libraries>>
** den Paketcache aufräumen (siehe <<paketcache-aufraeumen>>)
** Auch `/var/cache/apt` auf tmpfs gehört hier erwähnt, momentan unter <<cache-verzeichnis-auf-separater-partition>>
** `logrotate` (sollte eigentlich installiert sein, sorgt aber für nicht
  permanent wachsende Logfiles. Seine Konfiguration sollte angepasst
  werden, wenn man manuell weitere Logfiles in Anwendungen (VHosts im
  Apache z.B.) konfiguriert.
** Keinen Syslogd (Default-Paket ist 'rsyslog', dieses entfernen)
  verwenden und das Syslog nur in einen Ringbuffer laufen lassen.
*** Hat man systemd, kann man mit `journalctl` das Log im Ringbuffer
   anschauen.
*** Hat man sysvinit, so kann man das Paket 'busybox-syslogd'
   installieren und mit `logread` den Inhalt des Ringbuffers
   anschauen.
*** Gehört eigentlich nicht zur Paketverwaltung... Kann man
   entsprechend zum Kürzen wieder rauskippen.
** siehe ReduceDebian -- Reducing the size of the Debian Installation
unter Footprint unter https://wiki.debian.org/ReduceDebian
*** nicht-kritische Pakete entfernen
*** apt umkonfigurieren, so dass es nicht automatisch zusätzliche Pakete installiert
*** Pakete durch kleinere Äquivalente ersetzen
*** unnötige Pakete entfernen
*** unnötige Locales entfernen, bspw. mittels localepurge
*** unnötige Kernelmodule entfernen
** bleachbit benutzen (https://www.bleachbit.org/)

// Datei (Ende): ./praxis/plattenplatz-sparen-mit-der-paketverwaltung.adoc
