// Datei: ./praxis/plattenplatz-sparen-mit-der-paketverwaltung.adoc

// Baustelle: Rohtext

[[plattenplatz-sparen-mit-der-paketverwaltung]]

== Plattenplatz sparen mit der Paketverwaltung ==

Eine Installation eines Betriebssystems besteht aus vielen einzelnen 
Paketen. Um jegliche Software vorzuhalten, reicht der Speicherplatz 
nicht immer aus, d.h. ist stets in irgendeiner Form begrenzt. 
Einerseits hat das Filesystem Begrenzungen durch die Anzahl der Inodes,
andererseits hat jede Partition eine physische Grenze. Je mehr Platz 
belegt ist, um so langsamer werden die Plattenzugriffe, auch wenn
heutzutage SSDs im Alltagseinsatz dominieren. 

Durchgeführte Experimente -- d.h. das Ausprobieren von neuer Software 
-- hinterlassen ihre Spuren in Form von ``Paketresten'', die hinterher
übriggeblieben sind und trotz aller Vorkehrungen vielleicht doch nicht 
automatisch aufgeräumt wurden. Daher besprechen wir nachfolgend eine
Reihe von Lösungsmöglichkeiten mit Hilfe der Paketverwaltung, um den 
belegten Platz zu verringern. Welche davon passend sind, kann nicht
verallgemeinert werden und hängt vom konkreten Einzelfall ab.

=== Duplikate finden ===

// Stichworte für den Index
(((Debianpaket, util-linux)))
(((Identische Dateien finden)))
Als Duplikate gelten Dateien mit gleichem Namen und Inhalt. Wenn auch
eher selten, aber doch vorkommend, bringen unterschiedliche Pakete 
gleiche Dateien mit. Kandidaten dafür finden sich bspw. im Verzeichnis
`/usr/share/doc/` (siehe <<Beckert-Blog-Hardlinking-Duplicate-Files>>)
und umfassen Dokumentation und Logfiles.

** welche Pakete legen diese an?
** wie kommen diese durch die Paketverwaltung zustande?

Es spricht prinzipiell nichts gegen das manuelle Suchen -- es nimmt
nur mehr Zeit in Anspruch, als Hilfsmittel zur Automatisierung. Ins
Spiel kommt hier das Werkzeug `hardlink` aus dem Debianpaket 
'util-linux' <<Debian-Paket-util-linux>>, welches genau diese Aufgabe
übernimmt.

Es ersetzt Kopien einer Datei entweder durch harte Links oder durch 
Kopieren-beim-Schreiben-Clones ('copy-on-write clones'). Die Basis 
bildet ein Binärbaum aus Dateigrößen. Anschließend vergleicht es den 
Inhalt von den Dateien mit gleicher Größe. Dabei berechnet es 
entweder Checksummen (wie SHA256) oder verwendet die Methode 'memcmp'.
Hierbei liest es Datenblöcke direkt aus den Dateien und vergleicht 
sie miteinander.

// Stichworte für den Index
(((hardlink, --dry-run)))
(((hardlink, --ignore-time)))
(((hardlink, --method)))
(((hardlink, --verbose)))
(((hardlink, -n)))
(((hardlink, -t)))
(((hardlink, -v)))
(((hardlink, -y)))

Als Schalter kennt `hardlink` bspw. diese hier:

`-n` (Langform `--dry-run`) :: Trockendurchlauf, d.h. nur so tun als ob

`-t` (Langform `--ignore-time`) :: verlinkt und vergleicht Dateien 
selbst dann, wenn deren Änderungszeiten, unterschiedlich sind

`-v` (Langform `--verbose`) :: ausführliche Ausgabe; kann mehrfach
angegeben werden, um mehr Details zu erhalten

`-y` (Langform `--method`) :: Methode zum Dateivergleich auswählen,
bspw. 'sha1', 'sha256', 'crc32c' und 'memcmp'. Default ist 'sha256'

Im nachfolgenden Beispiel durchforstet `hardlink` das Verzeichnis 
`/usr/share/doc` und würde rund 100 MB Speicherplatz durch das 
Verlinken inhaltlich identischer Dateien einsparen. Das ist schon
ein vielversprechendes Ergebnis.

.Aufruf von `hardlink` (Auszug)
----
$ hardlink -tnv /usr/share/doc
[DryRun] Linking /usr/share/doc/libboost-iostreams1.74.0/copyright to /usr/share/doc/libboost-thread1.74.0/copyright (-1,96 MiB)
[DryRun] Linking /usr/share/doc/libboost-iostreams1.74.0/copyright to /usr/share/doc/libboost1.74-dev/copyright (-1,96 MiB)
[DryRun] Linking /usr/share/doc/libgnutls-dane0/changelog.gz to /usr/share/doc/libgnutls30/changelog.gz (-352,26 KiB)
[DryRun] Linking /usr/share/doc/libpcre2-8-0/changelog.gz to /usr/share/doc/libpcre2-16-0/changelog.gz (-45,9 KiB)
[DryRun] Linking /usr/share/doc/libpcre2-8-0/changelog.gz to /usr/share/doc/libpcre2-32-0/changelog.gz (-45,9 KiB)
Mode:                     dry-run
Method:                   sha256
Files:                    30138
Linked:                   2616 files
Compared:                 0 xattrs
Compared:                 62622 files
Saved:                    97,43 MiB
Duration:                 0.388422 seconds
$
----

[[plattenplatz-sparen-mit-der-paketverwaltung-pfade-ausschliessen]]
=== Pfade ausschließen ===
// Stichworte für den Index
(((dpkg, --path-exclude)))

* `dpkg --path-exclude=…`
* schließt bei der Installation eines Paketes Dateien aus, die 
  sonst mit in dieses Verzeichnis kopiert werden würden

.Alle Copyright-Dateien ausschließen
----
$ dpkg -i paket.deb --path-exclude=/usr/share/doc/*/copyright
----

[[plattenplatz-sparen-mit-der-paketverwaltung-lokalisierungen]]
=== Ungenutzte Lokalisierungen entfernen ===

// Stichworte für den Index
(((Debianpaket, localepurge)))

Hierbei nützt Ihnen das Paket 'localepurge' <<localepurge>>. Dieses
beschreiben wir ausführlicher unter <<mobile-geraete-localepurge>>.

[[plattenplatz-sparen-mit-der-paketverwaltung-ungenutzte-bibliotheken]]
=== Ungenutzte Bibliotheken prüfen ===

* ungenutzte Bibliotheken prüfen, denen aber das ``Automatisch installiert''-Flag fehlt 

* siehe <<Beckert-Blog-Finding-Libraries>>

[[plattenplatz-sparen-mit-der-paketverwaltung-paketcache-aufraeumen]]
=== Paketcache aufräumen ===

* siehe dazu <<paketcache-aufraeumen>>

[[plattenplatz-sparen-mit-der-paketverwaltung-paketcache-separat]]
=== Paketcache auf separater Paratition ===

* Verzeichnis `/var/cache/apt` auf tmpfs 

* siehe <<cache-verzeichnis-auf-separater-partition>>

[[plattenplatz-sparen-mit-der-paketverwaltung-logfiles-begrenzen]]
=== Logfiles begrenzen ===

* Werkzeug `logrotate` (sollte eigentlich installiert sein)

* sorgt aber für nicht permanent wachsende Logfiles. Seine 
  Konfiguration sollte angepasst werden, wenn man manuell weitere 
  Logfiles in Anwendungen (VHosts im Apache z.B.) konfiguriert.

[[plattenplatz-sparen-mit-der-paketverwaltung-syslog-deaktivieren]]
=== Syslog deaktivieren ===

* keinen Syslogd verwenden und Syslog nur in einen Ringbuffer 
  laufen lassen

* Default-Paket ist 'rsyslog', dieses entfernen
** bei systemd: mit `journalctl` das Log im Ringbuffer anschauen
** bei sysvinit: Paket 'busybox-syslogd' installieren und mit 
   `logread` den Inhalt des Ringbuffers anschauen.

* gehört eigentlich nicht zur Paketverwaltung... Kann man 
  entsprechend zum Kürzen wieder rauskippen

[[plattenplatz-sparen-mit-der-paketverwaltung-debian-installation]]
=== Die Größe der Debian-Installation verringern ===

Eine übliche Installation von Debian GNU/Linux für den Desktop kann 
durchaus mehr als 2000 Pakete umfassen. Um den "Fußabdruck" kleiner
zu machen, bleibt nur, von Anfang an konsequent zu sein:

* installieren Sie nur die Pakete, die Sie tatsächlich benötigen und auch benutzen
* identifizieren Sie unnötige Pakete und entfernen Sie diese, sofern das möglich ist
* vermeiden Sie `tasksel` (siehe <<tasksel>>), auch wenn das Werkzeug noch so toll ist und wählen stattdessen die Pakete aus, die Sie wirklich benötigen

Eine vollständigere Liste beinhaltet der Abschnitt ReduceDebian im 
Debian Wiki <<ReduceDebian>>. Diese Liste rät u. a. zu den folgenden 
Schritten:

* nicht-kritische Pakete entfernen
* Apt umkonfigurieren, so dass es nicht automatisch zusätzliche Pakete installiert
* Pakete durch kleinere Äquivalente ersetzen
* unnötige Pakete entfernen
* unnötige Spracheinstellungen (Locales) entfernen, bspw. mittels `localepurge` (siehe <<plattenplatz-sparen-mit-der-paketverwaltung-lokalisierungen>>)
* unnötige Kernelmodule entfernen
* einen kleineren, spezifischeren Kernel bauen

Stehen Softwaretests an, hilft es, diese in Virtuelle Maschinen oder 
Container auszulagern. Damit verringert sich der Ballast, der später 
vielleicht wieder aufgeräumt werden muss, sollte die gerade ausprobierte
Software doch nicht ihren Erwartungen entsprechen.

[[plattenplatz-sparen-mit-der-paketverwaltung-bleachbit]]
=== Mittels Bleachbit aufräumen ===

// Stichworte für den Index
(((Bleachbit)))
(((Debianpaket, bleachbit)))
* bleachbit <<bleachbit>>

* "with BleachBit you can free cache, delete cookies, clear Internet history, shred temporary files, delete logs, and discard junk you didn't know was there. Designed for Linux and Windows systems, it wipes clean thousands of applications including Firefox, Adobe Flash, Google Chrome, Opera, and more."

// Datei (Ende): ./praxis/plattenplatz-sparen-mit-der-paketverwaltung.adoc
