// Datei: ./praxis/plattenplatz-sparen-mit-der-paketverwaltung.adoc

// Baustelle: Rohtext

[[plattenplatz-sparen-mit-der-paketverwaltung]]
== Plattenplatz sparen mit der Paketverwaltung ==

// Stichworte für den Index
(((Belegten Festplattenplatz minimieren)))
Eine Installation eines Betriebssystems besteht aus vielen einzelnen 
Paketen. Um jegliche Software vorzuhalten, reicht der Speicherplatz 
nicht immer aus, d.h. ist stets in irgendeiner Form begrenzt. 
Einerseits hat das Filesystem Begrenzungen durch die Anzahl der Inodes,
andererseits hat jede Partition eine physische Grenze. Je mehr Platz 
belegt ist, um so langsamer werden die Plattenzugriffe, auch wenn
heutzutage SSDs im Alltagseinsatz dominieren. 

Durchgeführte Experimente -- d.h. das Ausprobieren von neuer Software 
-- hinterlassen ihre Spuren in Form von ``Paketresten'', die hinterher
übriggeblieben sind und trotz aller Vorkehrungen vielleicht doch nicht 
automatisch aufgeräumt wurden. Daher besprechen wir nachfolgend eine
Reihe von Lösungsmöglichkeiten mit Hilfe der Paketverwaltung, um den 
belegten Speicherplatz zu verringern. Welche davon passend sind, kann 
nicht verallgemeinert werden und hängt von ihrem konkreten Einzelfall 
ab.

=== Duplikate finden ===

// Stichworte für den Index
(((Debianpaket, util-linux)))
(((Identische Dateien finden)))
Als Duplikate gelten Dateien mit gleichem Namen und Inhalt. Wenn auch
eher selten, aber doch vorkommend, bringen unterschiedliche Pakete 
inhaltlich gleiche Dateien mit. Kandidaten dafür finden sich bspw. im 
Verzeichnis `/usr/share/doc/` (siehe 
<<Beckert-Blog-Hardlinking-Duplicate-Files>>) und umfassen Lizenzen, 
Dokumentation und Logfiles.

Es spricht prinzipiell nichts gegen das manuelle Suchen -- es nimmt nur 
mehr Zeit in Anspruch, als wenn Sie ein geeignetes Hilfsmittel zur 
Automatisierung einzusetzen. Ins Spiel kommt hier das Werkzeug 
`hardlink` aus dem Debianpaket 'util-linux' <<Debian-Paket-util-linux>>, 
welches genau diese Aufgabe übernimmt.

Es ersetzt Kopien einer Datei entweder durch harte Links oder durch 
Kopieren-beim-Schreiben-Clones ('copy-on-write clones'). Die Basis 
bildet ein Binärbaum aus Dateigrößen. Anschließend vergleicht es den 
Inhalt von den Dateien mit gleicher Größe. Dabei berechnet es 
entweder Checksummen (wie SHA256) oder verwendet die Methode 'memcmp'.
Hierbei liest es Datenblöcke direkt aus den Dateien, vergleicht sie 
miteinander.

// Stichworte für den Index
(((hardlink, --dry-run)))
(((hardlink, --ignore-time)))
(((hardlink, --method)))
(((hardlink, --verbose)))
(((hardlink, -n)))
(((hardlink, -t)))
(((hardlink, -v)))
(((hardlink, -y)))

Als Schalter kennt `hardlink` bspw. diese hier:

`-n` (Langform `--dry-run`) :: Trockendurchlauf, d.h. nur so tun als ob

`-t` (Langform `--ignore-time`) :: verlinkt und vergleicht Dateien 
selbst dann, wenn deren Änderungszeiten, unterschiedlich sind

`-v` (Langform `--verbose`) :: ausführliche Ausgabe; kann mehrfach
angegeben werden, um mehr Details zu erhalten

`-y` (Langform `--method`) :: Methode zum Dateivergleich auswählen,
bspw. 'sha1', 'sha256', 'crc32c' und 'memcmp'. Default ist 'sha256'

Im nachfolgenden Beispiel durchforstet `hardlink` das Verzeichnis 
`/usr/share/doc` und würde rund 100 MB Speicherplatz durch das 
Verlinken inhaltlich identischer Dateien einsparen. Das ist schon ein 
vielversprechendes Ergebnis.

.Aufruf von `hardlink` (Auszug)
----
$ hardlink -tnv /usr/share/doc
[DryRun] Linking /usr/share/doc/libboost-iostreams1.74.0/copyright to /usr/share/doc/libboost-thread1.74.0/copyright (-1,96 MiB)
[DryRun] Linking /usr/share/doc/libboost-iostreams1.74.0/copyright to /usr/share/doc/libboost1.74-dev/copyright (-1,96 MiB)
[DryRun] Linking /usr/share/doc/libgnutls-dane0/changelog.gz to /usr/share/doc/libgnutls30/changelog.gz (-352,26 KiB)
[DryRun] Linking /usr/share/doc/libpcre2-8-0/changelog.gz to /usr/share/doc/libpcre2-16-0/changelog.gz (-45,9 KiB)
[DryRun] Linking /usr/share/doc/libpcre2-8-0/changelog.gz to /usr/share/doc/libpcre2-32-0/changelog.gz (-45,9 KiB)
Mode:                     dry-run
Method:                   sha256
Files:                    30138
Linked:                   2616 files
Compared:                 0 xattrs
Compared:                 62622 files
Saved:                    97,43 MiB
Duration:                 0.388422 seconds
$
----

[[plattenplatz-sparen-mit-der-paketverwaltung-pfade-ausschliessen]]
=== Pfade ausschließen ===
// Stichworte für den Index
(((dpkg, --path-exclude)))
(((Paket installieren, Dateien und Verzeichnisse ausschließen)))
Wissen Sie bereits vorab, welche Komponenten oder Bereiche eines 
Pakets Sie nicht benötigen, schließen Sie Pfade oder Verzeichnisse
bei der Installation eines Paketes aus. Dafür bringt `dpkg` den 
Schalter `--path-exclude` mit. Die Dateien, die sich im Paket in
diesem Verzeichnis befinden, werden nicht mit extrahiert. Der
nachfolgende Aufruf demonstriert das beispielhaft und schließt alle 
Dateien namens `copyright` aus, die sich in den Unterverzeichnissen 
von `/usr/share/doc/` befinden.

.Alle Copyright-Dateien ausschließen
----
$ dpkg -i paket.deb --path-exclude=/usr/share/doc/*/copyright
----

WARNING: Geben Sie diesem Aufruf das falsche Verzeichnis mit, können 
Sie damit ihr System schwer schädigen. Installierte Programme oder 
Bibliotheken sind dann unvollständig und funktionieren nicht wie 
vorgesehen.

[[plattenplatz-sparen-mit-der-paketverwaltung-lokalisierungen]]
=== Ungenutzte Lokalisierungen entfernen ===

// Stichworte für den Index
(((Debianpaket, localepurge)))
(((localepurge)))
(((Ungenutzte Lokalisierungen entfernen)))
Hierbei nützt Ihnen das Werkzeug `localepurge` aus dem gleichnamigen
Paket <<Debian-Paket-localepurge>>. Auf dieses gehen wir ausführlicher 
in <<mobile-geraete-localepurge>> ein.

[[plattenplatz-sparen-mit-der-paketverwaltung-ungenutzte-bibliotheken]]
=== Ungenutzte Bibliotheken prüfen ===

// Stichworte für den Index
(((apt-mark, showauto)))
(((aptitude, search)))
(((aptitude, show)))
(((Paketmarkierungen, automatic)))
(((Ungenutzte Bibliotheken entfernen)))

Möchten Sie alle Pakete anzeigen, die das Flag ``Automatisch installiert'' 
tragen, helfen Ihnen die beiden Aufrufe `aptitude show` 'Paketname' (siehe 
<<lokale-paketmarkierungen-aptitude>>) und `apt-mark showauto` (siehe 
<<lokale-paketmarkierungen-apt-mark>>). Geht es hingegen um ungenutzte 
Bibliotheken, die installiert sind, aber denen das Flag fehlt, ist der 
Aufruf etwas trickreicher (siehe <<Beckert-Blog-Finding-Libraries>>). 

Für die bloße Auflistung aus Installationsstatus, Paketname und 
Kurzbeschreibung nutzen Sie diesen Aufruf:

.Ungenutzte Bibliotheken ausgeben
----
$ aptitude search '( ^lib !-dev$ !-dbg$ !-utils$ !-tools$ !-bin$ !-doc$ !^libreoffice | -data$ | -common$ | -base$ !^r-base ) !~M ~i'
i   cron-daemon-common       - Daemon für die Zeitplanung von Prozessen - Konfigurationsdateien 
i   exim4-base               - Support-Dateien für alle Exim-MTA-(v4)-Pakete                    
i   filezilla-common         - Architekturunabhängige Dateien für FileZilla                     
i   gcc-12-base              - GCC, die GNU Compiler Collection (Basis-Paket)                   
i   grub-common              - GRand Unified Bootloader 2 (gemeinsame Dateien)                  
i   isc-dhcp-common          - Handbuchseiten mit Bedeutung für alle »ISC DHCP«-Pakete          
i   libacl1                  - access control lists - Laufzeitbibliothek                        
i   libapparmor1             - AppArmor - »Change Hat«-Bibliothek                               
i   libapt-pkg6.0            - Laufzeitbibliothek zur Paketverwaltung                           
i   libargon2-1              - Speicherfeste Hash-Funktion - Laufzeitbibliothek
...
$
----

[[plattenplatz-sparen-mit-der-paketverwaltung-paketcache-aufraeumen]]
=== Paketcache aufräumen ===

* siehe dazu <<paketcache-aufraeumen>>

[[plattenplatz-sparen-mit-der-paketverwaltung-paketcache-separat]]
=== Paketcache auf separater Paratition ===

* Verzeichnis `/var/cache/apt` auf tmpfs 

* siehe <<cache-verzeichnis-auf-separater-partition>>

[[plattenplatz-sparen-mit-der-paketverwaltung-logfiles-begrenzen]]
=== Logfiles begrenzen ===

* Werkzeug `logrotate` (sollte eigentlich installiert sein)

* sorgt aber für nicht permanent wachsende Logfiles. Seine 
  Konfiguration sollte angepasst werden, wenn man manuell weitere 
  Logfiles in Anwendungen (VHosts im Apache z.B.) konfiguriert.

[[plattenplatz-sparen-mit-der-paketverwaltung-syslog-deaktivieren]]
=== Syslog deaktivieren ===

* keinen Syslogd verwenden und Syslog nur in einen Ringbuffer 
  laufen lassen

* Default-Paket ist 'rsyslog', dieses entfernen
** bei systemd: mit `journalctl` das Log im Ringbuffer anschauen
** bei sysvinit: Paket 'busybox-syslogd' installieren und mit 
   `logread` den Inhalt des Ringbuffers anschauen.

* gehört eigentlich nicht zur Paketverwaltung... Kann man 
  entsprechend zum Kürzen wieder rauskippen

[[plattenplatz-sparen-mit-der-paketverwaltung-debian-installation]]
=== Die Größe der Debian-Installation verringern ===

Eine übliche Installation von Debian GNU/Linux für den Desktop kann 
durchaus mehr als 2000 Pakete umfassen. Um den "Fußabdruck" kleiner
zu machen, bleibt nur, von Anfang an konsequent zu sein:

* installieren Sie nur die Pakete, die Sie tatsächlich benötigen und auch benutzen
* identifizieren Sie unnötige Pakete und entfernen Sie diese, sofern das möglich ist
* vermeiden Sie `tasksel` (siehe <<tasksel>>), auch wenn das Werkzeug noch so toll ist und wählen stattdessen die Pakete aus, die Sie wirklich benötigen

Eine vollständigere Liste beinhaltet der Abschnitt ReduceDebian im 
Debian Wiki <<ReduceDebian>>. Diese Liste rät u. a. zu den folgenden 
Schritten:

* nicht-kritische Pakete entfernen
* Apt umkonfigurieren, so dass es nicht automatisch zusätzliche Pakete installiert
* Pakete durch kleinere Äquivalente ersetzen
* unnötige Pakete entfernen
* unnötige Spracheinstellungen (Locales) entfernen, bspw. mittels `localepurge` (siehe <<plattenplatz-sparen-mit-der-paketverwaltung-lokalisierungen>>)
* unnötige Kernelmodule entfernen
* einen kleineren, spezifischeren Kernel bauen

Stehen Softwaretests an, hilft es, diese in Virtuelle Maschinen oder 
Container auszulagern. Damit verringert sich der Ballast, der später 
vielleicht wieder aufgeräumt werden muss, sollte die gerade ausprobierte
Software doch nicht ihren Erwartungen entsprechen.

[[plattenplatz-sparen-mit-der-paketverwaltung-bleachbit]]
=== Mittels Bleachbit aufräumen ===

// Stichworte für den Index
(((Bleachbit)))
(((Debianpaket, bleachbit)))
* bleachbit <<bleachbit>>

* "with BleachBit you can free cache, delete cookies, clear Internet history, shred temporary files, delete logs, and discard junk you didn't know was there. Designed for Linux and Windows systems, it wipes clean thousands of applications including Firefox, Adobe Flash, Google Chrome, Opera, and more."

// Datei (Ende): ./praxis/plattenplatz-sparen-mit-der-paketverwaltung.adoc
