// Datei: ./praxis/plattenplatz-sparen-mit-der-paketverwaltung.adoc

// Baustelle: Notizen

[[plattenplatz-sparen-mit-der-paketverwaltung]]

== Plattenplatz sparen mit der Paketverwaltung ==

* Hintergrund:
** Software besteht aus vielen einzelnen Paketen
** Speicherplatz reicht nicht immer aus, d.h. ist immer in irgendeiner 
   Form begrenzt
*** Filesystem hat Begrenzungen (Anzahl der Inodes) 
*** Partition hat eine physische Grenze
** je mehr Platz belegt ist, um so langsamer werden die Plattenzugriffe
** Experimente hinterlassen ihre Spuren in Form von "Paketresten", die
   übriggeblieben sind (aufräumen ist immer nützlich)

* Lösungsmöglichkeiten
** Hardlink über `/usr/share/doc/` laufen lassen <<Beckert-Blog-Hardlinking-Duplicate-Files>>
** `dpkg --path-exclude=…`
** Paket 'localepurge', momentan noch unter <<paketverwaltung-mit-eingeschraenkten-ressourcen-fuer-embedded-und-mobile-devices>>
** Ungenutzte Bibliotheken, denen aber das ``Automatisch installiert''-Flag fehlt <<Beckert-Blog-Finding-Libraries>>
** den Paketcache aufräumen (siehe <<paketcache-aufraeumen>>)
** Auch `/var/cache/apt` auf tmpfs gehört hier erwähnt, momentan unter <<cache-verzeichnis-auf-separater-partition>>
** `logrotate` (sollte eigentlich installiert sein, sorgt aber für nicht
  permanent wachsende Logfiles. Seine Konfiguration sollte angepasst
  werden, wenn man manuell weitere Logfiles in Anwendungen (VHosts im
  Apache z.B.) konfiguriert.
** Keinen Syslogd (Default-Paket ist 'rsyslog', dieses entfernen)
  verwenden und das Syslog nur in einen Ringbuffer laufen lassen.
*** Hat man systemd, kann man mit `journalctl` das Log im Ringbuffer
   anschauen.
*** Hat man sysvinit, so kann man das Paket 'busybox-syslogd'
   installieren und mit `logread` den Inhalt des Ringbuffers
   anschauen.
*** Gehört eigentlich nicht zur Paketverwaltung... Kann man
   entsprechend zum Kürzen wieder rauskippen.
** siehe ReduceDebian -- Reducing the size of the Debian Installation
unter Footprint unter https://wiki.debian.org/ReduceDebian
*** nicht-kritische Pakete entfernen
*** apt umkonfigurieren, so dass es nicht automatisch zusätzliche Pakete installiert
*** Pakete durch kleinere Äquivalente ersetzen
*** unnötige Pakete entfernen
*** unnötige Locales entfernen, bspw. mittels localepurge
*** unnötige Kernelmodule entfernen
** bleachbit benutzen (https://www.bleachbit.org/)

// Datei (Ende): ./praxis/plattenplatz-sparen-mit-der-paketverwaltung.adoc
